Equalizer: eq::SystemWindow Class Reference
eq::SystemWindow Class Reference abstract
The interface definition for system-specific windowing code.
#include <systemWindow.h>
Public Member Functions
EQ_API SystemWindow (NotifierInterface &parent, const WindowSettings &settings)
Create a new SystemWindow for the given eq::Window.
virtual EQ_API ~SystemWindow ()
Destroy the SystemWindow.
virtual EQ_API void queryDrawableConfig (DrawableConfig &dc)=0
Set up the given drawable based on the current context.
virtual const GLEWContext * glewGetContext () const
Get the GLEW context for this window.
EQ_API EventOCommand sendError (const uint32_t error)
Send a window error event to the application node.
EQ_API bool processEvent (EventType type)
Process a stateless event.
EQ_API bool processEvent (EventType type, SizeEvent &event)
Process a (re)size event.
EQ_API bool processEvent (EventType type, PointerEvent &event)
Process a mouse event.
EQ_API bool processEvent (EventType type, KeyEvent &event)
Process a keyboard event.
EQ_API bool processEvent (EventType type, AxisEvent &event)
Process an axis event.
EQ_API bool processEvent (EventType type, ButtonEvent &event)
Process a button event.
EQ_API void setPixelViewport (const PixelViewport &pvp)
Set the window's pixel viewport wrt its parent pipe.
EQ_API const PixelViewport & getPixelViewport () const
virtual EQ_API void resize (const PixelViewport &pvp)=0
Resize the underlying frame buffer to the given size.
EQ_API uint32_t getColorFormat () const
EQ_API void setName (const std::string &name)
Set the window's name.
EQ_API const std::string & getName () const
EQ_API int32_t getIAttribute (const WindowSettings::IAttribute attr) const
EQ_API const SystemWindow * getSharedContextWindow () const
Methods forwarded from eq::Window
virtual EQ_API bool configInit ()=0
Initialize this system window.
virtual EQ_API void configExit ()=0
De-initialize this system window.
virtual EQ_API void makeCurrent (const bool cache=true) const =0
Make the system window rendering context and drawable current.
virtual EQ_API void doneCurrent () const =0
This results in no context being current in the current thread.
virtual EQ_API void bindFrameBuffer () const =0
Bind the window's FBO, if it uses an FBO drawable.
virtual EQ_API void bindDrawFrameBuffer () const =0
Bind the window's draw FBO, used for multisampling.
virtual EQ_API void updateFrameBuffer () const =0
Update the window's FBO from the multisampled FBO.
virtual EQ_API void swapBuffers ()=0
Swap the front and back buffer.
virtual EQ_API void flush ()=0
Flush all command buffers.
virtual EQ_API void finish ()=0
Finish execution of all commands.
virtual EQ_API void joinNVSwapBarrier (const uint32_t group, const uint32_t barrier)=0
Join a NV_swap_group.
Frame Buffer Object support.
virtual const util::FrameBufferObject * getFrameBufferObject () const
virtual util::FrameBufferObject * getFrameBufferObject ()
Detailed Description
The interface definition for system-specific windowing code.
The system window abstracts all window system specific code and facilitates porting to new windowing systems. Each eq::Window uses one eq::SystemWindow, which is created and initialized in Window::configInitSystemWindow.
Definition at line 35 of file systemWindow.h.
Constructor & Destructor Documentation
EQ_API eq::SystemWindow::SystemWindow (NotifierInterface & parent, const WindowSettings & settings)
Create a new SystemWindow for the given eq::Window.
Version
1.7.2
virtual EQ_API eq::SystemWindow::~SystemWindow () virtual
Destroy the SystemWindow.
Version
1.0
Member Function Documentation
virtual EQ_API void eq::SystemWindow::bindDrawFrameBuffer () const pure virtual
Bind the window's draw FBO, used for multisampling.
Version
1.9
Implemented in eq::GLWindow, eq::qt::ShareContextWindow, and eq::x11::Window.
virtual EQ_API void eq::SystemWindow::bindFrameBuffer () const pure virtual
Bind the window's FBO, if it uses an FBO drawable.
Version
1.0
Implemented in eq::GLWindow, eq::qt::ShareContextWindow, and eq::x11::Window.
virtual EQ_API void eq::SystemWindow::configExit () pure virtual
De-initialize this system window.
This function might be called on partially or uninitialized system windows, and the implemenation has therefore be tolerant enough to handle this case.
Version
1.0
Implemented in eq::wgl::Window, eq::glx::Window, eq::qt::Window, eq::qt::ShareContextWindow, and eq::x11::Window.
virtual EQ_API bool eq::SystemWindow::configInit () pure virtual
Initialize this system window.
This method should take into account all attributes of the parent Window.
Returns
true if the window was correctly initialized, false on any error.
Version
1.0
Implemented in eq::wgl::Window, eq::glx::Window, eq::qt::Window, eq::qt::ShareContextWindow, and eq::x11::Window.
virtual EQ_API void eq::SystemWindow::doneCurrent () const pure virtual
This results in no context being current in the current thread.
This function resets the pipe's make current cache.
Version
1.10
Implemented in eq::wgl::Window, eq::glx::Window, eq::qt::Window, eq::qt::ShareContextWindow, eq::GLWindow, and eq::x11::Window.
virtual EQ_API void eq::SystemWindow::finish () pure virtual
Finish execution of all commands.
Version
1.5.2
Implemented in eq::GLWindow, eq::qt::ShareContextWindow, and eq::x11::Window.
virtual EQ_API void eq::SystemWindow::flush () pure virtual
Flush all command buffers.
Version
1.5.2
Implemented in eq::GLWindow, eq::qt::ShareContextWindow, and eq::x11::Window.
virtual const util::FrameBufferObject* eq::SystemWindow::getFrameBufferObject () const inline virtual
Returns
the FBO of this window, or 0.
Version
1.0
Reimplemented in eq::GLWindow.
Definition at line 119 of file systemWindow.h.
virtual util::FrameBufferObject* eq::SystemWindow::getFrameBufferObject () inline virtual
Returns
the FBO of this window, or 0.
Version
1.0
Reimplemented in eq::GLWindow.
Definition at line 122 of file systemWindow.h.
References queryDrawableConfig().
EQ_API int32_t eq::SystemWindow::getIAttribute (const WindowSettings::IAttribute attr) const
Returns
the value of an integer attribute.
Version
1.7.2
Referenced by glewGetContext().
EQ_API const std::string& eq::SystemWindow::getName () const
Returns
the window's name.
Version
1.7.2
Referenced by glewGetContext().
EQ_API const PixelViewport& eq::SystemWindow::getPixelViewport () const
Returns
the window's pixel viewport wrt the parent pipe.
Version
1.7.2
Referenced by glewGetContext().
EQ_API const SystemWindow* eq::SystemWindow::getSharedContextWindow () const
Returns
the window with which this window shares the GL context.
Version
1.7.2
Referenced by glewGetContext().
virtual const GLEWContext* eq::SystemWindow::glewGetContext () const inline virtual
Get the GLEW context for this window.
The glew context is initialized during window initialization, and provides access to OpenGL extensions. This function does not follow the Equalizer naming conventions, since GLEW uses a function of this name to automatically resolve OpenGL function entry points. Therefore, any supported GL function can be called directly from an initialized SystemWindow.
Returns
the extended OpenGL function table for the window's OpenGL context.
Version
1.0
Reimplemented in eq::GLWindow.
Definition at line 145 of file systemWindow.h.
References getIAttribute(), getName(), getPixelViewport(), getSharedContextWindow(), processEvent(), resize(), sendError(), setName(), and setPixelViewport().
virtual EQ_API void eq::SystemWindow::joinNVSwapBarrier (const uint32_t group, const uint32_t barrier) pure virtual
Join a NV_swap_group.
See WGL or GLX implementation and OpenGL extension for details on how to implement this function.
Parameters
group the swap group name.
barrier the swap barrier name.
Version
1.0
Implemented in eq::wgl::Window, eq::glx::Window, eq::qt::Window, eq::qt::ShareContextWindow, and eq::x11::Window.
virtual EQ_API void eq::SystemWindow::makeCurrent (const bool cache = true) const pure virtual
Make the system window rendering context and drawable current.
This function invalidates the pipe's make current cache.
Version
1.0
Implemented in eq::wgl::Window, eq::glx::Window, eq::qt::Window, eq::qt::ShareContextWindow, eq::GLWindow, and eq::x11::Window.
EQ_API bool eq::SystemWindow::processEvent (EventType type)
Process a stateless event.
Returns
true if the event was handled.
Referenced by glewGetContext(), eq::qt::WindowIF::processEvent(), eq::glx::WindowIF::processEvent(), and eq::wgl::WindowIF::processEvent().
EQ_API bool eq::SystemWindow::processEvent (EventType type, SizeEvent & event)
Process a (re)size event.
Returns
true if the event was handled.
EQ_API bool eq::SystemWindow::processEvent (EventType type, PointerEvent & event)
Process a mouse event.
Returns
true if the event was handled.
EQ_API bool eq::SystemWindow::processEvent (EventType type, KeyEvent & event)
Process a keyboard event.
Returns
true if the event was handled.
EQ_API bool eq::SystemWindow::processEvent (EventType type, AxisEvent & event)
Process an axis event.
Returns
true if the event was handled.
EQ_API bool eq::SystemWindow::processEvent (EventType type, ButtonEvent & event)
Process a button event.
Returns
true if the event was handled.
virtual EQ_API void eq::SystemWindow::queryDrawableConfig (DrawableConfig & dc) pure virtual
Set up the given drawable based on the current context.
Version
1.0
Implemented in eq::GLWindow, eq::qt::ShareContextWindow, and eq::x11::Window.
Referenced by getFrameBufferObject().
virtual EQ_API void eq::SystemWindow::resize (const PixelViewport & pvp) pure virtual
Resize the underlying frame buffer to the given size.
Parameters
pvp the viewport in pixels.
Version
2.1
Implemented in eq::qt::ShareContextWindow, and eq::GLWindow.
Referenced by glewGetContext().
EQ_API EventOCommand eq::SystemWindow::sendError (const uint32_t error)
Send a window error event to the application node.
Parameters
error the error code.
Version
1.7.1
Referenced by glewGetContext().
EQ_API void eq::SystemWindow::setName (const std::string & name)
Set the window's name.
Version
1.7.2
Referenced by glewGetContext().
EQ_API void eq::SystemWindow::setPixelViewport (const PixelViewport & pvp)
Set the window's pixel viewport wrt its parent pipe.
Parameters
pvp the viewport in pixels.
Version
1.7.2
Referenced by glewGetContext().
virtual EQ_API void eq::SystemWindow::swapBuffers () pure virtual
Swap the front and back buffer.
Version
1.0
Implemented in eq::wgl::Window, eq::glx::Window, eq::qt::Window, eq::qt::ShareContextWindow, and eq::x11::Window.
virtual EQ_API void eq::SystemWindow::updateFrameBuffer () const pure virtual
Update the window's FBO from the multisampled FBO.
Version
1.9
Implemented in eq::GLWindow, eq::qt::ShareContextWindow, and eq::x11::Window.
The documentation for this class was generated from the following file:
systemWindow.h