Equalizer: eq::glx::WindowIF Class Reference
eq::glx::WindowIF Class Reference abstract
The interface defining the minimum functionality for a glX window.
#include <window.h>
Public Member Functions
WindowIF (NotifierInterface &parent, const WindowSettings &settings)
virtual GLXContext getGLXContext () const =0
virtual XID getXDrawable () const =0
virtual Display * getXDisplay ()=0
virtual bool processEvent (EventType type, const XEvent &, SizeEvent &event)
Process a (re)size event.
virtual bool processEvent (EventType type, const XEvent &, PointerEvent &event)
Process a mouse event.
virtual bool processEvent (EventType type, const XEvent &, KeyEvent &event)
Process a keyboard event.
virtual bool processEvent (const XEvent &, AxisEvent &event)
Process an axis event.
virtual bool processEvent (const XEvent &, ButtonEvent &event)
Process a button event.
virtual bool processEvent (EventType type, const XEvent &)
Process a stateless event.
Public Member Functions inherited from eq::GLWindow
EQ_API GLWindow (NotifierInterface &parent, const WindowSettings &settings)
Construct a new OpenGL window.
virtual EQ_API ~GLWindow ()
Destruct a new OpenGL window.
EQ_API void resize (const PixelViewport &pvp) override
Resize the underlying FBO(s)
EQ_API void makeCurrent (const bool cache=true) const override
Bind the FBO and update the current cache.
EQ_API void doneCurrent () const override
Unbind the FBO and remove context from current cache.
EQ_API bool isCurrent () const
virtual EQ_API void initGLEW ()
Initialize the GLEW context for this window.
virtual EQ_API void exitGLEW ()
De-initialize the GLEW context.
EQ_API const GLEWContext * glewGetContext () const override
Get the GLEW context for this window.
EQ_API void queryDrawableConfig (DrawableConfig &) override
Set up the drawable config by querying the current context.
EQ_API void bindFrameBuffer () const override
Bind the window's FBO, if it uses an FBO drawable.
EQ_API void bindDrawFrameBuffer () const override
Bind the window's draw FBO, used for multisampling.
EQ_API void updateFrameBuffer () const override
Update the window's FBO from the multisampled FBO.
EQ_API void flush () override
Flush all command buffers.
EQ_API void finish () override
Finish execution of all commands.
virtual EQ_API bool configInitFBO ()
Build and initialize the FBO.
virtual EQ_API void configExitFBO ()
Destroy the FBO.
EQ_API const util::FrameBufferObject * getFrameBufferObject () const override
EQ_API util::FrameBufferObject * getFrameBufferObject () override
Public Member Functions inherited from eq::SystemWindow
EQ_API SystemWindow (NotifierInterface &parent, const WindowSettings &settings)
Create a new SystemWindow for the given eq::Window.
virtual EQ_API ~SystemWindow ()
Destroy the SystemWindow.
EQ_API EventOCommand sendError (const uint32_t error)
Send a window error event to the application node.
EQ_API bool processEvent (EventType type)
Process a stateless event.
EQ_API bool processEvent (EventType type, SizeEvent &event)
Process a (re)size event.
EQ_API bool processEvent (EventType type, PointerEvent &event)
Process a mouse event.
EQ_API bool processEvent (EventType type, KeyEvent &event)
Process a keyboard event.
EQ_API bool processEvent (AxisEvent &event)
Process an axis event.
EQ_API bool processEvent (ButtonEvent &event)
Process a button event.
EQ_API void setPixelViewport (const PixelViewport &pvp)
Set the window's pixel viewport wrt its parent pipe.
EQ_API const PixelViewport & getPixelViewport () const
EQ_API uint32_t getColorFormat () const
EQ_API void setName (const std::string &name)
Set the window's name.
EQ_API const std::string & getName () const
EQ_API int32_t getIAttribute (const WindowSettings::IAttribute attr) const
EQ_API const SystemWindow * getSharedContextWindow () const
virtual EQ_API bool configInit ()=0
Initialize this system window.
virtual EQ_API void configExit ()=0
De-initialize this system window.
virtual EQ_API void swapBuffers ()=0
Swap the front and back buffer.
virtual EQ_API void joinNVSwapBarrier (const uint32_t group, const uint32_t barrier)=0
Join a NV_swap_group.
Detailed Description
The interface defining the minimum functionality for a glX window.
Definition at line 33 of file glx/window.h.
Member Function Documentation
virtual GLXContext eq::glx::WindowIF::getGLXContext () const pure virtual
Returns
the glX rendering context.
Version
1.0
Implemented in eq::glx::Window.
virtual Display* eq::glx::WindowIF::getXDisplay () pure virtual
Returns
X11 display connection.
Version
1.0
Implemented in eq::glx::Window.
virtual XID eq::glx::WindowIF::getXDrawable () const pure virtual
Returns
the X11 drawable ID.
Version
1.0
Implemented in eq::glx::Window.
virtual bool eq::glx::WindowIF::processEvent (EventType type, const XEvent & , SizeEvent & event) inline virtual
Process a (re)size event.
Returns
true if the event was handled.
Definition at line 50 of file glx/window.h.
References eq::SystemWindow::processEvent().
virtual bool eq::glx::WindowIF::processEvent (EventType type, const XEvent & , PointerEvent & event) inline virtual
Process a mouse event.
Returns
true if the event was handled.
Reimplemented in eq::glx::Window.
Definition at line 55 of file glx/window.h.
References eq::SystemWindow::processEvent().
virtual bool eq::glx::WindowIF::processEvent (EventType type, const XEvent & , KeyEvent & event) inline virtual
Process a keyboard event.
Returns
true if the event was handled.
Definition at line 60 of file glx/window.h.
References eq::SystemWindow::processEvent().
virtual bool eq::glx::WindowIF::processEvent (const XEvent & , AxisEvent & event) inline virtual
Process an axis event.
Returns
true if the event was handled.
Definition at line 64 of file glx/window.h.
References eq::SystemWindow::processEvent().
virtual bool eq::glx::WindowIF::processEvent (const XEvent & , ButtonEvent & event) inline virtual
Process a button event.
Returns
true if the event was handled.
Definition at line 68 of file glx/window.h.
References eq::SystemWindow::processEvent().
virtual bool eq::glx::WindowIF::processEvent (EventType type, const XEvent &) inline virtual
Process a stateless event.
Returns
true if the event was handled.
Definition at line 72 of file glx/window.h.
References eq::SystemWindow::processEvent().
The documentation for this class was generated from the following file:
glx/window.h