Equalizer: eq::WindowSystemIF Class Reference
eq::WindowSystemIF Class Reference abstract
The interface for windowing toolkits.
#include <windowSystem.h>
Public Member Functions
virtual ~WindowSystemIF ()
Destroy the window system instance.
Protected Member Functions
EQ_API WindowSystemIF ()
Create a new window system instance.
virtual std::string getName () const =0
virtual SystemPipe * createPipe (Pipe *pipe)=0
virtual MessagePump * createMessagePump ()=0
virtual SystemWindow * createWindow (Window *window, const WindowSettings &settings)=0
virtual bool setupFont (util::ObjectManager &gl, const void *key, const std::string &name, const uint32_t size) const =0
Create a set of display lists for the given font.
virtual void configInit (Node *)
Perform per-process initialization for a Config.
virtual void configExit (Node *)
Perform per-process de-initialization for a Config.
virtual bool hasMainThreadEvents () const
Static Protected Member Functions
static uint32_t _setupLists (util::ObjectManager &gl, const void *key, const int num)
Friends
class WindowSystem
Detailed Description
The interface for windowing toolkits.
This class is intended to be overwritten by an (anonymous) class with exactly one static instance. The constructor will register this factory instance for use with the WindowSystem frontend. See glx/windowSystem.cpp for an example.
The implementation provides access to operating system dependent functionality needed by Equalizer, and hides these specifics behind interfaces.
Definition at line 40 of file windowSystem.h.
Constructor & Destructor Documentation
virtual eq::WindowSystemIF::~WindowSystemIF () inline virtual
Destroy the window system instance.
Version
1.6
Definition at line 44 of file windowSystem.h.
References createMessagePump(), createPipe(), createWindow(), getName(), setupFont(), and WindowSystemIF().
EQ_API eq::WindowSystemIF::WindowSystemIF () protected
Create a new window system instance.
Version
1.6
Referenced by ~WindowSystemIF().
Member Function Documentation
virtual void eq::WindowSystemIF::configExit (Node *) inline protected virtual
Perform per-process de-initialization for a Config.
Version
1.6
Definition at line 89 of file windowSystem.h.
virtual void eq::WindowSystemIF::configInit (Node *) inline protected virtual
Perform per-process initialization for a Config.
Version
1.6
Definition at line 86 of file windowSystem.h.
virtual MessagePump* eq::WindowSystemIF::createMessagePump () protected pure virtual
Returns
a new event message pump
Version
1.6
Referenced by ~WindowSystemIF().
virtual SystemPipe* eq::WindowSystemIF::createPipe (Pipe * pipe) protected pure virtual
Returns
a new system pipe.
Version
1.6
Referenced by ~WindowSystemIF().
virtual SystemWindow* eq::WindowSystemIF::createWindow (Window * window, const WindowSettings & settings) protected pure virtual
Returns
a new system window
Version
1.7.2
Referenced by ~WindowSystemIF().
virtual std::string eq::WindowSystemIF::getName () const protected pure virtual
Returns
the unique name of the window system.
Version
1.6
Referenced by ~WindowSystemIF().
virtual bool eq::WindowSystemIF::hasMainThreadEvents () const inline protected virtual
Returns
true if events have to be dispatched in the main thread.
Version
1.7.4
Definition at line 95 of file windowSystem.h.
virtual bool eq::WindowSystemIF::setupFont (util::ObjectManager & gl, const void * key, const std::string & name, const uint32_t size) const protected pure virtual
Create a set of display lists for the given font.
The implementation is expected to set up one display list per ASCII character, and store the name of the first list in the given object manager using the given key.
Parameters
gl the object manager for display list allocation.
key the key for display list allocation.
name the name of the font, OS-specific.
size the font size in points.
Returns
true if the font was created, false otherwise.
Warning
experimental, might not be supported in the future.
Referenced by ~WindowSystemIF().
The documentation for this class was generated from the following file:
windowSystem.h