Equalizer: eq Namespace Reference
eq Namespace Reference
The Equalizer client library.
Namespaces
agl
The system abstraction layer for Apple OpenGL and Carbon.
fabric
The Equalizer data synchronization fabric.
glx
The system abstraction layer for X11 and glX.
qt
The system abstraction layer for Qt.
util
Equalizer utility classes.
wgl
The system abstraction layer for Windows OpenGL.
x11
An abstraction layer for CPU-based rendering using X11.
Classes
class Canvas
A canvas represents a logical 2D projection surface.
class Channel
A channel represents a two-dimensional viewport within a Window.
class ChannelStatistics
Samples one channel statistics event.
class Client
The client represents a network node of the application in the cluster.
class CommandQueue
class Compositor
A set of functions performing compositing for a set of input frames.
class Config
A configuration is a visualization session driven by an application.
class ConfigStatistics
Samples one Config statistics event.
class EventHandler
Base class for window system-specific event handlers.
class EventICommand
A command specialization for config events.
class Exception
Exception class for Equalizer operations.
class Frame
A holder for a frame data and related parameters.
class FrameData
A holder for multiple images.
class GLException
OpenGL Exception.
class Global
Global parameter handling for the Equalizer client library.
class GLWindow
A system window for OpenGL rendering.
class Image
A holder for pixel data.
struct ImageOp
A structure describing an image assembly task, used by the Compositor.
class Layout
A layout groups one or more View, logically belonging together.
class MessagePump
An interface to process system messages or events.
class Node
A Node represents a single computer in the cluster.
class NodeFactory
The node factory is a per-node singleton used to create and release Equalizer resource instances.
class NotifierInterface
A base class for notifying errors and events.
class Observer
An Observer looks at one or more views from a certain position (head matrix) with a given eye separation.
class Pipe
A Pipe represents a graphics card (GPU) on a Node.
struct PixelData
The pixel data structure manages the pixel information for images.
class ResultImageListener
The result image listener gets notified on new images produced by destination channels.
class Segment
A segment covers a sub-area of a Canvas.
class Server
Proxy object for the connection to an Equalizer server.
class StatisticSampler
Utility to sample an statistics event.
class SystemPipe
The interface definition for system-specific GPU handling.
class SystemWindow
The interface definition for system-specific windowing code.
class Version
Information about the current EqualizerCompressor version.
class View
A View is a 2D area of a Layout.
class Window
A Window represents an on-screen or off-screen drawable.
class WindowSettings
A set of settings to setup an eq::SystemWindow.
class WindowStatistics
A statistics sampler for window-related events.
class WindowSystem
class WindowSystemIF
The interface for windowing toolkits.
Typedefs
typedef fabric::LeafVisitor< Segment > SegmentVisitor
A visitor to traverse segments.
typedef fabric::LeafVisitor< View > ViewVisitor
A visitor to traverse views.
typedef fabric::LeafVisitor< Observer > ObserverVisitor
A visitor to traverse channels.
typedef fabric::LeafVisitor< Channel > ChannelVisitor
A visitor to traverse channels.
typedef fabric::ElementVisitor< Canvas, SegmentVisitor > CanvasVisitor
A visitor to traverse canvases and children.
typedef fabric::ElementVisitor< Window, ChannelVisitor > WindowVisitor
A visitor to traverse windows and children.
typedef fabric::ElementVisitor< Pipe, WindowVisitor > PipeVisitor
A visitor to traverse pipes and children.
typedef fabric::ElementVisitor< Node, PipeVisitor > NodeVisitor
A visitor to traverse nodes and children.
typedef fabric::ElementVisitor< Layout, ViewVisitor > LayoutVisitor
A visitor to traverse layouts and children.
typedef fabric::ConfigVisitor< Config, ObserverVisitor, LayoutVisitor, CanvasVisitor, NodeVisitor > ConfigVisitor
A visitor to traverse configs and children.
typedef fabric::ElementVisitor< Server, ConfigVisitor > ServerVisitor
A visitor to traverse servers and children.
typedef std::vector< Config * > Configs
A vector of pointers to eq::Config.
typedef std::vector< Server * > Servers
A vector of pointers to eq::Server.
typedef std::vector< Node * > Nodes
A vector of pointers to eq::Node.
typedef std::vector< Pipe * > Pipes
A vector of pointers to eq::Pipe.
typedef std::vector< Window * > Windows
A vector of pointers to eq::Window.
typedef std::vector< Channel * > Channels
A vector of pointers to eq::Channel.
typedef std::vector< Frame * > Frames
A vector of pointers to eq::Frame.
typedef std::vector< Image * > Images
A vector of pointers to eq::Image.
typedef std::vector< Observer * > Observers
A vector of pointers to eq::Observer.
typedef std::vector< Canvas * > Canvases
A vector of pointers to eq::Canvas.
typedef std::vector< Layout * > Layouts
A vector of pointers to eq::Layout.
typedef std::vector< Segment * > Segments
A vector of pointers to eq::Segment.
typedef std::vector< View * > Views
A vector of pointers to eq::View.
typedef std::vector< PixelViewport > PixelViewports
A vector of eq::PixelViewport.
typedef std::vector< ImageOp > ImageOps
A vector of image compositing operations.
typedef Configs::const_iterator ConfigsCIter
A const_iterator over a eq::Config vector.
typedef Servers::const_iterator ServersCIter
A const_iterator over a eq::Server vector.
typedef Nodes::const_iterator NodesCIter
A const_iterator over a eq::Node vector.
typedef Pipes::const_iterator PipesCIter
A const_iterator over a eq::Pipe vector.
typedef Windows::const_iterator WindowsCIter
A const_iterator over a eq::Window vector.
typedef Channels::const_iterator ChannelsCIter
A const_iterator over a eq::Channel vector.
typedef Frames::iterator FramesIter
An iterator over a eq::Frame vector.
typedef Frames::const_iterator FramesCIter
A const_iterator over a eq::Frame vector.
typedef Images::const_iterator ImagesCIter
A const_iterator over a eq::Image vector.
typedef Observers::const_iterator ObserversCIter
A const_iterator over a eq::Observer vector.
typedef Canvases::const_iterator CanvasesCIter
A const_iterator over a eq::Canvas vector.
typedef Layouts::const_iterator LayoutsCIter
A const_iterator over a eq::Layout vector.
typedef Segments::const_iterator SegmentsCIter
A const_iterator over a eq::Segment vector.
typedef Views::const_iterator ViewsCIter
A const_iterator over a eq::View vector.
typedef PixelViewports::const_iterator PixelViewportsCIter
A const_iterator over a eq::PixelViewport vector.
typedef lunchbox::RefPtr< Client > ClientPtr
A reference-counted pointer to an eq::Client.
typedef lunchbox::RefPtr< const Client > ConstClientPtr
A reference-counted pointer to a const eq::Client.
typedef lunchbox::RefPtr< Server > ServerPtr
A reference-counted pointer to an eq::Server.
typedef lunchbox::RefPtr< FrameData > FrameDataPtr
A reference-counted pointer to an eq::FrameData.
typedef lunchbox::RefPtr< const FrameData > ConstFrameDataPtr
A reference-counted pointer to a const eq::FrameData.
typedef std::vector< uint8_t > Vectorub
A vector of bytes.
typedef std::vector< uint16_t > Vectorus
A vector of unsigned shorts.
using WindowSystemImpl = std::shared_ptr< WindowSystemIF >
Enumerations
enum LogTopics {
LOG_BUG = lunchbox::LOG_BUG, LOG_PLUGIN = pression::LOG_PLUGIN, LOG_INIT = fabric::LOG_INIT, LOG_ASSEMBLY = fabric::LOG_ASSEMBLY,
LOG_TASKS = fabric::LOG_TASKS, LOG_STATS = fabric::LOG_CUSTOM << 0, LOG_CUSTOM = 0x10000
}
Defines selective logging classes enabled by setting LB_LOG_TOPICS.
enum ZoomFilter { FILTER_NEAREST = 0x2600, FILTER_LINEAR = 0x2601 }
Filtering algorithm to applied during zoom operations.
Functions
EQ_API std::ostream & operator<< (std::ostream &os, const EventICommand &command)
Print the event command to the given output stream.
EQ_API std::ostream & operator<< (std::ostream &, const FrameData &)
Print the frame data to the given output stream.
EQ_API void debugGLError (const std::string &when, const GLenum error, const char *file, const int line)
Output an error OpenGL in a human-readable form to LBWARN.
EQ_API std::string glError (const GLenum error)
EQ_API co::DataOStream & operator<< (co::DataOStream &os, const Image &)
eq::Image serializer.
EQ_API co::DataIStream & operator>> (co::DataIStream &is, Image &)
eq::Image deserializer.
EQ_API bool _init (const int argc, char **argv, NodeFactory *nodeFactory)
bool init (const int argc, char **argv, NodeFactory *nodeFactory)
Initialize the Equalizer client library.
EQ_API bool exit ()
De-initialize the Equalizer client library.
EQ_API Config * getConfig (const int argc, char **argv)
Convenience function to retrieve a configuration.
EQ_API void releaseConfig (Config *config)
Convenience function to release a configuration.
EQ_API std::string getHelp ()
EQ_API std::ostream & operator<< (std::ostream &os, const WindowSystem &)
Print the window system name to the given output stream.
EQ_API co::DataOStream & operator<< (co::DataOStream &os, const WindowSystem &)
co::Object serializer.
EQ_API co::DataIStream & operator>> (co::DataIStream &is, WindowSystem &ws)
WindowSystem deserializer.
Detailed Description
The Equalizer client library.
This namespace implements the application-visible API to access the Equalizer server.
The Client represents the application instance and co::Node. A Client can connect to a Server to retrieve a Config.
The Server, Config, Node, Window and Channel hierarchy represents the rendering entities as described in the configuration file. Each process in the cluster only has the local entities instantiated, that is, there is at most one node per process. The Config is a co::Session, which is normally used to register distributed objects based on eq::Object or co::Object.
The Canvas, Segment, Layout, View and Observer hierarchy represents the physical projection system, logical layout and tracked users. Applications which want to be multi-view capable typically extend the View to attach application-specific data, e.g., a camera position or model.
A ConfigVisitor, NodeVisitor, PipeVisitor, WindowVisitor, ChannelVisitor, CanvasVisitor, SegmentVisitor, LayoutVisitor, ViewVisitor or ObserverVisitor may be used to traverse the corresponding entity and to execute methods for each child of the hierarchy.
The SystemWindow is used by the Window and abstracts window-system specific functionality. The GLWindow implements generic OpenGL functionality, and is in turn sub-classed by the interfaces GLXWindowIF, AGLWindowIF and WGLWindowIF, which extend the GLWindow by GLX, AGL and WGL-specific functionality. The GLXWindow, AGLWindow and WGLWindow implement the aforementioned interfaces.
The SystemPipe, GLXPipe, AGLPipe and WGLPipe hierarchy implements a similar abstraction for GPU-specific functionality.
The GLXMessagePump, AGLMessagePump and WGLMessagePump are used by the node and pipe threads to detect and dispatch system events. The GLXEventHandler, AGLEventHandler and WGLEventHandler receive these events and transform them into a AGLWindowEvent, GLXWindowEvent or WGLWindowEvent, respectively.
The window events are dispatched to the corresponding SystemWindow, which can execute window system specific tasks. The SystemWindow implementations forward a SizeEvent, PointerEvent or KeyEvent to the Window as well as a AxisEvent or ButtonEvent to the Node. The window or node will handle the necessary events locally, and will send them to the application node using Config::sendEvent() when desired.
During scalable rendering, a Frame is used to represent an output frame during Channel::frameReadback or an input frame during Channel::frameAssemble. Each Frame holds a FrameData, which is a container for images and links the input with the output frames. An Image represents a 2D framebuffer area, containing color and/or depth information.
Typedef Documentation
typedef fabric::ElementVisitor< Canvas, SegmentVisitor > eq::CanvasVisitor
A visitor to traverse canvases and children.
Definition at line 124 of file eq/types.h.
typedef fabric::LeafVisitor< Channel > eq::ChannelVisitor
A visitor to traverse channels.
See also
Channel::accept()
Definition at line 121 of file eq/types.h.
typedef fabric::ConfigVisitor< Config, ObserverVisitor, LayoutVisitor, CanvasVisitor, NodeVisitor > eq::ConfigVisitor
A visitor to traverse configs and children.
Definition at line 141 of file eq/types.h.
typedef std::vector< ImageOp > eq::ImageOps
A vector of image compositing operations.
Definition at line 176 of file eq/types.h.
typedef fabric::ElementVisitor< Layout, ViewVisitor > eq::LayoutVisitor
A visitor to traverse layouts and children.
Definition at line 136 of file eq/types.h.
typedef fabric::ElementVisitor< Node, PipeVisitor > eq::NodeVisitor
A visitor to traverse nodes and children.
Definition at line 133 of file eq/types.h.
typedef fabric::LeafVisitor< Observer > eq::ObserverVisitor
A visitor to traverse channels.
See also
Channel::accept()
Definition at line 118 of file eq/types.h.
typedef fabric::ElementVisitor< Pipe, WindowVisitor > eq::PipeVisitor
A visitor to traverse pipes and children.
Definition at line 130 of file eq/types.h.
typedef fabric::LeafVisitor< Segment > eq::SegmentVisitor
A visitor to traverse segments.
See also
Segment::accept()
Definition at line 112 of file eq/types.h.
typedef fabric::ElementVisitor< Server, ConfigVisitor > eq::ServerVisitor
A visitor to traverse servers and children.
Definition at line 144 of file eq/types.h.
typedef fabric::LeafVisitor< View > eq::ViewVisitor
A visitor to traverse views.
See also
View::accept()
Definition at line 115 of file eq/types.h.
typedef fabric::ElementVisitor< Window, ChannelVisitor > eq::WindowVisitor
A visitor to traverse windows and children.
Definition at line 127 of file eq/types.h.
Enumeration Type Documentation
enum eq::LogTopics
Defines selective logging classes enabled by setting LB_LOG_TOPICS.
Enumerator
LOG_BUG
Potential bugs (4)
LOG_PLUGIN
Plugin usage (16)
LOG_INIT
Initialization (512)
LOG_ASSEMBLY
Compositing tasks (1024)
LOG_TASKS
Rendering tasks (2048)
LOG_STATS
Statistic events (32768)
LOG_CUSTOM
User-defined log topics (65536)
Definition at line 27 of file log.h.
enum eq::ZoomFilter
Filtering algorithm to applied during zoom operations.
Enumerator
FILTER_NEAREST
GL_NEAREST.
FILTER_LINEAR
GL_LINEAR.
Definition at line 25 of file zoomFilter.h.
Function Documentation
EQ_API bool eq::exit ()
De-initialize the Equalizer client library.
De-initialize the Equalizer fabric namespace.
Returns
true if the library was successfully de-initialized, false otherwise.
Referenced by init().
EQ_API Config* eq::getConfig (const int argc, char ** argv)
Convenience function to retrieve a configuration.
This function initializes a local client node, connects it to the server, and retrieves a configuration. On any failure everything is correctly deinitialized and 0 is returned.
Returns
the pointer to a configuration, or 0 upon error.
Referenced by eq::View::getPipe(), and init().
EQ_API std::string eq::getHelp ()
Returns
a help string for all parsed command line arguments.
Version
2.1
Referenced by init().
EQ_API std::string eq::glError (const GLenum error)
Returns
the given error in human-readable form.
bool eq::init (const int argc, char ** argv, NodeFactory * nodeFactory) inline
Initialize the Equalizer client library.
The following command line options are recognized by this function:
–eq-logfile <filename> redirect all log output to the given file.
–eq-server <hostname> to specify an explicit server address (cf. Global::setServer())
–eq-config <filename> to specify the configuration file or hwsd session if an application-specific server is used (cf. Global::setConfigFile())
–eq-render-client <filename> to specify an alternate name for the render client executable (default is argv[0]). Also sets the working directory to the director part of the filename.
Please note that further command line parameters are recognized by co::LocalNode::initLocal().
exit() should be called independent of the return value of this function.
Parameters
argc the command line argument count.
argv the command line argument values.
nodeFactory the factory for allocating Equalizer objects.
Returns
true if the library was successfully initialized, false otherwise.
Definition at line 58 of file init.h.
References EQ_VERSION_ABI, exit(), eq::Version::getABI(), getConfig(), getHelp(), and releaseConfig().
EQ_API std::ostream& eq::operator<< (std::ostream & os, const EventICommand & command)
Print the event command to the given output stream.
Version
1.5.1
EQ_API std::ostream& eq::operator<< (std::ostream & os, const WindowSystem &)
Print the window system name to the given output stream.
Version
1.0
EQ_API co::DataOStream& eq::operator<< (co::DataOStream & os, const WindowSystem &)
co::Object serializer.
Version
1.1.3
EQ_API std::ostream& eq::operator<< (std::ostream & , const FrameData &)
Print the frame data to the given output stream.
Version
1.4
EQ_API co::DataOStream& eq::operator<< (co::DataOStream & os, const Image &)
eq::Image serializer.
Version
2.1
EQ_API co::DataIStream& eq::operator>> (co::DataIStream & is, WindowSystem & ws)
WindowSystem deserializer.
Version
1.1.3
EQ_API co::DataIStream& eq::operator>> (co::DataIStream & is, Image &)
eq::Image deserializer.
Version
2.1
EQ_API void eq::releaseConfig (Config * config)
Convenience function to release a configuration.
This function releases the configuration, disconnects the server, and stops the local client node.
Referenced by init().