Lunchbox: lunchbox::Future< T > Class Template Reference
lunchbox::Future< T > Class Template Reference
A future represents a asynchronous operation.
#include <future.h>
Public Member Functions
Future (Impl impl)
Construct a new future.
~Future ()
Destruct the future.
T wait ()
Wait for the promise to be fullfilled.
Blocking comparison operators.
operator bool_t ()
bool operator! ()
bool operator== (const T &rhs)
bool operator!= (const T &rhs)
bool operator< (const T &rhs)
bool operator> (const uint128_t &rhs)
bool operator<= (const uint128_t &rhs)
bool operator>= (const uint128_t &rhs)
Public Types
typedef RefPtr< FutureImpl< T > > Impl
The wait implementation.
Detailed Description
template<class T>
class lunchbox::Future< T >
A future represents a asynchronous operation.
Do not subclass.
Definition at line 44 of file future.h.
Constructor & Destructor Documentation
template<class T> lunchbox::Future< T >::Future (Impl impl) inline
Construct a new future.
Version
1.9.1
Definition at line 53 of file future.h.
template<class T> lunchbox::Future< T >::~Future () inline
Destruct the future.
Version
1.9.1
Definition at line 56 of file future.h.
Member Function Documentation
template<class T> lunchbox::Future< T >::operator bool_t () inline
Returns
a bool conversion of the result.
Version
1.9.1
Definition at line 64 of file future.h.
References lunchbox::Future< T >::wait().
template<class T> bool lunchbox::Future< T >::operator! () inline
Returns
true if the result does convert to false.
Version
1.9.1
Definition at line 67 of file future.h.
References lunchbox::Future< T >::wait().
template<class T> bool lunchbox::Future< T >::operator!= (const T & rhs) inline
Returns
true if the result is not equal to the rhs.
Version
1.9.1
Definition at line 73 of file future.h.
References lunchbox::Future< T >::wait().
template<class T> bool lunchbox::Future< T >::operator< (const T & rhs) inline
Returns
true if the result is smaller than the rhs.
Version
1.9.1
Definition at line 76 of file future.h.
References lunchbox::Future< T >::wait().
template<class T> bool lunchbox::Future< T >::operator<= (const uint128_t & rhs) inline
Returns
true if the result is smaller or equal.
Version
1.9.1
Definition at line 82 of file future.h.
References lunchbox::Future< T >::wait().
template<class T> bool lunchbox::Future< T >::operator== (const T & rhs) inline
Returns
true if the result is equal to the given value.
Version
1.9.1
Definition at line 70 of file future.h.
References lunchbox::Future< T >::wait().
template<class T> bool lunchbox::Future< T >::operator> (const uint128_t & rhs) inline
Returns
true if the result is bigger than the rhs.
Version
1.9.1
Definition at line 79 of file future.h.
References lunchbox::Future< T >::wait().
template<class T> bool lunchbox::Future< T >::operator>= (const uint128_t & rhs) inline
Returns
true if the result is bigger or equal.
Version
1.9.1
Definition at line 85 of file future.h.
References lunchbox::Future< T >::wait().
template<class T> T lunchbox::Future< T >::wait () inline
Wait for the promise to be fullfilled.
Version
1.9.1
Definition at line 59 of file future.h.
Referenced by lunchbox::Future< T >::operator bool_t(), lunchbox::Future< T >::operator!(), lunchbox::Future< T >::operator!=(), lunchbox::Future< T >::operator<(), lunchbox::Future< T >::operator<=(), lunchbox::Future< T >::operator==(), lunchbox::Future< T >::operator>(), and lunchbox::Future< T >::operator>=().
The documentation for this class was generated from the following file:
future.h