Lunchbox: WriteThread< T, hold > Class Template Reference
WriteThread< T, hold > Class Template Reference
Public Member Functions
virtual void run ()
The entry function for the child thread.
Public Member Functions inherited from lunchbox::Thread
LUNCHBOX_API Thread ()
Construct a new thread.
LUNCHBOX_API Thread (const Thread &from)
Copy constructor.
virtual LUNCHBOX_API ~Thread ()
Destruct the thread.
virtual LUNCHBOX_API bool start ()
Start the thread.
virtual bool init ()
The init function for the child thread.
virtual LUNCHBOX_API void exit ()
Exit the child thread immediately.
LUNCHBOX_API void cancel ()
Cancel (stop) the child thread.
LUNCHBOX_API bool join ()
Wait for the exit of the child thread.
LUNCHBOX_API bool isStopped () const
Return if the thread is stopped.
LUNCHBOX_API bool isRunning () const
Return if the thread is running.
LUNCHBOX_API bool isCurrent () const
LUNCHBOX_API Thread ()
Construct a new thread.
LUNCHBOX_API Thread (const Thread &from)
Copy constructor.
virtual LUNCHBOX_API ~Thread ()
Destruct the thread.
virtual LUNCHBOX_API bool start ()
Start the thread.
virtual bool init ()
The init function for the child thread.
virtual LUNCHBOX_API void exit ()
Exit the child thread immediately.
LUNCHBOX_API void cancel ()
Cancel (stop) the child thread.
LUNCHBOX_API bool join ()
Wait for the exit of the child thread.
LUNCHBOX_API bool isStopped () const
Return if the thread is stopped.
LUNCHBOX_API bool isRunning () const
Return if the thread is running.
LUNCHBOX_API bool isCurrent () const
Public Attributes
T * lock
size_t ops
double sTime
Additional Inherited Members
Public Types inherited from lunchbox::Thread
enum Affinity {
NONE = 0, CORE = 1, SOCKET = -65536, SOCKET_MAX = -1024,
NONE = 0, CORE = 1, SOCKET = -65536, SOCKET_MAX = -1024
}
Enumeration values for thread affinity.
enum Affinity {
NONE = 0, CORE = 1, SOCKET = -65536, SOCKET_MAX = -1024,
NONE = 0, CORE = 1, SOCKET = -65536, SOCKET_MAX = -1024
}
Enumeration values for thread affinity.
Static Public Member Functions inherited from lunchbox::Thread
static LUNCHBOX_API ThreadID getSelfThreadID ()
static LUNCHBOX_API void yield ()
static void pinCurrentThread ()
static LUNCHBOX_API void setName (const std::string &name)
static LUNCHBOX_API void setAffinity (const int32_t affinity)
static LUNCHBOX_API ThreadID getSelfThreadID ()
static LUNCHBOX_API void yield ()
static void pinCurrentThread ()
static LUNCHBOX_API void setName (const std::string &name)
static LUNCHBOX_API void setAffinity (const int32_t affinity)
Detailed Description
template<class T, uint32_t hold>
class WriteThread< T, hold >
Definition at line 43 of file rwLock.cpp.
Member Function Documentation
template<class T, uint32_t hold> virtual void WriteThread< T, hold >::run () inline virtual
The entry function for the child thread.
This method should contain the main execution routine for the thread and is called after a successful init().
Version
1.0
Implements lunchbox::Thread.
Definition at line 52 of file rwLock.cpp.
References lunchbox::Clock::getTimed(), lunchbox::Clock::getTimef(), and lunchbox::sleep().
The documentation for this class was generated from the following file:
rwLock.cpp