Lunchbox: PROJECT_namespace::Version Class Reference
PROJECT_namespace::Version Class Reference
Information about the current @ version.
#include <version.h>
Static Public Member Functions
static int getMajor ()
static int getMinor ()
static int getPatch ()
static std::string getString ()
static int getRevision ()
static int getABI ()
static std::string getRevString ()
static bool check ()
Runtime check for ABI compatibility.
Detailed Description
Information about the current @ version.
Definition at line 56 of file Lunchbox/CMake/common/cpp/version.h.
Member Function Documentation
static bool PROJECT_namespace::Version::check () inline static
Runtime check for ABI compatibility.
Call from code using Will fail if the executable was compiled against a version incompatible with the runtime version.
Returns
true if the link-time and compile-time DSO are compatible.
Definition at line 88 of file Lunchbox/CMake/common/cpp/version.h.
int PROJECT_namespace::Version::getABI () static
Returns
the current binary interface version of
Definition at line 24 of file version.cpp.
int PROJECT_namespace::Version::getMajor () static
Returns
the current major version of
Definition at line 9 of file version.cpp.
Referenced by getString().
int PROJECT_namespace::Version::getMinor () static
Returns
the current minor version of
Definition at line 14 of file version.cpp.
Referenced by getString().
int PROJECT_namespace::Version::getPatch () static
Returns
the current patch level of
Definition at line 19 of file version.cpp.
Referenced by getString().
int PROJECT_namespace::Version::getRevision () static
Returns
the SCM revision.
Definition at line 36 of file version.cpp.
Referenced by getRevString().
std::string PROJECT_namespace::Version::getRevString () static
Returns
the current @ version plus the git SHA hash (MM.mm.pp.rev).
Definition at line 41 of file version.cpp.
References getRevision(), and getString().
std::string PROJECT_namespace::Version::getString () static
Returns
the current @ version (MM.mm.pp).
Definition at line 29 of file version.cpp.
References getMajor(), getMinor(), and getPatch().
Referenced by getRevString().
The documentation for this class was generated from the following files:
Lunchbox/CMake/common/cpp/version.h
version.cpp