Lunchbox: Eraser Class Reference
Eraser Class Reference
Public Member Functions
virtual void run ()
The entry function for the child thread.
Eraser & operator= (const Eraser &)
Public Member Functions inherited from lunchbox::Thread
LUNCHBOX_API Thread ()
Construct a new thread.
LUNCHBOX_API Thread (const Thread &from)
Copy constructor.
virtual LUNCHBOX_API ~Thread ()
Destruct the thread.
virtual LUNCHBOX_API bool start ()
Start the thread.
virtual bool init ()
The init function for the child thread.
virtual LUNCHBOX_API void exit ()
Exit the child thread immediately.
LUNCHBOX_API void cancel ()
Cancel (stop) the child thread.
LUNCHBOX_API bool join ()
Wait for the exit of the child thread.
LUNCHBOX_API bool isStopped () const
Return if the thread is stopped.
LUNCHBOX_API bool isRunning () const
Return if the thread is running.
LUNCHBOX_API bool isCurrent () const
LUNCHBOX_API Thread ()
Construct a new thread.
LUNCHBOX_API Thread (const Thread &from)
Copy constructor.
virtual LUNCHBOX_API ~Thread ()
Destruct the thread.
virtual LUNCHBOX_API bool start ()
Start the thread.
virtual bool init ()
The init function for the child thread.
virtual LUNCHBOX_API void exit ()
Exit the child thread immediately.
LUNCHBOX_API void cancel ()
Cancel (stop) the child thread.
LUNCHBOX_API bool join ()
Wait for the exit of the child thread.
LUNCHBOX_API bool isStopped () const
Return if the thread is stopped.
LUNCHBOX_API bool isRunning () const
Return if the thread is running.
LUNCHBOX_API bool isCurrent () const
Public Attributes
Vector_t * vector
Additional Inherited Members
Public Types inherited from lunchbox::Thread
enum Affinity {
NONE = 0, CORE = 1, SOCKET = -65536, SOCKET_MAX = -1024,
NONE = 0, CORE = 1, SOCKET = -65536, SOCKET_MAX = -1024
}
Enumeration values for thread affinity.
enum Affinity {
NONE = 0, CORE = 1, SOCKET = -65536, SOCKET_MAX = -1024,
NONE = 0, CORE = 1, SOCKET = -65536, SOCKET_MAX = -1024
}
Enumeration values for thread affinity.
Static Public Member Functions inherited from lunchbox::Thread
static LUNCHBOX_API ThreadID getSelfThreadID ()
static LUNCHBOX_API void yield ()
static void pinCurrentThread ()
static LUNCHBOX_API void setName (const std::string &name)
static LUNCHBOX_API void setAffinity (const int32_t affinity)
static LUNCHBOX_API ThreadID getSelfThreadID ()
static LUNCHBOX_API void yield ()
static void pinCurrentThread ()
static LUNCHBOX_API void setName (const std::string &name)
static LUNCHBOX_API void setAffinity (const int32_t affinity)
Detailed Description
Definition at line 172 of file lfVector.cpp.
Member Function Documentation
virtual void Eraser::run () inline virtual
The entry function for the child thread.
This method should contain the main execution routine for the thread and is called after a successful init().
Version
1.0
Implements lunchbox::Thread.
Definition at line 178 of file lfVector.cpp.
References lunchbox::LFVector< T, nSlots >::begin(), lunchbox::LFVector< T, nSlots >::end(), lunchbox::LFVector< T, nSlots >::erase(), lunchbox::Clock::getTimef(), and lunchbox::LFVector< T, nSlots >::size().
The documentation for this class was generated from the following file:
lfVector.cpp