var files =
[
    [ "api.h", "api_8h.html", "api_8h" ],
    [ "gpu/dns_sd/api.h", "gpu_2dns__sd_2api_8h.html", "gpu_2dns__sd_2api_8h" ],
    [ "gpu/glx/api.h", "gpu_2glx_2api_8h.html", "gpu_2glx_2api_8h" ],
    [ "net/dns_sd/api.h", "net_2dns__sd_2api_8h.html", "net_2dns__sd_2api_8h" ],
    [ "net/sys/api.h", "net_2sys_2api_8h.html", "net_2sys_2api_8h" ],
    [ "defines.h", "defines_8h.html", null ],
    [ "definesLinux.h", "defines_linux_8h_source.html", null ],
    [ "gpu/dns_sd/dns_sd.h", "gpu_2dns__sd_2dns__sd_8h_source.html", null ],
    [ "net/dns_sd/dns_sd.h", "net_2dns__sd_2dns__sd_8h_source.html", null ],
    [ "filter.h", "filter_8h_source.html", null ],
    [ "functions.h", "functions_8h_source.html", null ],
    [ "glx.h", "glx_8h_source.html", null ],
    [ "gpuInfo.h", "gpu_info_8h_source.html", null ],
    [ "hwsd.h", "hwsd_8h_source.html", null ],
    [ "gpu/dns_sd/module.h", "gpu_2dns__sd_2module_8h_source.html", null ],
    [ "gpu/glx/module.h", "gpu_2glx_2module_8h_source.html", null ],
    [ "module.h", "module_8h_source.html", null ],
    [ "net/dns_sd/module.h", "net_2dns__sd_2module_8h_source.html", null ],
    [ "net/sys/module.h", "net_2sys_2module_8h_source.html", null ],
    [ "module.ipp", "module_8ipp_source.html", null ],
    [ "netInfo.h", "net_info_8h_source.html", null ],
    [ "nodeInfo.h", "node_info_8h_source.html", null ],
    [ "sys.h", "sys_8h_source.html", null ],
    [ "types.h", "types_8h_source.html", null ],
    [ "gpu/dns_sd/version.h", "gpu_2dns__sd_2version_8h.html", "gpu_2dns__sd_2version_8h" ],
    [ "gpu/glx/version.h", "gpu_2glx_2version_8h.html", "gpu_2glx_2version_8h" ],
    [ "net/dns_sd/version.h", "net_2dns__sd_2version_8h.html", "net_2dns__sd_2version_8h" ],
    [ "net/sys/version.h", "net_2sys_2version_8h.html", "net_2sys_2version_8h" ],
    [ "version.h", "version_8h.html", "version_8h" ]
];