Collage: co::RSPConnection Class Reference
co::RSPConnection Class Reference
A reliable multicast connection.
#include <rspConnection.h>
Public Member Functions
RSPConnection ()
Create a new RSP-based connection.
bool listen () override
Put the connection into the listening state.
void close () override
Close a connected or listening connection.
bool connect () override
Identical to listen() for multicast connections.
void acceptNB () override
Start an accept operation.
ConnectionPtr acceptSync () override
Complete an accept operation.
void readNB (void *, const uint64_t) override
Start a read operation on the connection.
int64_t readSync (void *buffer, const uint64_t bytes, const bool ignored) override
Finish reading data from the connection.
int64_t write (const void *buffer, const uint64_t bytes) override
Write data to the connection.
void finish () override
int64_t getSendRate () const
uint16_t getID () const
Notifier getNotifier () const override
Public Member Functions inherited from co::Connection
CO_API State getState () const
bool isClosed () const
bool isClosing () const
bool isConnected () const
bool isListening () const
CO_API bool isMulticast () const
CO_API
ConstConnectionDescriptionPtr getDescription () const
bool operator== (const Connection &rhs) const
void addListener (ConnectionListener *listener)
void removeListener (ConnectionListener *listener)
CO_API void recvNB (BufferPtr buffer, const uint64_t bytes)
Start a read operation on the connection.
CO_API bool recvSync (BufferPtr &buffer, const bool block=true)
Finish reading data from the connection.
BufferPtr resetRecvData ()
CO_API bool send (const void *buffer, const uint64_t bytes, const bool isLocked=false)
Send data using the connection.
CO_API void lockSend () const
Lock the connection, no other thread can send data.
CO_API void unlockSend () const
Unlock the connection.
Additional Inherited Members
Public Types inherited from co::Connection
enum State {
STATE_CLOSED, STATE_CONNECTING, STATE_CONNECTED, STATE_LISTENING,
STATE_CLOSING
}
The current state of the Connection.
typedef int Notifier
The Notifier used by the ConnectionSet to detect readiness of a Connection.
Static Public Member Functions inherited from co::Connection
static CO_API ConnectionPtr create (ConnectionDescriptionPtr desc)
Create a new connection.
Protected Types inherited from co::Connection
enum ReadStatus { READ_TIMEOUT = -2, READ_ERROR = -1 }
< error codes for readSync()
Protected Member Functions inherited from co::Connection
Connection ()
Construct a new connection.
virtual ~Connection ()
Destruct this connection.
CO_API void _setDescription (ConnectionDescriptionPtr description)
CO_API void _setState (const State state)
CO_API ConnectionDescriptionPtr _getDescription ()
Detailed Description
A reliable multicast connection.
This connection implements a reliable stream protocol (RSP) over IP V4 UDP multicast. The RSP design document describes the high-level protocol.
Definition at line 50 of file rspConnection.h.
Constructor & Destructor Documentation
co::RSPConnection::RSPConnection ()
Create a new RSP-based connection.
Member Function Documentation
void co::RSPConnection::acceptNB () inline override virtual
Start an accept operation.
This method returns immediately. The Notifier will signal a new connection request, upon which acceptSync() should be used to finish the accept operation. Only one accept operation might be outstanding, that is, acceptSync() has to be called before the next acceptNB().
See Also
acceptSync()
Version
1.0
Reimplemented from co::Connection.
Definition at line 62 of file rspConnection.h.
References co::Connection::isListening().
ConnectionPtr co::RSPConnection::acceptSync () override virtual
Complete an accept operation.
Returns
the new connection, 0 on error.
Version
1.0
Reimplemented from co::Connection.
void co::RSPConnection::close () inline override virtual
Close a connected or listening connection.
Version
1.0
Reimplemented from co::Connection.
Definition at line 57 of file rspConnection.h.
bool co::RSPConnection::connect () inline override virtual
Identical to listen() for multicast connections.
Reimplemented from co::Connection.
Definition at line 60 of file rspConnection.h.
References listen().
Notifier co::RSPConnection::getNotifier () const inline override virtual
Returns
the notifier signaling events.
Version
1.0
Implements co::Connection.
Definition at line 84 of file rspConnection.h.
bool co::RSPConnection::listen () override virtual
Put the connection into the listening state.
The ConnectionDescription of this connection is used to identify the listening parameters.
Returns
true if the connection is listening for new incoming connections, false if not.
Version
1.0
Reimplemented from co::Connection.
Referenced by connect().
void co::RSPConnection::readNB (void * buffer, const uint64_t bytes) inline override virtual
Start a read operation on the connection.
This method is the low-level counterpart used by recvNB(), implemented by the concrete connection.
This function returns immediately. The operation's Notifier will signal data availability, upon which readSync() is used to finish the operation.
Parameters
buffer the buffer receiving the data.
bytes the number of bytes to read.
See Also
readSync()
Implements co::Connection.
Definition at line 65 of file rspConnection.h.
int64_t co::RSPConnection::readSync (void * buffer, const uint64_t bytes, const bool block) override virtual
Finish reading data from the connection.
This method is the low-level counterpart used by recvSync(), implemented by the concrete connection. It may return with a partial read.
Parameters
buffer the buffer receiving the data.
bytes the number of bytes to read.
block internal WAR parameter, ignore it in the implementation unless you know exactly why not.
Returns
the number of bytes read, or -1 upon error.
Implements co::Connection.
int64_t co::RSPConnection::write (const void * buffer, const uint64_t bytes) override virtual
Write data to the connection.
This method is the low-level counterpart used by send(), implemented by the concrete connection. It may return with a partial write.
Parameters
buffer the buffer containing the message.
bytes the number of bytes to write.
Returns
the number of bytes written, or -1 upon error.
Implements co::Connection.
The documentation for this class was generated from the following file:
rspConnection.h