Collage: co::WorkerThread< Q > Class Template Reference
co::WorkerThread< Q > Class Template Reference
A worker thread processing items out of a CommandQueue.
#include <worker.h>
Public Member Functions
WorkerThread (const size_t maxSize=ULONG_MAX)
Construct a new worker thread.
virtual ~WorkerThread ()
Destruct the worker.
Q * getWorkerQueue ()
Protected Member Functions
CO_WORKER_API void run () override
virtual bool stopRunning ()
virtual bool notifyIdle ()
Detailed Description
template<class Q>
class co::WorkerThread< Q >
A worker thread processing items out of a CommandQueue.
Definition at line 35 of file worker.h.
Constructor & Destructor Documentation
template<class Q > co::WorkerThread< Q >::WorkerThread (const size_t maxSize = ULONG_MAX) [inline]
Construct a new worker thread.
Version:
1.0
Definition at line 39 of file worker.h.
template<class Q > virtual co::WorkerThread< Q >::~WorkerThread () [inline, virtual]
Destruct the worker.
Version:
1.0
Definition at line 42 of file worker.h.
Member Function Documentation
template<class Q > Q* co::WorkerThread< Q >::getWorkerQueue () [inline]
Returns:
the queue to the worker thread.
Version:
1.0
Definition at line 45 of file worker.h.
template<class Q > virtual bool co::WorkerThread< Q >::notifyIdle () [inline, protected, virtual]
Returns:
true to indicate pending idle tasks.
Version:
1.0
Definition at line 55 of file worker.h.
Referenced by co::WorkerThread< Q >::run().
template<class Q > void co::WorkerThread< Q >::run () [inline, override, protected]
See also:
lunchbox::Thread::run()
Definition at line 25 of file worker.ipp.
References co::WorkerThread< Q >::notifyIdle(), and co::WorkerThread< Q >::stopRunning().
template<class Q > virtual bool co::WorkerThread< Q >::stopRunning () [inline, protected, virtual]
Returns:
true to stop the worker thread.
Version:
1.0
Definition at line 52 of file worker.h.
Referenced by co::WorkerThread< Q >::run().
The documentation for this class was generated from the following files:
worker.h
worker.ipp