set(COLLAGE_MATURITY EP)
set(COLLAGE_DESCRIPTION "High-performance C++ library for developing object-oriented distributed applications.")
set(COLLAGE_GIT_ROOT_URL https://github.com/Eyescale/Collage.git)
set(COLLAGE_PACKAGE_URL https://launchpad.net/~eilemann/+archive/equalizer-dev)
set(COLLAGE_CI_URL https://travis-ci.org/Eyescale/Collage)
set(COLLAGE_CI_PNG https://travis-ci.org/Eyescale/Collage.png)
set(COLLAGE_ISSUES_URL https://github.com/Eyescale/Collage/issues)
