# Site settings
title: Eyescale Software Directory
organization: Eyescale

# Build settings
markdown: kramdown

# Do not exclude doxygen files starting with an underscore
include: [ _*.html ]

# Link to other documentation pages
seealso: www.equalizergraphics.com

# The collection of documentation metadata
collections:
  - projects
