# Site settings
title: Eyescale Software Directory
organization: Eyescale

# Build settings
markdown: kramdown

# Do not exclude doxygen files starting with an underscore
include: [ _*.html ]

# The collection of documentation metadata
collections:
  - projects
