Equalizer: eq::Channel Class Reference
eq::Channel Class Reference
A channel represents a two-dimensional viewport within a Window.
#include <channel.h>
Public Member Functions
Channel (Window *parent)
Construct a new channel.
virtual ~Channel ()
Destruct the channel.
virtual bool processEvent (const Event &event)
Process a received event.
virtual void drawStatistics ()
Draw a statistics overlay.
virtual void outlineViewport ()
Outline the current pixel viewport.
void changeLatency (const uint32_t latency)
Data Access
co::CommandQueue * getPipeThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
uint32_t getCurrentFrame () const
void waitFrameFinished (const uint32_t frame) const
bool isStopped () const
Pipe * getPipe ()
const Pipe * getPipe () const
Node * getNode ()
const Node * getNode () const
Config * getConfig ()
const Config * getConfig () const
ServerPtr getServer ()
const GLEWContext * glewGetContext () const
Get the GLEW context for this channel.
ObjectManager * getObjectManager ()
const DrawableConfig & getDrawableConfig () const
View * getNativeView ()
Get the channel's native view.
const View * getNativeView () const
const-version of getNativeView()
util::FrameBufferObject * getFrameBufferObject ()
const Vector3ub & getUniqueColor () const
void addStatistic (Event &event)
Context-specific data access.
The data returned by these methods depends on the context (callback) they are called from, typically the data for the current rendering task.
If they are called outside of a frame task method, they return the channel's native parameter or a placeholder value for the task decomposition parameters.
virtual Vector2f getJitter () const
const Frames & getInputFrames ()
const Frames & getOutputFrames ()
View * getView ()
Get the channel's current View.
const View * getView () const
Const version of getView().
Frustumf getScreenFrustum () const
Returns an orthographic frustum for 2D operations on the view.
Operations
Operations are only meaningful from within certain callbacks.
They are just convenience wrappers applying context-specific data to the OpenGL state using the context-specific data access above.
virtual void applyBuffer ()
Apply the current rendering buffer, including the color mask.
virtual void applyColorMask () const
Apply the current color mask.
virtual void applyViewport () const
Apply the OpenGL viewport for the current rendering task.
virtual void applyFrustum () const
Apply the frustum matrix for the current rendering task.
virtual void applyPerspective () const
Apply the perspective frustum matrix for the current rendering task.
virtual void applyOrtho () const
Apply the orthographic frustum matrix for the current rendering task.
void applyScreenFrustum () const
Apply an orthographic frustum for pixel-based 2D operations.
virtual void applyHeadTransform () const
Apply the transformation to position the view frustum.
virtual void applyPerspectiveTransform () const
Apply the transformation to position the perspective view frustum.
virtual void applyOrthoTransform () const
Apply the transformation to position the orthographic view frustum.
virtual void applyFrameBufferObject ()
Apply the current alternate frame buffer.
void bindFrameBuffer ()
Rebind the current alternate FBO of the channel or window.
Region of Interest.
virtual void resetRegions ()
Reset the declared regions of interest.
virtual void declareRegion (const eq::PixelViewport &region)
Declare a region covered by the current draw or assemble operation.
void declareRegion (const eq::Viewport &vp)
Convenience method to declare a region in relative coordinates.
PixelViewport getRegion () const
const PixelViewports & getRegions () const
Get the current regions of interest.
Public Member Functions inherited from eq::fabric::Channel< Window, Channel >
virtual bool omitOutput () const
virtual void output (std::ostream &) const
void init ()
Window * getWindow ()
const Window * getWindow () const
bool isDestination () const
void setViewVersion (const co::ObjectVersion &view)
const co::ObjectVersion & getViewVersion () const
void setPixelViewport (const PixelViewport &pvp)
EQFABRIC_INL void setViewport (const Viewport &vp)
const PixelViewport & getNativePixelViewport () const
bool hasFixedViewport () const
EQFABRIC_INL void setNearFar (const float nearPlane, const float farPlane)
Set the near and far planes for this channel.
uint32_t getDrawable () const
EQFABRIC_INL VisitorResult accept (Visitor &visitor)
Perform a depth-first traversal of this channel.
EQFABRIC_INL VisitorResult accept (Visitor &visitor) const
Const-version of accept().
EQFABRIC_INL void setCapabilities (const uint64_t bitmask)
Set the capabilities supported by the channel.
EQFABRIC_INL uint64_t getCapabilities () const
EQFABRIC_INL void setMaxSize (const Vector2i &size)
void setOverdraw (const Vector4i &overdraw)
const Vector2i & getMaxSize () const
EQFABRIC_INL ChannelPath getPath () const
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
uint32_t getDrawBuffer () const
uint32_t getReadBuffer () const
const ColorMask & getDrawBufferMask () const
const PixelViewport & getPixelViewport () const
virtual bool useOrtho () const
Select perspective or orthographic rendering.
const Frustumf & getFrustum () const
const Frustumf & getPerspective () const
const Frustumf & getOrtho () const
const Matrix4f & getHeadTransform () const
Return the view matrix.
const Matrix4f & getPerspectiveTransform () const
Return the perspective view matrix.
const Matrix4f & getOrthoTransform () const
Return the orthographic view matrix.
const Viewport & getViewport () const
const Range & getRange () const
const Pixel & getPixel () const
const SubPixel & getSubPixel () const
const Zoom & getZoom () const
uint32_t getPeriod () const
uint32_t getPhase () const
const Vector2i & getPixelOffset () const
Get the channel's current position wrt the destination channel.
Eye getEye () const
const Vector4i & getOverdraw () const
uint32_t getTaskID () const
EQFABRIC_INL int32_t getIAttribute (const IAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual bool isDirty () const
virtual uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
void setError (const int32_t error)
Set an error code why the last operation failed.
eq::fabric::Error getError () const
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Public Member Functions inherited from co::Serializable
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
Public Member Functions inherited from co::Object
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API ObjectOCommand send (NodePtr node, const uint32_t cmd, const uint32_t instanceID=EQ_INSTANCE_ALL)
Send a command with optional data to object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (MasterCMCommand &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (ICommand &command)
Dispatch a command from the receiver thread to the registered queue.
Protected Member Functions
void attach (const UUID &id, const uint32_t instanceID)
virtual void frameTilesStart (const uint128_t &frameID)
Start a batch of tile rendering operations.
virtual void frameTilesFinish (const uint128_t &frameID)
Finish a batch of tile rendering operations.
virtual void notifyViewportChanged ()
Notification that parameters influencing the vp/pvp have changed.
virtual void notifyStopFrame (const uint32_t lastFrameNumber)
Notify interruption of the rendering.
Actions
void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the parent for a frame.
virtual void setupAssemblyState ()
Setup the OpenGL state for a readback or assemble operation.
virtual void resetAssemblyState ()
Reset the OpenGL state after an assembly operation.
Task Methods
The task methods (callbacks) are called by Equalizer during rendering to execute various rendering tasks.
Each task method has a useful default implementation, but at least frameDraw() is implemented by an application.
virtual bool configInit (const uint128_t &initID)
Initialize this channel.
virtual bool configExit ()
Exit this channel.
virtual void frameStart (const uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
virtual void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
virtual void frameClear (const uint128_t &frameID)
Clear the frame buffer.
virtual void frameDraw (const uint128_t &frameID)
Draw the scene.
virtual void frameAssemble (const uint128_t &frameID)
Assemble all input frames.
virtual void frameReadback (const uint128_t &frameID)
Read back the rendered frame buffer into the output frames.
virtual void frameViewStart (const uint128_t &frameID)
Start updating a destination channel.
virtual void frameViewFinish (const uint128_t &frameID)
Finish updating a destination channel.
Protected Member Functions inherited from eq::fabric::Channel< Window, Channel >
EQFABRIC_INL Channel (Window *parent)
Construct a new channel.
Channel (const Channel &from)
Construct a copy of a channel (view/segment dest).
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
Worker for pack() and getInstanceData().
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
Worker for unpack() and applyInstanceData().
virtual EQFABRIC_INL void setDirty (const uint64_t bits)
Add dirty flags to mark data for distribution.
void setDrawable (const uint32_t drawable)
void setIAttribute (const IAttribute attr, const int32_t value)
virtual ChangeType getChangeType () const
virtual uint64_t getRedistributableBits () const
virtual void updateCapabilities ()
void overrideContext (RenderContext &context)
void resetRenderContext ()
const RenderContext & getContext () const
const RenderContext & getNativeContext () const
Protected Member Functions inherited from eq::fabric::Object
Object ()
Construct a new Object.
virtual ~Object ()
Destruct the object.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
void setTasks (const uint32_t tasks)
virtual void notifyDetach ()
Notify that this object will be deregistered or unmapped.
void postRemove (Object *child)
virtual void removeChild (const UUID &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
bool _cmdSync (co::ICommand &command)
Protected Member Functions inherited from co::Serializable
CO_API Serializable ()
Construct a new Serializable.
CO_API Serializable (const Serializable &)
Construct an unmapped, unregistered copy of an serializable.
virtual CO_API ~Serializable ()
Destruct the serializable.
virtual CO_API void unsetDirty (const uint64_t bits)
Remove dirty flags to clear data from distribution.
virtual CO_API void notifyAttached ()
Notify that this object has been registered or mapped.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (ICommand &command)
The default handler for handling commands.
Friends
class fabric::Window< Pipe, Window, Channel >
Additional Inherited Members
Static Public Member Functions inherited from eq::fabric::Channel< Window, Channel >
static EQFABRIC_INL const
std::string & getIAttributeString (const IAttribute attr)
Public Types inherited from eq::fabric::Channel< Window, Channel >
enum Drawable
The drawable format defines the components used as an alternate drawable for this cannel.
typedef LeafVisitor< Channel > Visitor
The channel visitor type.
typedef Window Parent
The parent window type.
enum IAttribute
Integer attributes for a channel.
Public Types inherited from eq::fabric::Object
Protected Types inherited from eq::fabric::Channel< Window, Channel >
enum DirtyBits
The changed parts of the object since the last pack().
Detailed Description
A channel represents a two-dimensional viewport within a Window.
The channel is the basic rendering entity. It represents a 2D rendering area within a Window. It executes all rendering-relevant tasks, such as clear, draw, assemble and readback. Each rendering task is using its own RenderContext, which is computed by the server based on the rendering description of the current configuration.
See also:
fabric::Channel
Definition at line 43 of file include/eq/client/channel.h.
Constructor & Destructor Documentation
eq::Channel::Channel (Window * parent)
Construct a new channel.
Version:
1.0
Reimplemented in osgScaleViewer::Channel, eqPly::Channel, eVolve::Channel, eqAsync::Channel, eqNbody::Channel, and eqPixelBench::Channel.
virtual eq::Channel::~Channel () virtual
Destruct the channel.
Version:
1.0
Reimplemented from eq::fabric::Channel< Window, Channel >.
Reimplemented in eqPly::Channel, eVolve::Channel, eqNbody::Channel, and eqPixelBench::Channel.
Member Function Documentation
virtual void eq::Channel::applyBuffer () virtual
Apply the current rendering buffer, including the color mask.
See also:
getReadBuffer() , getDrawBuffer(), getDrawBufferMask()
Version:
1.0
Referenced by eqPly::Channel::frameAssemble(), eVolve::Channel::frameClear(), eqPly::Channel::frameClear(), eqPixelBench::Channel::frameDraw(), eVolve::Channel::frameDraw(), eqPly::Channel::frameViewFinish(), and osgScaleViewer::Channel::frameViewFinish().
virtual void eq::Channel::applyColorMask () const virtual
Apply the current color mask.
See also:
applyBuffer(), getDrawBufferMask()
Version:
1.0
virtual void eq::Channel::applyFrameBufferObject () virtual
Apply the current alternate frame buffer.
Version:
1.0
virtual void eq::Channel::applyFrustum () const virtual
Apply the frustum matrix for the current rendering task.
If a sub-pixel decomposition is defined, the frustum is jittered by the amount given by getJitter() to implement software anti-aliasing. Applications which want to implement a different multi-sampling algorithm, e.g., depth-of-field, have to re-implement getJitter() or applyFrustum() accordingly.
See also:
useOrtho(), getJitter(), getSubPixel()
Version:
1.0
Referenced by eqPixelBench::Channel::frameDraw(), and eVolve::Channel::frameDraw().
virtual void eq::Channel::applyHeadTransform () const virtual
Apply the transformation to position the view frustum.
Version:
1.0
See also:
useOrtho()
Referenced by eqPixelBench::Channel::frameDraw(), and eVolve::Channel::frameDraw().
virtual void eq::Channel::applyOrtho () const virtual
Apply the orthographic frustum matrix for the current rendering task.
Version:
1.0
virtual void eq::Channel::applyOrthoTransform () const virtual
Apply the transformation to position the orthographic view frustum.
Version:
1.0
virtual void eq::Channel::applyPerspective () const virtual
Apply the perspective frustum matrix for the current rendering task.
Version:
1.0
virtual void eq::Channel::applyPerspectiveTransform () const virtual
Apply the transformation to position the perspective view frustum.
Version:
1.0
void eq::Channel::applyScreenFrustum () const
Apply an orthographic frustum for pixel-based 2D operations.
One unit of the frustum covers one pixel on screen. The frustum is positioned relative to the view.
Version:
1.0
virtual void eq::Channel::applyViewport () const virtual
Apply the OpenGL viewport for the current rendering task.
See also:
getViewport()
Version:
1.0
Referenced by eqPly::Channel::frameAssemble(), eVolve::Channel::frameClear(), eqPly::Channel::frameClear(), eqPixelBench::Channel::frameDraw(), eVolve::Channel::frameDraw(), eqPly::Channel::frameViewFinish(), and osgScaleViewer::Channel::frameViewFinish().
void eq::Channel::bindFrameBuffer ()
Rebind the current alternate FBO of the channel or window.
Version:
1.0
virtual bool eq::Channel::configExit () protected virtual
Exit this channel.
Version:
1.0
Reimplemented in eqPly::Channel, and eqPixelBench::Channel.
virtual bool eq::Channel::configInit (const uint128_t & initID) protected virtual
Initialize this channel.
Parameters:
initID the init identifier.
Version:
1.0
Reimplemented in eqPly::Channel, eVolve::Channel, and eqNbody::Channel.
Referenced by eqNbody::Channel::configInit(), eVolve::Channel::configInit(), and eqPly::Channel::configInit().
virtual void eq::Channel::declareRegion (const eq::PixelViewport & region) virtual
Declare a region covered by the current draw or assemble operation.
The region is relative to the current pixel viewport. It is clipped against the current pixel viewport of the channel. Called with the full pixel viewport after frameDraw if no region has been declared. The implementation might merge or split the declared regions.
Version:
1.3
void eq::Channel::declareRegion (const eq::Viewport & vp)
Convenience method to declare a region in relative coordinates.
The given viewport is relative to the current pixel viewport.
Version:
1.3
virtual void eq::Channel::drawStatistics () virtual
Draw a statistics overlay.
Version:
1.0
Referenced by eqPly::Channel::frameViewFinish(), and osgScaleViewer::Channel::frameViewFinish().
virtual void eq::Channel::frameAssemble (const uint128_t & frameID) protected virtual
Assemble all input frames.
Called 0 to n times during one frame.
Parameters:
frameID the per-frame identifier.
See also:
getInputFrames()
Version:
1.0
Reimplemented in eqPly::Channel, and eVolve::Channel.
virtual void eq::Channel::frameClear (const uint128_t & frameID) protected virtual
Clear the frame buffer.
Called 0 to n times during one frame.
Parameters:
frameID the per-frame identifier.
Version:
1.0
Reimplemented in osgScaleViewer::Channel, eqPly::Channel, and eVolve::Channel.
virtual void eq::Channel::frameDraw (const uint128_t & frameID) protected virtual
Draw the scene.
Called 0 to n times during one frame.
Parameters:
frameID the per-frame identifier.
Version:
1.0
Reimplemented in osgScaleViewer::Channel, eqPly::Channel, eVolve::Channel, eqNbody::Channel, eqPixelBench::Channel, and eqAsync::Channel.
virtual void eq::Channel::frameDrawFinish (const uint128_t & frameID, const uint32_t frameNumber) protected virtual
Finish drawing.
Called once per frame after the last draw operation. Typically releases the local node thread synchronization for this frame.
Parameters:
frameID the per-frame identifier.
frameNumber the frame to finished with draw.
Version:
1.0
virtual void eq::Channel::frameFinish (const uint128_t & frameID, const uint32_t frameNumber) protected virtual
Finish rendering a frame.
Called once at the end of each frame, to do per-frame updates of channel-specific data. This method has to call releaseFrame().
Parameters:
frameID the per-frame identifier.
frameNumber the frame to finish.
Version:
1.0
Reimplemented in eqPly::Channel.
virtual void eq::Channel::frameReadback (const uint128_t & frameID) protected virtual
Read back the rendered frame buffer into the output frames.
Called 0 to n times during one frame.
Parameters:
frameID the per-frame identifier.
See also:
getOutputFrames()
Version:
1.0
Reimplemented in eqPly::Channel, and eVolve::Channel.
virtual void eq::Channel::frameStart (const uint128_t & frameID, const uint32_t frameNumber) protected virtual
Start rendering a frame.
Called once at the beginning of each frame, to do per-frame updates of channel-specific data. This method has to call startFrame().
Parameters:
frameID the per-frame identifier.
frameNumber the frame to start.
See also:
Config::startFrame()
Version:
1.0
Reimplemented in eqPly::Channel, eVolve::Channel, and eqPixelBench::Channel.
virtual void eq::Channel::frameTilesFinish (const uint128_t & frameID) inline protected virtual
Finish a batch of tile rendering operations.
Version:
1.1.6
Definition at line 543 of file include/eq/client/channel.h.
virtual void eq::Channel::frameTilesStart (const uint128_t & frameID) inline protected virtual
Start a batch of tile rendering operations.
Version:
1.1.6
Definition at line 540 of file include/eq/client/channel.h.
virtual void eq::Channel::frameViewFinish (const uint128_t & frameID) protected virtual
Finish updating a destination channel.
Called once on each destination channel, e.g., channels which are defined by a view/segment intersection, before frameFinish to update a part of a view.
This is typically used to do operations on the output channel after it has been fully updated, e.g., to draw a 2D overlay.
Parameters:
frameID the per-frame identifier.
Version:
1.0
Reimplemented in eqPly::Channel, osgScaleViewer::Channel, and eVolve::Channel.
virtual void eq::Channel::frameViewStart (const uint128_t & frameID) protected virtual
Start updating a destination channel.
Called once on each destination channel, e.g., channels which are defined by a view/segment intersection, after frameStart to update a part of a display.
Parameters:
frameID the per-frame identifier.
Version:
1.0
Reimplemented in eqPly::Channel.
Config* eq::Channel::getConfig ()
Returns:
the parent config.
Version:
1.0
Referenced by eqNbody::Channel::configInit(), eqPixelBench::Channel::frameStart(), and eqPly::Channel::frameViewFinish().
const Config* eq::Channel::getConfig () const
Returns:
the parent config.
Version:
1.0
const DrawableConfig& eq::Channel::getDrawableConfig () const
Returns:
the channel's drawable config.
Version:
1.0
Referenced by eqPixelBench::Channel::Channel(), and eVolve::Channel::frameAssemble().
util::FrameBufferObject* eq::Channel::getFrameBufferObject ()
Returns:
the FBO used as an alternate frame buffer.
Version:
1.0
const Frames& eq::Channel::getInputFrames ()
Returns:
the list of input frames, used from frameAssemble().
Version:
1.0
Referenced by eVolve::Channel::frameAssemble(), and eqPly::Channel::frameAssemble().
virtual Vector2f eq::Channel::getJitter () const virtual
Returns:
the jitter vector for the current subpixel decomposition.
Version:
1.0
Reimplemented in eqPly::Channel.
Referenced by eqPly::Channel::getJitter().
View* eq::Channel::getNativeView ()
Get the channel's native view.
This function always returns the channel's native view, no matter in which context it is called. Only destination channels have a native view.
Returns:
the channel's native view, or 0 if it does not have one.
See also:
getView()
Version:
1.0
const View* eq::Channel::getNativeView () const
const-version of getNativeView()
Version:
1.0
Node* eq::Channel::getNode ()
Returns:
the parent node.
Version:
1.0
const Node* eq::Channel::getNode () const
Returns:
the parent node.
Version:
1.0
ObjectManager* eq::Channel::getObjectManager ()
Returns:
the window's object manager instance.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble().
const Frames& eq::Channel::getOutputFrames ()
Returns:
the list of output frames, used from frameReadback().
Version:
1.0
Referenced by eVolve::Channel::frameReadback(), and eqPly::Channel::frameReadback().
Pipe* eq::Channel::getPipe ()
Returns:
the parent pipe.
Version:
1.0
Referenced by eqNbody::Channel::configInit(), eqAsync::Channel::frameDraw(), eqNbody::Channel::frameDraw(), eVolve::Channel::frameDraw(), osgScaleViewer::Channel::frameDraw(), and osgScaleViewer::Channel::frameViewFinish().
const Pipe* eq::Channel::getPipe () const
Returns:
the parent pipe.
Version:
1.0
PixelViewport eq::Channel::getRegion () const
Returns:
a region covering all declared regions.
Version:
1.3
const PixelViewports& eq::Channel::getRegions () const
Get the current regions of interest.
The returned regions are guaranteed not to overlap with each other. Therefore they may differ in number and size from the declared regions. The actual algorithm to create the non-overlapping regions is unspecified and may change in the future.
Returns:
current regions of interest.
Version:
1.3
Referenced by eVolve::Channel::frameAssemble().
Frustumf eq::Channel::getScreenFrustum () const
Returns an orthographic frustum for 2D operations on the view.
One unit of the frustum covers one pixel on screen. The frustum is positioned relative to the view.
Returns:
the 2D orthographic frustum.
Version:
1.0
ServerPtr eq::Channel::getServer ()
Returns:
the parent server.
Version:
1.0
const Vector3ub& eq::Channel::getUniqueColor () const
Returns:
a fixed unique color for this channel.
Version:
1.0
Referenced by eqPly::Channel::frameClear(), eVolve::Channel::frameDraw(), eqPly::Channel::frameDraw(), and eVolve::Channel::frameStart().
View* eq::Channel::getView ()
Get the channel's current View.
During a frame task method, i.e., in one of the frameFoo functions, the view is set to the view of the destination channel, that is, the channel for which this channel is executing the rendering task. Outside of a frame task method the native view of the channel, or 0, is returned.
Returns:
the channel's view, or 0 if it does not have a view.
See also:
getNativeView()
Version:
1.0
Referenced by eqPly::Channel::frameClear(), eqPly::Channel::frameViewFinish(), and eqPly::Channel::getJitter().
const View* eq::Channel::getView () const
Const version of getView().
Version:
1.0
const GLEWContext* eq::Channel::glewGetContext () const
Get the GLEW context for this channel.
The GLEW context is initialized during window initialization, and provides access to OpenGL extensions. This function does not follow the Equalizer naming conventions, since GLEW uses a function of this name to automatically resolve OpenGL function entry points. Therefore, any supported GL function can be called directly from an initialized Channel.
Returns:
the extended OpenGL function table for the channel's OpenGL context.
Version:
1.0
Referenced by eqNbody::Channel::Channel().
bool eq::Channel::isStopped () const
Returns:
true if this channel is stopped, false otherwise.
Version:
1.0
virtual void eq::Channel::notifyStopFrame (const uint32_t lastFrameNumber) inline protected virtual
Notify interruption of the rendering.
This method is called from the Client command thread, as opposed to the rendering thread. Its purpose is to cause the rendering thread to stop its operations as soon as possible. Normal rendering shall recommence after the given frame.
Parameters:
lastFrameNumber stop rendering until this frame has been processed.
Version:
1.0
Reimplemented in eqPly::Channel.
Definition at line 560 of file include/eq/client/channel.h.
virtual void eq::Channel::notifyViewportChanged () protected virtual
Notification that parameters influencing the vp/pvp have changed.
Reimplemented from eq::fabric::Channel< Window, Channel >.
virtual void eq::Channel::outlineViewport () virtual
Outline the current pixel viewport.
Version:
1.0
Referenced by eqNbody::Channel::frameDraw(), and eVolve::Channel::frameDraw().
virtual bool eq::Channel::processEvent (const Event & event) virtual
Process a received event.
The task of this method is to update the channel as necessary, and transform the event into an config event to be send to the application using Config::sendEvent().
Parameters:
event the received event.
Returns:
true when the event was handled, false if not.
Version:
1.0
void eq::Channel::releaseFrame (const uint32_t frameNumber) protected
Signal the completion of a frame to the parent.
Parameters:
frameNumber the frame to end.
Version:
1.0
void eq::Channel::releaseFrameLocal (const uint32_t frameNumber) protected
Release the local synchronization of the parent for a frame.
Parameters:
frameNumber the frame to release.
Version:
1.0
virtual void eq::Channel::resetAssemblyState () protected virtual
Reset the OpenGL state after an assembly operation.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble(), eqPly::Channel::frameAssemble(), eqPixelBench::Channel::frameDraw(), and eqPly::Channel::frameViewFinish().
virtual void eq::Channel::resetRegions () virtual
Reset the declared regions of interest.
Called from frameStart and frameClear to reset the area to be used to optimize compositing and load balancing for each frame.
Version:
1.3
Referenced by eqPly::Channel::frameClear().
virtual void eq::Channel::setupAssemblyState () protected virtual
Setup the OpenGL state for a readback or assemble operation.
The default implementation is very conservative and saves any state which is potentially changed by the assembly routines. Applications may overwrite this and resetAssemblyState() to optimize performance in accordance with their rendering code.
Version:
1.0
Referenced by eqPly::Channel::frameAssemble(), eqPixelBench::Channel::frameDraw(), and eqPly::Channel::frameViewFinish().
void eq::Channel::startFrame (const uint32_t frameNumber) protected
Start a frame by unlocking all child resources.
Parameters:
frameNumber the frame to start.
Version:
1.0
The documentation for this class was generated from the following file:
include/eq/client/channel.h