Equalizer: co::ICommand Class Reference
co::ICommand Class Reference
A class managing received commands.
#include <iCommand.h>
Public Member Functions
CO_API ICommand (LocalNodePtr local, NodePtr remote, ConstBufferPtr buffer, const bool swap)
CO_API ICommand (const ICommand &rhs)
CO_API ICommand & operator= (const ICommand &rhs)
CO_API void clear ()
Data Access
CO_API uint32_t getType () const
CO_API uint32_t getCommand () const
CO_API uint64_t getSize () const
template<typename T >
T get ()
CO_API NodePtr getNode () const
CO_API LocalNodePtr getLocalNode () const
CO_API bool isValid () const
CO_API ConstBufferPtr getBuffer () const
CO_API void setType (const CommandType type)
CO_API void setCommand (const uint32_t cmd)
void setDispatchFunction (const Dispatcher::Func &func)
CO_API bool operator() ()
Public Member Functions inherited from co::DataIStream
template<>
DataIStream & operator>> (std::string &str)
Read a std::string.
template<>
DataIStream & operator>> (Object *&object)
Deserialize an object (id+version).
template<>
DataIStream & operator>> (std::vector< uint8_t > &value)
Optimized specialization to read a std::vector of uint8_t.
template<>
DataIStream & operator>> (std::vector< uint16_t > &value)
Optimized specialization to read a std::vector of uint16_t.
template<>
DataIStream & operator>> (std::vector< int16_t > &value)
Optimized specialization to read a std::vector of int16_t.
template<>
DataIStream & operator>> (std::vector< uint32_t > &value)
Optimized specialization to read a std::vector of uint32_t.
template<>
DataIStream & operator>> (std::vector< int32_t > &value)
Optimized specialization to read a std::vector of int32_t.
template<>
DataIStream & operator>> (std::vector< uint64_t > &value)
Optimized specialization to read a std::vector of uint64_t.
template<>
DataIStream & operator>> (std::vector< int64_t > &value)
Optimized specialization to read a std::vector of int64_t.
template<>
DataIStream & operator>> (std::vector< float > &value)
Optimized specialization to read a std::vector of float.
template<>
DataIStream & operator>> (std::vector< double > &value)
Optimized specialization to read a std::vector of double.
template<>
DataIStream & operator>> (std::vector< ObjectVersion > &value)
Optimized specialization to read a std::vector of ObjectVersion.
virtual void reset ()
void setSwapping (const bool onOff)
CO_API bool isSwapping () const
DataIStream & operator= (const DataIStream &rhs)
template<class T >
DataIStream & operator>> (T &value)
Read a plain data item.
template<class T >
DataIStream & operator>> (Array< T > array)
Read a C array.
template<class T >
DataIStream & operator>> (lunchbox::Buffer< T > &)
Read a lunchbox::Buffer.
template<class T >
DataIStream & operator>> (std::vector< T > &)
Read a std::vector of serializable items.
template<class K , class V >
DataIStream & operator>> (std::map< K, V > &)
Read a std::map of serializable items.
template<class T >
DataIStream & operator>> (std::set< T > &)
Read a std::set of serializable items.
template<class K , class V >
DataIStream & operator>> (stde::hash_map< K, V > &)
Read a stde::hash_map of serializable items.
template<class T >
DataIStream & operator>> (stde::hash_set< T > &)
Read a stde::hash_set of serializable items.
template<typename O , typename C >
void deserializeChildren (O *object, const std::vector< C * > &old, std::vector< C * > &result)
CO_API const void * getRemainingBuffer (const uint64_t size)
CO_API uint64_t getRemainingBufferSize ()
bool hasData ()
Friends
CO_API std::ostream & operator<< (std::ostream &, const ICommand &)
Additional Inherited Members
Static Public Member Functions inherited from co::DataIStream
template<class T >
static void swap (T &v)
CO_IGNORE_BYTESWAP: If set, no byteswapping of transmitted data is performed.
Protected Member Functions inherited from co::DataIStream
CO_API DataIStream (const bool swap)
DataIStream (const DataIStream &)
virtual CO_API ~DataIStream ()
Detailed Description
A class managing received commands.
This class is used by the LocalNode to pass received buffers to the Dispatcher and ultimately command handler functions. It is not intended to be instantiated by applications. The derivates of this ICommand have to be instaniated by the application if the command type requires it. The data retrieval is possible with the provided DataIStream methods or with the templated get() function.
Definition at line 43 of file iCommand.h.
Member Function Documentation
template<typename T > T co::ICommand::get () inline
Returns
a value from the command.
Version
1.0
Definition at line 69 of file iCommand.h.
Referenced by eqPixelBench::Config::handleEvent(), eVolve::Config::handleEvent(), osgScaleViewer::Config::handleEvent(), and eqPly::Config::handleEvent().
CO_API uint32_t co::ICommand::getCommand () const
Returns
the command.
Version
1.0
CO_API LocalNodePtr co::ICommand::getLocalNode () const
Returns
the receiving node.
Version
1.0
CO_API NodePtr co::ICommand::getNode () const
Returns
the sending node proxy instance.
Version
1.0
CO_API uint64_t co::ICommand::getSize () const
Returns
the command payload size.
Version
1.0
CO_API uint32_t co::ICommand::getType () const
Returns
the command type.
Version
1.0
CO_API bool co::ICommand::isValid () const
Returns
true if the command has valid data.
Version
1.0
The documentation for this class was generated from the following file:
iCommand.h