Equalizer: eq::fabric::ElementVisitor< T, C > Class Template Reference
eq::fabric::ElementVisitor< T, C > Class Template Reference
A visitor to traverse non-leaf elements and their children in a tree.
#include <elementVisitor.h>
Public Member Functions
ElementVisitor ()
Construct a new visitor.
virtual ~ElementVisitor ()
Destruct the visitor.
virtual VisitorResult visitPre (T *element)
Visit an element on the down traversal.
virtual VisitorResult visitPost (T *element)
Visit an element on the up traversal.
virtual VisitorResult visitPre (const T *)
Visit an element on a const down traversal.
virtual VisitorResult visitPost (const T *)
Visit an element on a const up traversal.
Detailed Description
template<class T, class C>
class eq::fabric::ElementVisitor< T, C >
A visitor to traverse non-leaf elements and their children in a tree.
Definition at line 31 of file elementVisitor.h.
Constructor & Destructor Documentation
template<class T , class C > eq::fabric::ElementVisitor< T, C >::ElementVisitor () inline
Construct a new visitor.
Definition at line 35 of file elementVisitor.h.
template<class T , class C > virtual eq::fabric::ElementVisitor< T, C >::~ElementVisitor () inline virtual
Destruct the visitor.
Definition at line 38 of file elementVisitor.h.
Member Function Documentation
template<class T , class C > virtual VisitorResult eq::fabric::ElementVisitor< T, C >::visitPost (T * element) inline virtual
Visit an element on the up traversal.
Definition at line 45 of file elementVisitor.h.
References eq::fabric::ElementVisitor< T, C >::visitPost().
Referenced by eq::fabric::ElementVisitor< T, C >::visitPost().
template<class T , class C > virtual VisitorResult eq::fabric::ElementVisitor< T, C >::visitPost (const T *) inline virtual
Visit an element on a const up traversal.
Definition at line 53 of file elementVisitor.h.
References eq::fabric::TRAVERSE_CONTINUE.
template<class T , class C > virtual VisitorResult eq::fabric::ElementVisitor< T, C >::visitPre (T * element) inline virtual
Visit an element on the down traversal.
Definition at line 41 of file elementVisitor.h.
References eq::fabric::ElementVisitor< T, C >::visitPre().
Referenced by eq::fabric::ElementVisitor< T, C >::visitPre().
template<class T , class C > virtual VisitorResult eq::fabric::ElementVisitor< T, C >::visitPre (const T *) inline virtual
Visit an element on a const down traversal.
Definition at line 49 of file elementVisitor.h.
References eq::fabric::TRAVERSE_CONTINUE.
The documentation for this class was generated from the following file:
elementVisitor.h