Equalizer: eq::EventICommand Class Reference
eq::EventICommand Class Reference
A command specialization for config events.
#include <eventICommand.h>
Public Member Functions
EventICommand (const co::ICommand &command)
EventICommand (const EventICommand &rhs)
Copy-construct an event command.
~EventICommand ()
Destruct an event command.
uint32_t getEventType () const
Returns the event type.
Public Member Functions inherited from co::ObjectICommand
CO_API ObjectICommand (LocalNodePtr local, NodePtr remote, ConstBufferPtr buffer, const bool swap)
CO_API ObjectICommand (const ICommand &command)
CO_API ObjectICommand (const ObjectICommand &rhs)
Copy-construct an object command.
virtual CO_API ~ObjectICommand ()
Destruct an object command.
const UUID & getObjectID () const
uint32_t getInstanceID () const
Public Member Functions inherited from co::ICommand
CO_API ICommand (LocalNodePtr local, NodePtr remote, ConstBufferPtr buffer, const bool swap)
CO_API ICommand (const ICommand &rhs)
CO_API ICommand & operator= (const ICommand &rhs)
CO_API void clear ()
CO_API uint32_t getType () const
CO_API uint32_t getCommand () const
CO_API uint64_t getSize_ () const
CO_API ConstBufferPtr getBuffer () const
template<typename T >
T get ()
CO_API NodePtr getNode () const
CO_API LocalNodePtr getLocalNode () const
CO_API bool isValid () const
CO_API void setType (const CommandType type)
Change the command type for subsequent dispatching.
CO_API void setCommand (const uint32_t cmd)
Change the command for subsequent dispatching.
void setDispatchFunction (const Dispatcher::Func &func)
Set the function to which the command is dispatched.
CO_API bool operator() ()
Invoke and clear the command function of a dispatched command.
Public Member Functions inherited from co::DataIStream
template<>
DataIStream & operator>> (std::string &str)
Read a std::string.
template<>
DataIStream & operator>> (Object *&object)
Deserialize an object (id+version).
template<>
DataIStream & operator>> (std::vector< uint8_t > &value)
Optimized specialization to read a std::vector of uint8_t.
template<>
DataIStream & operator>> (std::vector< uint16_t > &value)
Optimized specialization to read a std::vector of uint16_t.
template<>
DataIStream & operator>> (std::vector< int16_t > &value)
Optimized specialization to read a std::vector of int16_t.
template<>
DataIStream & operator>> (std::vector< uint32_t > &value)
Optimized specialization to read a std::vector of uint32_t.
template<>
DataIStream & operator>> (std::vector< int32_t > &value)
Optimized specialization to read a std::vector of int32_t.
template<>
DataIStream & operator>> (std::vector< uint64_t > &value)
Optimized specialization to read a std::vector of uint64_t.
template<>
DataIStream & operator>> (std::vector< int64_t > &value)
Optimized specialization to read a std::vector of int64_t.
template<>
DataIStream & operator>> (std::vector< float > &value)
Optimized specialization to read a std::vector of float.
template<>
DataIStream & operator>> (std::vector< double > &value)
Optimized specialization to read a std::vector of double.
template<>
DataIStream & operator>> (std::vector< ObjectVersion > &value)
Optimized specialization to read a std::vector of ObjectVersion.
virtual void reset ()
void setSwapping (const bool onOff)
CO_API bool isSwapping () const
DataIStream & operator= (const DataIStream &rhs)
template<class T >
DataIStream & operator>> (T &value)
Read a plain data item.
template<class T >
DataIStream & operator>> (Array< T > array)
Read a C array.
template<class T >
DataIStream & operator>> (lunchbox::Buffer< T > &)
Read a lunchbox::Buffer.
template<class T >
DataIStream & operator>> (std::vector< T > &)
Read a std::vector of serializable items.
template<class K , class V >
DataIStream & operator>> (std::map< K, V > &)
Read a std::map of serializable items.
template<class T >
DataIStream & operator>> (std::set< T > &)
Read a std::set of serializable items.
template<class K , class V >
DataIStream & operator>> (stde::hash_map< K, V > &)
Read a stde::hash_map of serializable items.
template<class T >
DataIStream & operator>> (stde::hash_set< T > &)
Read a stde::hash_set of serializable items.
template<typename O , typename C >
void deserializeChildren (O *object, const std::vector< C * > &old, std::vector< C * > &result)
CO_API const void * getRemainingBuffer (const uint64_t size)
Get the pointer to the remaining data in the current buffer.
CO_API uint64_t getRemainingBufferSize ()
bool hasData ()
Detailed Description
A command specialization for config events.
Event commands are generated by Config::sendEvent and arrive in Config::handleEvent. User data can be extracted with the API provided by co::DataIStream. The user data sent with this command is added while sending the event.
Definition at line 38 of file eventICommand.h.
Constructor & Destructor Documentation
eq::EventICommand::EventICommand (const EventICommand & rhs)
Copy-construct an event command.
Version:
1.5.1
eq::EventICommand::~EventICommand ()
Destruct an event command.
Version:
1.5.1
Member Function Documentation
uint32_t eq::EventICommand::getEventType () const
Returns the event type.
The data extracted from this event has to match the data streamed to the EventOCommand by the event's sender. Equalizer events use an event type less than Event::USER. For those events, the data in this command is the eq::Event struct.
Returns:
the event type.
Version:
1.5.1
Referenced by eqPixelBench::Config::handleEvent(), eqNbody::Config::handleEvent(), eVolve::Config::handleEvent(), osgScaleViewer::Config::handleEvent(), and eqPly::Config::handleEvent().
The documentation for this class was generated from the following file:
eventICommand.h