Equalizer: eqNbody::Pipe Class Reference
eqNbody::Pipe Class Reference
Public Member Functions
Pipe (eq::Node *parent)
Construct a new pipe.
SharedData & getSharedData ()
Public Member Functions inherited from eq::Pipe
void waitExited () const
void notifyMapped ()
void waitFrameFinished (const uint32_t frameNumber) const
void waitFrameLocal (const uint32_t frameNumber) const
void startThread ()
void exitThread ()
void cancelThread ()
bool startTransferThread ()
bool hasTransferThread () const
virtual void setDirty (const uint64_t bits)
Add dirty flags to mark data for distribution.
co::CommandQueue * getPipeThreadQueue ()
co::CommandQueue * getMainThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
co::CommandQueue * getTransferThreadQueue ()
Config * getConfig ()
const Config * getConfig () const
ClientPtr getClient ()
ServerPtr getServer ()
bool isRunning () const
bool isStopped () const
uint32_t getCurrentFrame () const
Return the current frame number.
uint32_t getFinishedFrame () const
WindowSystem getWindowSystem () const
Return the window system used by this pipe.
void setSystemPipe (SystemPipe *pipe)
Set the system-specific pipe implementation.
SystemPipe * getSystemPipe ()
const SystemPipe * getSystemPipe () const
void setComputeContext (ComputeContext *ctx)
Set the compute-specific context.
const ComputeContext * getComputeContext () const
ComputeContext * getComputeContext ()
virtual MessagePump * createMessagePump ()
Create a new MessagePump for this pipe.
MessagePump * getMessagePump ()
Frame * getFrame (const co::ObjectVersion &frameVersion, const Eye eye, const bool output)
co::QueueSlave * getQueue (const UUID &queueID)
void flushFrames (ObjectManager *om)
const View * getView (const co::ObjectVersion &viewVersion) const
View * getView (const co::ObjectVersion &viewVersion)
Public Member Functions inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
Node * getNode ()
const Node * getNode () const
const Windows & getWindows () const
uint32_t getPort () const
Returns the port number of this pipe.
EQFABRIC_INL void setPort (const uint32_t port)
uint32_t getDevice () const
Returns the device number of this pipe.
EQFABRIC_INL void setDevice (const uint32_t device)
const PixelViewport & getPixelViewport () const
EQFABRIC_INL void setPixelViewport (const PixelViewport &pvp)
Set the pipe's pixel viewport.
void notifyPixelViewportChanged ()
EQFABRIC_INL PipePath getPath () const
EQFABRIC_INL VisitorResult accept (PipeVisitor &visitor)
Perform a depth-first traversal of this pipe.
EQFABRIC_INL VisitorResult accept (PipeVisitor &visitor) const
Const-version of accept().
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
void create (eq::Window **window)
void release (eq::Window *window)
virtual void output (std::ostream &) const
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
EQFABRIC_INL void setIAttribute (const IAttribute attr, const int32_t value)
int32_t getIAttribute (const IAttribute attr) const
bool isThreaded () const
Public Member Functions inherited from eq::fabric::Object
virtual bool isDirty () const
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
void setError (const int32_t error)
Set an error code why the last operation failed.
eq::fabric::Error getError () const
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Public Member Functions inherited from co::Serializable
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
Public Member Functions inherited from co::Object
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API ObjectOCommand send (NodePtr node, const uint32_t cmd, const uint32_t instanceID=EQ_INSTANCE_ALL)
Send a command with optional data to object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (MasterCMCommand &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (ICommand &command)
Dispatch a command from the receiver thread to the registered queue.
Protected Member Functions
virtual ~Pipe ()
Destruct the pipe.
virtual bool configInit (const eq::uint128_t &initID)
Initialize this pipe.
virtual bool configExit ()
De-initialize this pipe.
virtual void frameStart (const eq::uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
Protected Member Functions inherited from eq::Pipe
void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the parent for a frame.
virtual bool supportsWindowSystem (const WindowSystem ws) const
Tests wether a particular windowing system is supported by this pipe and all its windows.
virtual WindowSystem selectWindowSystem () const
Choose the window system to be used by this pipe.
virtual bool configInitSystemPipe (const uint128_t &initID)
Initialize the OS-specific pipe.
virtual void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
virtual void attach (const UUID &id, const uint32_t instanceID)
Detailed Description
Definition at line 39 of file share/Equalizer/examples/eqNBody/pipe.h.
Constructor & Destructor Documentation
eqNbody::Pipe::Pipe (eq::Node * parent)
Construct a new pipe.
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 41 of file eqNBody/pipe.cpp.
virtual eqNbody::Pipe::~Pipe () inline protected virtual
Destruct the pipe.
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 47 of file share/Equalizer/examples/eqNBody/pipe.h.
Member Function Documentation
bool eqNbody::Pipe::configExit () protected virtual
De-initialize this pipe.
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 69 of file eqNBody/pipe.cpp.
References eq::Pipe::getConfig(), and eq::Config::unmapObject().
bool eqNbody::Pipe::configInit (const eq::uint128_t & initID) protected virtual
Initialize this pipe.
Parameters:
initID the init identifier.
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 47 of file eqNBody/pipe.cpp.
References eq::Pipe::configInit(), eq::Pipe::getConfig(), and eq::Config::mapObject().
void eqNbody::Pipe::frameStart (const eq::uint128_t & frameID, const uint32_t frameNumber) protected virtual
Start rendering a frame.
Called once at the beginning of each frame, to do per-frame updates of pipe-specific data, for example updating the rendering engine. Waits for the node to start the frame, unless the thread model is async. If the thread model is async, the local synchronization is released immediately.
This method has to call startFrame().
Parameters:
frameID the per-frame identifier.
frameNumber the frame to start.
See also:
Config::startFrame(), Node::startFrame(), Node::waitFrameStarted()
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 81 of file eqNBody/pipe.cpp.
References co::Object::sync().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqNBody/pipe.h
eqNBody/pipe.cpp