Equalizer: eq::fabric::Frame Class Reference
eq::fabric::Frame Class Reference
A holder for a frame data and related parameters.
#include <frame.h>
Public Member Functions
Frame ()
Construct a new frame.
virtual ~Frame ()
Destruct the frame.
const std::vector< uint128_t > & getInputNodes (const Eye eye) const
const std::vector< uint128_t > & getInputNetNodes (const Eye eye) const
Data Access
void setName (const std::string &name)
Set the name of the frame.
const std::string & getName () const
const Vector2i & getOffset () const
void setOffset (const Vector2i &offset)
Set the position of the frame wrt the channel.
void setZoom (const Zoom &zoom)
Set the zoom for this frame holder.
const Zoom & getZoom () const
const co::ObjectVersion & getDataVersion (const Eye) const
Public Member Functions inherited from co::Object
CO_API Object ()
Construct a new distributed object.
virtual CO_API ~Object ()
Destruct the distributed object.
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
virtual bool isDirty () const
Return if this object needs a commit.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
virtual CO_API uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
virtual void pack (DataOStream &os)
Serialize the modifications since the last call to commit().
virtual void unpack (DataIStream &is)
Deserialize a change.
CO_API ObjectOCommand send (NodePtr node, const uint32_t cmd, const uint32_t instanceID=EQ_INSTANCE_ALL)
Send a command with optional data to object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyAttached ()
Notify that this object has been registered or mapped.
virtual CO_API void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (MasterCMCommand &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void attach (const UUID &id, const uint32_t instanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (ICommand &command)
Dispatch a command from the receiver thread to the registered queue.
Public Types
enum Buffer {
BUFFER_NONE = LB_BIT_NONE, BUFFER_UNDEFINED = LB_BIT1, BUFFER_COLOR = LB_BIT5, BUFFER_DEPTH = LB_BIT9,
BUFFER_ALL = LB_BIT_ALL_32
}
The buffer format defines which components of the frame are to be used during readback and assembly.
enum Type { TYPE_MEMORY, TYPE_TEXTURE }
The storage type for pixel data.
Public Types inherited from co::Object
enum ChangeType {
NONE, STATIC, INSTANCE, DELTA,
UNBUFFERED
}
Object change handling characteristics, see Programming Guide.
Public Types inherited from co::Dispatcher
typedef CommandFunc< Dispatcher > Func
Protected Member Functions
virtual ChangeType getChangeType () const
virtual void getInstanceData (co::DataOStream &os)
Serialize all instance information of this distributed object.
virtual void applyInstanceData (co::DataIStream &is)
Deserialize the instance data.
void _setDataVersion (const unsigned i, const co::ObjectVersion &ov)
std::vector< uint128_t > & _getInputNodes (const unsigned i)
std::vector< uint128_t > & _getInputNetNodes (const unsigned i)
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (ICommand &command)
The default handler for handling commands.
Detailed Description
A holder for a frame data and related parameters.
Definition at line 32 of file fabric/frame.h.
Member Enumeration Documentation
enum eq::fabric::Frame::Buffer
The buffer format defines which components of the frame are to be used during readback and assembly.
Version:
1.0
Enumerator:
BUFFER_UNDEFINED
Inherit, only if no others are set.
BUFFER_COLOR
Use color images.
BUFFER_DEPTH
Use depth images.
Definition at line 40 of file fabric/frame.h.
enum eq::fabric::Frame::Type
The storage type for pixel data.
Version:
1.0
Enumerator:
TYPE_MEMORY
use main memory to store pixel data
TYPE_TEXTURE
use a GL texture to store pixel data
Definition at line 50 of file fabric/frame.h.
Constructor & Destructor Documentation
eq::fabric::Frame::Frame ()
Construct a new frame.
Version:
1.0
Reimplemented in eq::Frame.
virtual eq::fabric::Frame::~Frame () virtual
Destruct the frame.
Version:
1.0
Reimplemented in eq::Frame.
Member Function Documentation
virtual void eq::fabric::Frame::applyInstanceData (co::DataIStream & is) protected virtual
Deserialize the instance data.
This method is called during object mapping to populate slave instances with the master object's data.
Parameters:
is the input stream.
Implements co::Object.
virtual ChangeType eq::fabric::Frame::getChangeType () const inline protected virtual
Returns:
how the changes are to be handled.
Reimplemented from co::Object.
Definition at line 109 of file fabric/frame.h.
References co::Object::INSTANCE.
virtual void eq::fabric::Frame::getInstanceData (co::DataOStream & os) protected virtual
Serialize all instance information of this distributed object.
Parameters:
os The output stream.
Implements co::Object.
const std::string& eq::fabric::Frame::getName () const
Returns:
the name of the frame.
Version:
1.0
Reimplemented in eq::Frame.
const Vector2i& eq::fabric::Frame::getOffset () const
Returns:
the position of the frame wrt the channel.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble().
const Zoom& eq::fabric::Frame::getZoom () const
Returns:
the zoom factor for readback or assemble.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble().
void eq::fabric::Frame::setName (const std::string & name)
Set the name of the frame.
Version:
1.3.3
void eq::fabric::Frame::setOffset (const Vector2i & offset)
Set the position of the frame wrt the channel.
The offset is only applied for operations on this frame holder, i.e., it does not apply to other (input) frames using the same underlying frame data.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble().
void eq::fabric::Frame::setZoom (const Zoom & zoom)
Set the zoom for this frame holder.
The zoom is only applied for operations on this frame holder, i.e., it does not apply to other (input) frames using the same underlying frame data.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble().
The documentation for this class was generated from the following file:
fabric/frame.h