Sequel: seqPly::Renderer Class Reference
seqPly::Renderer Class Reference
Public Member Functions
Renderer (seq::Application &app)
Construct a new renderer.
virtual ~Renderer ()
Destruct this renderer.
State & getState ()
Public Member Functions inherited from seq::Renderer
virtual bool initContext (co::Object *initData)
Initialize an OpenGL context.
virtual bool exitContext ()
De-initialize an OpenGL context.
virtual void clear (co::Object *frameData)
Clear the frame buffer.
virtual void applyRenderContext ()
Apply the current rendering parameters to OpenGL.
const RenderContext & getRenderContext () const
virtual void applyModelMatrix ()
Apply the current model matrix to OpenGL.
detail::Renderer * getImpl ()
co::Object * getFrameData ()
Application & getApplication ()
const Application & getApplication () const
virtual ViewData * createViewData ()
Create a new per-view data instance.
virtual void destroyViewData (ViewData *viewData)
Delete the given view data.
const GLEWContext * glewGetContext () const
Get the GLEW context for this renderer.
const Frustumf & getFrustum () const
const Matrix4f & getViewMatrix () const
const Matrix4f & getModelMatrix () const
virtual co::Object * createObject (const uint32_t type)
virtual void destroyObject (co::Object *object, const uint32_t type)
Protected Member Functions
virtual bool init (co::Object *initData)
Initialize the renderer.
virtual bool exit ()
De-initialize the renderer.
virtual void draw (co::Object *frameData)
Render the scene.
Detailed Description
Definition at line 37 of file share/Equalizer/examples/seqPly/renderer.h.
Constructor & Destructor Documentation
seqPly::Renderer::Renderer (seq::Application & application) inline
Construct a new renderer.
Version:
1.0
Reimplemented from seq::Renderer.
Definition at line 40 of file share/Equalizer/examples/seqPly/renderer.h.
virtual seqPly::Renderer::~Renderer () inline virtual
Destruct this renderer.
Version:
1.0
Reimplemented from seq::Renderer.
Definition at line 41 of file share/Equalizer/examples/seqPly/renderer.h.
Member Function Documentation
void seqPly::Renderer::draw (co::Object * frameData) protected virtual
Render the scene.
Parameters:
frameData the renderer's instance of the object passed to Config::run.
Version:
1.0
Implements seq::Renderer.
Definition at line 60 of file renderer.cpp.
References seq::Renderer::applyModelMatrix(), seq::Renderer::applyRenderContext(), seq::Renderer::getApplication(), seq::Renderer::getFrustum(), seq::Renderer::getModelMatrix(), seq::Renderer::getRenderContext(), and seq::Renderer::getViewMatrix().
bool seqPly::Renderer::exit () protected virtual
De-initialize the renderer.
Called just before the last context will be destroyed after the last call to exitContext().
Returns:
true on success, false otherwise.
Version:
1.0
Reimplemented from seq::Renderer.
Definition at line 52 of file renderer.cpp.
bool seqPly::Renderer::init (co::Object * initData) protected virtual
Initialize the renderer.
Called once per renderer with an OpenGL context current before the first call to initContext().
Parameters:
initData a per-renderer instance of the object passed to Config::init().
Returns:
true on success, false otherwise.
Version:
1.0
Reimplemented from seq::Renderer.
Definition at line 46 of file renderer.cpp.
References seq::Renderer::glewGetContext().
The documentation for this class was generated from the following files:
share/Equalizer/examples/seqPly/renderer.h
renderer.cpp