Equalizer: eqPly::Window Class Reference
eqPly::Window Class Reference
A window represent an OpenGL drawable and context.
#include <window.h>
Public Member Functions
Window (eq::Pipe *parent)
Construct a new window.
const eq::util::Texture * getLogoTexture () const
VertexBufferState & getState ()
Protected Member Functions
virtual ~Window ()
Destruct the window.
virtual bool configInitSystemWindow (const eq::uint128_t &initID)
Initialize the OS-specific window.
virtual bool configInitGL (const eq::uint128_t &initID)
Initialize the OpenGL state for this window.
virtual bool configExitGL ()
De-initialize the OpenGL state for this window.
virtual void frameStart (const eq::uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
Detailed Description
A window represent an OpenGL drawable and context.
Manages OpenGL-specific data, i.e., it creates the logo texture during initialization and holds a state object for GL object creation. It initializes the OpenGL state and draws the statistics overlay.
Definition at line 45 of file share/Equalizer/examples/eqPly/window.h.
Constructor & Destructor Documentation
eqPly::Window::Window (eq::Pipe * parent) [inline]
Construct a new window.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 48 of file share/Equalizer/examples/eqPly/window.h.
virtual eqPly::Window::~Window () [inline, protected, virtual]
Destruct the window.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 55 of file share/Equalizer/examples/eqPly/window.h.
Member Function Documentation
bool eqPly::Window::configExitGL () [protected, virtual]
De-initialize the OpenGL state for this window.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 101 of file eqPly/window.cpp.
bool eqPly::Window::configInitGL (const eq::uint128_t & initID) [protected, virtual]
Initialize the OpenGL state for this window.
Parameters:
initID the init identifier.
Returns:
true if the initialization was successful, false if not.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 77 of file eqPly/window.cpp.
References eq::Window::configInitGL(), eq::Window::getConfig(), and eq::Window::getObjectManager().
bool eqPly::Window::configInitSystemWindow (const eq::uint128_t & initID) [protected, virtual]
Initialize the OS-specific window.
See also:
setSystemWindow()
Version:
1.0
Reimplemented from eq::Window.
Definition at line 46 of file eqPly/window.cpp.
References eq::Window::configExitSystemWindow(), eq::Window::configInitSystemWindow(), eq::fabric::Window< Pipe, Window, Channel >::getDrawableConfig(), eq::fabric::Window< Pipe, Window, Channel >::IATTR_PLANES_ACCUM, and eq::fabric::Window< Pipe, Window, Channel >::setIAttribute().
void eqPly::Window::frameStart (const eq::uint128_t & frameID, const uint32_t frameNumber) [protected, virtual]
Start rendering a frame.
Called once at the beginning of each frame, to do per-frame updates of window-specific data. This method has to call startFrame().
Parameters:
frameID the per-frame identifier.
frameNumber the frame to start.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 221 of file eqPly/window.cpp.
References eq::fabric::Window< Pipe, Window, Channel >::getPipe().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqPly/window.h
eqPly/window.cpp