Collage: co::Connection Class Reference
co::Connection Class Reference
An interface definition for communication between hosts.
#include <connection.h>
Public Member Functions
virtual Notifier getNotifier () const =0
template<typename T >
bool send (Packet &packet, const std::vector< T > &data)
Data Access
CO_API State getState () const
bool isClosed () const
bool isClosing () const
bool isConnected () const
bool isListening () const
CO_API
ConstConnectionDescriptionPtr getDescription () const
bool operator== (const Connection &rhs) const
Connection State Changes
virtual bool connect ()
Connect to the remote peer.
virtual bool listen ()
Put the connection into the listening state.
virtual void close ()
Close a connected or listening connection.
Listener Interface
void addListener (ConnectionListener *listener)
void removeListener (ConnectionListener *listener)
Asynchronous accept
virtual void acceptNB ()
Start an accept operation.
virtual ConnectionPtr acceptSync ()
Complete an accept operation.
Asynchronous read
CO_API void recvNB (void *buffer, const uint64_t bytes)
Start a read operation on the connection.
CO_API bool recvSync (void **buffer, uint64_t *bytes, const bool block=true)
Finish reading data from the connection.
void resetRecvData (void **buffer, uint64_t *bytes)
Static Public Member Functions
static CO_API ConnectionPtr create (ConnectionDescriptionPtr desc)
Create a new connection.
Public Types
enum State {
STATE_CLOSED, STATE_CONNECTING, STATE_CONNECTED, STATE_LISTENING,
STATE_CLOSING
}
The current state of the Connection.
typedef int Notifier
The Notifier used by the ConnectionSet to detect readiness of a Connection.
Protected Member Functions
Connection ()
Construct a new connection.
virtual ~Connection ()
Destruct this connection.
CO_API void _setDescription (ConnectionDescriptionPtr description)
CO_API void _setState (const State state)
CO_API ConnectionDescriptionPtr _getDescription ()
Synchronous write to the connection
static CO_API bool send (const Connections &connections, const Packet &packet, const bool isLocked=false)
Sends a packaged message to multiple connections.
static CO_API bool send (const Connections &connections, Packet &packet, const void *data, const uint64_t size, const bool isLocked=false)
Sends a packaged message including additional data to multiple connections.
static bool CO_API send (const Connections &connections, Packet &packet, const void *const *items, const uint64_t *itemSizes, const size_t nItems)
Sends a packaged message including additional, multiple data items to multiple connections.
CO_API bool send (const void *buffer, const uint64_t bytes, const bool isLocked=false)
Send data using the connection.
CO_API void lockSend () const
Lock the connection, no other thread can send data.
CO_API void unlockSend () const
Unlock the connection.
bool send (const Packet &packet)
Sends a packaged message using the connection.
bool send (Packet &packet, const std::string &string)
Sends a packaged message including a string using the connection.
template<typename T >
bool send (Packet &packet, const std::vector< T > &data)
Sends a packaged message including additional data.
CO_API bool send (Packet &packet, const void *data, const uint64_t size)
Sends a packaged message including additional data.
virtual void finish ()
Low-level IO methods.
enum ReadStatus { READ_TIMEOUT = -2, READ_ERROR = -1 }
< error codes for readSync()
virtual void readNB (void *buffer, const uint64_t bytes)=0
Start a read operation on the connection.
virtual int64_t readSync (void *buffer, const uint64_t bytes, const bool block)=0
Finish reading data from the connection.
virtual int64_t write (const void *buffer, const uint64_t bytes)=0
Write data to the connection.
Detailed Description
An interface definition for communication between hosts.
Connections are stream-oriented communication lines. The parameters of a Connection are described in a ConnectionDescription, which is used in listen() and connect(). A Connection has a Connection::State, which changes when calling listen(), connect() or close(), or whenever the underlying connection is closed by the operating system.
The Connection class defines the interface for connections, various derived classes implement it for the low-level communication protocols, e.g., SocketConnection for TCP/IP. An implementation may not implement all the functionality defined in this interface.
The Connection is used reference-counted in co, since it has multiple owners, such as the ConnectionSet and Node.
Definition at line 58 of file connection.h.
Member Enumeration Documentation
enum co::Connection::State
The current state of the Connection.
Version:
1.0
Enumerator:
STATE_CLOSED
Closed, initial state.
STATE_CONNECTING
A connect() or listen() is in progress.
STATE_CONNECTED
The connection has been connected and is open.
STATE_LISTENING
The connection is listening for connects.
STATE_CLOSING
A close() is in progress.
Definition at line 61 of file connection.h.
Constructor & Destructor Documentation
co::Connection::Connection () [protected]
Construct a new connection.
virtual co::Connection::~Connection () [protected, virtual]
Destruct this connection.
Member Function Documentation
CO_API ConnectionDescriptionPtr co::Connection::_getDescription () [protected]
Returns:
the description for this connection.
virtual void co::Connection::acceptNB () [inline, virtual]
Start an accept operation.
This method returns immediately. The Notifier will signal a new connection request, upon which acceptSync() should be used to finish the accept operation.
See also:
acceptSync()
Version:
1.0
Definition at line 157 of file connection.h.
virtual ConnectionPtr co::Connection::acceptSync () [inline, virtual]
Complete an accept operation.
Returns:
the new connection, 0 on error.
Version:
1.0
Definition at line 165 of file connection.h.
virtual void co::Connection::close () [inline, virtual]
Close a connected or listening connection.
Version:
1.0
Definition at line 133 of file connection.h.
virtual bool co::Connection::connect () [inline, virtual]
Connect to the remote peer.
The ConnectionDescription of this connection is used to identify the peer's parameters.
Returns:
true if the connection was successfully connected, false if not.
Version:
1.0
Definition at line 118 of file connection.h.
static CO_API ConnectionPtr co::Connection::create (ConnectionDescriptionPtr desc) [static]
Create a new connection.
This factory method creates a new concrete connection for the requested type. The description is set on the created Connection.
Parameters:
desc the connection parameters.
Returns:
the connection.
Version:
1.0
CO_API ConstConnectionDescriptionPtr co::Connection::getDescription () const
Returns:
the description for this connection.
Version:
1.0
virtual Notifier co::Connection::getNotifier () const [pure virtual]
Returns:
the notifier signaling events on the connection.
Implemented in co::BufferConnection.
CO_API State co::Connection::getState () const
Returns:
the State of this connection.
Version:
1.0
Referenced by isClosed(), isClosing(), isConnected(), and isListening().
bool co::Connection::isClosed () const [inline]
Returns:
true if the connection is closed.
Version:
1.0
Definition at line 88 of file connection.h.
References getState(), and STATE_CLOSED.
bool co::Connection::isClosing () const [inline]
Returns:
true if the connection is about to close.
Version:
1.0
Definition at line 91 of file connection.h.
References getState(), and STATE_CLOSING.
bool co::Connection::isConnected () const [inline]
Returns:
true if the connection is connected.
Version:
1.0
Definition at line 94 of file connection.h.
References getState(), and STATE_CONNECTED.
bool co::Connection::isListening () const [inline]
Returns:
true if the connection is listening.
Version:
1.0
Definition at line 97 of file connection.h.
References getState(), and STATE_LISTENING.
virtual bool co::Connection::listen () [inline, virtual]
Put the connection into the listening state.
The ConnectionDescription of this connection is used to identify the listening parameters.
Returns:
true if the connection is listening for new incoming connections, false if not.
Version:
1.0
Definition at line 130 of file connection.h.
CO_API void co::Connection::lockSend () const
Lock the connection, no other thread can send data.
Version:
1.0
virtual void co::Connection::readNB (void * buffer, const uint64_t bytes) [protected, pure virtual]
Start a read operation on the connection.
This method is the low-level counterpart used by recvNB(), implemented by the concrete connection.
This function returns immediately. The operation's Notifier will signal data availability, upon which readSync() is used to finish the operation.
Parameters:
buffer the buffer receiving the data.
bytes the number of bytes to read.
See also:
readSync()
Implemented in co::BufferConnection.
virtual int64_t co::Connection::readSync (void * buffer, const uint64_t bytes, const bool block) [protected, pure virtual]
Finish reading data from the connection.
This method is the low-level counterpart used by recvSync(), implemented by the concrete connection. It may return with a partial read.
Parameters:
buffer the buffer receiving the data.
bytes the number of bytes to read.
block internal WAR parameter, ignore it in the implementation unless you know exactly why not.
Returns:
the number of bytes read, or -1 upon error.
Implemented in co::BufferConnection.
CO_API void co::Connection::recvNB (void * buffer, const uint64_t bytes)
Start a read operation on the connection.
This function returns immediately. The Notifier will signal data availability, upon which recvSync() should be used to finish the operation.
Parameters:
buffer the buffer receiving the data.
bytes the number of bytes to read.
See also:
recvSync()
Version:
1.0
CO_API bool co::Connection::recvSync (void ** buffer, uint64_t * bytes, const bool block = true)
Finish reading data from the connection.
This function may block even if data availability was signaled, i.e., when only a part of the data requested has been received. The buffer and bytes return value pointers can be 0. This method uses readNB() and readSync() to fill a buffer, potentially by using multiple reads.
Parameters:
buffer return value, the buffer pointer passed to recvNB().
bytes return value, the number of bytes read.
block internal WAR parameter, do not use unless you know exactly why.
Returns:
true if all requested data has been read, false otherwise.
Version:
1.0
CO_API bool co::Connection::send (const void * buffer, const uint64_t bytes, const bool isLocked = false)
Send data using the connection.
A send may be performed using multiple write() operations. For thread-safe sending from multiple threads it is therefore crucial to protect the send() operation internally. If the connection is not already locked externally, it will use an internal mutex.
Parameters:
buffer the buffer containing the message.
bytes the number of bytes to send.
isLocked true if the connection is locked externally.
Returns:
true if all data has been read, false if not.
See also:
lockSend(), unlockSend()
Version:
1.0
bool co::Connection::send (const Packet & packet) [inline]
Sends a packaged message using the connection.
Parameters:
packet the message packet.
Returns:
true if all data has been read, false if not.
Version:
1.0
Definition at line 238 of file connection.h.
References send(), and co::Packet::size.
Referenced by send().
bool co::Connection::send (Packet & packet, const std::string & string) [inline]
Sends a packaged message including a string using the connection.
The packet has to define a 8-byte-aligned, 8-char array at the end of the packet. When the packet is sent the whole string is appended to the packet, so that the receiver has to do nothing special to receive and use the full packet.
Parameters:
packet the message packet.
string the string.
Returns:
true if all data has been read, false if not.
Version:
1.0
Definition at line 254 of file connection.h.
References send().
Referenced by send().
template<typename T > bool co::Connection::send (Packet & packet, const std::vector< T > & data)
Sends a packaged message including additional data.
The last item of the packet has to be able to hold one item or eight bytes of the data, whatever is bigger.
Parameters:
packet the message packet.
data the vector containing the data.
Returns:
true if all data has been read, false if not.
Version:
1.0
Definition at line 9 of file connection.h.
CO_API bool co::Connection::send (Packet & packet, const void * data, const uint64_t size)
Sends a packaged message including additional data.
Parameters:
packet the message packet.
data the data.
size the data size in bytes.
Returns:
true if all data has been read, false if not.
Version:
1.0
static CO_API bool co::Connection::send (const Connections & connections, const Packet & packet, const bool isLocked = false) [static]
Sends a packaged message to multiple connections.
Parameters:
connections The connections.
packet the message packet.
isLocked true if the connection is locked externally.
Returns:
true if the packet was sent successfully to all connections.
Version:
1.0
static CO_API bool co::Connection::send (const Connections & connections, Packet & packet, const void * data, const uint64_t size, const bool isLocked = false) [static]
Sends a packaged message including additional data to multiple connections.
Parameters:
connections The connections.
packet the message packet.
data the data.
size the data size in bytes.
isLocked true if the connection is locked externally.
Returns:
true if the packet was sent successfully to all receivers.
Version:
1.0
static bool CO_API co::Connection::send (const Connections & connections, Packet & packet, const void *const * items, const uint64_t * itemSizes, const size_t nItems) [static]
Sends a packaged message including additional, multiple data items to multiple connections.
Automatically locks each individual connection during send. The data items are appended to the packet individually as a 8-byte size token followed by size bytes data. The packet.size is updated to the size of all data send (packet + sizes + items).
Parameters:
connections The connections.
packet the message packet.
items a pointer array to the data items.
itemSizes an array containing the size of each item.
nItems the number of data elements.
Returns:
true if the packet was sent successfully to all receivers.
Version:
1.0
CO_API void co::Connection::unlockSend () const
Unlock the connection.
Version:
1.0
virtual int64_t co::Connection::write (const void * buffer, const uint64_t bytes) [protected, pure virtual]
Write data to the connection.
This method is the low-level counterpart used by send(), implemented by the concrete connection. It may return with a partial write.
Parameters:
buffer the buffer containing the message.
bytes the number of bytes to write.
Returns:
the number of bytes written, or -1 upon error.
Implemented in co::BufferConnection.
The documentation for this class was generated from the following files:
connection.h
connection.ipp