EqualizerInternal: eqNbody::SharedData Class Reference
eqNbody::SharedData Class Reference
#include <sharedData.h>
Public Member Functions
SharedData (Config *cfg)
virtual ~SharedData ()
const FrameData & getFrameData () const
void registerMemory (const eq::Range &range)
void releaseMemory ()
void mapMemory ()
void syncMemory ()
void updateMemory (const eq::Range &range, Controller *controller)
float * getPos ()
float * getCol ()
float * getVel ()
float getTimeStep ()
uint32_t getNumBytes ()
bool useStatistics () const
Detailed Description
Definition at line 46 of file sharedData.h.
Constructor & Destructor Documentation
eqNbody::SharedData::SharedData (Config * cfg)
Definition at line 39 of file sharedData.cpp.
eqNbody::SharedData::~SharedData () virtual
Definition at line 44 of file sharedData.cpp.
References eqNbody::FrameData::getNumDataProxies().
Member Function Documentation
float* eqNbody::SharedData::getCol () inline
Definition at line 62 of file sharedData.h.
References eqNbody::FrameData::getCol().
Referenced by eqNbody::Channel::frameDraw().
const FrameData& eqNbody::SharedData::getFrameData () const inline
Definition at line 53 of file sharedData.h.
Referenced by eqNbody::Pipe::configExit(), eqNbody::Pipe::configInit(), and eqNbody::Pipe::frameStart().
uint32_t eqNbody::SharedData::getNumBytes (void) inline
Definition at line 66 of file sharedData.h.
References eqNbody::FrameData::getNumBytes().
Referenced by eqNbody::Channel::frameDraw().
float* eqNbody::SharedData::getPos () inline
Definition at line 61 of file sharedData.h.
References eqNbody::FrameData::getPos().
Referenced by eqNbody::Channel::configInit(), and eqNbody::Channel::frameDraw().
float eqNbody::SharedData::getTimeStep () inline
Definition at line 65 of file sharedData.h.
References eqNbody::FrameData::getTimeStep().
Referenced by eqNbody::Channel::frameDraw().
float* eqNbody::SharedData::getVel () inline
Definition at line 63 of file sharedData.h.
References eqNbody::FrameData::getVel().
Referenced by eqNbody::Channel::frameDraw().
void eqNbody::SharedData::mapMemory ()
Definition at line 77 of file sharedData.cpp.
References eqNbody::FrameData::getCol(), eqNbody::FrameData::getNumDataProxies(), eqNbody::FrameData::getPos(), eqNbody::FrameData::getProxyID(), eqNbody::FrameData::getVel(), and eqNbody::SharedDataProxy::init().
Referenced by eqNbody::Channel::frameDraw().
void eqNbody::SharedData::registerMemory (const eq::Range & range)
Definition at line 56 of file sharedData.cpp.
References eqNbody::DATA_CHANGED, eqNbody::FrameData::getCol(), eqNbody::FrameData::getNumBodies(), eqNbody::FrameData::getNumBytes(), eqNbody::FrameData::getPos(), eqNbody::FrameData::getVel(), and eqNbody::SharedDataProxy::init().
Referenced by eqNbody::Channel::frameDraw().
void eqNbody::SharedData::releaseMemory ()
Definition at line 99 of file sharedData.cpp.
References eqNbody::FrameData::getNumDataProxies().
Referenced by eqNbody::Pipe::configExit().
void eqNbody::SharedData::syncMemory ()
Definition at line 107 of file sharedData.cpp.
References eqNbody::FrameData::getNumDataProxies(), and eqNbody::FrameData::getVersionForProxyID().
Referenced by eqNbody::Channel::frameDraw().
void eqNbody::SharedData::updateMemory (const eq::Range & range, Controller * controller)
Definition at line 119 of file sharedData.cpp.
References eqNbody::BODYSYSTEM_POSITION, eqNbody::BODYSYSTEM_VELOCITY, eqNbody::Controller::getArray(), and eqNbody::PROXY_CHANGED.
Referenced by eqNbody::Channel::frameDraw().
bool eqNbody::SharedData::useStatistics () const inline
Definition at line 68 of file sharedData.h.
References eqNbody::FrameData::useStatistics().
Referenced by eqNbody::Window::swapBuffers().
The documentation for this class was generated from the following files:
sharedData.h
sharedData.cpp