EqualizerInternal: eqNbody::Controller Class Reference
eqNbody::Controller Class Reference
#include <controller.h>
Public Member Functions
Controller (const GLEWContext *const glewContext)
bool init (const InitData &initData, float *hPos=NULL, bool usePBO=true)
bool exit ()
void compute (const float timeStep, const eq::Range &range)
void draw (float *pos, float *col)
void setSoftening (float softening)
void getArray (BodyArray array, SharedDataProxy &proxy)
void setArray (BodyArray array, const float *pos, unsigned int numBytes)
const GLEWContext * glewGetContext () const
Detailed Description
Definition at line 48 of file controller.h.
Constructor & Destructor Documentation
eqNbody::Controller::Controller (const GLEWContext *const glewContext)
Definition at line 41 of file controller.cpp.
Member Function Documentation
void eqNbody::Controller::compute (const float timeStep, const eq::Range & range)
Definition at line 122 of file controller.cpp.
References integrateNbodySystem().
Referenced by eqNbody::Channel::frameDraw().
void eqNbody::Controller::draw (float * pos, float * col)
Definition at line 134 of file controller.cpp.
References eqNbody::ParticleRenderer::draw(), eqNbody::PARTICLE_SPRITES_COLOR, eqNbody::ParticleRenderer::setColors(), eqNbody::ParticleRenderer::setPBO(), eqNbody::ParticleRenderer::setPositions(), and eqNbody::ParticleRenderer::setSpriteSize().
Referenced by eqNbody::Channel::frameDraw().
bool eqNbody::Controller::exit ()
Definition at line 104 of file controller.cpp.
References deleteNBodyArrays(), and unregisterGLBufferObject().
void eqNbody::Controller::getArray (BodyArray array, SharedDataProxy & proxy)
Definition at line 160 of file controller.cpp.
References eqNbody::BODYSYSTEM_POSITION, eqNbody::BODYSYSTEM_VELOCITY, copyArrayFromDevice(), eqNbody::SharedDataProxy::getNumBytes(), eqNbody::SharedDataProxy::getOffset(), eqNbody::SharedDataProxy::getPosition(), eqNbody::SharedDataProxy::getVelocity(), and eqNbody::SharedDataProxy::markDirty().
Referenced by eqNbody::SharedData::updateMemory().
const GLEWContext* eqNbody::Controller::glewGetContext () const inline
Definition at line 64 of file controller.h.
bool eqNbody::Controller::init (const InitData & initData, float * hPos = NULL, bool usePBO = true)
Definition at line 55 of file controller.cpp.
References allocateNBodyArrays(), eqNbody::InitData::getDamping(), eqNbody::InitData::getNumBodies(), eqNbody::InitData::getP(), eqNbody::InitData::getQ(), eqNbody::ParticleRenderer::init(), registerGLBufferObject(), and setSoftening().
Referenced by eqNbody::Channel::configInit().
void eqNbody::Controller::setArray (BodyArray array, const float * pos, unsigned int numBytes)
Definition at line 190 of file controller.cpp.
References eqNbody::BODYSYSTEM_POSITION, eqNbody::BODYSYSTEM_VELOCITY, copyArrayToDevice(), registerGLBufferObject(), and unregisterGLBufferObject().
Referenced by eqNbody::Channel::frameDraw().
void eqNbody::Controller::setSoftening (float softening)
Definition at line 155 of file controller.cpp.
References setDeviceSoftening().
Referenced by init().
The documentation for this class was generated from the following files:
controller.h
controller.cpp