EqualizerInternal: eqNbody::Client Class Reference
eqNbody::Client Class Reference
#include <client.h>
Public Member Functions
Client (const InitData &initData)
int init ()
int exit ()
void run ()
Protected Member Functions
virtual ~Client ()
Detailed Description
Definition at line 43 of file client.h.
Constructor & Destructor Documentation
eqNbody::Client::Client (const InitData & initData)
Definition at line 40 of file client.cpp.
virtual eqNbody::Client::~Client () inline protected virtual
Definition at line 54 of file client.h.
Member Function Documentation
int eqNbody::Client::exit ()
Definition at line 83 of file client.cpp.
References eqNbody::Config::exit().
int eqNbody::Client::init ()
Definition at line 45 of file client.cpp.
References eqNbody::Config::init(), and eqNbody::Config::setInitData().
void eqNbody::Client::run ()
Definition at line 101 of file client.cpp.
References eqNbody::Config::needsRedraw(), and eqNbody::Config::startFrame().
The documentation for this class was generated from the following files:
client.h
client.cpp