EqualizerInternal: mesh::VertexBufferRoot Class Reference
mesh::VertexBufferRoot Class Reference
#include <vertexBufferRoot.h>
Public Member Functions
VertexBufferRoot ()
virtual void cullDraw (VertexBufferState &state) const
virtual void draw (VertexBufferState &state) const
void setupTree (VertexData &data)
bool writeToFile (const std::string &filename)
bool readFromFile (const std::string &filename)
bool hasColors () const
void useInvertedFaces ()
const std::string & getName () const
Public Member Functions inherited from mesh::VertexBufferNode
VertexBufferNode ()
virtual ~VertexBufferNode ()
virtual Index getNumberOfVertices () const
virtual const VertexBufferBase * getLeft () const
virtual const VertexBufferBase * getRight () const
Public Member Functions inherited from mesh::VertexBufferBase
virtual ~VertexBufferBase ()
void drawBoundingSphere (VertexBufferState &state) const
const BoundingSphere & getBoundingSphere () const
const float * getRange () const
Protected Member Functions
virtual void toStream (std::ostream &os)
virtual void fromMemory (char *start)
Protected Member Functions inherited from mesh::VertexBufferNode
virtual void fromMemory (char **addr, VertexBufferData &globalData)
virtual void setupTree (VertexData &data, const Index start, const Index length, const Axis axis, const size_t depth, VertexBufferData &globalData)
virtual const BoundingSphere & updateBoundingSphere ()
virtual void updateRange ()
Protected Member Functions inherited from mesh::VertexBufferBase
VertexBufferBase ()
Friends
class eqPly::VertexBufferDist
Additional Inherited Members
Protected Attributes inherited from mesh::VertexBufferBase
BoundingSphere _boundingSphere
Range _range
Detailed Description
Definition at line 40 of file vertexBufferRoot.h.
Constructor & Destructor Documentation
mesh::VertexBufferRoot::VertexBufferRoot () inline
Definition at line 43 of file vertexBufferRoot.h.
Member Function Documentation
void mesh::VertexBufferRoot::cullDraw (VertexBufferState & state) const virtual
Definition at line 86 of file vertexBufferRoot.cpp.
References mesh::VertexBufferBase::draw(), mesh::VertexBufferBase::getBoundingSphere(), mesh::VertexBufferBase::getLeft(), getName(), mesh::VertexBufferBase::getNumberOfVertices(), mesh::VertexBufferState::getProjectionModelViewMatrix(), mesh::VertexBufferBase::getRange(), mesh::VertexBufferState::getRange(), mesh::VertexBufferBase::getRight(), MESHINFO, mesh::VertexBufferState::stopRendering(), and mesh::VertexBufferState::useFrustumCulling().
Referenced by seqPly::Renderer::draw().
void mesh::VertexBufferRoot::draw (VertexBufferState & state) const virtual
Reimplemented from mesh::VertexBufferNode.
Definition at line 207 of file vertexBufferRoot.cpp.
References mesh::VertexBufferNode::draw().
void mesh::VertexBufferRoot::fromMemory (char * start) protected virtual
Definition at line 430 of file vertexBufferRoot.cpp.
References mesh::FILE_VERSION(), mesh::VertexBufferNode::fromMemory(), mesh::VertexBufferData::fromMemory(), mesh::memRead(), and mesh::ROOT_TYPE.
const std::string& mesh::VertexBufferRoot::getName () const inline
Definition at line 55 of file vertexBufferRoot.h.
Referenced by cullDraw().
bool mesh::VertexBufferRoot::hasColors () const inline
Definition at line 51 of file vertexBufferRoot.h.
References mesh::VertexBufferData::colors.
Referenced by seqPly::Renderer::draw().
bool mesh::VertexBufferRoot::readFromFile (const std::string & filename)
Definition at line 382 of file vertexBufferRoot.cpp.
References mesh::getArchitectureFilename().
void mesh::VertexBufferRoot::setupTree (VertexData & data)
Definition at line 56 of file vertexBufferRoot.cpp.
References mesh::VertexBufferBase::_boundingSphere, mesh::VertexBufferData::clear(), mesh::VertexData::getLongestAxis(), mesh::VertexBufferNode::setupTree(), mesh::VertexData::triangles, mesh::VertexBufferNode::updateBoundingSphere(), mesh::VertexBufferNode::updateRange(), and mesh::VertexBufferData::vertices.
void mesh::VertexBufferRoot::toStream (std::ostream & os) protected virtual
Reimplemented from mesh::VertexBufferNode.
Definition at line 449 of file vertexBufferRoot.cpp.
References mesh::FILE_VERSION(), mesh::ROOT_TYPE, mesh::VertexBufferData::toStream(), and mesh::VertexBufferNode::toStream().
Referenced by writeToFile().
void mesh::VertexBufferRoot::useInvertedFaces () inline
Definition at line 53 of file vertexBufferRoot.h.
bool mesh::VertexBufferRoot::writeToFile (const std::string & filename)
Definition at line 398 of file vertexBufferRoot.cpp.
References mesh::getArchitectureFilename(), MESHERROR, and toStream().
Friends And Related Function Documentation
friend class eqPly::VertexBufferDist friend
Definition at line 72 of file vertexBufferRoot.h.
The documentation for this class was generated from the following files:
vertexBufferRoot.h
vertexBufferRoot.cpp