EqualizerInternal: eqNbody::ParticleRenderer Class Reference
eqNbody::ParticleRenderer Class Reference
#include <render_particles.h>
Public Member Functions
ParticleRenderer (const GLEWContext *const glewContext)
~ParticleRenderer ()
void init ()
void setPositions (float *pos, int numParticles)
void setColors (float *color, int numParticles)
void setPBO (unsigned int pbo, int numParticles)
void draw (DisplayMode mode=PARTICLE_POINTS)
void setPointSize (float size)
void setSpriteSize (float size)
const GLEWContext * glewGetContext () const
Protected Member Functions
void _createTexture (int resolution)
void _drawPoints (bool color=false)
Protected Attributes
float * m_pos
int m_numParticles
float m_pointSize
float m_spriteSize
unsigned int m_vertexShader
unsigned int m_pixelShader
unsigned int m_program
unsigned int m_texture
unsigned int m_pbo
unsigned int m_vboColor
Detailed Description
Definition at line 50 of file render_particles.h.
Constructor & Destructor Documentation
eqNbody::ParticleRenderer::ParticleRenderer (const GLEWContext *const glewContext) inline
Definition at line 53 of file render_particles.h.
eqNbody::ParticleRenderer::~ParticleRenderer ()
Definition at line 58 of file render_particles.cpp.
References m_pos.
Member Function Documentation
void eqNbody::ParticleRenderer::_createTexture (int resolution) protected
Definition at line 291 of file render_particles.cpp.
References eqNbody::createGaussianMap(), and m_texture.
Referenced by init().
void eqNbody::ParticleRenderer::_drawPoints (bool color = false) protected
Definition at line 82 of file render_particles.cpp.
References m_numParticles, m_pbo, m_pos, and m_vboColor.
Referenced by draw().
void eqNbody::ParticleRenderer::draw (DisplayMode mode = PARTICLE_POINTS)
Definition at line 121 of file render_particles.cpp.
References eqNbody::_checkGLErrors(), _drawPoints(), GL_COORD_REPLACE_ARB, GL_POINT_SPRITE_ARB, GL_VERTEX_PROGRAM_POINT_SIZE_NV, m_pointSize, m_program, m_spriteSize, m_texture, eqNbody::PARTICLE_POINTS, eqNbody::PARTICLE_SPRITES, and eqNbody::PARTICLE_SPRITES_COLOR.
Referenced by eqNbody::Controller::draw().
const GLEWContext* eqNbody::ParticleRenderer::glewGetContext () const inline
Definition at line 78 of file render_particles.h.
void eqNbody::ParticleRenderer::init ()
Definition at line 218 of file render_particles.cpp.
References _createTexture(), m_numParticles, m_pixelShader, m_program, m_vboColor, m_vertexShader, eqNbody::pixelShader, and eqNbody::vertexShader.
Referenced by eqNbody::Controller::init().
void eqNbody::ParticleRenderer::setColors (float * color, int numParticles)
Definition at line 69 of file render_particles.cpp.
References m_vboColor.
Referenced by eqNbody::Controller::draw().
void eqNbody::ParticleRenderer::setPBO (unsigned int pbo, int numParticles)
Definition at line 76 of file render_particles.cpp.
References m_numParticles, and m_pbo.
Referenced by eqNbody::Controller::draw().
void eqNbody::ParticleRenderer::setPointSize (float size) inline
Definition at line 76 of file render_particles.h.
References m_pointSize.
void eqNbody::ParticleRenderer::setPositions (float * pos, int numParticles)
Definition at line 63 of file render_particles.cpp.
References m_numParticles, and m_pos.
Referenced by eqNbody::Controller::draw().
void eqNbody::ParticleRenderer::setSpriteSize (float size) inline
Definition at line 77 of file render_particles.h.
References m_spriteSize.
Referenced by eqNbody::Controller::draw().
Member Data Documentation
int eqNbody::ParticleRenderer::m_numParticles protected
Definition at line 87 of file render_particles.h.
Referenced by _drawPoints(), init(), setPBO(), and setPositions().
unsigned int eqNbody::ParticleRenderer::m_pbo protected
Definition at line 96 of file render_particles.h.
Referenced by _drawPoints(), and setPBO().
unsigned int eqNbody::ParticleRenderer::m_pixelShader protected
Definition at line 93 of file render_particles.h.
Referenced by init().
float eqNbody::ParticleRenderer::m_pointSize protected
Definition at line 89 of file render_particles.h.
Referenced by draw(), and setPointSize().
float* eqNbody::ParticleRenderer::m_pos protected
Definition at line 86 of file render_particles.h.
Referenced by _drawPoints(), setPositions(), and ~ParticleRenderer().
unsigned int eqNbody::ParticleRenderer::m_program protected
Definition at line 94 of file render_particles.h.
Referenced by draw(), and init().
float eqNbody::ParticleRenderer::m_spriteSize protected
Definition at line 90 of file render_particles.h.
Referenced by draw(), and setSpriteSize().
unsigned int eqNbody::ParticleRenderer::m_texture protected
Definition at line 95 of file render_particles.h.
Referenced by _createTexture(), and draw().
unsigned int eqNbody::ParticleRenderer::m_vboColor protected
Definition at line 97 of file render_particles.h.
Referenced by _drawPoints(), init(), and setColors().
unsigned int eqNbody::ParticleRenderer::m_vertexShader protected
Definition at line 92 of file render_particles.h.
Referenced by init().
The documentation for this class was generated from the following files:
render_particles.h
render_particles.cpp