EqualizerInternal: eVolve::RawVolumeModel Class Reference
eVolve::RawVolumeModel Class Reference
Load model to texture.
#include <rawVolModel.h>
Public Member Functions
RawVolumeModel (const std::string &filename)
bool loadHeader (const float brightness, const float alpha)
bool getVolumeInfo (VolumeInfo &info, const eq::Range &range)
void releaseVolumeInfo (const eq::Range &range)
const std::string & getFileName () const
uint32_t getResolution () const
const VolumeScaling & getVolumeScaling () const
void glewSetContext (const GLEWContext *context)
const GLEWContext * glewGetContext () const
Protected Member Functions
bool _createVolumeTexture (GLuint &volume, DataInTextureDimensions &TD, const eq::Range &range)
Reading requested part of volume and derivatives from data file.
Detailed Description
Load model to texture.
Definition at line 81 of file rawVolModel.h.
Constructor & Destructor Documentation
eVolve::RawVolumeModel::RawVolumeModel (const std::string & filename)
Definition at line 53 of file rawVolModel.cpp.
Member Function Documentation
bool eVolve::RawVolumeModel::_createVolumeTexture (GLuint & volume, DataInTextureDimensions & TD, const eq::Range & range) protected
Reading requested part of volume and derivatives from data file.
Definition at line 200 of file rawVolModel.cpp.
References eVolve::DataInTextureDimensions::D, eVolve::DataInTextureDimensions::Db, eVolve::DataInTextureDimensions::Do, eVolve::DataInTextureDimensions::H, and eVolve::DataInTextureDimensions::W.
Referenced by getVolumeInfo().
const std::string& eVolve::RawVolumeModel::getFileName () const inline
Definition at line 92 of file rawVolModel.h.
uint32_t eVolve::RawVolumeModel::getResolution () const inline
Definition at line 93 of file rawVolModel.h.
bool eVolve::RawVolumeModel::getVolumeInfo (VolumeInfo & info, const eq::Range & range)
Definition at line 123 of file rawVolModel.cpp.
References _createVolumeTexture(), eVolve::VolumeScaling::D, eVolve::VolumeScaling::H, eVolve::VolumeInfo::hasDerivatives, loadHeader(), eVolve::VolumeInfo::preint, eVolve::VolumeInfo::TD, eVolve::VolumeInfo::volScaling, eVolve::VolumeInfo::volume, eVolve::VolumeInfo::voxelSize, and eVolve::VolumeScaling::W.
const VolumeScaling& eVolve::RawVolumeModel::getVolumeScaling () const inline
Definition at line 94 of file rawVolModel.h.
Referenced by eVolve::RawVolumeModelRenderer::getVolumeScaling().
const GLEWContext* eVolve::RawVolumeModel::glewGetContext () const inline
Definition at line 99 of file rawVolModel.h.
void eVolve::RawVolumeModel::glewSetContext (const GLEWContext * context) inline
Definition at line 96 of file rawVolModel.h.
Referenced by eVolve::RawVolumeModelRenderer::glewSetContext().
bool eVolve::RawVolumeModel::loadHeader (const float brightness, const float alpha)
Definition at line 67 of file rawVolModel.cpp.
References hlpFuncs::hFile::f.
Referenced by getVolumeInfo(), and eVolve::RawVolumeModelRenderer::loadHeader().
void eVolve::RawVolumeModel::releaseVolumeInfo (const eq::Range & range)
Definition at line 169 of file rawVolModel.cpp.
The documentation for this class was generated from the following files:
rawVolModel.h
rawVolModel.cpp