EqualizerInternal: mesh::VertexData Class Reference
mesh::VertexData Class Reference
#include <vertexData.h>
Public Member Functions
VertexData ()
bool readPlyFile (const std::string &file)
void sort (const Index start, const Index length, const Axis axis)
void scale (const float baseSize=2.0f)
void calculateNormals ()
void calculateBoundingBox ()
const BoundingBox & getBoundingBox () const
Axis getLongestAxis (const size_t start, const size_t elements) const
void useInvertedFaces ()
Public Attributes
std::vector< Vertex > vertices
std::vector< Color > colors
std::vector< Normal > normals
std::vector< Triangle > triangles
Detailed Description
Definition at line 45 of file vertexData.h.
Constructor & Destructor Documentation
VertexData::VertexData ()
Definition at line 46 of file vertexData.cpp.
Member Function Documentation
void VertexData::calculateBoundingBox ()
Definition at line 288 of file vertexData.cpp.
References vertices.
Referenced by scale().
void VertexData::calculateNormals ()
Definition at line 242 of file vertexData.cpp.
References MESHINFO, normals, triangles, and vertices.
const BoundingBox& mesh::VertexData::getBoundingBox () const inline
Definition at line 55 of file vertexData.h.
Axis VertexData::getLongestAxis (const size_t start, const size_t elements) const
Definition at line 302 of file vertexData.cpp.
References mesh::AXIS_X, mesh::AXIS_Y, mesh::AXIS_Z, triangles, and vertices.
Referenced by mesh::VertexBufferRoot::setupTree(), and mesh::VertexBufferNode::setupTree().
bool VertexData::readPlyFile (const std::string & file)
Definition at line 149 of file vertexData.cpp.
References colors, equal_strings(), MESHASSERT, MESHERROR, MESHINFO, PlyProperty::name, ply_close(), ply_get_element_description(), ply_open_for_reading(), triangles, and vertices.
void VertexData::scale (const float baseSize = 2.0f)
Definition at line 342 of file vertexData.cpp.
References calculateBoundingBox(), and vertices.
void VertexData::sort (const Index start, const Index length, const Axis axis)
Definition at line 419 of file vertexData.cpp.
References MESHASSERT, and triangles.
Referenced by mesh::VertexBufferLeaf::setupTree(), and mesh::VertexBufferNode::setupTree().
void mesh::VertexData::useInvertedFaces () inline
Definition at line 58 of file vertexData.h.
Member Data Documentation
std::vector< Color > mesh::VertexData::colors
Definition at line 61 of file vertexData.h.
Referenced by readPlyFile(), and mesh::VertexBufferLeaf::setupTree().
std::vector< Normal > mesh::VertexData::normals
Definition at line 62 of file vertexData.h.
Referenced by calculateNormals(), and mesh::VertexBufferLeaf::setupTree().
std::vector< Triangle > mesh::VertexData::triangles
Definition at line 63 of file vertexData.h.
Referenced by calculateNormals(), getLongestAxis(), readPlyFile(), mesh::VertexBufferRoot::setupTree(), mesh::VertexBufferLeaf::setupTree(), and sort().
std::vector< Vertex > mesh::VertexData::vertices
Definition at line 60 of file vertexData.h.
Referenced by calculateBoundingBox(), calculateNormals(), getLongestAxis(), readPlyFile(), scale(), and mesh::VertexBufferLeaf::setupTree().
The documentation for this class was generated from the following files:
vertexData.h
vertexData.cpp