EqualizerInternal: mesh::VertexBufferState Class Reference
mesh::VertexBufferState Class Reference abstract
#include <vertexBufferState.h>
Public Member Functions
virtual bool useColors () const
virtual void setColors (const bool colors)
virtual bool stopRendering () const
virtual RenderMode getRenderMode () const
virtual void setRenderMode (const RenderMode mode)
virtual bool useFrustumCulling () const
virtual void setFrustumCulling (const bool frustumCullingState)
void setProjectionModelViewMatrix (const Matrix4f &pmv)
const Matrix4f & getProjectionModelViewMatrix () const
void setRange (const Range &range)
const Range & getRange () const
void resetRegion ()
void updateRegion (const BoundingBox &box)
virtual void declareRegion (const Vector4f &region)
Vector4f getRegion () const
virtual GLuint getDisplayList (const void *key)=0
virtual GLuint newDisplayList (const void *key)=0
virtual GLuint getBufferObject (const void *key)=0
virtual GLuint newBufferObject (const void *key)=0
virtual void deleteAll ()=0
const GLEWContext * glewGetContext () const
Public Types
enum { INVALID = 0 }
Protected Member Functions
VertexBufferState (const GLEWContext *glewContext)
virtual ~VertexBufferState ()
Protected Attributes
Matrix4f _pmvMatrix
projection * modelView matrix
Range _range
normalized [0,1] part of the model to draw
const GLEWContext *const _glewContext
RenderMode _renderMode
Vector4f _region
normalized x1 y1 x2 y2 region from cullDraw
bool _useColors
bool _useFrustumCulling
Detailed Description
Definition at line 45 of file vertexBufferState.h.
Member Enumeration Documentation
anonymous enum
Enumerator
INVALID
Definition at line 48 of file vertexBufferState.h.
Constructor & Destructor Documentation
mesh::VertexBufferState::VertexBufferState (const GLEWContext * glewContext) protected
Definition at line 34 of file vertexBufferState.cpp.
References _range, MESHASSERT, and resetRegion().
virtual mesh::VertexBufferState::~VertexBufferState () inline protected virtual
Definition at line 85 of file vertexBufferState.h.
Member Function Documentation
virtual void mesh::VertexBufferState::declareRegion (const Vector4f & region) inline virtual
Reimplemented in eqPly::VertexBufferState.
Definition at line 72 of file vertexBufferState.h.
Referenced by updateRegion().
virtual void mesh::VertexBufferState::deleteAll () pure virtual
Implemented in eqPly::VertexBufferState, and mesh::VertexBufferStateSimple.
virtual GLuint mesh::VertexBufferState::getBufferObject (const void * key) pure virtual
Implemented in eqPly::VertexBufferState, and mesh::VertexBufferStateSimple.
virtual GLuint mesh::VertexBufferState::getDisplayList (const void * key) pure virtual
Implemented in eqPly::VertexBufferState, and mesh::VertexBufferStateSimple.
Referenced by mesh::VertexBufferBase::drawBoundingSphere().
const Matrix4f& mesh::VertexBufferState::getProjectionModelViewMatrix () const inline
Definition at line 64 of file vertexBufferState.h.
References _pmvMatrix.
Referenced by mesh::VertexBufferRoot::cullDraw().
const Range& mesh::VertexBufferState::getRange () const inline
Definition at line 68 of file vertexBufferState.h.
References _range.
Referenced by mesh::VertexBufferRoot::cullDraw().
Vector4f mesh::VertexBufferState::getRegion () const
Definition at line 108 of file vertexBufferState.cpp.
References _region.
virtual RenderMode mesh::VertexBufferState::getRenderMode () const inline virtual
Definition at line 56 of file vertexBufferState.h.
References _renderMode.
Referenced by mesh::VertexBufferLeaf::draw().
const GLEWContext* mesh::VertexBufferState::glewGetContext () const inline
Definition at line 81 of file vertexBufferState.h.
References _glewContext.
virtual GLuint mesh::VertexBufferState::newBufferObject (const void * key) pure virtual
Implemented in eqPly::VertexBufferState, and mesh::VertexBufferStateSimple.
virtual GLuint mesh::VertexBufferState::newDisplayList (const void * key) pure virtual
Implemented in eqPly::VertexBufferState, and mesh::VertexBufferStateSimple.
Referenced by mesh::VertexBufferBase::drawBoundingSphere().
void mesh::VertexBufferState::resetRegion ()
Definition at line 62 of file vertexBufferState.cpp.
References _region.
Referenced by VertexBufferState().
virtual void mesh::VertexBufferState::setColors (const bool colors) inline virtual
Definition at line 54 of file vertexBufferState.h.
References _useColors.
Referenced by seqPly::Renderer::draw().
virtual void mesh::VertexBufferState::setFrustumCulling (const bool frustumCullingState) inline virtual
Definition at line 59 of file vertexBufferState.h.
References _useFrustumCulling.
Referenced by eqPly::Channel::frameDraw().
void mesh::VertexBufferState::setProjectionModelViewMatrix (const Matrix4f & pmv) inline
Definition at line 62 of file vertexBufferState.h.
References _pmvMatrix.
Referenced by seqPly::Renderer::draw().
void mesh::VertexBufferState::setRange (const Range & range) inline
Definition at line 67 of file vertexBufferState.h.
References _range.
Referenced by seqPly::Renderer::draw().
void mesh::VertexBufferState::setRenderMode (const RenderMode mode) virtual
Definition at line 47 of file vertexBufferState.cpp.
References _renderMode, MESHINFO, mesh::RENDER_MODE_BUFFER_OBJECT, and mesh::RENDER_MODE_DISPLAY_LIST.
Referenced by eqPly::Window::frameStart().
virtual bool mesh::VertexBufferState::stopRendering () const inline virtual
Reimplemented in eqPly::VertexBufferState.
Definition at line 55 of file vertexBufferState.h.
Referenced by mesh::VertexBufferRoot::cullDraw(), mesh::VertexBufferNode::draw(), and mesh::VertexBufferLeaf::draw().
void mesh::VertexBufferState::updateRegion (const BoundingBox & box)
Definition at line 70 of file vertexBufferState.cpp.
References _pmvMatrix, _region, and declareRegion().
Referenced by mesh::VertexBufferLeaf::draw().
virtual bool mesh::VertexBufferState::useColors () const inline virtual
Definition at line 53 of file vertexBufferState.h.
References _useColors.
virtual bool mesh::VertexBufferState::useFrustumCulling () const inline virtual
Definition at line 58 of file vertexBufferState.h.
References _useFrustumCulling.
Referenced by mesh::VertexBufferRoot::cullDraw().
Member Data Documentation
const GLEWContext* const mesh::VertexBufferState::_glewContext protected
Definition at line 89 of file vertexBufferState.h.
Referenced by glewGetContext().
Matrix4f mesh::VertexBufferState::_pmvMatrix protected
projection * modelView matrix
Definition at line 87 of file vertexBufferState.h.
Referenced by getProjectionModelViewMatrix(), setProjectionModelViewMatrix(), and updateRegion().
Range mesh::VertexBufferState::_range protected
normalized [0,1] part of the model to draw
Definition at line 88 of file vertexBufferState.h.
Referenced by getRange(), setRange(), and VertexBufferState().
Vector4f mesh::VertexBufferState::_region protected
normalized x1 y1 x2 y2 region from cullDraw
Definition at line 91 of file vertexBufferState.h.
Referenced by getRegion(), resetRegion(), and updateRegion().
RenderMode mesh::VertexBufferState::_renderMode protected
Definition at line 90 of file vertexBufferState.h.
Referenced by getRenderMode(), and setRenderMode().
bool mesh::VertexBufferState::_useColors protected
Definition at line 92 of file vertexBufferState.h.
Referenced by setColors(), and useColors().
bool mesh::VertexBufferState::_useFrustumCulling protected
Definition at line 93 of file vertexBufferState.h.
Referenced by setFrustumCulling(), and useFrustumCulling().
The documentation for this class was generated from the following files:
vertexBufferState.h
vertexBufferState.cpp