EqualizerInternal: eqPly::CameraAnimation Class Reference
eqPly::CameraAnimation Class Reference
Loads sequence of camera positions and interpolates them on a per-frame basis.
#include <cameraAnimation.h>
Classes
struct Step
Public Member Functions
CameraAnimation ()
bool loadAnimation (const std::string &fileName)
bool isValid () const
Step getNextStep ()
uint32_t getCurrentFrame ()
const eq::Vector3f & getModelRotation () const
Detailed Description
Loads sequence of camera positions and interpolates them on a per-frame basis.
Definition at line 41 of file cameraAnimation.h.
Constructor & Destructor Documentation
eqPly::CameraAnimation::CameraAnimation () inline
Definition at line 46 of file cameraAnimation.h.
Member Function Documentation
uint32_t eqPly::CameraAnimation::getCurrentFrame () inline
Definition at line 54 of file cameraAnimation.h.
Referenced by eqPly::Config::getAnimationFrame().
const eq::Vector3f& eqPly::CameraAnimation::getModelRotation () const inline
Definition at line 56 of file cameraAnimation.h.
CameraAnimation::Step eqPly::CameraAnimation::getNextStep ()
Definition at line 37 of file cameraAnimation.cpp.
References eqPly::CameraAnimation::Step::frame, eqPly::CameraAnimation::Step::position, and eqPly::CameraAnimation::Step::rotation.
bool eqPly::CameraAnimation::isValid () const inline
Definition at line 50 of file cameraAnimation.h.
Referenced by eqPly::Config::init().
bool eqPly::CameraAnimation::loadAnimation (const std::string & fileName)
Definition at line 80 of file cameraAnimation.cpp.
References M_PI_2.
Referenced by eqPly::Config::init().
The documentation for this class was generated from the following files:
cameraAnimation.h
cameraAnimation.cpp