EqualizerInternal: eqPly::InitData Class Reference
eqPly::InitData Class Reference
#include <initData.h>
Public Member Functions
InitData ()
virtual ~InitData ()
void setFrameDataID (const eq::uint128_t &id)
eq::uint128_t getFrameDataID () const
eq::WindowSystem getWindowSystem () const
mesh::RenderMode getRenderMode () const
bool useGLSL () const
bool useInvertedFaces () const
bool showLogo () const
bool useROI () const
Protected Member Functions
virtual void getInstanceData (co::DataOStream &os)
virtual void applyInstanceData (co::DataIStream &is)
void setWindowSystem (const eq::WindowSystem windowSystem)
void setRenderMode (const mesh::RenderMode renderMode)
void enableGLSL ()
void enableInvertedFaces ()
void disableLogo ()
void disableROI ()
Detailed Description
Definition at line 37 of file eqPly/initData.h.
Constructor & Destructor Documentation
eqPly::InitData::InitData ()
Definition at line 43 of file eqPly/initData.cpp.
eqPly::InitData::~InitData () virtual
Definition at line 57 of file eqPly/initData.cpp.
References setFrameDataID().
Member Function Documentation
void eqPly::InitData::applyInstanceData (co::DataIStream & is) protected virtual
Definition at line 68 of file eqPly/initData.cpp.
void eqPly::InitData::disableLogo () inline protected
Definition at line 64 of file eqPly/initData.h.
Referenced by eqPly::LocalInitData::operator=(), and eqPly::LocalInitData::parseArguments().
void eqPly::InitData::disableROI () inline protected
Definition at line 65 of file eqPly/initData.h.
Referenced by eqPly::LocalInitData::operator=(), and eqPly::LocalInitData::parseArguments().
void eqPly::InitData::enableGLSL () inline protected
Definition at line 62 of file eqPly/initData.h.
Referenced by eqPly::LocalInitData::operator=(), and eqPly::LocalInitData::parseArguments().
void eqPly::InitData::enableInvertedFaces () inline protected
Definition at line 63 of file eqPly/initData.h.
Referenced by eqPly::LocalInitData::operator=(), and eqPly::LocalInitData::parseArguments().
eq::uint128_t eqPly::InitData::getFrameDataID () const inline
Definition at line 46 of file eqPly/initData.h.
Referenced by eqPly::Pipe::configInit().
void eqPly::InitData::getInstanceData (co::DataOStream & os) protected virtual
Definition at line 62 of file eqPly/initData.cpp.
mesh::RenderMode eqPly::InitData::getRenderMode () const inline
Definition at line 48 of file eqPly/initData.h.
Referenced by eqPly::Config::init(), and eqPly::LocalInitData::operator=().
eq::WindowSystem eqPly::InitData::getWindowSystem () const inline
Definition at line 47 of file eqPly/initData.h.
Referenced by eqPly::LocalInitData::operator=(), and eqPly::Pipe::selectWindowSystem().
void eqPly::InitData::setFrameDataID (const eq::uint128_t & id) inline
Definition at line 43 of file eqPly/initData.h.
Referenced by eqPly::Config::init(), and ~InitData().
void eqPly::InitData::setRenderMode (const mesh::RenderMode renderMode) inline protected
Definition at line 60 of file eqPly/initData.h.
Referenced by eqPly::LocalInitData::operator=(), and eqPly::LocalInitData::parseArguments().
void eqPly::InitData::setWindowSystem (const eq::WindowSystem windowSystem) inline protected
Definition at line 58 of file eqPly/initData.h.
Referenced by eqPly::LocalInitData::operator=(), and eqPly::LocalInitData::parseArguments().
bool eqPly::InitData::showLogo () const inline
Definition at line 51 of file eqPly/initData.h.
Referenced by eqPly::Window::configInitGL(), and eqPly::LocalInitData::operator=().
bool eqPly::InitData::useGLSL () const inline
Definition at line 49 of file eqPly/initData.h.
Referenced by eqPly::Window::configInitGL(), and eqPly::LocalInitData::operator=().
bool eqPly::InitData::useInvertedFaces () const inline
Definition at line 50 of file eqPly/initData.h.
Referenced by eqPly::LocalInitData::operator=().
bool eqPly::InitData::useROI () const inline
Definition at line 52 of file eqPly/initData.h.
Referenced by eqPly::LocalInitData::operator=().
The documentation for this class was generated from the following files:
eqPly/initData.h
eqPly/initData.cpp