EqualizerInternal: osgScaleViewer::Pipe Class Reference
osgScaleViewer::Pipe Class Reference
The Pipe holds the viewer and the frame data.
#include <pipe.h>
Public Member Functions
Pipe (eq::Node *parent)
Creates a Pipe.
const FrameData & getFrameData () const
Gets the FrameData object.
Protected Member Functions
virtual ~Pipe ()
virtual bool configInit (const eq::uint128_t &initID)
Creates the scene graph and registers the frame data, so it can be synced with the server later.
virtual bool configExit ()
Deregisters the frame data.
virtual void frameStart (const eq::uint128_t &frameID, const uint32_t frameNumber)
Syncs the frame data with the server and calls updateSceneGraph().
Detailed Description
The Pipe holds the viewer and the frame data.
Each frame, it updates the scene graph of the viewer with the new data of the frame data. The frame data is synced with the server.
Definition at line 52 of file osgScaleViewer/pipe.h.
Constructor & Destructor Documentation
osgScaleViewer::Pipe::Pipe (eq::Node * parent)
Creates a Pipe.
Parameters
parent the pipe's parent.
Definition at line 40 of file osgScaleViewer/pipe.cpp.
osgScaleViewer::Pipe::~Pipe () protected virtual
Definition at line 45 of file osgScaleViewer/pipe.cpp.
Member Function Documentation
bool osgScaleViewer::Pipe::configExit () protected virtual
Deregisters the frame data.
Definition at line 68 of file osgScaleViewer/pipe.cpp.
bool osgScaleViewer::Pipe::configInit (const eq::uint128_t & initID) protected virtual
Creates the scene graph and registers the frame data, so it can be synced with the server later.
Definition at line 54 of file osgScaleViewer/pipe.cpp.
References osgScaleViewer::InitData::getFrameDataID(), and osgScaleViewer::Config::getInitData().
void osgScaleViewer::Pipe::frameStart (const eq::uint128_t & frameID, const uint32_t frameNumber) protected virtual
Syncs the frame data with the server and calls updateSceneGraph().
Definition at line 74 of file osgScaleViewer/pipe.cpp.
const FrameData & osgScaleViewer::Pipe::getFrameData () const
Gets the FrameData object.
Returns
the frame data object.
Definition at line 49 of file osgScaleViewer/pipe.cpp.
Referenced by osgScaleViewer::Channel::frameDraw(), and osgScaleViewer::Channel::frameViewFinish().
The documentation for this class was generated from the following files:
osgScaleViewer/pipe.h
osgScaleViewer/pipe.cpp