EqualizerInternal: mesh::VertexBufferBase Class Reference
mesh::VertexBufferBase Class Reference abstract
#include <vertexBufferBase.h>
Public Member Functions
virtual ~VertexBufferBase ()
virtual void draw (VertexBufferState &state) const =0
void drawBoundingSphere (VertexBufferState &state) const
virtual Index getNumberOfVertices () const =0
const BoundingSphere & getBoundingSphere () const
const float * getRange () const
virtual const VertexBufferBase * getLeft () const
virtual const VertexBufferBase * getRight () const
virtual const BoundingSphere & updateBoundingSphere ()=0
Protected Member Functions
VertexBufferBase ()
virtual void toStream (std::ostream &os)
virtual void fromMemory (char **addr, VertexBufferData &globalData)
virtual void setupTree (VertexData &data, const Index start, const Index length, const Axis axis, const size_t depth, VertexBufferData &globalData)=0
virtual void updateRange ()=0
Protected Attributes
BoundingSphere _boundingSphere
Range _range
Friends
class eqPly::VertexBufferDist
Detailed Description
Definition at line 54 of file vertexBufferBase.h.
Constructor & Destructor Documentation
virtual mesh::VertexBufferBase::~VertexBufferBase () inline virtual
Definition at line 57 of file vertexBufferBase.h.
mesh::VertexBufferBase::VertexBufferBase () inline protected
Definition at line 74 of file vertexBufferBase.h.
References _range.
Member Function Documentation
virtual void mesh::VertexBufferBase::draw (VertexBufferState & state) const pure virtual
Implemented in mesh::VertexBufferLeaf, mesh::VertexBufferNode, and mesh::VertexBufferRoot.
Referenced by mesh::VertexBufferRoot::cullDraw(), and mesh::VertexBufferNode::draw().
void mesh::VertexBufferBase::drawBoundingSphere (VertexBufferState & state) const
Definition at line 34 of file vertexBufferBase.cpp.
References _boundingSphere, mesh::VertexBufferState::getDisplayList(), mesh::VertexBufferState::INVALID, and mesh::VertexBufferState::newDisplayList().
virtual void mesh::VertexBufferBase::fromMemory (char ** addr, VertexBufferData & globalData) inline protected virtual
Reimplemented in mesh::VertexBufferNode, and mesh::VertexBufferLeaf.
Definition at line 87 of file vertexBufferBase.h.
References _boundingSphere, _range, and mesh::memRead().
Referenced by mesh::VertexBufferLeaf::fromMemory(), and mesh::VertexBufferNode::fromMemory().
const BoundingSphere& mesh::VertexBufferBase::getBoundingSphere () const inline
Definition at line 63 of file vertexBufferBase.h.
References _boundingSphere.
Referenced by mesh::VertexBufferRoot::cullDraw(), and eqPly::Channel::frameDraw().
virtual const VertexBufferBase* mesh::VertexBufferBase::getLeft () const inline virtual
Reimplemented in mesh::VertexBufferNode.
Definition at line 68 of file vertexBufferBase.h.
Referenced by mesh::VertexBufferRoot::cullDraw(), and eqPly::VertexBufferDist::VertexBufferDist().
virtual Index mesh::VertexBufferBase::getNumberOfVertices () const pure virtual
Implemented in mesh::VertexBufferLeaf, and mesh::VertexBufferNode.
Referenced by mesh::VertexBufferRoot::cullDraw(), and mesh::VertexBufferNode::getNumberOfVertices().
const float* mesh::VertexBufferBase::getRange () const inline
Definition at line 66 of file vertexBufferBase.h.
References _range.
Referenced by mesh::VertexBufferRoot::cullDraw(), and mesh::VertexBufferNode::updateRange().
virtual const VertexBufferBase* mesh::VertexBufferBase::getRight () const inline virtual
Reimplemented in mesh::VertexBufferNode.
Definition at line 69 of file vertexBufferBase.h.
Referenced by mesh::VertexBufferRoot::cullDraw(), and eqPly::VertexBufferDist::VertexBufferDist().
virtual void mesh::VertexBufferBase::setupTree (VertexData & data, const Index start, const Index length, const Axis axis, const size_t depth, VertexBufferData & globalData) protected pure virtual
Implemented in mesh::VertexBufferNode, and mesh::VertexBufferLeaf.
virtual void mesh::VertexBufferBase::toStream (std::ostream & os) inline protected virtual
Reimplemented in mesh::VertexBufferRoot, mesh::VertexBufferNode, and mesh::VertexBufferLeaf.
Definition at line 80 of file vertexBufferBase.h.
References _boundingSphere, and _range.
Referenced by mesh::VertexBufferLeaf::toStream(), and mesh::VertexBufferNode::toStream().
virtual const BoundingSphere& mesh::VertexBufferBase::updateBoundingSphere () pure virtual
Implemented in mesh::VertexBufferNode, and mesh::VertexBufferLeaf.
Referenced by mesh::VertexBufferNode::updateBoundingSphere().
virtual void mesh::VertexBufferBase::updateRange () protected pure virtual
Implemented in mesh::VertexBufferNode, and mesh::VertexBufferLeaf.
Friends And Related Function Documentation
friend class eqPly::VertexBufferDist friend
Definition at line 104 of file vertexBufferBase.h.
Member Data Documentation
BoundingSphere mesh::VertexBufferBase::_boundingSphere protected
Definition at line 102 of file vertexBufferBase.h.
Referenced by eqPly::VertexBufferDist::applyInstanceData(), drawBoundingSphere(), fromMemory(), getBoundingSphere(), eqPly::VertexBufferDist::getInstanceData(), mesh::VertexBufferRoot::setupTree(), toStream(), mesh::VertexBufferLeaf::updateBoundingSphere(), and mesh::VertexBufferNode::updateBoundingSphere().
Range mesh::VertexBufferBase::_range protected
Definition at line 103 of file vertexBufferBase.h.
Referenced by eqPly::VertexBufferDist::applyInstanceData(), fromMemory(), eqPly::VertexBufferDist::getInstanceData(), getRange(), toStream(), mesh::VertexBufferLeaf::updateRange(), mesh::VertexBufferNode::updateRange(), and VertexBufferBase().
The documentation for this class was generated from the following files:
vertexBufferBase.h
vertexBufferBase.cpp