EqualizerInternal: eqNbody::SharedDataProxy Class Reference
eqNbody::SharedDataProxy Class Reference
#include <sharedDataProxy.h>
Public Member Functions
SharedDataProxy ()
void init (const unsigned int offset, const unsigned int numBytes, float *pos, float *vel, float *col)
void init (float *pos, float *vel, float *col)
void exit ()
void markDirty ()
unsigned int getOffset () const
unsigned int getNumBytes () const
float * getPosition () const
float * getVelocity () const
Protected Member Functions
virtual void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual ChangeType getChangeType () const
Protected Types
enum DirtyBits { DIRTY_DATA = co::Serializable::DIRTY_CUSTOM << 0 }
Detailed Description
Definition at line 37 of file sharedDataProxy.h.
Member Enumeration Documentation
enum eqNbody::SharedDataProxy::DirtyBits protected
Enumerator
DIRTY_DATA
Definition at line 62 of file sharedDataProxy.h.
Constructor & Destructor Documentation
eqNbody::SharedDataProxy::SharedDataProxy ()
Definition at line 36 of file sharedDataProxy.cpp.
Member Function Documentation
void eqNbody::SharedDataProxy::deserialize (co::DataIStream & is, const uint64_t dirtyBits) protected virtual
Definition at line 60 of file sharedDataProxy.cpp.
References DIRTY_DATA.
void eqNbody::SharedDataProxy::exit ()
Definition at line 98 of file sharedDataProxy.cpp.
virtual ChangeType eqNbody::SharedDataProxy::getChangeType () const inline protected virtual
Definition at line 61 of file sharedDataProxy.h.
unsigned int eqNbody::SharedDataProxy::getNumBytes (void) const inline
Definition at line 51 of file sharedDataProxy.h.
Referenced by eqNbody::Controller::getArray().
unsigned int eqNbody::SharedDataProxy::getOffset () const inline
Definition at line 50 of file sharedDataProxy.h.
Referenced by eqNbody::Controller::getArray().
float* eqNbody::SharedDataProxy::getPosition () const inline
Definition at line 53 of file sharedDataProxy.h.
Referenced by eqNbody::Controller::getArray().
float* eqNbody::SharedDataProxy::getVelocity () const inline
Definition at line 54 of file sharedDataProxy.h.
Referenced by eqNbody::Controller::getArray().
void eqNbody::SharedDataProxy::init (const unsigned int offset, const unsigned int numBytes, float * pos, float * vel, float * col)
Definition at line 77 of file sharedDataProxy.cpp.
References DIRTY_DATA.
Referenced by eqNbody::SharedData::mapMemory(), and eqNbody::SharedData::registerMemory().
void eqNbody::SharedDataProxy::init (float * pos, float * vel, float * col)
Definition at line 89 of file sharedDataProxy.cpp.
References DIRTY_DATA.
void eqNbody::SharedDataProxy::markDirty ()
Definition at line 108 of file sharedDataProxy.cpp.
References DIRTY_DATA.
Referenced by eqNbody::Controller::getArray().
void eqNbody::SharedDataProxy::serialize (co::DataOStream & os, const uint64_t dirtyBits) protected virtual
Definition at line 43 of file sharedDataProxy.cpp.
References DIRTY_DATA.
The documentation for this class was generated from the following files:
sharedDataProxy.h
sharedDataProxy.cpp