EqualizerInternal: osgScaleViewer::FrameData Class Reference
osgScaleViewer::FrameData Class Reference
#include <frameData.h>
Public Member Functions
FrameData ()
void setCameraPosition (eq::Vector3f cameraPosition)
Sets the camera position.
const eq::Vector3f getCameraPosition () const
Gets the camera position.
void setCameraLookAtPoint (eq::Vector3f cameraLookAtPoint)
Sets the camera look at point.
const eq::Vector3f getCameraLookAtPoint () const
Gets the camera look at point.
void setCameraUpVector (eq::Vector3f cameraUpVector)
Sets the camera up vector.
const eq::Vector3f getCameraUpVector () const
Gets the camera up vector.
void toggleStatistics ()
Toggle the display of run-time statistics.
bool useStatistics () const
Protected Member Functions
virtual void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual ChangeType getChangeType () const
Reimplemented.
Protected Types
enum DirtyBits { DIRTY_CAMERA = co::Serializable::DIRTY_CUSTOM << 0, DIRTY_FLAGS = co::Serializable::DIRTY_CUSTOM << 1 }
The changed parts of the data since the last pack().
Detailed Description
Definition at line 44 of file osgScaleViewer/frameData.h.
Member Enumeration Documentation
enum osgScaleViewer::FrameData::DirtyBits protected
The changed parts of the data since the last pack().
Enumerator
DIRTY_CAMERA
DIRTY_FLAGS
Definition at line 101 of file osgScaleViewer/frameData.h.
Constructor & Destructor Documentation
osgScaleViewer::FrameData::FrameData ()
Definition at line 38 of file osgScaleViewer/frameData.cpp.
Member Function Documentation
void osgScaleViewer::FrameData::deserialize (co::DataIStream & is, const uint64_t dirtyBits) protected virtual
See Also
Object::deserialize()
Definition at line 54 of file osgScaleViewer/frameData.cpp.
References DIRTY_CAMERA, and DIRTY_FLAGS.
const eq::Vector3f osgScaleViewer::FrameData::getCameraLookAtPoint () const inline
Gets the camera look at point.
Returns
the camera look at point vector.
Definition at line 71 of file osgScaleViewer/frameData.h.
Referenced by osgScaleViewer::Channel::frameDraw().
const eq::Vector3f osgScaleViewer::FrameData::getCameraPosition () const inline
Gets the camera position.
Returns
the camera position.
Definition at line 59 of file osgScaleViewer/frameData.h.
Referenced by osgScaleViewer::Channel::frameDraw(), and osgScaleViewer::Config::updateFrameData().
const eq::Vector3f osgScaleViewer::FrameData::getCameraUpVector () const inline
Gets the camera up vector.
Returns
the camera up vector.
Definition at line 84 of file osgScaleViewer/frameData.h.
Referenced by osgScaleViewer::Channel::frameDraw().
co::Object::ChangeType osgScaleViewer::FrameData::getChangeType () const protected virtual
Reimplemented.
Definition at line 88 of file osgScaleViewer/frameData.cpp.
void osgScaleViewer::FrameData::serialize (co::DataOStream & os, const uint64_t dirtyBits) protected virtual
See Also
Object::serialize()
Definition at line 45 of file osgScaleViewer/frameData.cpp.
References DIRTY_CAMERA, and DIRTY_FLAGS.
void osgScaleViewer::FrameData::setCameraLookAtPoint (eq::Vector3f cameraLookAtPoint)
Sets the camera look at point.
Parameters
cameraLookAtPoint the camera look at point vector.
Definition at line 70 of file osgScaleViewer/frameData.cpp.
References DIRTY_CAMERA.
Referenced by osgScaleViewer::Config::updateFrameData().
void osgScaleViewer::FrameData::setCameraPosition (eq::Vector3f cameraPosition)
Sets the camera position.
Parameters
cameraPosition the camera position.
Definition at line 64 of file osgScaleViewer/frameData.cpp.
References DIRTY_CAMERA.
Referenced by osgScaleViewer::Config::updateFrameData().
void osgScaleViewer::FrameData::setCameraUpVector (eq::Vector3f cameraUpVector)
Sets the camera up vector.
Parameters
cameraUpVector the camera up vector.
Definition at line 76 of file osgScaleViewer/frameData.cpp.
References DIRTY_CAMERA.
Referenced by osgScaleViewer::Config::updateFrameData().
void osgScaleViewer::FrameData::toggleStatistics ()
Toggle the display of run-time statistics.
Definition at line 82 of file osgScaleViewer/frameData.cpp.
References DIRTY_FLAGS.
Referenced by osgScaleViewer::Config::handleEvent().
bool osgScaleViewer::FrameData::useStatistics () const inline
Returns
true of the statistics overlay is enabled.
Definition at line 90 of file osgScaleViewer/frameData.h.
Referenced by osgScaleViewer::Channel::frameViewFinish().
The documentation for this class was generated from the following files:
osgScaleViewer/frameData.h
osgScaleViewer/frameData.cpp