EqualizerInternal: eVolve::InitData Class Reference
eVolve::InitData Class Reference
#include <initData.h>
Public Member Functions
InitData ()
virtual ~InitData ()
void setFrameDataID (const co::UUID &id)
lunchbox::UUID getFrameDataID () const
eq::WindowSystem getWindowSystem () const
uint32_t getPrecision () const
float getBrightness () const
float getAlpha () const
const std::string & getFilename () const
Protected Member Functions
virtual void getInstanceData (co::DataOStream &os)
virtual void applyInstanceData (co::DataIStream &is)
void setWindowSystem (const eq::WindowSystem &windowSystem)
void setPrecision (const uint32_t precision)
void setBrightness (const float brightness)
void setAlpha (const float alpha)
void setFilename (const std::string &filename)
Detailed Description
Definition at line 39 of file eVolve/initData.h.
Constructor & Destructor Documentation
eVolve::InitData::InitData ()
Definition at line 42 of file eVolve/initData.cpp.
eVolve::InitData::~InitData () virtual
Definition at line 65 of file eVolve/initData.cpp.
References setFrameDataID().
Member Function Documentation
void eVolve::InitData::applyInstanceData (co::DataIStream & is) protected virtual
Definition at line 76 of file eVolve/initData.cpp.
float eVolve::InitData::getAlpha () const inline
Definition at line 51 of file eVolve/initData.h.
Referenced by eVolve::Pipe::configInit(), and eVolve::LocalInitData::operator=().
float eVolve::InitData::getBrightness () const inline
Definition at line 50 of file eVolve/initData.h.
Referenced by eVolve::Pipe::configInit(), and eVolve::LocalInitData::operator=().
const std::string& eVolve::InitData::getFilename () const inline
Definition at line 52 of file eVolve/initData.h.
Referenced by eVolve::Pipe::configInit(), and eVolve::LocalInitData::operator=().
lunchbox::UUID eVolve::InitData::getFrameDataID () const inline
Definition at line 47 of file eVolve/initData.h.
Referenced by eVolve::Pipe::configInit().
void eVolve::InitData::getInstanceData (co::DataOStream & os) protected virtual
Definition at line 70 of file eVolve/initData.cpp.
uint32_t eVolve::InitData::getPrecision () const inline
Definition at line 49 of file eVolve/initData.h.
Referenced by eVolve::Pipe::configInit(), and eVolve::LocalInitData::operator=().
eq::WindowSystem eVolve::InitData::getWindowSystem () const inline
Definition at line 48 of file eVolve/initData.h.
Referenced by eVolve::LocalInitData::operator=(), and eVolve::Pipe::selectWindowSystem().
void eVolve::InitData::setAlpha (const float alpha) inline protected
Definition at line 62 of file eVolve/initData.h.
Referenced by eVolve::LocalInitData::operator=(), and eVolve::LocalInitData::parseArguments().
void eVolve::InitData::setBrightness (const float brightness) inline protected
Definition at line 61 of file eVolve/initData.h.
Referenced by eVolve::LocalInitData::operator=(), and eVolve::LocalInitData::parseArguments().
void eVolve::InitData::setFilename (const std::string & filename) inline protected
Definition at line 63 of file eVolve/initData.h.
Referenced by eVolve::LocalInitData::operator=(), and eVolve::LocalInitData::parseArguments().
void eVolve::InitData::setFrameDataID (const co::UUID & id) inline
Definition at line 45 of file eVolve/initData.h.
Referenced by eVolve::Config::init(), and ~InitData().
void eVolve::InitData::setPrecision (const uint32_t precision) inline protected
Definition at line 60 of file eVolve/initData.h.
Referenced by eVolve::LocalInitData::operator=(), and eVolve::LocalInitData::parseArguments().
void eVolve::InitData::setWindowSystem (const eq::WindowSystem & windowSystem) inline protected
Definition at line 58 of file eVolve/initData.h.
Referenced by eVolve::LocalInitData::operator=(), and eVolve::LocalInitData::parseArguments().
The documentation for this class was generated from the following files:
eVolve/initData.h
eVolve/initData.cpp