EqualizerInternal: eqAsync::AsyncFetcher Class Reference
eqAsync::AsyncFetcher Class Reference
Asynchronous fetching thread.
#include <asyncFetcher.h>
Public Member Functions
AsyncFetcher ()
~AsyncFetcher ()
void setup (Window *window)
void stop ()
bool tryGetTextureId (TextureId &val)
void deleteTexture (const void *key)
Protected Member Functions
virtual void run ()
Function for creating and holding of shared context.
const GLEWContext * glewGetContext () const
Detailed Description
Asynchronous fetching thread.
Creates and supplies new textures to the main rendering pipe.
Definition at line 56 of file asyncFetcher.h.
Constructor & Destructor Documentation
eqAsync::AsyncFetcher::AsyncFetcher ()
Definition at line 41 of file asyncFetcher.cpp.
eqAsync::AsyncFetcher::~AsyncFetcher ()
Definition at line 47 of file asyncFetcher.cpp.
References stop().
Member Function Documentation
void eqAsync::AsyncFetcher::deleteTexture (const void * key) inline
Definition at line 67 of file asyncFetcher.h.
Referenced by eqAsync::Pipe::frameStart(), and stop().
const GLEWContext * eqAsync::AsyncFetcher::glewGetContext () const protected
Definition at line 52 of file asyncFetcher.cpp.
Referenced by run().
void eqAsync::AsyncFetcher::run () protected virtual
Function for creating and holding of shared context.
Generation and uploading of new textures over some period with sleep time.
Definition at line 120 of file asyncFetcher.cpp.
References glewGetContext().
void eqAsync::AsyncFetcher::setup (Window * window)
Definition at line 97 of file asyncFetcher.cpp.
Referenced by eqAsync::Pipe::startAsyncFetcher().
void eqAsync::AsyncFetcher::stop ()
Definition at line 103 of file asyncFetcher.cpp.
References deleteTexture().
Referenced by eqAsync::Pipe::configExit(), and ~AsyncFetcher().
bool eqAsync::AsyncFetcher::tryGetTextureId (TextureId & val) inline
Definition at line 66 of file asyncFetcher.h.
Referenced by eqAsync::Pipe::frameStart().
The documentation for this class was generated from the following files:
asyncFetcher.h
asyncFetcher.cpp