EqualizerInternal: mesh::VertexBufferNode Class Reference
mesh::VertexBufferNode Class Reference
#include <vertexBufferNode.h>
Public Member Functions
VertexBufferNode ()
virtual ~VertexBufferNode ()
virtual void draw (VertexBufferState &state) const
virtual Index getNumberOfVertices () const
virtual const VertexBufferBase * getLeft () const
virtual const VertexBufferBase * getRight () const
Public Member Functions inherited from mesh::VertexBufferBase
virtual ~VertexBufferBase ()
void drawBoundingSphere (VertexBufferState &state) const
const BoundingSphere & getBoundingSphere () const
const float * getRange () const
Protected Member Functions
virtual void toStream (std::ostream &os)
virtual void fromMemory (char **addr, VertexBufferData &globalData)
virtual void setupTree (VertexData &data, const Index start, const Index length, const Axis axis, const size_t depth, VertexBufferData &globalData)
virtual const BoundingSphere & updateBoundingSphere ()
virtual void updateRange ()
Protected Member Functions inherited from mesh::VertexBufferBase
VertexBufferBase ()
Friends
class eqPly::VertexBufferDist
Additional Inherited Members
Protected Attributes inherited from mesh::VertexBufferBase
BoundingSphere _boundingSphere
Range _range
Detailed Description
Definition at line 43 of file vertexBufferNode.h.
Constructor & Destructor Documentation
mesh::VertexBufferNode::VertexBufferNode () inline
Definition at line 46 of file vertexBufferNode.h.
Referenced by fromMemory(), and setupTree().
mesh::VertexBufferNode::~VertexBufferNode () virtual
Definition at line 41 of file vertexBufferNode.cpp.
Member Function Documentation
void mesh::VertexBufferNode::draw (VertexBufferState & state) const virtual
Implements mesh::VertexBufferBase.
Reimplemented in mesh::VertexBufferRoot.
Definition at line 154 of file vertexBufferNode.cpp.
References mesh::VertexBufferBase::draw(), and mesh::VertexBufferState::stopRendering().
Referenced by mesh::VertexBufferRoot::draw().
void mesh::VertexBufferNode::fromMemory (char ** addr, VertexBufferData & globalData) protected virtual
Reimplemented from mesh::VertexBufferBase.
Definition at line 165 of file vertexBufferNode.cpp.
References mesh::VertexBufferBase::fromMemory(), mesh::LEAF_TYPE, mesh::memRead(), mesh::NODE_TYPE, and VertexBufferNode().
Referenced by mesh::VertexBufferRoot::fromMemory().
virtual const VertexBufferBase* mesh::VertexBufferNode::getLeft () const inline virtual
Reimplemented from mesh::VertexBufferBase.
Definition at line 53 of file vertexBufferNode.h.
Referenced by eqPly::VertexBufferDist::VertexBufferDist().
virtual Index mesh::VertexBufferNode::getNumberOfVertices () const inline virtual
Implements mesh::VertexBufferBase.
Definition at line 50 of file vertexBufferNode.h.
References mesh::VertexBufferBase::getNumberOfVertices().
virtual const VertexBufferBase* mesh::VertexBufferNode::getRight () const inline virtual
Reimplemented from mesh::VertexBufferBase.
Definition at line 54 of file vertexBufferNode.h.
Referenced by eqPly::VertexBufferDist::VertexBufferDist().
void mesh::VertexBufferNode::setupTree (VertexData & data, const Index start, const Index length, const Axis axis, const size_t depth, VertexBufferData & globalData) protected virtual
Implements mesh::VertexBufferBase.
Definition at line 55 of file vertexBufferNode.cpp.
References mesh::AXIS_X, mesh::VertexData::getLongestAxis(), MESHINFO, mesh::VertexData::sort(), and VertexBufferNode().
Referenced by mesh::VertexBufferRoot::setupTree().
void mesh::VertexBufferNode::toStream (std::ostream & os) protected virtual
Reimplemented from mesh::VertexBufferBase.
Reimplemented in mesh::VertexBufferRoot.
Definition at line 202 of file vertexBufferNode.cpp.
References mesh::NODE_TYPE, and mesh::VertexBufferBase::toStream().
Referenced by mesh::VertexBufferRoot::toStream().
const BoundingSphere & mesh::VertexBufferNode::updateBoundingSphere () protected virtual
Implements mesh::VertexBufferBase.
Definition at line 105 of file vertexBufferNode.cpp.
References mesh::VertexBufferBase::_boundingSphere, MESHINFO, and mesh::VertexBufferBase::updateBoundingSphere().
Referenced by mesh::VertexBufferRoot::setupTree().
void mesh::VertexBufferNode::updateRange () protected virtual
Implements mesh::VertexBufferBase.
Definition at line 136 of file vertexBufferNode.cpp.
References mesh::VertexBufferBase::_range, mesh::VertexBufferBase::getRange(), and MESHINFO.
Referenced by mesh::VertexBufferRoot::setupTree().
Friends And Related Function Documentation
friend class eqPly::VertexBufferDist friend
Definition at line 70 of file vertexBufferNode.h.
The documentation for this class was generated from the following files:
vertexBufferNode.h
vertexBufferNode.cpp