EqualizerInternal: eqPly::VertexBufferState Class Reference
eqPly::VertexBufferState Class Reference
#include <vertexBufferState.h>
Public Member Functions
VertexBufferState (eq::Window::ObjectManager *objectManager)
virtual GLuint getDisplayList (const void *key)
virtual GLuint newDisplayList (const void *key)
virtual GLuint getTexture (const void *key)
virtual GLuint newTexture (const void *key)
virtual GLuint getBufferObject (const void *key)
virtual GLuint newBufferObject (const void *key)
virtual GLuint getProgram (const void *key)
virtual GLuint newProgram (const void *key)
virtual GLuint getShader (const void *key)
virtual GLuint newShader (const void *key, GLenum type)
virtual void deleteAll ()
bool isShared () const
void setChannel (Channel *channel)
virtual bool stopRendering () const
virtual void declareRegion (const mesh::Vector4f &region)
Public Member Functions inherited from mesh::VertexBufferState
virtual bool useColors () const
virtual void setColors (const bool colors)
virtual RenderMode getRenderMode () const
virtual void setRenderMode (const RenderMode mode)
virtual bool useFrustumCulling () const
virtual void setFrustumCulling (const bool frustumCullingState)
void setProjectionModelViewMatrix (const Matrix4f &pmv)
const Matrix4f & getProjectionModelViewMatrix () const
void setRange (const Range &range)
const Range & getRange () const
void resetRegion ()
void updateRegion (const BoundingBox &box)
Vector4f getRegion () const
const GLEWContext * glewGetContext () const
Additional Inherited Members
Public Types inherited from mesh::VertexBufferState
enum { INVALID = 0 }
Protected Member Functions inherited from mesh::VertexBufferState
VertexBufferState (const GLEWContext *glewContext)
virtual ~VertexBufferState ()
Protected Attributes inherited from mesh::VertexBufferState
Matrix4f _pmvMatrix
projection * modelView matrix
Range _range
normalized [0,1] part of the model to draw
const GLEWContext *const _glewContext
RenderMode _renderMode
Vector4f _region
normalized x1 y1 x2 y2 region from cullDraw
bool _useColors
bool _useFrustumCulling
Detailed Description
Definition at line 126 of file vertexBufferState.h.
Constructor & Destructor Documentation
eqPly::VertexBufferState::VertexBufferState (eq::Window::ObjectManager * objectManager) inline
Definition at line 129 of file vertexBufferState.h.
Member Function Documentation
virtual void eqPly::VertexBufferState::declareRegion (const mesh::Vector4f & region) inline virtual
Reimplemented from mesh::VertexBufferState.
Definition at line 172 of file vertexBufferState.h.
virtual void eqPly::VertexBufferState::deleteAll () inline virtual
Implements mesh::VertexBufferState.
Definition at line 164 of file vertexBufferState.h.
Referenced by eqPly::Window::configExitGL().
virtual GLuint eqPly::VertexBufferState::getBufferObject (const void * key) inline virtual
Implements mesh::VertexBufferState.
Definition at line 146 of file vertexBufferState.h.
virtual GLuint eqPly::VertexBufferState::getDisplayList (const void * key) inline virtual
Implements mesh::VertexBufferState.
Definition at line 134 of file vertexBufferState.h.
virtual GLuint eqPly::VertexBufferState::getProgram (const void * key) inline virtual
Definition at line 152 of file vertexBufferState.h.
virtual GLuint eqPly::VertexBufferState::getShader (const void * key) inline virtual
Definition at line 158 of file vertexBufferState.h.
virtual GLuint eqPly::VertexBufferState::getTexture (const void * key) inline virtual
Definition at line 140 of file vertexBufferState.h.
bool eqPly::VertexBufferState::isShared () const inline
Definition at line 165 of file vertexBufferState.h.
Referenced by eqPly::Window::configExitGL().
virtual GLuint eqPly::VertexBufferState::newBufferObject (const void * key) inline virtual
Implements mesh::VertexBufferState.
Definition at line 149 of file vertexBufferState.h.
virtual GLuint eqPly::VertexBufferState::newDisplayList (const void * key) inline virtual
Implements mesh::VertexBufferState.
Definition at line 137 of file vertexBufferState.h.
virtual GLuint eqPly::VertexBufferState::newProgram (const void * key) inline virtual
Definition at line 155 of file vertexBufferState.h.
virtual GLuint eqPly::VertexBufferState::newShader (const void * key, GLenum type) inline virtual
Definition at line 161 of file vertexBufferState.h.
virtual GLuint eqPly::VertexBufferState::newTexture (const void * key) inline virtual
Definition at line 143 of file vertexBufferState.h.
void eqPly::VertexBufferState::setChannel (Channel * channel) inline
Definition at line 167 of file vertexBufferState.h.
virtual bool eqPly::VertexBufferState::stopRendering () const inline virtual
Reimplemented from mesh::VertexBufferState.
Definition at line 169 of file vertexBufferState.h.
References eqPly::Channel::stopRendering().
The documentation for this class was generated from the following file:
vertexBufferState.h