EqualizerInternal: osgScaleViewer::Config Class Reference
osgScaleViewer::Config Class Reference
#include <config.h>
Public Member Functions
Config (eq::ServerPtr parent)
virtual bool init ()
Reimplemented.
virtual bool exit ()
Reimplemented.
virtual uint32_t startFrame ()
Reimplemented.
virtual bool handleEvent (const eq::ConfigEvent *event)
Reimplemented for camera controls.
void setInitData (const InitData &data)
Sets the InitData object.
const InitData & getInitData () const
Gets the InitData object.
bool mapData (const eq::uint128_t &initDataID)
Protected Member Functions
void updateFrameData (float elapsed)
Detailed Description
Definition at line 45 of file osgScaleViewer/config.h.
Constructor & Destructor Documentation
osgScaleViewer::Config::Config (eq::ServerPtr parent)
Definition at line 54 of file osgScaleViewer/config.cpp.
Member Function Documentation
bool osgScaleViewer::Config::exit () virtual
Reimplemented.
Definition at line 95 of file osgScaleViewer/config.cpp.
References osgScaleViewer::InitData::setFrameDataID().
Referenced by osgScaleViewer::OSGScaleViewer::run().
const InitData & osgScaleViewer::Config::getInitData () const
Gets the InitData object.
Returns
the init data.
Definition at line 156 of file osgScaleViewer/config.cpp.
Referenced by osgScaleViewer::Node::configInit(), and osgScaleViewer::Pipe::configInit().
bool osgScaleViewer::Config::handleEvent (const eq::ConfigEvent * event) virtual
Reimplemented for camera controls.
If a keypress happens, this function updates _moveDirection, so that the new camera position can be calculated in updateFrameData(). If a mouse move event happens, this function updates _pointerXDiff and mPointerYDiff, so that the new camera viewing direction can be calculated in updateFrameData().
Definition at line 175 of file osgScaleViewer/config.cpp.
References orthographicVector(), and osgScaleViewer::FrameData::toggleStatistics().
bool osgScaleViewer::Config::init () virtual
Reimplemented.
Definition at line 65 of file osgScaleViewer/config.cpp.
References osgScaleViewer::InitData::getTrackerPort(), Tracker::init(), M_PI_2, osgScaleViewer::InitData::setFrameDataID(), Tracker::setSensorToObject(), and Tracker::setWorldToEmitter().
Referenced by osgScaleViewer::OSGScaleViewer::run().
bool osgScaleViewer::Config::mapData (const eq::uint128_t & initDataID)
Definition at line 161 of file osgScaleViewer/config.cpp.
Referenced by osgScaleViewer::Node::configInit().
void osgScaleViewer::Config::setInitData (const InitData & data)
Sets the InitData object.
Parameters
data the init data.
Definition at line 151 of file osgScaleViewer/config.cpp.
Referenced by osgScaleViewer::OSGScaleViewer::run().
uint32_t osgScaleViewer::Config::startFrame () virtual
Reimplemented.
Definition at line 133 of file osgScaleViewer/config.cpp.
References Tracker::getMatrix(), Tracker::isRunning(), Tracker::update(), and updateFrameData().
Referenced by osgScaleViewer::OSGScaleViewer::run().
void osgScaleViewer::Config::updateFrameData (float elapsed) protected
Definition at line 105 of file osgScaleViewer/config.cpp.
References osgScaleViewer::FrameData::getCameraPosition(), osgScaleViewer::FrameData::setCameraLookAtPoint(), osgScaleViewer::FrameData::setCameraPosition(), and osgScaleViewer::FrameData::setCameraUpVector().
Referenced by startFrame().
The documentation for this class was generated from the following files:
osgScaleViewer/config.h
osgScaleViewer/config.cpp