EqualizerInternal: eqPly::VertexBufferDist Class Reference
eqPly::VertexBufferDist Class Reference
co::Object to distribute a model, holds a VertexBufferBase node.
#include <vertexBufferDist.h>
Public Member Functions
VertexBufferDist ()
VertexBufferDist (const mesh::VertexBufferRoot *root)
virtual ~VertexBufferDist ()
void registerTree (co::LocalNodePtr node)
void deregisterTree ()
mesh::VertexBufferRoot * loadModel (co::NodePtr master, co::LocalNodePtr localNode, const eq::uint128_t &modelID)
Protected Member Functions
VertexBufferDist (const mesh::VertexBufferRoot *root, const mesh::VertexBufferBase *node)
virtual void getInstanceData (co::DataOStream &os)
virtual void applyInstanceData (co::DataIStream &is)
Detailed Description
co::Object to distribute a model, holds a VertexBufferBase node.
Definition at line 41 of file vertexBufferDist.h.
Constructor & Destructor Documentation
eqPly::VertexBufferDist::VertexBufferDist ()
Definition at line 40 of file vertexBufferDist.cpp.
Referenced by applyInstanceData(), and VertexBufferDist().
eqPly::VertexBufferDist::VertexBufferDist (const mesh::VertexBufferRoot * root)
Definition at line 48 of file vertexBufferDist.cpp.
References mesh::VertexBufferNode::getLeft(), mesh::VertexBufferNode::getRight(), and VertexBufferDist().
eqPly::VertexBufferDist::~VertexBufferDist () virtual
Definition at line 80 of file vertexBufferDist.cpp.
eqPly::VertexBufferDist::VertexBufferDist (const mesh::VertexBufferRoot * root, const mesh::VertexBufferBase * node) protected
Definition at line 62 of file vertexBufferDist.cpp.
References mesh::VertexBufferBase::getLeft(), mesh::VertexBufferBase::getRight(), and VertexBufferDist().
Member Function Documentation
void eqPly::VertexBufferDist::applyInstanceData (co::DataIStream & is) protected virtual
Definition at line 178 of file vertexBufferDist.cpp.
References mesh::VertexBufferBase::_boundingSphere, mesh::VertexBufferBase::_range, mesh::VertexBufferData::colors, mesh::VertexBufferData::indices, mesh::VertexBufferData::normals, VertexBufferDist(), and mesh::VertexBufferData::vertices.
void eqPly::VertexBufferDist::deregisterTree ()
Definition at line 100 of file vertexBufferDist.cpp.
References deregisterTree().
Referenced by deregisterTree().
void eqPly::VertexBufferDist::getInstanceData (co::DataOStream & os) protected virtual
Definition at line 144 of file vertexBufferDist.cpp.
References mesh::VertexBufferBase::_boundingSphere, mesh::VertexBufferBase::_range, mesh::VertexBufferData::colors, mesh::VertexBufferData::indices, mesh::VertexBufferData::normals, and mesh::VertexBufferData::vertices.
mesh::VertexBufferRoot * eqPly::VertexBufferDist::loadModel (co::NodePtr master, co::LocalNodePtr localNode, const eq::uint128_t & modelID)
Definition at line 113 of file vertexBufferDist.cpp.
Referenced by seqPly::Application::getModel().
void eqPly::VertexBufferDist::registerTree (co::LocalNodePtr node)
Definition at line 88 of file vertexBufferDist.cpp.
References registerTree().
Referenced by registerTree().
The documentation for this class was generated from the following files:
vertexBufferDist.h
vertexBufferDist.cpp