EqualizerInternal: eqPly::LocalInitData Class Reference
eqPly::LocalInitData Class Reference
Manages the argument parsing and non-distributed part of the initialization data.
#include <localInitData.h>
Public Member Functions
LocalInitData ()
void parseArguments (const int argc, char **argv)
const std::string & getPathFilename () const
uint32_t getMaxFrames () const
bool useColor () const
bool isResident () const
const std::vector< std::string > & getFilenames () const
const LocalInitData & operator= (const LocalInitData &from)
Public Member Functions inherited from eqPly::InitData
InitData ()
virtual ~InitData ()
void setFrameDataID (const eq::uint128_t &id)
eq::uint128_t getFrameDataID () const
eq::WindowSystem getWindowSystem () const
mesh::RenderMode getRenderMode () const
bool useGLSL () const
bool useInvertedFaces () const
bool showLogo () const
bool useROI () const
Additional Inherited Members
Protected Member Functions inherited from eqPly::InitData
virtual void getInstanceData (co::DataOStream &os)
virtual void applyInstanceData (co::DataIStream &is)
void setWindowSystem (const eq::WindowSystem windowSystem)
void setRenderMode (const mesh::RenderMode renderMode)
void enableGLSL ()
void enableInvertedFaces ()
void disableLogo ()
void disableROI ()
Detailed Description
Manages the argument parsing and non-distributed part of the initialization data.
Definition at line 42 of file eqPly/localInitData.h.
Constructor & Destructor Documentation
eqPly::LocalInitData::LocalInitData ()
Definition at line 43 of file eqPly/localInitData.cpp.
Member Function Documentation
const std::vector< std::string >& eqPly::LocalInitData::getFilenames () const inline
Definition at line 54 of file eqPly/localInitData.h.
uint32_t eqPly::LocalInitData::getMaxFrames () const inline
Definition at line 50 of file eqPly/localInitData.h.
Referenced by eqPly::EqPly::run().
const std::string& eqPly::LocalInitData::getPathFilename () const inline
Definition at line 49 of file eqPly/localInitData.h.
Referenced by eqPly::Config::init().
bool eqPly::LocalInitData::isResident () const inline
Definition at line 52 of file eqPly/localInitData.h.
Referenced by eqPly::EqPly::clientLoop().
const LocalInitData & eqPly::LocalInitData::operator= (const LocalInitData & from)
Definition at line 62 of file eqPly/localInitData.cpp.
References eqPly::InitData::disableLogo(), eqPly::InitData::disableROI(), eqPly::InitData::enableGLSL(), eqPly::InitData::enableInvertedFaces(), eqPly::InitData::getRenderMode(), eqPly::InitData::getWindowSystem(), eqPly::InitData::setRenderMode(), eqPly::InitData::setWindowSystem(), eqPly::InitData::showLogo(), eqPly::InitData::useGLSL(), eqPly::InitData::useInvertedFaces(), and eqPly::InitData::useROI().
void eqPly::LocalInitData::parseArguments (const int argc, char ** argv)
Definition at line 84 of file eqPly/localInitData.cpp.
References eqPly::InitData::disableLogo(), eqPly::InitData::disableROI(), eqPly::InitData::enableGLSL(), eqPly::InitData::enableInvertedFaces(), eqPly::EqPly::getHelp(), mesh::RENDER_MODE_BUFFER_OBJECT, mesh::RENDER_MODE_DISPLAY_LIST, mesh::RENDER_MODE_IMMEDIATE, eqPly::InitData::setRenderMode(), and eqPly::InitData::setWindowSystem().
Referenced by main().
bool eqPly::LocalInitData::useColor () const inline
Definition at line 51 of file eqPly/localInitData.h.
Referenced by eqPly::Config::init().
The documentation for this class was generated from the following files:
eqPly/localInitData.h
eqPly/localInitData.cpp