EqualizerInternal: eqNbody::InitData Class Reference
eqNbody::InitData Class Reference
#include <initData.h>
Public Member Functions
InitData ()
virtual ~InitData ()
void setFrameDataID (const eq::uint128_t id)
const eq::uint128_t & getFrameDataID () const
float getDamping () const
uint32_t getNumBodies () const
uint32_t getP () const
uint32_t getQ () const
Protected Member Functions
virtual void getInstanceData (co::DataOStream &os)
virtual void applyInstanceData (co::DataIStream &is)
Detailed Description
Definition at line 38 of file eqNBody/initData.h.
Constructor & Destructor Documentation
eqNbody::InitData::InitData ()
Definition at line 40 of file eqNBody/initData.cpp.
References NUM_BODIES.
eqNbody::InitData::~InitData () virtual
Definition at line 48 of file eqNBody/initData.cpp.
References setFrameDataID().
Member Function Documentation
void eqNbody::InitData::applyInstanceData (co::DataIStream & is) protected virtual
Definition at line 58 of file eqNBody/initData.cpp.
float eqNbody::InitData::getDamping () const inline
Definition at line 47 of file eqNBody/initData.h.
Referenced by eqNbody::Controller::init().
const eq::uint128_t& eqNbody::InitData::getFrameDataID () const inline
Definition at line 45 of file eqNBody/initData.h.
Referenced by eqNbody::Pipe::configInit().
void eqNbody::InitData::getInstanceData (co::DataOStream & os) protected virtual
Definition at line 53 of file eqNBody/initData.cpp.
uint32_t eqNbody::InitData::getNumBodies () const inline
Definition at line 48 of file eqNBody/initData.h.
Referenced by eqNbody::Pipe::configInit(), eqNbody::Config::init(), and eqNbody::Controller::init().
uint32_t eqNbody::InitData::getP () const inline
Definition at line 49 of file eqNBody/initData.h.
Referenced by eqNbody::Controller::init().
uint32_t eqNbody::InitData::getQ () const inline
Definition at line 50 of file eqNBody/initData.h.
Referenced by eqNbody::Controller::init().
void eqNbody::InitData::setFrameDataID (const eq::uint128_t id) inline
Definition at line 44 of file eqNBody/initData.h.
Referenced by eqNbody::Config::init(), and ~InitData().
The documentation for this class was generated from the following files:
eqNBody/initData.h
eqNBody/initData.cpp