EqualizerInternal: eqNbody::Config Class Reference
eqNbody::Config Class Reference
#include <config.h>
Public Member Functions
Config (eq::ServerPtr parent)
virtual bool init ()
virtual bool exit ()
virtual uint32_t startFrame ()
void setInitData (const InitData &data)
const InitData & getInitData () const
void mapData (const eq::uint128_t &initDataID)
void releaseData ()
virtual bool handleEvent (eq::EventICommand command)
virtual bool handleEvent (const eq::ConfigEvent *event)
bool needsRedraw ()
Protected Member Functions
virtual ~Config ()
Detailed Description
Definition at line 42 of file eqNBody/config.h.
Constructor & Destructor Documentation
eqNbody::Config::Config (eq::ServerPtr parent)
Definition at line 36 of file eqNBody/config.cpp.
virtual eqNbody::Config::~Config () inline protected virtual
Definition at line 63 of file eqNBody/config.h.
Member Function Documentation
bool eqNbody::Config::exit () virtual
Definition at line 61 of file eqNBody/config.cpp.
Referenced by eqNbody::Client::exit().
const InitData& eqNbody::Config::getInitData () const inline
Definition at line 53 of file eqNBody/config.h.
Referenced by eqNbody::Pipe::configInit().
bool eqNbody::Config::handleEvent (eq::EventICommand command) virtual
Definition at line 119 of file eqNBody/config.cpp.
References eqNbody::FrameData::commit(), eqNbody::DATA_CHANGED, and eqNbody::PROXY_CHANGED.
bool eqNbody::Config::handleEvent (const eq::ConfigEvent * event) virtual
Definition at line 150 of file eqNBody/config.cpp.
bool eqNbody::Config::init () virtual
Definition at line 42 of file eqNBody/config.cpp.
References eqNbody::InitData::getNumBodies(), eqNbody::FrameData::init(), and eqNbody::InitData::setFrameDataID().
Referenced by eqNbody::Client::init().
void eqNbody::Config::mapData (const eq::uint128_t & initDataID)
Definition at line 78 of file eqNBody/config.cpp.
References releaseData().
Referenced by eqNbody::Node::configInit().
bool eqNbody::Config::needsRedraw ()
Definition at line 114 of file eqNBody/config.cpp.
Referenced by eqNbody::Client::run().
void eqNbody::Config::releaseData ()
Definition at line 91 of file eqNBody/config.cpp.
Referenced by eqNbody::Node::configExit(), and mapData().
void eqNbody::Config::setInitData (const InitData & data) inline
Definition at line 52 of file eqNBody/config.h.
Referenced by eqNbody::Client::init().
uint32_t eqNbody::Config::startFrame () virtual
Definition at line 96 of file eqNBody/config.cpp.
References eqNbody::FrameData::commit(), eqNbody::FrameData::initHostData(), eqNbody::NBODY_CONFIG_SHELL, and eqNbody::FrameData::updateParameters().
Referenced by eqNbody::Client::run().
The documentation for this class was generated from the following files:
eqNBody/config.h
eqNBody/config.cpp