EqualizerInternal: eVolve::LocalInitData Class Reference
eVolve::LocalInitData Class Reference
#include <localInitData.h>
Public Member Functions
LocalInitData ()
void parseArguments (int argc, char **argv)
bool isResident () const
bool getOrtho () const
uint32_t getMaxFrames () const
const LocalInitData & operator= (const LocalInitData &from)
Public Member Functions inherited from eVolve::InitData
InitData ()
virtual ~InitData ()
void setFrameDataID (const co::UUID &id)
lunchbox::UUID getFrameDataID () const
eq::WindowSystem getWindowSystem () const
uint32_t getPrecision () const
float getBrightness () const
float getAlpha () const
const std::string & getFilename () const
Additional Inherited Members
Protected Member Functions inherited from eVolve::InitData
virtual void getInstanceData (co::DataOStream &os)
virtual void applyInstanceData (co::DataIStream &is)
void setWindowSystem (const eq::WindowSystem &windowSystem)
void setPrecision (const uint32_t precision)
void setBrightness (const float brightness)
void setAlpha (const float alpha)
void setFilename (const std::string &filename)
Detailed Description
Definition at line 38 of file eVolve/localInitData.h.
Constructor & Destructor Documentation
eVolve::LocalInitData::LocalInitData ()
Definition at line 43 of file eVolve/localInitData.cpp.
Member Function Documentation
uint32_t eVolve::LocalInitData::getMaxFrames () const inline
Definition at line 47 of file eVolve/localInitData.h.
Referenced by eVolve::EVolve::run().
bool eVolve::LocalInitData::getOrtho () const inline
Definition at line 46 of file eVolve/localInitData.h.
Referenced by eVolve::Config::init().
bool eVolve::LocalInitData::isResident () const inline
Definition at line 45 of file eVolve/localInitData.h.
Referenced by eVolve::EVolve::clientLoop().
const LocalInitData & eVolve::LocalInitData::operator= (const LocalInitData & from)
Definition at line 49 of file eVolve/localInitData.cpp.
References eVolve::InitData::getAlpha(), eVolve::InitData::getBrightness(), eVolve::InitData::getFilename(), eVolve::InitData::getPrecision(), eVolve::InitData::getWindowSystem(), eVolve::InitData::setAlpha(), eVolve::InitData::setBrightness(), eVolve::InitData::setFilename(), eVolve::InitData::setPrecision(), and eVolve::InitData::setWindowSystem().
void eVolve::LocalInitData::parseArguments (int argc, char ** argv)
Definition at line 63 of file eVolve/localInitData.cpp.
References eVolve::EVolve::getHelp(), eVolve::InitData::setAlpha(), eVolve::InitData::setBrightness(), eVolve::InitData::setFilename(), eVolve::InitData::setPrecision(), and eVolve::InitData::setWindowSystem().
Referenced by main().
The documentation for this class was generated from the following files:
eVolve/localInitData.h
eVolve/localInitData.cpp