EqualizerInternal: mesh::VertexBufferLeaf Class Reference
mesh::VertexBufferLeaf Class Reference
#include <vertexBufferLeaf.h>
Public Member Functions
VertexBufferLeaf (VertexBufferData &data)
virtual ~VertexBufferLeaf ()
virtual void draw (VertexBufferState &state) const
virtual Index getNumberOfVertices () const
Public Member Functions inherited from mesh::VertexBufferBase
virtual ~VertexBufferBase ()
void drawBoundingSphere (VertexBufferState &state) const
const BoundingSphere & getBoundingSphere () const
const float * getRange () const
virtual const VertexBufferBase * getLeft () const
virtual const VertexBufferBase * getRight () const
Protected Member Functions
virtual void toStream (std::ostream &os)
virtual void fromMemory (char **addr, VertexBufferData &globalData)
virtual void setupTree (VertexData &data, const Index start, const Index length, const Axis axis, const size_t depth, VertexBufferData &globalData)
virtual const BoundingSphere & updateBoundingSphere ()
virtual void updateRange ()
Protected Member Functions inherited from mesh::VertexBufferBase
VertexBufferBase ()
Friends
class eqPly::VertexBufferDist
Additional Inherited Members
Protected Attributes inherited from mesh::VertexBufferBase
BoundingSphere _boundingSphere
Range _range
Detailed Description
Definition at line 44 of file vertexBufferLeaf.h.
Constructor & Destructor Documentation
mesh::VertexBufferLeaf::VertexBufferLeaf (VertexBufferData & data) inline
Definition at line 47 of file vertexBufferLeaf.h.
virtual mesh::VertexBufferLeaf::~VertexBufferLeaf () inline virtual
Definition at line 50 of file vertexBufferLeaf.h.
Member Function Documentation
void mesh::VertexBufferLeaf::draw (VertexBufferState & state) const virtual
Implements mesh::VertexBufferBase.
Definition at line 264 of file vertexBufferLeaf.cpp.
References mesh::VertexBufferState::getRenderMode(), mesh::RENDER_MODE_BUFFER_OBJECT, mesh::RENDER_MODE_DISPLAY_LIST, mesh::RENDER_MODE_IMMEDIATE, mesh::VertexBufferState::stopRendering(), and mesh::VertexBufferState::updateRegion().
void mesh::VertexBufferLeaf::fromMemory (char ** addr, VertexBufferData & globalData) protected virtual
Reimplemented from mesh::VertexBufferBase.
Definition at line 348 of file vertexBufferLeaf.cpp.
References mesh::VertexBufferBase::fromMemory(), mesh::LEAF_TYPE, and mesh::memRead().
virtual Index mesh::VertexBufferLeaf::getNumberOfVertices () const inline virtual
Implements mesh::VertexBufferBase.
Definition at line 53 of file vertexBufferLeaf.h.
void mesh::VertexBufferLeaf::setupTree (VertexData & data, const Index start, const Index length, const Axis axis, const size_t depth, VertexBufferData & globalData) protected virtual
Implements mesh::VertexBufferBase.
Definition at line 41 of file vertexBufferLeaf.cpp.
References mesh::VertexData::colors, mesh::VertexBufferData::colors, mesh::VertexBufferData::indices, MESHASSERT, MESHINFO, mesh::VertexData::normals, mesh::VertexBufferData::normals, mesh::VertexData::sort(), mesh::VertexData::triangles, mesh::VertexData::vertices, and mesh::VertexBufferData::vertices.
void mesh::VertexBufferLeaf::toStream (std::ostream & os) protected virtual
Reimplemented from mesh::VertexBufferBase.
Definition at line 370 of file vertexBufferLeaf.cpp.
References mesh::LEAF_TYPE, and mesh::VertexBufferBase::toStream().
const BoundingSphere & mesh::VertexBufferLeaf::updateBoundingSphere () protected virtual
Implements mesh::VertexBufferBase.
Definition at line 86 of file vertexBufferLeaf.cpp.
References mesh::VertexBufferBase::_boundingSphere, mesh::VertexBufferData::indices, MESHINFO, and mesh::VertexBufferData::vertices.
void mesh::VertexBufferLeaf::updateRange () protected virtual
Implements mesh::VertexBufferBase.
Definition at line 189 of file vertexBufferLeaf.cpp.
References mesh::VertexBufferBase::_range, mesh::VertexBufferData::indices, and MESHINFO.
Friends And Related Function Documentation
friend class eqPly::VertexBufferDist friend
Definition at line 78 of file vertexBufferLeaf.h.
The documentation for this class was generated from the following files:
vertexBufferLeaf.h
vertexBufferLeaf.cpp