EqualizerInternal: eqAsync::Pipe Class Reference
eqAsync::Pipe Class Reference
#include <eqAsync.h>
Public Member Functions
Pipe (eq::Node *parent)
void startAsyncFetcher (Window *wnd)
AsyncFetcher & getAsyncFetcher ()
GLuint getTextureId () const
Protected Member Functions
virtual void frameStart (const eq::uint128_t &frameID, const uint32_t frameNumber)
virtual bool configExit ()
Detailed Description
Definition at line 62 of file eqAsync.h.
Constructor & Destructor Documentation
eqAsync::Pipe::Pipe (eq::Node * parent) inline
Definition at line 65 of file eqAsync.h.
Member Function Documentation
bool eqAsync::Pipe::configExit () protected virtual
Definition at line 70 of file eqAsync.cpp.
References eqAsync::AsyncFetcher::stop().
void eqAsync::Pipe::frameStart (const eq::uint128_t & frameID, const uint32_t frameNumber) protected virtual
Definition at line 56 of file eqAsync.cpp.
References eqAsync::AsyncFetcher::deleteTexture(), eqAsync::TextureId::key, and eqAsync::AsyncFetcher::tryGetTextureId().
AsyncFetcher& eqAsync::Pipe::getAsyncFetcher () inline
Definition at line 69 of file eqAsync.h.
GLuint eqAsync::Pipe::getTextureId () const inline
Definition at line 70 of file eqAsync.h.
References eqAsync::TextureId::id.
Referenced by eqAsync::Channel::frameDraw().
void eqAsync::Pipe::startAsyncFetcher (Window * wnd)
Definition at line 46 of file eqAsync.cpp.
References eqAsync::AsyncFetcher::setup().
Referenced by eqAsync::Window::configInitGL().
The documentation for this class was generated from the following files:
eqAsync.h
eqAsync.cpp