EqualizerInternal: eVolve::RawVolumeModelRenderer Class Reference
eVolve::RawVolumeModelRenderer Class Reference
#include <rawVolModelRenderer.h>
Public Member Functions
RawVolumeModelRenderer (const std::string &filename, const uint32_t precision=1)
bool loadHeader (const float brightness, const float alpha)
const VolumeScaling & getVolumeScaling () const
void glewSetContext (const GLEWContext *context)
bool render (const eq::Range &range, const eq::Matrix4d &modelviewM, const eq::Matrix3d &modelviewITM, const eq::Matrix4f &invRotationM, const eq::Vector4f &taintColor, const int normalsQuality)
void setPrecision (const uint32_t precision)
void setOrtho (const uint32_t ortho)
const GLEWContext * glewGetContext ()
bool loadShaders ()
Detailed Description
Definition at line 40 of file rawVolModelRenderer.h.
Constructor & Destructor Documentation
eVolve::RawVolumeModelRenderer::RawVolumeModelRenderer (const std::string & filename, const uint32_t precision = 1)
Definition at line 39 of file rawVolModelRenderer.cpp.
Member Function Documentation
const VolumeScaling& eVolve::RawVolumeModelRenderer::getVolumeScaling () const inline
Definition at line 51 of file rawVolModelRenderer.h.
References eVolve::RawVolumeModel::getVolumeScaling().
const GLEWContext* eVolve::RawVolumeModelRenderer::glewGetContext () inline
Definition at line 73 of file rawVolModelRenderer.h.
void eVolve::RawVolumeModelRenderer::glewSetContext (const GLEWContext * context) inline
Definition at line 56 of file rawVolModelRenderer.h.
References eVolve::RawVolumeModel::glewSetContext().
Referenced by eVolve::Window::configInitGL().
bool eVolve::RawVolumeModelRenderer::loadHeader (const float brightness, const float alpha) inline
Definition at line 46 of file rawVolModelRenderer.h.
References eVolve::RawVolumeModel::loadHeader().
Referenced by eVolve::Pipe::configInit().
bool eVolve::RawVolumeModelRenderer::loadShaders ()
Definition at line 199 of file rawVolModelRenderer.cpp.
References eVolve::GLSLShaders::loadShaders().
Referenced by eVolve::Window::configInitGL().
bool eVolve::RawVolumeModelRenderer::render (const eq::Range & range, const eq::Matrix4d & modelviewM, const eq::Matrix3d & modelviewITM, const eq::Matrix4f & invRotationM, const eq::Vector4f & taintColor, const int normalsQuality)
Definition at line 149 of file rawVolModelRenderer.cpp.
References eVolve::VolumeScaling::D, eVolve::VolumeScaling::H, eVolve::VolumeInfo::volScaling, and eVolve::VolumeScaling::W.
Referenced by eVolve::Channel::frameDraw().
void eVolve::RawVolumeModelRenderer::setOrtho (const uint32_t ortho) inline
Definition at line 71 of file rawVolModelRenderer.h.
Referenced by eVolve::Pipe::frameStart().
void eVolve::RawVolumeModelRenderer::setPrecision (const uint32_t precision) inline
Definition at line 70 of file rawVolModelRenderer.h.
The documentation for this class was generated from the following files:
rawVolModelRenderer.h
rawVolModelRenderer.cpp