EqualizerInternal: main.cpp File Reference
eVolve/main.cpp File Reference
#include "eVolve.h"
#include "channel.h"
#include "config.h"
#include "error.h"
#include "node.h"
#include "pipe.h"
#include "window.h"
#include <stdlib.h>
Classes
class NodeFactory
Functions
int main (const int argc, char **argv)
Function Documentation
int main (const int argc, char ** argv)
Definition at line 55 of file eVolve/main.cpp.
References eVolve::exitErrors(), eVolve::initErrors(), and eVolve::LocalInitData::parseArguments().