EqualizerInternal: eqAdmin Namespace Reference
eqAdmin Namespace Reference
Functions
bool addWindow (eq::admin::ServerPtr server, const bool passiveStereo)
eq::admin::Pipe * findPipe (eq::admin::ServerPtr server)
bool removeWindow (eq::admin::ServerPtr server)
Function Documentation
bool eqAdmin::addWindow (eq::admin::ServerPtr server, const bool passiveStereo) inline
Definition at line 38 of file addWindow.h.
References findPipe().
eq::admin::Pipe* eqAdmin::findPipe (eq::admin::ServerPtr server) inline
Definition at line 36 of file findPipe.h.
Referenced by addWindow(), and removeWindow().
bool eqAdmin::removeWindow (eq::admin::ServerPtr server) inline
Definition at line 142 of file removeWindow.h.
References findPipe().