EqualizerInternal: eqNbody Namespace Reference
eqNbody Namespace Reference
Classes
class Channel
class Client
class Config
class Controller
class FrameData
class InitData
class Node
class Pipe
class ParticleRenderer
class SharedData
class SharedDataProxy
class Window
Functions
void _checkGLErrors (char const *s)
float evalHermite (float pA, float pB, float vA, float vB, float u)
EvalHermite(float pA, float pB, float vA, float vB, float u)
unsigned char * createGaussianMap (int N)
Enumerations
enum ConfigEventType { DATA_CHANGED = eq::Event::USER, PROXY_CHANGED }
enum BodyArray { BODYSYSTEM_POSITION, BODYSYSTEM_VELOCITY }
enum NBodyConfig { NBODY_CONFIG_RANDOM, NBODY_CONFIG_SHELL, NBODY_CONFIG_EXPAND, NBODY_NUM_CONFIGS }
enum DisplayMode { PARTICLE_POINTS, PARTICLE_SPRITES, PARTICLE_SPRITES_COLOR, PARTICLE_NUM_MODES }
Variables
const char vertexShader []
const char pixelShader []
Function Documentation
void eqNbody::_checkGLErrors (char const * s)
Definition at line 47 of file render_particles.cpp.
Referenced by eqNbody::ParticleRenderer::draw().
unsigned char* eqNbody::createGaussianMap (int N)
Definition at line 265 of file render_particles.cpp.
References evalHermite().
Referenced by eqNbody::ParticleRenderer::_createTexture().
float eqNbody::evalHermite (float pA, float pB, float vA, float vB, float u) inline
EvalHermite(float pA, float pB, float vA, float vB, float u)
Evaluates Hermite basis functions for the specified coefficients.
Definition at line 255 of file render_particles.cpp.
Referenced by createGaussianMap().
Enumeration Type Documentation
enum eqNbody::BodyArray
Enumerator
BODYSYSTEM_POSITION
BODYSYSTEM_VELOCITY
Definition at line 42 of file controller.h.
enum eqNbody::ConfigEventType
Enumerator
DATA_CHANGED
PROXY_CHANGED
Definition at line 38 of file eqNBody/configEvent.h.
enum eqNbody::DisplayMode
Enumerator
PARTICLE_POINTS
PARTICLE_SPRITES
PARTICLE_SPRITES_COLOR
PARTICLE_NUM_MODES
Definition at line 42 of file render_particles.h.
enum eqNbody::NBodyConfig
Enumerator
NBODY_CONFIG_RANDOM
NBODY_CONFIG_SHELL
NBODY_CONFIG_EXPAND
NBODY_NUM_CONFIGS
Definition at line 38 of file eqNBody/frameData.h.
Variable Documentation
const char eqNbody::pixelShader[]
Initial value:
=
    {
    "uniform sampler2D splatTexture;                                        \n"
    "void main()                                                            \n"
    "{                                                                      \n"
    "    vec4 color = (0.6 + 0.4 * gl_Color) * texture2D(splatTexture, gl_TexCoord[0].st); \n"
    "    gl_FragColor =                                                     \n"
    "         color * mix(vec4(0.1, 0.0, 0.0, color.w), vec4(1.0, 0.7, 0.3, color.w), color.w);\n"
    "}                                                                      \n"
    }
Definition at line 206 of file render_particles.cpp.
Referenced by eqNbody::ParticleRenderer::init().
const char eqNbody::vertexShader[]
Initial value:
=
{
    "void main()                                                            \n"
    "{                                                                      \n"
    "    float pointSize = 500.0 * gl_Point.size;                           \n"
    "    vec4 vert = gl_Vertex;                                             \n"
    "    vert.w = 1.0;                                                      \n"
    "    vec3 pos_eye = vec3 (gl_ModelViewMatrix * vert);                   \n"
    "    gl_PointSize = max(1.0, pointSize / (1.0 - pos_eye.z));            \n"
    "    gl_TexCoord[0] = gl_MultiTexCoord0;                                \n"
    "    gl_Position = ftransform();                                        \n"
    "    gl_FrontColor = gl_Color;                                          \n"
    "}                                                                      \n"
    }
Definition at line 191 of file render_particles.cpp.
Referenced by eqNbody::ParticleRenderer::init(), and eVolve::GLSLShaders::loadShaders().