EqualizerInternal: mesh Namespace Reference
mesh Namespace Reference
Classes
struct MeshException
struct NullOStream
struct ArrayWrapper
class VertexBufferBase
class VertexBufferData
Holds the final kd-tree data, sorted and reindexed.
class VertexBufferLeaf
class VertexBufferNode
class VertexBufferRoot
class VertexBufferState
class VertexBufferStateSimple
class VertexData
Functions
const Index LEAF_SIZE (21845)
const unsigned short FILE_VERSION (0x0118)
std::ostream & operator<< (std::ostream &os, const Axis axis)
std::ostream & operator<< (std::ostream &os, const RenderMode mode)
void memRead (char *destination, char **source, size_t length)
size_t getArchitectureBits ()
bool isArchitectureLittleEndian ()
std::string getArchitectureFilename (const std::string &filename)
Typedefs
typedef vmml::vector< 3, float > Vertex
typedef vmml::vector< 3, uint8_t > Color
typedef vmml::vector< 3, float > Normal
typedef vmml::matrix< 4, 4, float > Matrix4f
typedef vmml::vector< 4, float > Vector4f
typedef size_t Index
typedef GLushort ShortIndex
typedef vmml::vector< 3, Index > Triangle
typedef ArrayWrapper< Vertex, 2 > BoundingBox
typedef vmml::vector< 4, float > BoundingSphere
typedef ArrayWrapper< float, 2 > Range
typedef vmml::frustum_culler
< float > FrustumCuller
Enumerations
enum Axis { AXIS_X, AXIS_Y, AXIS_Z }
enum BufferObject { VERTEX_OBJECT, NORMAL_OBJECT, COLOR_OBJECT, INDEX_OBJECT }
enum RenderMode { RENDER_MODE_IMMEDIATE = 0, RENDER_MODE_DISPLAY_LIST, RENDER_MODE_BUFFER_OBJECT, RENDER_MODE_ALL }
enum NodeType { ROOT_TYPE = 0x07, NODE_TYPE = 0xde, LEAF_TYPE = 0xef }
Function Documentation
const unsigned short mesh::FILE_VERSION (0x0118)
Referenced by mesh::VertexBufferRoot::fromMemory(), and mesh::VertexBufferRoot::toStream().
size_t mesh::getArchitectureBits ()
Definition at line 237 of file vertexBufferRoot.cpp.
Referenced by getArchitectureFilename().
std::string mesh::getArchitectureFilename (const std::string & filename)
Definition at line 253 of file vertexBufferRoot.cpp.
References getArchitectureBits(), and isArchitectureLittleEndian().
Referenced by mesh::VertexBufferRoot::readFromFile(), and mesh::VertexBufferRoot::writeToFile().
bool mesh::isArchitectureLittleEndian ()
Definition at line 244 of file vertexBufferRoot.cpp.
Referenced by getArchitectureFilename().
const Index mesh::LEAF_SIZE (21845)
void mesh::memRead (char * destination, char ** source, size_t length) inline
Definition at line 186 of file typedefs.h.
Referenced by mesh::VertexBufferLeaf::fromMemory(), mesh::VertexBufferNode::fromMemory(), mesh::VertexBufferRoot::fromMemory(), and mesh::VertexBufferBase::fromMemory().
std::ostream& mesh::operator<< (std::ostream & os, const Axis axis) inline
Definition at line 144 of file typedefs.h.
References AXIS_X, AXIS_Y, and AXIS_Z.
std::ostream& mesh::operator<< (std::ostream & os, const RenderMode mode) inline
Definition at line 168 of file typedefs.h.
References RENDER_MODE_BUFFER_OBJECT, RENDER_MODE_DISPLAY_LIST, and RENDER_MODE_IMMEDIATE.
Typedef Documentation
typedef ArrayWrapper< Vertex, 2 > mesh::BoundingBox
Definition at line 125 of file typedefs.h.
typedef vmml::vector< 4, float > mesh::BoundingSphere
Definition at line 126 of file typedefs.h.
typedef vmml::vector< 3, uint8_t > mesh::Color
Definition at line 72 of file typedefs.h.
typedef vmml::frustum_culler< float > mesh::FrustumCuller
Definition at line 46 of file vertexBufferRoot.cpp.
typedef size_t mesh::Index
Definition at line 76 of file typedefs.h.
typedef vmml::matrix< 4, 4, float > mesh::Matrix4f
Definition at line 74 of file typedefs.h.
typedef vmml::vector< 3, float > mesh::Normal
Definition at line 73 of file typedefs.h.
typedef ArrayWrapper< float, 2 > mesh::Range
Definition at line 127 of file typedefs.h.
typedef GLushort mesh::ShortIndex
Definition at line 77 of file typedefs.h.
typedef vmml::vector< 3, Index > mesh::Triangle
Definition at line 124 of file typedefs.h.
typedef vmml::vector< 4, float > mesh::Vector4f
Definition at line 75 of file typedefs.h.
typedef vmml::vector< 3, float > mesh::Vertex
Definition at line 71 of file typedefs.h.
Enumeration Type Documentation
enum mesh::Axis
Enumerator
AXIS_X
AXIS_Y
AXIS_Z
Definition at line 138 of file typedefs.h.
enum mesh::BufferObject
Enumerator
VERTEX_OBJECT
NORMAL_OBJECT
COLOR_OBJECT
INDEX_OBJECT
Definition at line 152 of file typedefs.h.
enum mesh::NodeType
Enumerator
ROOT_TYPE
NODE_TYPE
LEAF_TYPE
Definition at line 177 of file typedefs.h.
enum mesh::RenderMode
Enumerator
RENDER_MODE_IMMEDIATE
RENDER_MODE_DISPLAY_LIST
RENDER_MODE_BUFFER_OBJECT
RENDER_MODE_ALL
Definition at line 161 of file typedefs.h.