EqualizerInternal: nbody.h File Reference
nbody.h File Reference
#include <cuda.h>
Functions
void cudaInit (int argc, char **argv)
void setDeviceSoftening (float softening)
void allocateHostArrays (float **pos, float **vel, float **col, int nBytes)
void deleteHostArrays (float *pos, float *vel, float *col)
void allocateNBodyArrays (float *vel[2], int numBytes)
void deleteNBodyArrays (float *vel[2])
void integrateNbodySystem (float *newPos, float *newVel, float *oldPos, float *oldVel, unsigned int pboOldPos, unsigned int pboNewPos, float deltaTime, float damping, unsigned int numBodies, int offset, int length, int p, int q, int bUsePBO)
void copyArrayFromDevice (float *host, const float *device, unsigned int pbo, int numBytes)
void copyArrayToDevice (float *device, const float *host, int numBytes)
void registerGLBufferObject (unsigned int pbo)
void unregisterGLBufferObject (unsigned int pbo)
void threadSync ()
Function Documentation
void allocateHostArrays (float ** pos, float ** vel, float ** col, int nBytes)
Referenced by eqNbody::FrameData::initHostData().
void allocateNBodyArrays (float * vel[2], int numBytes)
Referenced by eqNbody::Controller::init().
void copyArrayFromDevice (float * host, const float * device, unsigned int pbo, int numBytes)
Referenced by eqNbody::Controller::getArray().
void copyArrayToDevice (float * device, const float * host, int numBytes)
Referenced by eqNbody::Controller::setArray().
void cudaInit (int argc, char ** argv)
void deleteHostArrays (float * pos, float * vel, float * col)
Referenced by eqNbody::FrameData::exit().
void deleteNBodyArrays (float * vel[2])
Referenced by eqNbody::Controller::exit().
void integrateNbodySystem (float * newPos, float * newVel, float * oldPos, float * oldVel, unsigned int pboOldPos, unsigned int pboNewPos, float deltaTime, float damping, unsigned int numBodies, int offset, int length, int p, int q, int bUsePBO)
Referenced by eqNbody::Controller::compute().
void registerGLBufferObject (unsigned int pbo)
Referenced by eqNbody::Controller::init(), and eqNbody::Controller::setArray().
void setDeviceSoftening (float softening)
Referenced by eqNbody::Controller::setSoftening().
void threadSync ()
void unregisterGLBufferObject (unsigned int pbo)
Referenced by eqNbody::Controller::exit(), and eqNbody::Controller::setArray().