Equalizer: eVolve::Window Class Reference
eVolve::Window Class Reference
Public Member Functions
Window (eq::Pipe *parent)
Construct a new window.
GLuint getDisplayList (const void *key)
GLuint newDisplayList (const void *key)
const eq::util::Texture * getLogoTexture () const
Public Member Functions inherited from eq::Window
co::CommandQueue * getPipeThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
uint32_t getCurrentFrame () const
const Node * getNode () const
Node * getNode ()
const Config * getConfig () const
Config * getConfig ()
ClientPtr getClient ()
ServerPtr getServer ()
bool isRunning () const
bool isStopped () const
bool getRenderContext (const int32_t x, const int32_t y, RenderContext &context) const
Get the last rendering context at the x, y position.
void setSharedContextWindow (Window *sharedContextWindow)
Set the window with which this window shares the OpenGL context.
const Window * getSharedContextWindow () const
Window * getSharedContextWindow ()
ObjectManager * getObjectManager ()
const ObjectManager * getObjectManager () const
const Font * getSmallFont ()
const Font * getMediumFont ()
const GLEWContext * glewGetContext () const
Get the GLEW context for this window.
const GLEWContext * getTransferGlewContext ()
uint32_t getColorFormat () const
void setSystemWindow (SystemWindow *window)
Set the OS-specific window.
const SystemWindow * getSystemWindow () const
SystemWindow * getSystemWindow ()
const SystemPipe * getSystemPipe () const
SystemPipe * getSystemPipe ()
const eq::SystemWindow * getTransferSystemWindow ()
void deleteTransferSystemWindow ()
virtual void flush () const
Flush outstanding rendering requests.
virtual void finish () const
Finish outstanding rendering requests.
virtual void drawFPS ()
Render the current framerate as on overlay.
float getFPS () const
virtual void makeCurrent (const bool cache=true) const
Make the window's drawable and context current.
void makeCurrentTransfer (const bool cache=true)
virtual void bindFrameBuffer () const
virtual void notifyViewportChanged ()
virtual bool processEvent (const Event &event)
Process a received event.
Public Member Functions inherited from eq::fabric::Window< Pipe, Window, Channel >
EQFABRIC_INL WindowPath getPath () const
void init ()
const Pipe * getPipe () const
Pipe * getPipe ()
const Channels & getChannels () const
const DrawableConfig & getDrawableConfig () const
const PixelViewport & getPixelViewport () const
const Viewport & getViewport () const
virtual EQFABRIC_INL void setPixelViewport (const PixelViewport &pvp)
Set the window's pixel viewport wrt its parent pipe.
EQFABRIC_INL void setViewport (const Viewport &vp)
Set the window's viewport wrt its parent pipe.
bool hasFixedViewport () const
EQFABRIC_INL VisitorResult accept (Visitor &visitor)
Perform a depth-first traversal of this window.
EQFABRIC_INL VisitorResult accept (Visitor &visitor) const
Const-version of accept().
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
void create (Channel **channel)
void release (Channel *channel)
virtual void output (std::ostream &) const
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
void setIAttribute (const IAttribute attr, const int32_t value)
Set a window attribute.
int32_t getIAttribute (const IAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual bool isDirty () const
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
void setError (const int32_t error)
Set an error code why the last operation failed.
eq::fabric::Error getError () const
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Public Member Functions inherited from co::Serializable
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
Public Member Functions inherited from co::Object
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API ObjectOCommand send (NodePtr node, const uint32_t cmd, const uint32_t instanceID=EQ_INSTANCE_ALL)
Send a command with optional data to object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (MasterCMCommand &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (ICommand &command)
Dispatch a command from the receiver thread to the registered queue.
Protected Member Functions
virtual ~Window ()
Destruct the window.
virtual bool configInit (const eq::uint128_t &initID)
Initialize this window.
virtual bool configInitGL (const eq::uint128_t &initID)
Initialize the OpenGL state for this window.
virtual void swapBuffers ()
Swap the front and back buffer of the window.
Protected Member Functions inherited from eq::Window
virtual void attach (const UUID &id, const uint32_t instanceID)
void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
void releaseFrameLocal (const uint32_t frameNumber)
Signal the release of the local synchronization to the parent.
virtual bool configInitSystemWindow (const uint128_t &initID)
Initialize the OS-specific window.
virtual bool configExit ()
Exit this window.
virtual bool configExitSystemWindow ()
De-initialize the OS-specific window.
virtual bool configExitGL ()
De-initialize the OpenGL state for this window.
virtual void frameStart (const uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
virtual void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
Protected Member Functions inherited from eq::fabric::Window< Pipe, Window, Channel >
Window (Pipe *parent)
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
Worker for pack() and getInstanceData().
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
Worker for unpack() and applyInstanceData().
virtual EQFABRIC_INL void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual EQFABRIC_INL void setDirty (const uint64_t bits)
void _setDrawableConfig (const DrawableConfig &drawableConfig)
virtual ChangeType getChangeType () const
Channel * _findChannel (const UUID &id)
virtual uint64_t getRedistributableBits () const
Protected Member Functions inherited from eq::fabric::Object
Object ()
Construct a new Object.
virtual ~Object ()
Destruct the object.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
void setTasks (const uint32_t tasks)
void postRemove (Object *child)
virtual void removeChild (const UUID &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
bool _cmdSync (co::ICommand &command)
Protected Member Functions inherited from co::Serializable
CO_API Serializable ()
Construct a new Serializable.
CO_API Serializable (const Serializable &)
Construct an unmapped, unregistered copy of an serializable.
virtual CO_API ~Serializable ()
Destruct the serializable.
virtual CO_API void unsetDirty (const uint64_t bits)
Remove dirty flags to clear data from distribution.
virtual CO_API void notifyAttached ()
Notify that this object has been registered or mapped.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (ICommand &command)
The default handler for handling commands.
Additional Inherited Members
Public Types inherited from eq::Window
typedef eq::ObjectManager ObjectManager
The per-window OpenGL object manager.
typedef BitmapFont Font
Fonts used for overlays.
Public Types inherited from eq::fabric::Window< Pipe, Window, Channel >
typedef std::vector< Channel * > Channels
A vector of pointers to channels.
typedef ElementVisitor< Window,
LeafVisitor< Channel > > Visitor
The Window visitor type.
enum IAttribute
Window attributes.
Public Types inherited from eq::fabric::Object
Detailed Description
Definition at line 36 of file share/Equalizer/examples/eVolve/window.h.
Constructor & Destructor Documentation
eVolve::Window::Window (eq::Pipe * parent) inline
Construct a new window.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 39 of file share/Equalizer/examples/eVolve/window.h.
virtual eVolve::Window::~Window () inline protected virtual
Destruct the window.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 50 of file share/Equalizer/examples/eVolve/window.h.
Member Function Documentation
bool eVolve::Window::configInit (const eq::uint128_t & initID) protected virtual
Initialize this window.
Parameters:
initID the init identifier.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 37 of file eVolve/window.cpp.
References eq::fabric::Window< Pipe, Window, Channel >::IATTR_PLANES_ALPHA, and eq::fabric::Window< Pipe, Window, Channel >::setIAttribute().
bool eVolve::Window::configInitGL (const eq::uint128_t & initID) protected virtual
Initialize the OpenGL state for this window.
Parameters:
initID the init identifier.
Returns:
true if the initialization was successful, false if not.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 45 of file eVolve/window.cpp.
References eq::fabric::Window< Pipe, Window, Channel >::getPipe(), eq::Window::glewGetContext(), eq::fabric::Object::setError(), and swapBuffers().
void eVolve::Window::swapBuffers () protected virtual
Swap the front and back buffer of the window.
Version:
1.0
Reimplemented from eq::Window.
Definition at line 135 of file eVolve/window.cpp.
References eq::fabric::Window< Pipe, Window, Channel >::getChannels(), and eq::fabric::Window< Pipe, Window, Channel >::getPipe().
Referenced by configInitGL().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eVolve/window.h
eVolve/window.cpp