Equalizer: osgScaleViewer::InitData Class Reference
osgScaleViewer::InitData Class Reference
The init data holds all data which is needed during initalization.
#include <initData.h>
Public Member Functions
void setFrameDataID (const eq::uint128_t &id)
const eq::uint128_t & getFrameDataID () const
void setModelFileName (const std::string &filename)
Sets the model filename.
std::string getModelFileName () const
Gets the model filename.
void setImageFileName (const std::string &filename)
Sets the image filename.
std::string getImageFileName () const
Gets the image filename.
const std::string getTrackerPort () const
Gets the tracker port.
bool parseCommandLine (char **argv, int argc)
Parses the command line arguments and puts the things it can parse into the init data.
Public Member Functions inherited from co::Object
CO_API Object ()
Construct a new distributed object.
virtual CO_API ~Object ()
Destruct the distributed object.
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual ChangeType getChangeType () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
virtual bool isDirty () const
Return if this object needs a commit.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
virtual CO_API uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
virtual void pack (DataOStream &os)
Serialize the modifications since the last call to commit().
virtual void unpack (DataIStream &is)
Deserialize a change.
CO_API ObjectOCommand send (NodePtr node, const uint32_t cmd, const uint32_t instanceID=EQ_INSTANCE_ALL)
Send a command with optional data to object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyAttached ()
Notify that this object has been registered or mapped.
virtual CO_API void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (MasterCMCommand &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void attach (const UUID &id, const uint32_t instanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (ICommand &command)
Dispatch a command from the receiver thread to the registered queue.
Protected Member Functions
virtual void getInstanceData (co::DataOStream &stream)
Reimplemented.
virtual void applyInstanceData (co::DataIStream &stream)
Reimplemented.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (ICommand &command)
The default handler for handling commands.
Additional Inherited Members
Public Types inherited from co::Object
enum ChangeType {
NONE, STATIC, INSTANCE, DELTA,
UNBUFFERED
}
Object change handling characteristics, see Programming Guide.
Public Types inherited from co::Dispatcher
typedef CommandFunc< Dispatcher > Func
Detailed Description
The init data holds all data which is needed during initalization.
It is sent by the server to all render clients.
It holds the frame data ID, so all clients can sync the frame data object. It also holds the model or image filename to load.
Definition at line 47 of file osgScaleViewer/initData.h.
Member Function Documentation
std::string osgScaleViewer::InitData::getImageFileName () const
Gets the image filename.
Returns:
the image filename.
Definition at line 76 of file osgScaleViewer/initData.cpp.
Referenced by osgScaleViewer::Node::configInit().
std::string osgScaleViewer::InitData::getModelFileName () const
Gets the model filename.
Returns:
the model filename.
Definition at line 66 of file osgScaleViewer/initData.cpp.
Referenced by osgScaleViewer::Node::configInit().
const std::string osgScaleViewer::InitData::getTrackerPort () const
Gets the tracker port.
Returns:
the tracker port.
Definition at line 81 of file osgScaleViewer/initData.cpp.
Referenced by osgScaleViewer::Config::init().
bool osgScaleViewer::InitData::parseCommandLine (char ** argv, int argc)
Parses the command line arguments and puts the things it can parse into the init data.
Returns:
true if the command line was successfully parsed.
Definition at line 86 of file osgScaleViewer/initData.cpp.
References setImageFileName(), and setModelFileName().
void osgScaleViewer::InitData::setImageFileName (const std::string & filename)
Sets the image filename.
Parameters:
filename the image filename.
Definition at line 71 of file osgScaleViewer/initData.cpp.
Referenced by parseCommandLine().
void osgScaleViewer::InitData::setModelFileName (const std::string & filename)
Sets the model filename.
Parameters:
filename the model filename.
Definition at line 61 of file osgScaleViewer/initData.cpp.
Referenced by parseCommandLine().
The documentation for this class was generated from the following files:
osgScaleViewer/initData.h
osgScaleViewer/initData.cpp