Equalizer: eq::fabric::Object Class Reference
eq::fabric::Object Class Reference
Internal base class for all distributed, inheritable Equalizer objects.
#include <object.h>
Inherits co::Serializable.
Inherited by eq::fabric::Canvas< Config, Canvas, Segment, Layout >, eq::fabric::Channel< Window, Channel >, eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >, eq::fabric::Canvas< CFG, C, S, L >, eq::fabric::Channel< W, C >, eq::fabric::Config< S, C, O, L, CV, N, V >, eq::fabric::Layout< C, L, V >, eq::fabric::Node< C, N, P, V >, eq::fabric::Observer< C, O >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Segment< C, S, CH >, eq::fabric::View< L, V, O >, eq::fabric::Window< P, W, C >, eq::fabric::Layout< Config, Layout, View >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eq::fabric::Observer< Config, Observer >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::View< Layout, View, Observer >, and eq::fabric::Window< Pipe, Window, Channel >.
Classes
struct BackupData
Public Member Functions
virtual bool isDirty () const
virtual uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
virtual void backup ()
virtual void restore ()
Data Access.
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
Error Information.
void setError (const int32_t error)
Set an error code why the last operation failed.
eq::fabric::Error getError () const
Data Access
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Public Member Functions inherited from co::Serializable
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
Public Member Functions inherited from co::Object
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API ObjectOCommand send (NodePtr node, const uint32_t cmd, const uint32_t instanceID=EQ_INSTANCE_ALL)
Send a command with optional data to object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (MasterCMCommand &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void attach (const UUID &id, const uint32_t instanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (ICommand &command)
Dispatch a command from the receiver thread to the registered queue.
Public Types
enum DirtyBits {
DIRTY_NAME = Serializable::DIRTY_CUSTOM << 0, DIRTY_USERDATA = Serializable::DIRTY_CUSTOM << 1, DIRTY_ERROR = Serializable::DIRTY_CUSTOM << 2, DIRTY_TASKS = Serializable::DIRTY_CUSTOM << 3,
DIRTY_REMOVED = Serializable::DIRTY_CUSTOM << 4, DIRTY_SERIAL = Serializable::DIRTY_CUSTOM << 5, DIRTY_CUSTOM = Serializable::DIRTY_CUSTOM << 6, DIRTY_OBJECT_BITS = DIRTY_NAME | DIRTY_USERDATA | DIRTY_ERROR
}
The changed parts of the object since the last pack().
Protected Member Functions
Object ()
Construct a new Object.
virtual ~Object ()
Destruct the object.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
void setTasks (const uint32_t tasks)
virtual void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual void serialize (co::DataOStream &os, const uint64_t dirtyBits)
Worker for pack() and getInstanceData().
virtual void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
Worker for unpack() and applyInstanceData().
virtual uint64_t getRedistributableBits () const
void postRemove (Object *child)
virtual void removeChild (const UUID &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
bool _cmdSync (co::ICommand &command)
Protected Member Functions inherited from co::Serializable
CO_API Serializable ()
Construct a new Serializable.
CO_API Serializable (const Serializable &)
Construct an unmapped, unregistered copy of an serializable.
virtual CO_API ~Serializable ()
Destruct the serializable.
virtual ChangeType getChangeType () const
virtual CO_API void setDirty (const uint64_t bits)
Add dirty flags to mark data for distribution.
virtual CO_API void unsetDirty (const uint64_t bits)
Remove dirty flags to clear data from distribution.
virtual CO_API void notifyAttached ()
Notify that this object has been registered or mapped.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (ICommand &command)
The default handler for handling commands.
Additional Inherited Members
Protected Types inherited from co::Serializable
Detailed Description
Internal base class for all distributed, inheritable Equalizer objects.
This class provides common data storage used by all Equalizer resource entities. Do not subclass directly.
Definition at line 39 of file eq/fabric/object.h.
Member Enumeration Documentation
enum eq::fabric::Object::DirtyBits
The changed parts of the object since the last pack().
Subclasses should define their own bits, starting at DIRTY_CUSTOM.
Reimplemented from co::Serializable.
Reimplemented in eq::fabric::Channel< W, C >, eq::fabric::Channel< Window, Channel >, eq::fabric::View< L, V, O >, eq::fabric::View< Layout, View, Observer >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Segment< C, S, CH >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eq::fabric::Observer< C, O >, eq::fabric::Observer< Config, Observer >, eq::fabric::Layout< C, L, V >, and eq::fabric::Layout< Config, Layout, View >.
Definition at line 119 of file eq/fabric/object.h.
Constructor & Destructor Documentation
eq::fabric::Object::Object () protected
Construct a new Object.
Reimplemented from co::Object.
virtual eq::fabric::Object::~Object () protected virtual
Destruct the object.
Reimplemented from co::Object.
Member Function Documentation
virtual uint128_t eq::fabric::Object::commit (const uint32_t incarnation = CO_COMMIT_NEXT) virtual
Commit a new version of this object.
Objects using the change type STATIC can not be committed.
Master instances will increment new versions continously, starting at VERSION_FIRST. If the object has not changed, no new version will be generated, that is, the current version is returned. The high value of the returned version will always be 0.
Slave objects can be commited, but have certain caveats for serialization. Please refer to the Programming Guide for more details. Slave object commits will return a random version on a successful commit, or VERSION_NONE if the object has not changed since the last commit. The high value of a successful commit will never be 0.
The incarnation count is meaningful for buffered master objects. The commit implementation will keep all instance data committed with an incarnation count newer than current_incarnation - getAutoObsolete(). By default, each call to commit creates a new incarnation, retaining the data from last getAutoObsolete() commit calls. When the application wishes to auto obsolete by another metric than commit calls, it has to consistently provide an incarnation counter. Buffers with a higher incarnation count than the current are discarded. A typical use case is to tie the auto obsoletion to an application-specific frame loop. Decreasing the incarnation counter will lead to undefined results.
Parameters:
incarnation the commit incarnation for auto obsoletion.
Returns:
the new head version.
Reimplemented from co::Serializable.
Reimplemented in eq::fabric::Config< S, C, O, L, CV, N, V >, eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Segment< C, S, CH >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Node< C, N, P, V >, and eq::fabric::Node< Config, Node, Pipe, NodeVisitor >.
virtual void eq::fabric::Object::deserialize (co::DataIStream & , const uint64_t) protected virtual
Worker for unpack() and applyInstanceData().
This function is called with the dirty bits send by the master instance. The dirty bits are received beforehand, and do not need to be deserialized by the overriding method.
See also:
serialize()
Version:
1.0
Reimplemented from co::Serializable.
Reimplemented in eq::fabric::Channel< W, C >, eq::fabric::Channel< Window, Channel >, eq::fabric::View< L, V, O >, eq::fabric::View< Layout, View, Observer >, eq::fabric::Config< S, C, O, L, CV, N, V >, eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Segment< C, S, CH >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::Canvas< CFG, C, S, L >, eq::fabric::Canvas< Config, Canvas, Segment, Layout >, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eq::fabric::Observer< C, O >, eq::fabric::Observer< Config, Observer >, eq::fabric::Layout< C, L, V >, eq::fabric::Layout< Config, Layout, View >, and eq::View.
eq::fabric::Error eq::fabric::Object::getError () const inline
Returns:
the error from the last failed operation.
Version:
1.0
Definition at line 82 of file eq/fabric/object.h.
Referenced by eVolve::Pipe::configInit(), eVolve::EVolve::run(), osgScaleViewer::OSGScaleViewer::run(), and eqPly::EqPly::run().
const std::string& eq::fabric::Object::getName () const
Returns:
the name of the object.
Version:
1.0
uint32_t eq::fabric::Object::getTasks () const inline
Return the set of tasks this channel might execute in the worst case.
It is not guaranteed that all the tasks will be actually executed during rendering.
Returns:
the tasks.
Warning:
Experimental - may not be supported in the future
Definition at line 96 of file eq/fabric/object.h.
co::Object* eq::fabric::Object::getUserData () inline
Returns:
the user-specific data.
Version:
1.0
Definition at line 62 of file eq/fabric/object.h.
const co::Object* eq::fabric::Object::getUserData () const inline
Returns:
the user-specific data.
Version:
1.0
Definition at line 65 of file eq/fabric/object.h.
virtual uint32_t eq::fabric::Object::getUserDataLatency () const inline protected virtual
Returns:
the latency to be used for keeping user data versions.
Reimplemented in eq::fabric::View< L, V, O >, and eq::fabric::View< Layout, View, Observer >.
Definition at line 146 of file eq/fabric/object.h.
virtual bool eq::fabric::Object::hasMasterUserData () inline protected virtual
Returns:
true if this instance shall hold the master instance of the user data object, false otherwise.
Reimplemented in eq::fabric::View< L, V, O >, and eq::fabric::View< Layout, View, Observer >.
Definition at line 143 of file eq/fabric/object.h.
virtual bool eq::fabric::Object::isDirty () const virtual
Returns:
true if the object has data to commit.
Version:
1.0
Reimplemented from co::Serializable.
virtual void eq::fabric::Object::notifyDetach () protected virtual
Notify that this object will be deregistered or unmapped.
The method is called from the thread initiating the deregistration or unmapping, before the operation is executed.
See also:
isMaster()
Reimplemented from co::Object.
Reimplemented in eq::Config, eq::fabric::Config< S, C, O, L, CV, N, V >, eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Canvas< CFG, C, S, L >, eq::fabric::Canvas< Config, Canvas, Segment, Layout >, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eq::fabric::Layout< C, L, V >, and eq::fabric::Layout< Config, Layout, View >.
virtual void eq::fabric::Object::serialize (co::DataOStream & , const uint64_t) protected virtual
Worker for pack() and getInstanceData().
Override this and deserialize() if you want to distribute subclassed data.
This method is called with DIRTY_ALL from getInstanceData() and with the actual dirty bits from pack(), which also resets the dirty state afterwards. The dirty bits are transmitted beforehand, and do not need to be transmitted by the overriding method.
Version:
1.0
Reimplemented from co::Serializable.
Reimplemented in eq::fabric::Channel< W, C >, eq::fabric::Channel< Window, Channel >, eq::fabric::View< L, V, O >, eq::fabric::View< Layout, View, Observer >, eq::fabric::Config< S, C, O, L, CV, N, V >, eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Segment< C, S, CH >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::Canvas< CFG, C, S, L >, eq::fabric::Canvas< Config, Canvas, Segment, Layout >, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eq::fabric::Observer< C, O >, eq::fabric::Observer< Config, Observer >, eq::fabric::Layout< C, L, V >, and eq::fabric::Layout< Config, Layout, View >.
void eq::fabric::Object::setError (const int32_t error)
Set an error code why the last operation failed.
The error will be transmitted to the originator of the request, for example to Config::init when set from within configInit().
Parameters:
error the error message.
Version:
1.0
Referenced by eVolve::Node::configInit(), eVolve::Pipe::configInit(), eqPly::Node::configInit(), and eVolve::Window::configInitGL().
void eq::fabric::Object::setName (const std::string & name)
Set the name of the object.
Version:
1.0
void eq::fabric::Object::setUserData (co::Object * userData)
Set user-specific data.
Registration, mapping, commit and sync of the user data object are automatically executed when committing and syncing this object. Not all instances of the object have to set a user data object. All instances have to set the same type of object.
Version:
1.0
Referenced by eqPly::View::View(), and eqPly::View::~View().
The documentation for this class was generated from the following file:
eq/fabric/object.h