Equalizer: eq::Config Class Reference
eq::Config Class Reference
A configuration is a visualization session driven by an application.
#include <config.h>
Public Member Functions
Config (ServerPtr parent)
Construct a new config.
virtual ~Config ()
Destruct a config.
void setupMessagePump (Pipe *pipe)
void setupServerConnections (const std::string &connectionData)
Data Access
ClientPtr getClient ()
ConstClientPtr getClient () const
co::NodePtr getApplicationNode ()
co::CommandQueue * getMainThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
uint32_t getCurrentFrame () const
uint32_t getFinishedFrame () const
void getStatistics (std::vector< FrameStatistics > &stats)
bool isRunning () const
void stopRunning ()
Stop the config.
int64_t getTime () const
Get the current time in milliseconds.
MessagePump * getMessagePump ()
const Channel * findChannel (const std::string &name) const
Operations
virtual bool init (const uint128_t &initID)
Initialize this configuration.
virtual bool exit ()
Exit this configuration.
bool update ()
Update the configuration.
virtual void setLatency (const uint32_t latency)
Object registry.
virtual bool registerObject (co::Object *object)
Register a distributed object.
virtual void deregisterObject (co::Object *object)
Deregister a distributed object.
virtual bool mapObject (co::Object *object, const UUID &id, const uint128_t &version=co::VERSION_OLDEST)
Map a distributed object.
virtual uint32_t mapObjectNB (co::Object *object, const UUID &id, const uint128_t &version=co::VERSION_OLDEST)
Start mapping a distributed object.
virtual uint32_t mapObjectNB (co::Object *object, const UUID &id, const uint128_t &version, co::NodePtr master)
Start mapping a distributed object from a known master.
virtual bool mapObjectSync (const uint32_t requestID)
Finalize the mapping of a distributed object.
virtual void unmapObject (co::Object *object)
Unmap a mapped object.
void releaseObject (co::Object *object)
Convenience method to deregister or unmap an object.
Frame Control
virtual uint32_t startFrame (const uint128_t &frameID)
Request a new frame of rendering.
virtual uint32_t finishFrame ()
Finish the rendering of a frame.
virtual uint32_t finishAllFrames ()
Finish rendering all pending frames.
void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the config for a frame.
void stopFrames ()
Asynchronously signal all channels to interrupt their rendering.
Event handling
void sendEvent (ConfigEvent &event)
Send an event to the application node.
const ConfigEvent * nextEvent ()
Get the next event.
const ConfigEvent * tryNextEvent ()
Try to get the next event.
virtual bool handleEvent (const ConfigEvent *event)
Handle one config event.
EventOCommand sendEvent (const uint32_t type)
Send an event to the application node.
EventICommand getNextEvent (const uint32_t timeout=LB_TIMEOUT_INDEFINITE) const
Get the next event.
virtual bool handleEvent (EventICommand command)
Handle one config event.
bool checkEvent () const
virtual void handleEvents ()
Handle all config events.
Public Member Functions inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
virtual void output (std::ostream &) const
void create (Observer **observer)
void create (Layout **layout)
void create (Canvas **canvas)
void create (Node **node)
void release (Observer *observer)
void release (Layout *layout)
void release (Canvas *canvas)
void release (Node *node)
EQFABRIC_INL lunchbox::RefPtr
< Server > getServer ()
EQFABRIC_INL lunchbox::RefPtr
< const Server > getServer () const
const Observers & getObservers () const
const Layouts & getLayouts () const
const Canvases & getCanvases () const
EQFABRIC_INL uint32_t getTimeout () const
const Nodes & getNodes () const
EQFABRIC_INL Node * findAppNode ()
EQFABRIC_INL const Node * findAppNode () const
EQFABRIC_INL VisitorResult accept (ConfigVisitor &visitor)
Perform a depth-first traversal of this config.
EQFABRIC_INL VisitorResult accept (ConfigVisitor &visitor) const
Const-version of accept().
EQFABRIC_INL T * find (const uint128_t &id)
EQFABRIC_INL const T * find (const uint128_t &id) const
EQFABRIC_INL T * find (const std::string &name)
EQFABRIC_INL const T * find (const std::string &name) const
void find (const uint128_t &id, T **result)
void find (const std::string &name, const T **result) const
Observer * getObserver (const ObserverPath &path)
Layout * getLayout (const LayoutPath &path)
Canvas * getCanvas (const CanvasPath &path)
virtual void updateCanvas (Canvas *)
virtual void exitCanvas (Canvas *)
uint32_t getLatency () const
virtual EQFABRIC_INL void restore ()
void setFAttribute (const FAttribute attr, const float value)
void setIAttribute (const IAttribute attr, const int32_t value)
float getFAttribute (const FAttribute attr) const
int32_t getIAttribute (const IAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual bool isDirty () const
virtual void backup ()
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
void setError (const int32_t error)
Set an error code why the last operation failed.
eq::fabric::Error getError () const
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Public Member Functions inherited from co::Serializable
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
Public Member Functions inherited from co::Object
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API ObjectOCommand send (NodePtr node, const uint32_t cmd, const uint32_t instanceID=EQ_INSTANCE_ALL)
Send a command with optional data to object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (MasterCMCommand &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (ICommand &command)
Dispatch a command from the receiver thread to the registered queue.
Public Member Functions inherited from co::ObjectHandler
ObjectHandler ()
Construct a new object handler.
virtual ~ObjectHandler ()
Destroy this object handler.
Public Types
typedef fabric::Config< Server,
Config, Observer, Layout,
Canvas, Node, ConfigVisitor > Super
base class
Public Types inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
typedef std::vector< Observer * > Observers
A vector of observers.
typedef std::vector< Layout * > Layouts
A vector of layouts.
typedef std::vector< Canvas * > Canvases
A vector of canvases.
typedef std::vector< Node * > Nodes
A vector of nodes.
enum FAttribute
Floating-point attributes.
enum IAttribute
Integer attributes.
Public Types inherited from eq::fabric::Object
Protected Member Functions
virtual void attach (const UUID &id, const uint32_t instanceID)
virtual void notifyAttached ()
Notify that this object has been registered or mapped.
virtual void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual void changeLatency (const uint32_t latency)
virtual bool mapViewObjects () const
Protected Member Functions inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
EQFABRIC_INL Config (lunchbox::RefPtr< Server > parent)
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
Worker for pack() and getInstanceData().
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
Worker for unpack() and applyInstanceData().
virtual void _removeChild (const UUID &)
void setAppNodeID (const co::NodeID &nodeID)
const co::NodeID & getAppNodeID () const
virtual bool mapNodeObjects () const
virtual VisitorResult _acceptCompounds (ConfigVisitor &)
virtual VisitorResult _acceptCompounds (ConfigVisitor &) const
Node * _findNode (const uint128_t &id)
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
Protected Member Functions inherited from eq::fabric::Object
Object ()
Construct a new Object.
virtual ~Object ()
Destruct the object.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
void setTasks (const uint32_t tasks)
void postRemove (Object *child)
virtual void removeChild (const UUID &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
bool _cmdSync (co::ICommand &command)
Protected Member Functions inherited from co::Serializable
CO_API Serializable ()
Construct a new Serializable.
CO_API Serializable (const Serializable &)
Construct an unmapped, unregistered copy of an serializable.
virtual CO_API ~Serializable ()
Destruct the serializable.
virtual ChangeType getChangeType () const
virtual CO_API void setDirty (const uint64_t bits)
Add dirty flags to mark data for distribution.
virtual CO_API void unsetDirty (const uint64_t bits)
Remove dirty flags to clear data from distribution.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (ICommand &command)
The default handler for handling commands.
Friends
class Node
Additional Inherited Members
Static Public Member Functions inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
static const std::string & getFAttributeString (const FAttribute attr)
static const std::string & getIAttributeString (const IAttribute attr)
Detailed Description
A configuration is a visualization session driven by an application.
The application Client can choose a configuration from a Server. The Config will be instantiated though the NodeFactory. The Config groups all processes of the application in a single session.
A configuration has a number of nodes, which represent the processes involved in it. While the Server drives all nodes, a Config instance in a given process only has its Node instantiated, that is, any given Config has at most one Node.
The Config in the application process has access to all Canvas, Segment, Layout, View and Observer instances. Only the active Layout of the each Canvas, the Frustum of each View and the Observer parameters are writable. Views can be sub-classed to attach application-specific data.
The render client processes have only access to the current View for each of their channels.
See also:
fabric::Config for public methods
Definition at line 55 of file include/eq/client/config.h.
Constructor & Destructor Documentation
eq::Config::Config (ServerPtr parent)
Construct a new config.
Version:
1.0
Reimplemented in eqPly::Config, osgScaleViewer::Config, eqNbody::Config, eVolve::Config, and eqPixelBench::Config.
virtual eq::Config::~Config () virtual
Destruct a config.
Version:
1.0
Reimplemented from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >.
Reimplemented in eqPly::Config, eqNbody::Config, eVolve::Config, and eqPixelBench::Config.
Member Function Documentation
bool eq::Config::checkEvent () const
Returns:
true if events are pending.
Version:
1.0
virtual void eq::Config::deregisterObject (co::Object * object) virtual
Deregister a distributed object.
This method ensures that the data for buffered object is kept for latency frames to allow mapping on slave nodes.
Parameters:
object the object instance.
Version:
1.0
Implements co::ObjectHandler.
Referenced by osgScaleViewer::Config::exit().
virtual bool eq::Config::exit () virtual
Exit this configuration.
This method is to be called only on the application node on an initialized configuration.
Exiting a configuration calls configExit on all active render entities, releases the entities using the NodeFactory and stops the render clients.
A configuration which was not exited properly may not be re-initialized.
Returns:
true if the exit was successful, false if not.
Version:
1.0
Reimplemented in eqPly::Config, osgScaleViewer::Config, eqNbody::Config, and eVolve::Config.
virtual uint32_t eq::Config::finishAllFrames () virtual
Finish rendering all pending frames.
This method is to be called only on the application node on an initialized configuration.
Returns:
the frame number of the last finished frame.
Version:
1.0
Referenced by eVolve::EVolve::run(), osgScaleViewer::OSGScaleViewer::run(), and eqPly::EqPly::run().
virtual uint32_t eq::Config::finishFrame () virtual
Finish the rendering of a frame.
This method is to be called only on the application node on an initialized configuration.
This method synchronizes the local and global rendering. The global rendering is always synchronized to finish the frame (current - latency). The local rendering is synchronized according to the current thread model (cf. Node::IATTR_THREAD_MODEL)
Returns:
the frame number of the globally finished frame, or 0 if no frame has been finished yet.
Version:
1.0
Referenced by eVolve::EVolve::run(), osgScaleViewer::OSGScaleViewer::run(), and eqPly::EqPly::run().
co::NodePtr eq::Config::getApplicationNode ()
Returns:
the application node.
Warning:
experimental, may not be supported in the future
Referenced by eqPly::Config::getModel(), and eqPly::Config::loadData().
ClientPtr eq::Config::getClient ()
Returns:
the local client node.
Version:
1.0
Referenced by eqPly::Config::getModel().
ConstClientPtr eq::Config::getClient () const
Returns:
the local client node.
Version:
1.0
uint32_t eq::Config::getCurrentFrame () const
Returns:
the frame number of the last frame started.
Version:
1.0
uint32_t eq::Config::getFinishedFrame () const
Returns:
the frame number of the last frame finished.
Version:
1.0
Referenced by eqPly::EqPly::run().
MessagePump* eq::Config::getMessagePump ()
Returns:
the config's message pump, or 0.
Version:
1.0
EventICommand eq::Config::getNextEvent (const uint32_t timeout = LB_TIMEOUT_INDEFINITE) const
Get the next event.
To be called only on the application node.
The returned event command is valid until it gets out of scope. This method does not block if the given timeout is 0.
Parameters:
timeout time in ms to wait for incoming events
Returns:
the event command.
Version:
1.5.1
See also:
Client::processCommand()
Referenced by eqPly::EqPly::run().
int64_t eq::Config::getTime () const
Get the current time in milliseconds.
The clock in all processes of the config is synchronized to the Server clock. The precision of this synchronization is typically about 1 ms. The clock of the last instantiated config is used as the lunchbox::Log clock.
Returns:
the global time in ms.
Version:
1.0
virtual bool eq::Config::handleEvent (const ConfigEvent * event) virtual
Handle one config event.
Parameters:
event the event.
Returns:
true if the event requires a redraw, false if not.
Deprecated:
virtual bool eq::Config::handleEvent (EventICommand command) virtual
Handle one config event.
Parameters:
command the event command.
Returns:
true if the event requires a redraw, false if not.
Version:
1.5.1
Reimplemented in eqPly::Config, osgScaleViewer::Config, eVolve::Config, eqNbody::Config, and eqPixelBench::Config.
virtual void eq::Config::handleEvents () virtual
Handle all config events.
To be called only on the application node.
Called automatically at the end of each frame to handle pending config events. The default implementation calls handleEvent() on all pending events, without blocking.
Version:
1.0
Referenced by eqPly::EqPly::run().
virtual bool eq::Config::init (const uint128_t & initID) virtual
Initialize this configuration.
This method is to be called only on the application node on an uninitialized configuration.
Initializing a configuration starts and connects all render clients, instantiates all active render entities (Node, Pipe, Window, Channel) using the NodeFactory of each process, and calls the configInit task methods on each of these entities, passing the given identifier.
The identifier is typically the identifier of a static Object containing initialization data.
The initialization fails if at least one of the configInit task methods fails. The application can use setErrorMessage on the render client to pass an error string to the application process, which it can query it using getError().
Parameters:
initID an identifier to be passed to all init methods.
Returns:
true if the initialization was successful, false if not.
Version:
1.0
Referenced by eVolve::Config::init(), and eqPly::Config::init().
bool eq::Config::isRunning () const
Returns:
true while the config is initialized and no exit event has happened.
Version:
1.0
Referenced by eVolve::EVolve::run(), osgScaleViewer::OSGScaleViewer::run(), and eqPly::EqPly::run().
virtual bool eq::Config::mapObject (co::Object * object, const UUID & id, const uint128_t & version = co::VERSION_OLDEST) virtual
Map a distributed object.
Provided for symmetry with deregisterObject. Forwards mapping to local client node.
Version:
1.0
Referenced by eqNbody::Pipe::configInit(), eVolve::Pipe::configInit(), eqPly::Pipe::configInit(), osgScaleViewer::Pipe::configInit(), and eVolve::Config::mapData().
virtual uint32_t eq::Config::mapObjectNB (co::Object * object, const UUID & id, const uint128_t & version = co::VERSION_OLDEST) virtual
Start mapping a distributed object.
Version:
1.0
Referenced by eqPly::Config::loadData().
virtual uint32_t eq::Config::mapObjectNB (co::Object * object, const UUID & id, const uint128_t & version, co::NodePtr master) virtual
Start mapping a distributed object from a known master.
Version:
1.0
Implements co::ObjectHandler.
virtual bool eq::Config::mapObjectSync (const uint32_t requestID) virtual
Finalize the mapping of a distributed object.
Version:
1.0
Implements co::ObjectHandler.
Referenced by eqPly::Config::loadData().
const ConfigEvent* eq::Config::nextEvent ()
Get the next event.
To be called only on the application node.
The returned event is valid until the next call to this method. This method may block.
Returns:
the event.
Deprecated:
See also:
Client::processCommand()
virtual void eq::Config::notifyAttached () protected virtual
Notify that this object has been registered or mapped.
The method is called from the thread initiating the registration or mapping, after the operation has been completed successfully.
See also:
isMaster()
Reimplemented from co::Serializable.
virtual void eq::Config::notifyDetach () protected virtual
Notify that this object will be deregistered or unmapped.
The method is called from the thread initiating the deregistration or unmapping, before the operation is executed.
See also:
isMaster()
Reimplemented from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >.
virtual bool eq::Config::registerObject (co::Object * object) virtual
Register a distributed object.
Provided for symmetry with deregisterObject. Forwards registration to local client node.
Version:
1.0
Implements co::ObjectHandler.
Referenced by eVolve::Config::init(), osgScaleViewer::Config::init(), and eqPly::Config::init().
void eq::Config::releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the config for a frame.
Used by the local Node to release the process-local frame synchronization. An application typically does not call this method directly, it is called from Node::releaseFrameLocal(), which in turn is called from the appropriate task method depending on the thread model.
Parameters:
frameNumber the frame to release.
Version:
1.0
void eq::Config::releaseObject (co::Object * object)
Convenience method to deregister or unmap an object.
Version:
1.0
void eq::Config::sendEvent (ConfigEvent & event)
Send an event to the application node.
Parameters:
event the event.
Deprecated:
Referenced by eqPly::Channel::frameViewFinish().
EventOCommand eq::Config::sendEvent (const uint32_t type)
Send an event to the application node.
The returned command can be used to pass additional data to the event. The event will be send after the command is destroyed, aka when it is running out of scope.
Parameters:
type the event type.
Returns:
the event command to pass additional data to
Version:
1.5.1
virtual void eq::Config::setLatency (const uint32_t latency) virtual
See also:
fabric::Config::setLatency()
Reimplemented from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >.
virtual uint32_t eq::Config::startFrame (const uint128_t & frameID) virtual
Request a new frame of rendering.
This method is to be called only on the application node on an initialized configuration. It implicitely calls update().
The server will sync to the new data, and generate all render tasks, which are queued on the render clients for execution.
Each call to startFrame() has to be completed by a finishFrame() or finishAllFrames() before the next call to startFrame().
Parameters:
frameID a per-frame identifier passed to all rendering methods.
Returns:
the frame number of the new frame.
Version:
1.0
Reimplemented in eqPixelBench::Config.
void eq::Config::stopFrames ()
Asynchronously signal all channels to interrupt their rendering.
This method may be called from any thread in the application process. It causes Channel::notifyStopFrame() to be called immediately on all active channels.
Version:
1.0
void eq::Config::stopRunning ()
Stop the config.
Version:
1.0
const ConfigEvent* eq::Config::tryNextEvent ()
Try to get the next event.
To be called only on the application node.
The returned event is valid until the next call to this method. This method does not block.
Returns:
a config event, or 0 if no events are pending.
Deprecated:
virtual void eq::Config::unmapObject (co::Object * object) virtual
Unmap a mapped object.
Provided for symmetry with deregisterObject. Forwards unmapping to local client node.
Version:
1.0
Implements co::ObjectHandler.
Referenced by eqNbody::Pipe::configExit(), eVolve::Pipe::configExit(), eqPly::Pipe::configExit(), osgScaleViewer::Pipe::configExit(), eqPly::Config::loadData(), and eVolve::Config::mapData().
bool eq::Config::update ()
Update the configuration.
This method is to be called only on the application node on an initialized configuration. Dirty objects on the config are committed, i.e., the View, Canvas and Observer, and any changes on the configuration are effected. Changes may be caused by the eq::admin API or by the application, e.g., through a layout change on a Canvas. Any change causes an implicit finish of all outstanding frames.
This function always returns false when a resource failed to initialize or exit. When robustness is not activated, the config is exited by the update upon failure. When robustness is activated, the config keeps running and may be used with reduced functionality.
Returns:
true if the configuration update was successful, false if a resource failed to initialize or exit.
Version:
1.0
The documentation for this class was generated from the following file:
include/eq/client/config.h