set(GLSTATS_MATURITY "EP")
set(GLSTATS_DESCRIPTION "")
set(GLSTATS_GIT_ROOT_URL "git@github.com:tribal-tec/GLStats.git")
set(GLSTATS_PACKAGE_URL "https://launchpad.net/~bbp/+archive/ppa")
set(GLSTATS_CI_URL "git@travis-ci.org:tribal-tec/GLStats")
set(GLSTATS_CI_PNG "git@travis-ci.org:tribal-tec/GLStats.png")
set(GLSTATS_ISSUES_URL "git@github.com:tribal-tec/GLStats/issues")
