set(GLSTATS_MATURITY "EP")
set(GLSTATS_DESCRIPTION "")
set(GLSTATS_GIT_ROOT_URL "https://github.com/Eyescale/GLStats.git")
set(GLSTATS_PACKAGE_URL "")
set(GLSTATS_CI_URL "https://travis-ci.org/Eyescale/GLStats")
set(GLSTATS_CI_PNG "https://travis-ci.org/Eyescale/GLStats.png")
set(GLSTATS_ISSUES_URL "https://github.com/Eyescale/GLStats/issues")
