Equalizer: osgScaleViewer::OSGScaleViewer Class Reference
osgScaleViewer::OSGScaleViewer Class Reference
Public Member Functions
OSGScaleViewer (const InitData &initData)
Create an OSG application.
int run ()
Run the application.
Public Member Functions inherited from eq::Client
Client ()
Construct a new client.
virtual ~Client ()
Destruct the client.
bool connectServer (ServerPtr server)
Open and connect an Equalizer server to the local client.
bool disconnectServer (ServerPtr server)
Disconnect and close the connection to an Equalizer server.
virtual bool initLocal (const int argc, char **argv)
Initialize a local, listening node.
virtual bool exitLocal ()
De-initialize a local, listening node.
bool hasCommands ()
virtual co::CommandQueue * getMainThreadQueue ()
const Strings & getActiveLayouts ()
const std::string & getGPUFilter () const
float getModelUnit () const
Public Member Functions inherited from eq::fabric::Client
bool connectServer (co::NodePtr server)
Open and connect an Equalizer server to the local client.
bool disconnectServer (co::NodePtr server)
Disconnect and close the connection to an Equalizer server.
void processCommand (const uint32_t timeout=LB_TIMEOUT_INDEFINITE)
Get and process one pending command from the node command queue.
virtual bool dispatchCommand (co::ICommand &command)
Additional Inherited Members
Protected Member Functions inherited from eq::Client
virtual void clientLoop ()
Implements the processing loop for render clients.
virtual void exitClient ()
Exit the process cleanly on render clients.
Detailed Description
Definition at line 42 of file osgScaleViewer.h.
Constructor & Destructor Documentation
osgScaleViewer::OSGScaleViewer::OSGScaleViewer (const InitData & initData)
Create an OSG application.
Parameters
initData the init data object.
Definition at line 40 of file osgScaleViewer.cpp.
Member Function Documentation
int osgScaleViewer::OSGScaleViewer::run ()
Run the application.
Definition at line 45 of file osgScaleViewer.cpp.
References eq::Client::connectServer(), eq::Client::disconnectServer(), osgScaleViewer::Config::exit(), eq::Config::finishAllFrames(), eq::Config::finishFrame(), eq::fabric::Object::getError(), osgScaleViewer::Config::init(), eq::Config::isRunning(), osgScaleViewer::Config::setInitData(), and osgScaleViewer::Config::startFrame().
The documentation for this class was generated from the following files:
osgScaleViewer.h
osgScaleViewer.cpp