Equalizer: eqPly::Config Class Reference
eqPly::Config Class Reference
The configuration, run be the EqPly application.
#include <config.h>
Public Member Functions
Config (eq::ServerPtr parent)
virtual bool init ()
virtual bool exit ()
virtual uint32_t startFrame ()
void setInitData (const LocalInitData &data)
const InitData & getInitData () const
bool loadData (const eq::uint128_t &initDataID)
Map per-config data to the local node process.
const Model * getModel (const eq::uint128_t &id)
virtual bool handleEvent (const eq::ConfigEvent *event)
virtual bool handleEvent (eq::EventICommand command)
Handle one config event.
bool isIdleAA ()
bool needRedraw ()
uint32_t getAnimationFrame ()
Public Member Functions inherited from eq::Config
Config (ServerPtr parent)
Construct a new config.
void setupMessagePump (Pipe *pipe)
void setupServerConnections (const std::string &connectionData)
ClientPtr getClient ()
ConstClientPtr getClient () const
co::NodePtr getApplicationNode ()
co::CommandQueue * getMainThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
uint32_t getCurrentFrame () const
uint32_t getFinishedFrame () const
GLStats::Data getStatistics () const
bool isRunning () const
void stopRunning ()
Stop the config.
int64_t getTime () const
Get the current time in milliseconds.
MessagePump * getMessagePump ()
const Channel * findChannel (const std::string &name) const
virtual bool init (const uint128_t &initID)
Initialize this configuration.
bool update ()
Update the configuration.
virtual void setLatency (const uint32_t latency)
virtual bool registerObject (co::Object *object)
Register a distributed object.
virtual void deregisterObject (co::Object *object)
Deregister a distributed object.
virtual bool mapObject (co::Object *object, const UUID &id, const uint128_t &version=co::VERSION_OLDEST)
Map a distributed object.
virtual uint32_t mapObjectNB (co::Object *object, const UUID &id, const uint128_t &version=co::VERSION_OLDEST)
Start mapping a distributed object.
virtual uint32_t mapObjectNB (co::Object *object, const UUID &id, const uint128_t &version, co::NodePtr master)
Start mapping a distributed object from a known master.
virtual bool mapObjectSync (const uint32_t requestID)
Finalize the mapping of a distributed object.
virtual void unmapObject (co::Object *object)
Unmap a mapped object.
void releaseObject (co::Object *object)
Convenience method to deregister or unmap an object.
virtual uint32_t startFrame (const uint128_t &frameID)
Request a new frame of rendering.
virtual uint32_t finishFrame ()
Finish the rendering of a frame.
virtual uint32_t finishAllFrames ()
Finish rendering all pending frames.
void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the config for a frame.
void stopFrames ()
Asynchronously signal all channels to interrupt their rendering.
const ConfigEvent * nextEvent ()
Get the next event.
const ConfigEvent * tryNextEvent ()
Try to get the next event.
void sendEvent (ConfigEvent &event)
Send an (old) event to the application node.
EventOCommand sendEvent (const uint32_t type)
Send an event to the application node.
EventICommand getNextEvent (const uint32_t timeout=LB_TIMEOUT_INDEFINITE) const
Get the next event.
bool checkEvent () const
virtual void handleEvents ()
Handle all config events.
void addStatistic (const uint32_t originator, const Statistic &stat)
Add an statistic event to the statistics overlay.
Public Member Functions inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
virtual void output (std::ostream &) const
void create (Observer **observer)
void create (Layout **layout)
void create (Canvas **canvas)
void create (Node **node)
void release (Observer *observer)
void release (Layout *layout)
void release (Canvas *canvas)
void release (Node *node)
EQFABRIC_INL lunchbox::RefPtr
< Server > getServer ()
EQFABRIC_INL lunchbox::RefPtr
< const Server > getServer () const
const Observers & getObservers () const
const Layouts & getLayouts () const
const Canvases & getCanvases () const
EQFABRIC_INL uint32_t getTimeout () const
const Nodes & getNodes () const
EQFABRIC_INL Node * findAppNode ()
EQFABRIC_INL const Node * findAppNode () const
EQFABRIC_INL VisitorResult accept (ConfigVisitor &visitor)
Perform a depth-first traversal of this config.
EQFABRIC_INL VisitorResult accept (ConfigVisitor &visitor) const
Const-version of accept().
EQFABRIC_INL T * find (const uint128_t &id)
EQFABRIC_INL const T * find (const uint128_t &id) const
EQFABRIC_INL T * find (const std::string &name)
EQFABRIC_INL const T * find (const std::string &name) const
void find (const uint128_t &id, T **result)
void find (const std::string &name, const T **result) const
Observer * getObserver (const ObserverPath &path)
Layout * getLayout (const LayoutPath &path)
Canvas * getCanvas (const CanvasPath &path)
virtual void updateCanvas (Canvas *)
virtual void exitCanvas (Canvas *)
uint32_t getLatency () const
virtual EQFABRIC_INL void restore ()
void setFAttribute (const FAttribute attr, const float value)
void setIAttribute (const IAttribute attr, const int32_t value)
float getFAttribute (const FAttribute attr) const
int32_t getIAttribute (const IAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual bool isDirty () const
virtual void backup ()
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
void setError (const int32_t error)
Set an error code why the last operation failed.
eq::fabric::Error getError () const
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Protected Member Functions
virtual ~Config ()
Destruct a config.
virtual co::uint128_t sync (const co::uint128_t &version=co::VERSION_HEAD)
Synchronize config and admin copy.
Protected Member Functions inherited from eq::Config
virtual void attach (const UUID &id, const uint32_t instanceID)
virtual void notifyAttached ()
virtual void notifyDetach ()
virtual void changeLatency (const uint32_t latency)
virtual bool mapViewObjects () const
Protected Member Functions inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
EQFABRIC_INL Config (lunchbox::RefPtr< Server > parent)
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual void _removeChild (const UUID &)
void setAppNodeID (const co::NodeID &nodeID)
const co::NodeID & getAppNodeID () const
virtual bool mapNodeObjects () const
virtual VisitorResult _acceptCompounds (ConfigVisitor &)
virtual VisitorResult _acceptCompounds (ConfigVisitor &) const
Node * _findNode (const uint128_t &id)
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Protected Member Functions inherited from eq::fabric::Object
Object ()
Construct a new Object.
virtual ~Object ()
Destruct the object.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
void setTasks (const uint32_t tasks)
void postRemove (Object *child)
virtual void removeChild (const UUID &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
bool _cmdSync (co::ICommand &command)
Additional Inherited Members
Static Public Member Functions inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
static const std::string & getFAttributeString (const FAttribute attr)
static const std::string & getIAttributeString (const IAttribute attr)
Public Types inherited from eq::Config
typedef fabric::Config< Server,
Config, Observer, Layout,
Canvas, Node, ConfigVisitor > Super
base class
Detailed Description
The configuration, run be the EqPly application.
A configuration instance manages configuration-specific data: it distributes the initialization and model data, updates frame-specific data and manages frame generation based on event handling.
Definition at line 53 of file share/Equalizer/examples/eqPly/config.h.
Constructor & Destructor Documentation
eqPly::Config::~Config () protected virtual
Destruct a config.
Version
1.0
Reimplemented from eq::Config.
Definition at line 56 of file eqPly/config.cpp.
Member Function Documentation
bool eqPly::Config::exit () virtual
See Also
eq::Config::exit.
Reimplemented from eq::Config.
Definition at line 106 of file eqPly/config.cpp.
References eq::Config::exit().
Referenced by eqPly::EqPly::run().
uint32_t eqPly::Config::getAnimationFrame ()
Returns
the current animation frame number.
Definition at line 327 of file eqPly/config.cpp.
Referenced by eqPly::EqPly::run().
const Model * eqPly::Config::getModel (const eq::uint128_t & id)
Returns
the requested, default model or 0.
Definition at line 245 of file eqPly/config.cpp.
References eq::Config::getApplicationNode(), eq::Config::getClient(), eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >::getNodes(), and eq::fabric::Node< C, N, P, V >::getPipes().
bool eqPly::Config::handleEvent (const eq::ConfigEvent * event) virtual
See Also
eq::Config::handleEvent
Reimplemented from eq::Config.
Definition at line 347 of file eqPly/config.cpp.
References eq::PointerEvent::button, eq::MagellanEvent::button, eq::PointerEvent::buttons, eq::Event::CHANNEL_POINTER_BUTTON_PRESS, eq::Event::CHANNEL_POINTER_BUTTON_RELEASE, eq::Event::CHANNEL_POINTER_WHEEL, eq::ConfigEvent::data, eq::PointerEvent::dx, eq::PointerEvent::dy, eq::fabric::Canvas< CFG, C, S, L >::getActiveLayout(), eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >::getCanvases(), eq::fabric::View< class, class, class >::getLayout(), eq::Config::handleEvent(), eq::Event::KEY_PRESS, eq::Event::keyPress, eq::Event::magellan, eq::Event::MAGELLAN_AXIS, eq::Event::MAGELLAN_BUTTON, eq::Event::pointerMotion, eq::Event::pointerWheel, eq::Event::type, eq::Event::VIEW_RESIZE, eq::Event::WINDOW_CLOSE, eq::Event::WINDOW_EXPOSE, eq::Event::WINDOW_RESIZE, eq::PointerEvent::xAxis, eq::MagellanEvent::xAxis, eq::MagellanEvent::xRotation, eq::PointerEvent::yAxis, eq::MagellanEvent::yAxis, eq::MagellanEvent::yRotation, eq::MagellanEvent::zAxis, and eq::MagellanEvent::zRotation.
Referenced by eqPly::EqPly::run().
bool eqPly::Config::handleEvent (eq::EventICommand command) virtual
Handle one config event.
Thread safe.
Parameters
command the event command.
Returns
true if the event requires a redraw, false if not.
Version
1.5.1
Reimplemented from eq::Config.
Definition at line 494 of file eqPly/config.cpp.
References eq::EventICommand::getEventType(), and eq::Config::handleEvent().
bool eqPly::Config::init () virtual
See Also
eq::Config::init.
Definition at line 70 of file eqPly/config.cpp.
References eqPly::COLOR_WHITE, eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >::getCanvases(), eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >::getLatency(), eq::Config::init(), and eq::Config::registerObject().
Referenced by eqPly::EqPly::run().
bool eqPly::Config::isIdleAA ()
Returns
true if the application is idling.
Definition at line 317 of file eqPly/config.cpp.
bool eqPly::Config::needRedraw ()
Returns
true if an event required a redraw.
Definition at line 322 of file eqPly/config.cpp.
Referenced by eqPly::EqPly::run().
uint32_t eqPly::Config::startFrame () virtual
See Also
eq::Config::startFrame.
Definition at line 274 of file eqPly/config.cpp.
References eq::Config::startFrame().
Referenced by eqPly::EqPly::run().
co::uint128_t eqPly::Config::sync (const co::uint128_t & version = co::VERSION_HEAD) protected virtual
Synchronize config and admin copy.
Definition at line 797 of file eqPly/config.cpp.
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqPly/config.h
eqPly/config.cpp