Equalizer: seq Namespace Reference
seq Namespace Reference
Sequel - A simple interface to the Equalizer parallel rendering framework.
Classes
class Application
The main application object.
class Renderer
A renderer instance.
class ViewData
Stores per-view data.
Functions
void initErrors ()
Set up Sequel-specific error codes.
void exitErrors ()
Clear Sequel-specific error codes.
Typedefs
typedef lunchbox::RefPtr
< Application > ApplicationPtr
Enumerations
enum Error { ERROR_SEQUEL_MAPOBJECT_FAILED = eq::ERROR_CUSTOM, ERROR_SEQUEL_CREATERENDERER_FAILED }
Defines errors produced by Sequel.
enum ObjectType { OBJECTTYPE_INITDATA = co::OBJECTTYPE_CUSTOM, OBJECTTYPE_FRAMEDATA, OBJECTTYPE_MODELMATRIX, OBJECTTYPE_CUSTOM = 100 }
Built-in object types.
Detailed Description
Sequel - A simple interface to the Equalizer parallel rendering framework.
This namespace provides a simple programming interface to the Equalizer parallel rendering framework. Sequel allows rapid development of clustered multi-GPU applications while not sacrificing the flexibility and power of the underlying Equalizer framework.
Function Documentation
void seq::exitErrors ()
Clear Sequel-specific error codes.
Definition at line 58 of file eqPly/error.cpp.
References eq::fabric::ErrorRegistry::eraseString(), and eq::fabric::Global::getErrorRegistry().
void seq::initErrors ()
Set up Sequel-specific error codes.
Definition at line 50 of file eqPly/error.cpp.
References eq::fabric::Global::getErrorRegistry(), and eq::fabric::ErrorRegistry::setString().
Enumeration Type Documentation
enum seq::Error
Defines errors produced by Sequel.
Definition at line 26 of file include/seq/error.h.
enum seq::ObjectType
Built-in object types.
Version
1.0
Enumerator
OBJECTTYPE_INITDATA
The object passed to Application::init()
OBJECTTYPE_FRAMEDATA
The object passed to Application::run()
OBJECTTYPE_MODELMATRIX
Per-view global model transformation.
OBJECTTYPE_CUSTOM
Application-specific objects.
Definition at line 26 of file objectType.h.