DASH: dash::Node Class Reference
dash::Node Class Reference
A node of a dash graph.
#include <node.h>
Public Member Functions
Node ()
Construct a new empty node.
Node (const Node &from)
Construct a shallow, parent-less copy.
virtual ~Node ()
Destruct this node.
Node & operator= (const Node &from)
Perform a shallow, parent-less copy.
bool operator== (const Node &rhs) const
Check this Node on equality w/o traversing the children.
bool operator!= (const Node &rhs) const
Check this Node on inequality w/o traversing the children.
VisitorResult accept (Visitor &visitor)
Traverse this node tree using the given visitor.
VisitorResult accept (ConstVisitor &visitor) const
Traverse this const node tree using the given visitor.
node.hierarchy
void insert (NodePtr child)
Establish a relationship between the two nodes.
void erase (NodePtr child)
Break the relationship between the two nodes.
bool hasParents () const
size_t getNParents () const
size_t getNChildren () const
NodePtr getChild (const size_t i)
ConstNodePtr getChild (const size_t i) const
ConstChildIterator childrenBegin () const
ConstChildIterator childrenEnd () const
ChildIterator childrenBegin ()
ChildIterator childrenEnd ()
Attribute data storage
void insert (AttributePtr attribute)
Add an attribute to this node.
void erase (AttributePtr attribute)
Remove an attribute from this node.
size_t getNAttributes () const
AttributePtr getAttribute (const size_t i)
ConstAttributePtr getAttribute (const size_t i) const
ConstAttributeIterator attributesBegin () const
ConstAttributeIterator attributesEnd () const
AttributeIterator attributesBegin ()
AttributeIterator attributesEnd ()
Internal
detail::Node * getImpl ()
const detail::Node * getImpl () const
Public Types
typedef NodeVisitor< NodePtr,
AttributePtr > Visitor
Node tree visitor.
typedef NodeVisitor
< ConstNodePtr,
ConstAttributePtr > ConstVisitor
Const node tree visitor.
typedef
detail::AttributeIterator
< Node, Attribute > AttributeIterator
An iterator over the attribute vector.
typedef
detail::AttributeIterator
< const Node, const Attribute > ConstAttributeIterator
A const iterator over the attribute vector.
typedef detail::ChildIterator
< Node > ChildIterator
An iterator over the child vector.
typedef detail::ChildIterator
< const Node > ConstChildIterator
A const iterator over the child vector.
Detailed Description
A node of a dash graph.
Nodes form directed acyclic graphs (DAG) in dash. They hold one or more Attribute data items. All data access to a Node is thread-safe as long as it happens with different contexts. Modifying a Node is not visible to other contexts until a Commit is applied to the Context.
Nodes are by default only visible in the Context they are constructed in. They are made visible in other contexts using Context::map().
Definition at line 50 of file node.h.
Member Typedef Documentation
typedef detail::AttributeIterator< Node, Attribute > dash::Node::AttributeIterator
An iterator over the attribute vector.
Definition at line 60 of file node.h.
typedef detail::ChildIterator< Node > dash::Node::ChildIterator
An iterator over the child vector.
Definition at line 66 of file node.h.
typedef detail::AttributeIterator< const Node, const Attribute > dash::Node::ConstAttributeIterator
A const iterator over the attribute vector.
Definition at line 63 of file node.h.
typedef detail::ChildIterator< const Node > dash::Node::ConstChildIterator
A const iterator over the child vector.
Definition at line 68 of file node.h.
Constructor & Destructor Documentation
dash::Node::Node ()
Construct a new empty node.
Version:
0.1
Definition at line 33 of file node.cpp.
Referenced by Node().
dash::Node::Node (const Node & from)
Construct a shallow, parent-less copy.
Version:
0.1
Definition at line 39 of file node.cpp.
References Node().
dash::Node::~Node () virtual
Destruct this node.
Version:
0.1
Definition at line 46 of file node.cpp.
Member Function Documentation
VisitorResult dash::Node::accept (Visitor & visitor)
Traverse this node tree using the given visitor.
Returns:
the result of the last visit.
Version:
1.0
Definition at line 106 of file node.cpp.
VisitorResult dash::Node::accept (ConstVisitor & visitor) const
Traverse this const node tree using the given visitor.
Returns:
the result of the last visit.
Version:
1.0
Definition at line 111 of file node.cpp.
Node::ConstAttributeIterator dash::Node::attributesBegin () const
Returns:
iterator pointing to the first attribute.
Version:
0.1
Definition at line 198 of file node.cpp.
Node::AttributeIterator dash::Node::attributesBegin ()
Returns:
iterator pointing to the start of the attributes.
Version:
0.1
Definition at line 208 of file node.cpp.
Node::ConstAttributeIterator dash::Node::attributesEnd () const
Returns:
iterator pointing to the end of the attributes.
Version:
0.1
Definition at line 203 of file node.cpp.
References getNAttributes().
Node::AttributeIterator dash::Node::attributesEnd ()
Returns:
iterator pointing to the end of the attributes.
Version:
0.1
Definition at line 213 of file node.cpp.
References getNAttributes().
Node::ConstChildIterator dash::Node::childrenBegin () const
Returns:
an iterator pointing to the start of the children.
Version:
0.1
Definition at line 152 of file node.cpp.
Node::ChildIterator dash::Node::childrenBegin ()
Returns:
an iterator pointing to the start of the children.
Version:
0.1
Definition at line 162 of file node.cpp.
Node::ConstChildIterator dash::Node::childrenEnd () const
Returns:
an iterator pointing to the end of the children.
Version:
0.1
Definition at line 157 of file node.cpp.
References getNChildren().
Node::ChildIterator dash::Node::childrenEnd ()
Returns:
an iterator pointing to the end of the children.
Version:
0.1
Definition at line 167 of file node.cpp.
References getNChildren().
void dash::Node::erase (NodePtr child)
Break the relationship between the two nodes.
Version:
0.1
Definition at line 122 of file node.cpp.
void dash::Node::erase (AttributePtr attribute)
Remove an attribute from this node.
Version:
0.1
Definition at line 178 of file node.cpp.
AttributePtr dash::Node::getAttribute (const size_t i)
Returns:
the attribute at the given position.
Version:
0.1
Definition at line 188 of file node.cpp.
ConstAttributePtr dash::Node::getAttribute (const size_t i) const
Returns:
the const attribute at the given position.
Version:
0.1
Definition at line 193 of file node.cpp.
NodePtr dash::Node::getChild (const size_t i)
Returns:
the child at the given position.
Version:
0.1
Definition at line 142 of file node.cpp.
ConstNodePtr dash::Node::getChild (const size_t i) const
Returns:
the child at the given position.
Version:
0.1
Definition at line 147 of file node.cpp.
size_t dash::Node::getNAttributes () const
Returns:
the current number of attributes.
Version:
0.1
Definition at line 183 of file node.cpp.
Referenced by attributesEnd().
size_t dash::Node::getNChildren () const
Returns:
the current number of children.
Version:
0.1
Definition at line 137 of file node.cpp.
Referenced by childrenEnd().
size_t dash::Node::getNParents () const
Returns:
the current number of parents.
Version:
0.1
Definition at line 132 of file node.cpp.
bool dash::Node::hasParents () const
Returns:
true of the node.has parents, false otherwise.
Version:
0.1
Definition at line 127 of file node.cpp.
void dash::Node::insert (NodePtr child)
Establish a relationship between the two nodes.
Version:
0.1
Definition at line 117 of file node.cpp.
void dash::Node::insert (AttributePtr attribute)
Add an attribute to this node.
Version:
0.1
Definition at line 173 of file node.cpp.
bool dash::Node::operator!= (const Node & rhs) const inline
Check this Node on inequality w/o traversing the children.
Version:
0.1
Definition at line 84 of file node.h.
Node & dash::Node::operator= (const Node & from)
Perform a shallow, parent-less copy.
Version:
0.1
Definition at line 52 of file node.cpp.
bool dash::Node::operator== (const Node & rhs) const
Check this Node on equality w/o traversing the children.
Version:
0.1
Definition at line 60 of file node.cpp.
The documentation for this class was generated from the following files:
node.h
node.cpp