set(HWSD_MATURITY "EP")
set(HWSD_DESCRIPTION "")
set(HWSD_GIT_ROOT_URL "https://github.com/Eyescale/hwsd.git")
set(HWSD_PACKAGE_URL "")
set(HWSD_CI_URL "https://travis-ci.org/Eyescale/hwsd")
set(HWSD_CI_PNG "https://travis-ci.org/Eyescale/hwsd.png")
set(HWSD_ISSUES_URL "https://github.com/Eyescale/hwsd/issues")
