Lunchbox: lunchbox::Buffer< T > Class Template Reference
lunchbox::Buffer< T > Class Template Reference
A simple memory buffer with some helper functions.
#include <buffer.h>
Public Member Functions
Buffer ()
Construct a new, empty buffer.
Buffer (const uint64_t size)
Construct a new buffer of the given size.
Buffer (Buffer &from)
Copy constructor, transfers ownership to new Buffer.
~Buffer ()
Destruct the buffer.
void clear ()
Flush the buffer, deleting all data.
T * pack ()
Tighten the allocated memory to the size of the buffer.
const Buffer & operator= (const Buffer &from)
Assignment operator, copies data from Buffer.
T & operator[] (const uint64_t position)
Direct access to the element at the given index.
const T & operator[] (const uint64_t position) const
Direct const access to an element.
T * resize (const uint64_t newSize)
Ensure that the buffer contains at least newSize elements.
void grow (const uint64_t newSize)
Ensure that the buffer contains at least newSize elements.
T * reserve (const uint64_t newSize)
Ensure that the buffer contains at least newSize elements.
T * reset (const uint64_t newSize)
Set the buffer size and malloc enough memory.
void append (const T *data, const uint64_t size)
Append elements to the buffer, increasing the size.
void append (const T &element)
Append one element to the buffer.
void replace (const void *data, const uint64_t size)
Replace the existing data with new data.
void replace (const Buffer &from)
Replace the existing data.
void swap (Buffer &buffer)
Swap the buffer contents with another Buffer.
T * getData ()
const T * getData () const
bool setSize (const uint64_t size)
Set the size of the buffer without changing its allocation.
uint64_t getSize () const
uint64_t getNumBytes () const
bool isEmpty () const
uint64_t getMaxSize () const
Detailed Description
template<class T>
class lunchbox::Buffer< T >
A simple memory buffer with some helper functions.
For bigger data (>100k) using a std::vector< uint8_t > has a high overhead when resizing (>1ms). This buffer just memcpy's elements, i.e., it should only be used for PODs since the copy constructor or assignment operator is not called on the copied elements. Primarily used for binary data, e.g., in eq::Image. The implementation works like a pool, that is, data is only released when the buffer is deleted or clear() is called.
Definition at line 40 of file buffer.h.
Constructor & Destructor Documentation
template<class T > lunchbox::Buffer< T >::Buffer () inline
Construct a new, empty buffer.
Version
1.0
Definition at line 44 of file buffer.h.
template<class T > lunchbox::Buffer< T >::Buffer (const uint64_t size) inline
Construct a new buffer of the given size.
Version
1.0
Definition at line 47 of file buffer.h.
References lunchbox::Buffer< T >::reset().
template<class T > lunchbox::Buffer< T >::Buffer (Buffer< T > & from) inline
Copy constructor, transfers ownership to new Buffer.
Version
1.0
Definition at line 51 of file buffer.h.
template<class T > lunchbox::Buffer< T >::~Buffer () inline
Destruct the buffer.
Version
1.0
Definition at line 58 of file buffer.h.
References lunchbox::Buffer< T >::clear().
Member Function Documentation
template<class T > void lunchbox::Buffer< T >::append (const T * data, const uint64_t size) inline
Append elements to the buffer, increasing the size.
Version
1.0
Definition at line 160 of file buffer.h.
References lunchbox::Buffer< T >::resize().
template<class T > void lunchbox::Buffer< T >::append (const T & element) inline
Append one element to the buffer.
Version
1.0
Definition at line 171 of file buffer.h.
References lunchbox::Buffer< T >::resize().
template<class T > void lunchbox::Buffer< T >::clear () inline
Flush the buffer, deleting all data.
Version
1.0
Definition at line 61 of file buffer.h.
Referenced by lunchbox::Buffer< T >::~Buffer().
template<class T > T* lunchbox::Buffer< T >::getData () inline
Returns
a pointer to the data.
Version
1.0
Definition at line 209 of file buffer.h.
template<class T > const T* lunchbox::Buffer< T >::getData () const inline
Returns
a const pointer to the data.
Version
1.0
Definition at line 212 of file buffer.h.
template<class T > uint64_t lunchbox::Buffer< T >::getMaxSize () const inline
Returns
the maximum size of the buffer.
Version
1.0
Definition at line 242 of file buffer.h.
template<class T > uint64_t lunchbox::Buffer< T >::getNumBytes () const inline
Returns
the current storage size.
Version
1.5.1
Definition at line 236 of file buffer.h.
template<class T > uint64_t lunchbox::Buffer< T >::getSize () const inline
Returns
the current number of elements.
Version
1.0
Definition at line 233 of file buffer.h.
template<class T > void lunchbox::Buffer< T >::grow (const uint64_t newSize) inline
Ensure that the buffer contains at least newSize elements.
Existing data is retained. The size is increased, if necessary.
Version
1.0
Definition at line 122 of file buffer.h.
References lunchbox::Buffer< T >::resize().
template<class T > bool lunchbox::Buffer< T >::isEmpty () const inline
Returns
true if the buffer is empty, false if not.
Version
1.0
Definition at line 239 of file buffer.h.
template<class T > const Buffer& lunchbox::Buffer< T >::operator= (const Buffer< T > & from) inline
Assignment operator, copies data from Buffer.
Version
1.0
Definition at line 81 of file buffer.h.
References lunchbox::Buffer< T >::replace().
template<class T > T& lunchbox::Buffer< T >::operator[] (const uint64_t position) inline
Direct access to the element at the given index.
Version
1.0
Definition at line 88 of file buffer.h.
template<class T > const T& lunchbox::Buffer< T >::operator[] (const uint64_t position) const inline
Direct const access to an element.
Version
1.0
Definition at line 92 of file buffer.h.
template<class T > T* lunchbox::Buffer< T >::pack () inline
Tighten the allocated memory to the size of the buffer.
Returns
the new pointer to the first element.
Version
1.0
Definition at line 69 of file buffer.h.
template<class T > void lunchbox::Buffer< T >::replace (const void * data, const uint64_t size) inline
Replace the existing data with new data.
Version
1.0
Definition at line 178 of file buffer.h.
References lunchbox::Buffer< T >::reserve().
Referenced by lunchbox::Buffer< T >::operator=().
template<class T > void lunchbox::Buffer< T >::replace (const Buffer< T > & from) inline
Replace the existing data.
Version
1.5.1
Definition at line 189 of file buffer.h.
References lunchbox::Buffer< T >::replace().
Referenced by lunchbox::Buffer< T >::replace().
template<class T > T* lunchbox::Buffer< T >::reserve (const uint64_t newSize) inline
Ensure that the buffer contains at least newSize elements.
Existing data is preserved.
Returns
the new pointer to the first element.
Version
1.0
Definition at line 135 of file buffer.h.
Referenced by lunchbox::Buffer< T >::replace(), and lunchbox::Buffer< T >::reset().
template<class T > T* lunchbox::Buffer< T >::reset (const uint64_t newSize) inline
Set the buffer size and malloc enough memory.
Existing data may be deleted.
Returns
the new pointer to the first element.
Version
1.0
Definition at line 152 of file buffer.h.
References lunchbox::Buffer< T >::reserve(), and lunchbox::Buffer< T >::setSize().
Referenced by lunchbox::Buffer< T >::Buffer().
template<class T > T* lunchbox::Buffer< T >::resize (const uint64_t newSize) inline
Ensure that the buffer contains at least newSize elements.
Existing data is retained. The size is set.
Returns
the new pointer to the first element.
Version
1.0
Definition at line 102 of file buffer.h.
Referenced by lunchbox::Buffer< T >::append(), and lunchbox::Buffer< T >::grow().
template<class T > bool lunchbox::Buffer< T >::setSize (const uint64_t size) inline
Set the size of the buffer without changing its allocation.
This method only modifies the size parameter. If the current allocation of the buffer is too small, it asserts, returns false and does not change the size.
Version
1.0
Definition at line 222 of file buffer.h.
Referenced by lunchbox::Buffer< T >::reset().
template<class T > void lunchbox::Buffer< T >::swap (Buffer< T > & buffer) inline
Swap the buffer contents with another Buffer.
Version
1.0
Definition at line 193 of file buffer.h.
The documentation for this class was generated from the following file:
buffer.h