Equalizer: co::ErrorRegistry Class Reference
co::ErrorRegistry Class Reference
The registry translating error codes to strings.
#include <errorRegistry.h>
Public Member Functions
CO_API const std::string & getString (const uint32_t error) const
CO_API void setString (const uint32_t error, const std::string &text)
Set an error string for the given error code.
CO_API void eraseString (const uint32_t error)
Clear a given error code string.
CO_API bool isEmpty () const
Detailed Description
The registry translating error codes to strings.
Applications can register custom error strings starting at eq::ERROR_CUSTOM. Error registration and erasure is not thread-safe. Equalizer registers errors only during eq::init(). It is strongly advised to register application-specific errors before eq::init() and erase them after eq::exit().
See also:
co::Error, eq::Error
Definition at line 40 of file errorRegistry.h.
Member Function Documentation
CO_API void co::ErrorRegistry::eraseString (const uint32_t error)
Clear a given error code string.
Version:
1.0
Referenced by eqPly::exitErrors(), and eVolve::exitErrors().
CO_API const std::string& co::ErrorRegistry::getString (const uint32_t error) const
Returns:
the error string for the given error code.
Version:
1.0
CO_API void co::ErrorRegistry::setString (const uint32_t error, const std::string & text)
Set an error string for the given error code.
Version:
1.0
Referenced by eqPly::initErrors(), and eVolve::initErrors().
The documentation for this class was generated from the following file:
errorRegistry.h