Equalizer: eq::ResultImageListener Class Reference
eq::ResultImageListener Class Reference abstract
The result image listener gets notified on new images produced by destination channels.
#include <resultImageListener.h>
Public Member Functions
ResultImageListener ()
Construct a new result image listener.
virtual ~ResultImageListener ()
Destruct the result image listener.
virtual void notifyNewImage (Channel &channel, const Image &image)=0
Notify on new image, called from rendering thread in Channel::frameViewFinish().
Detailed Description
The result image listener gets notified on new images produced by destination channels.
See also
Channel::addResultImageListener
Version
1.9
Definition at line 33 of file resultImageListener.h.
Constructor & Destructor Documentation
eq::ResultImageListener::ResultImageListener () inline
Construct a new result image listener.
Version
1.9
Definition at line 37 of file resultImageListener.h.
Referenced by ~ResultImageListener().
virtual eq::ResultImageListener::~ResultImageListener () inline virtual
Destruct the result image listener.
Version
1.9
Definition at line 40 of file resultImageListener.h.
References notifyNewImage(), and ResultImageListener().
Member Function Documentation
virtual void eq::ResultImageListener::notifyNewImage (Channel & channel, const Image & image) pure virtual
Notify on new image, called from rendering thread in Channel::frameViewFinish().
Parameters
channel the destination channel
image the new image, valid only in the current frame
Version
1.9
Referenced by ~ResultImageListener().
The documentation for this class was generated from the following file:
resultImageListener.h