Equalizer: eq::fabric::Frustum Class Reference
eq::fabric::Frustum Class Reference
A distributed object for frustum data.
#include <frustum.h>
Public Types
enum Type { TYPE_NONE, TYPE_WALL, TYPE_PROJECTION }
The type of the last specified frustum.
Public Member Functions
EQFABRIC_API Frustum ()
Construct a new frustum.
virtual EQFABRIC_API ~Frustum ()
Destruct the frustum.
EQFABRIC_API void setWall (const Wall &wall)
Set the frustum using a wall description.
EQFABRIC_API void setProjection (const Projection &projection)
Set the frustum using a projection description.
const Wall & getWall () const
const Projection & getProjection () const
Type getCurrentType () const
EQFABRIC_API void unsetFrustum ()
Set the last specified frustum to TYPE_NONE.
EQFABRIC_API void serialize (co::DataOStream &os)
EQFABRIC_API void deserialize (co::DataIStream &is)
virtual EQFABRIC_API void backup ()
virtual EQFABRIC_API void restore ()
Protected Member Functions
virtual void updateFrustum ()
virtual void notifyFrustumChanged ()
Detailed Description
A distributed object for frustum data.
Definition at line 30 of file frustum.h.
Member Enumeration Documentation
enum eq::fabric::Frustum::Type
The type of the last specified frustum.
Version
1.0
Enumerator
TYPE_NONE
No frustum has been specified.
TYPE_WALL
A wall description has been set last.
TYPE_PROJECTION
A projection description has been set last.
Definition at line 40 of file frustum.h.
Constructor & Destructor Documentation
EQFABRIC_API eq::fabric::Frustum::Frustum ()
Construct a new frustum.
Version
1.0
virtual EQFABRIC_API eq::fabric::Frustum::~Frustum () virtual
Destruct the frustum.
Version
1.0
Member Function Documentation
Type eq::fabric::Frustum::getCurrentType () const inline
Returns
the type of the latest specified frustum.
Version
1.0
Definition at line 60 of file frustum.h.
References eq::fabric::operator<<(), TYPE_NONE, and unsetFrustum().
const Projection& eq::fabric::Frustum::getProjection () const inline
Returns
the last specified frustum as a projection.
Version
1.0
Definition at line 57 of file frustum.h.
const Wall& eq::fabric::Frustum::getWall () const inline
Returns
the last specified frustum as a wall.
Version
1.0
Definition at line 54 of file frustum.h.
EQFABRIC_API void eq::fabric::Frustum::setProjection (const Projection & projection)
Set the frustum using a projection description.
Version
1.0
EQFABRIC_API void eq::fabric::Frustum::setWall (const Wall & wall)
Set the frustum using a wall description.
Version
1.0
EQFABRIC_API void eq::fabric::Frustum::unsetFrustum ()
Set the last specified frustum to TYPE_NONE.
Version
1.0
Referenced by getCurrentType().
The documentation for this class was generated from the following file:
frustum.h