Equalizer: seq::Renderer Class Reference
seq::Renderer Class Reference abstract
A renderer instance.
#include <renderer.h>
Public Member Functions
SEQ_API Renderer (Application &application)
Construct a new renderer.
virtual SEQ_API ~Renderer ()
Destruct this renderer.
Operations
virtual SEQ_API bool init (co::Object *initData)
Initialize the renderer.
virtual SEQ_API bool exit ()
De-initialize the renderer.
virtual SEQ_API bool initContext (co::Object *initData)
Initialize a rendering context.
virtual SEQ_API bool exitContext ()
De-initialize a rendering context.
virtual SEQ_API void clear (co::Object *frameData)
Clear the frame buffer.
virtual void draw (co::Object *frameData)=0
Render the scene.
SEQ_API void requestRedraw ()
Request another call to draw().
SEQ_API void updateNearFar (const Vector4f &boundingSphere)
Update the near and far planes to tightly enclose the given sphere.
SEQ_API void setNearFar (const float nearPlane, const float farPlane)
Set the near and far planes.
virtual SEQ_API void applyRenderContext ()
Apply the current rendering parameters to the rendering context.
SEQ_API void bindDrawFrameBuffer ()
Bind the window draw buffer, which can be (multisampled) FBO or window buffer.
SEQ_API const RenderContext & getRenderContext () const
virtual SEQ_API void applyModelMatrix ()
Apply the current model matrix to the rendering context.
virtual SEQ_API void applyScreenFrustum ()
Apply an orthographic frustum for pixel-based 2D operations.
virtual SEQ_API void applyPerspectiveFrustum ()
Apply the perspective frustum matrix for the current rendering task.
virtual bool processEvent (EventType)
virtual bool processEvent (EventType, const SizeEvent &)
virtual bool processEvent (EventType, const PointerEvent &)
virtual bool processEvent (EventType, const KeyEvent &)
virtual bool processEvent (EventType, const AxisEvent &)
virtual bool processEvent (EventType, const ButtonEvent &)
Data Access
detail::Renderer * getImpl ()
SEQ_API co::Object * getFrameData ()
Application & getApplication ()
const Application & getApplication () const
SEQ_API const ObjectManager & getObjectManager () const
SEQ_API ObjectManager & getObjectManager ()
virtual SEQ_API ViewData * createViewData (View &view)
Create a new per-view data instance.
virtual SEQ_API void destroyViewData (ViewData *viewData)
Delete the given view data.
SEQ_API const ViewData * getViewData () const
SEQ_API const GLEWContext * glewGetContext () const
Get the GLEW context for this renderer.
SEQ_API const Frustumf & getFrustum () const
SEQ_API const Matrix4f & getViewMatrix () const
SEQ_API const Matrix4f & getModelMatrix () const
SEQ_API const PixelViewport & getPixelViewport () const
SEQ_API uint32_t getWindowID () const
Distributed Object API
virtual SEQ_API co::Object * createObject (const uint32_t type)
virtual SEQ_API void destroyObject (co::Object *object, const uint32_t type)
SEQ_API co::Object * mapObject (const uint128_t &identifier, co::Object *instance)
Map and return an object.
SEQ_API bool unmap (co::Object *object)
Unmap an object from the object map.
Detailed Description
A renderer instance.
All calls to one renderer instance are guaranteed to be executed from a single thread.
Definition at line 34 of file renderer.h.
Constructor & Destructor Documentation
SEQ_API seq::Renderer::Renderer (Application & application) explicit
Construct a new renderer.
Version
1.0
virtual SEQ_API seq::Renderer::~Renderer () virtual
Destruct this renderer.
Version
1.0
Member Function Documentation
virtual SEQ_API void seq::Renderer::applyModelMatrix () virtual
Apply the current model matrix to the rendering context.
This method is not included in applyRenderContext() since ligthing parameters are often applied before positioning the model.
This method is only to be called from clear(), draw() and TBD.
Version
1.0
Referenced by exit().
virtual SEQ_API void seq::Renderer::applyPerspectiveFrustum () virtual
Apply the perspective frustum matrix for the current rendering task.
Version
1.8
Referenced by exit().
virtual SEQ_API void seq::Renderer::applyRenderContext () virtual
Apply the current rendering parameters to the rendering context.
This method sets the draw buffer, color mask, viewport as well as the projection and view matrix.
This method is only to be called from clear(), draw() and TBD.
Version
1.0
Referenced by exit().
virtual SEQ_API void seq::Renderer::applyScreenFrustum () virtual
Apply an orthographic frustum for pixel-based 2D operations.
One unit of the frustum covers one pixel on screen. The frustum is positioned relative to the eq::View.
Version
1.8
Referenced by exit().
SEQ_API void seq::Renderer::bindDrawFrameBuffer ()
Bind the window draw buffer, which can be (multisampled) FBO or window buffer.
Version
1.12
Referenced by exit().
virtual SEQ_API void seq::Renderer::clear (co::Object * frameData) virtual
Clear the frame buffer.
Parameters
frameData the renderer's instance of the object passed to Config::run.
Version
1.0
Referenced by exit().
virtual SEQ_API co::Object* seq::Renderer::createObject (const uint32_t type) virtual
See also
seq::Application::createObject()
Referenced by getApplication().
virtual SEQ_API ViewData* seq::Renderer::createViewData (View & view) virtual
Create a new per-view data instance.
Called once for each view used by this renderer. Creates the view instance used by the renderer to retrieve parameters from the application for rendering.
Parameters
view the view requesting the view data
Returns
the new view data
Version
1.11
Referenced by getApplication().
virtual SEQ_API void seq::Renderer::destroyObject (co::Object * object, const uint32_t type) virtual
See also
seq::Application::destroyObject()
Referenced by getApplication().
virtual SEQ_API void seq::Renderer::destroyViewData (ViewData * viewData) virtual
Delete the given view data.
Version
1.0
Referenced by getApplication().
virtual void seq::Renderer::draw (co::Object * frameData) pure virtual
Render the scene.
Parameters
frameData the renderer's instance of the object passed to Config::run.
Version
1.0
Referenced by exit().
virtual SEQ_API bool seq::Renderer::exit () inline virtual
De-initialize the renderer.
Called just before the last context will be destroyed after the last call to exitContext().
Returns
true on success, false otherwise.
Version
1.0
Definition at line 68 of file renderer.h.
References applyModelMatrix(), applyPerspectiveFrustum(), applyRenderContext(), applyScreenFrustum(), bindDrawFrameBuffer(), clear(), draw(), exitContext(), getRenderContext(), initContext(), requestRedraw(), setNearFar(), and updateNearFar().
virtual SEQ_API bool seq::Renderer::exitContext () virtual
De-initialize a rendering context.
Called just before the context will be destroyed.
Returns
true on success, false otherwise.
Version
1.0
Referenced by exit().
Application& seq::Renderer::getApplication () inline
Returns
the application instance for this renderer.
Version
1.0
Definition at line 205 of file renderer.h.
const Application& seq::Renderer::getApplication () const inline
Returns
the application instance for this renderer.
Version
1.0
Definition at line 208 of file renderer.h.
References createObject(), createViewData(), destroyObject(), destroyViewData(), getFrustum(), getModelMatrix(), getObjectManager(), getPixelViewport(), getViewData(), getViewMatrix(), getWindowID(), glewGetContext(), mapObject(), and unmap().
SEQ_API co::Object* seq::Renderer::getFrameData ()
Returns
A frame-synchronous instance of the data passed to Application::run().
Version
1.8
Referenced by processEvent().
SEQ_API const Frustumf& seq::Renderer::getFrustum () const
Returns
the current view frustum.
Version
1.0
Referenced by getApplication().
SEQ_API const Matrix4f& seq::Renderer::getModelMatrix () const
Returns
the current model (scene) transformation.
Version
1.0
Referenced by getApplication().
SEQ_API const ObjectManager& seq::Renderer::getObjectManager () const
Returns
the object manager of this renderer.
Version
1.0
Referenced by getApplication().
SEQ_API ObjectManager& seq::Renderer::getObjectManager ()
Returns
the object manager of this renderer.
Version
1.0
SEQ_API const PixelViewport& seq::Renderer::getPixelViewport () const
Returns
the current rendering area.
Version
1.8
Referenced by getApplication().
SEQ_API const RenderContext& seq::Renderer::getRenderContext () const
Returns
the current rendering parameters.
Version
1.4
Referenced by exit().
SEQ_API const ViewData* seq::Renderer::getViewData () const
Returns
the current view data.
Version
1.12
Referenced by getApplication().
SEQ_API const Matrix4f& seq::Renderer::getViewMatrix () const
Returns
the current view (frustum) transformation.
Version
1.0
Referenced by getApplication().
SEQ_API uint32_t seq::Renderer::getWindowID () const
Returns
a unique, stable identifier for the current window.
Version
1.8
Referenced by getApplication().
SEQ_API const GLEWContext* seq::Renderer::glewGetContext () const
Get the GLEW context for this renderer.
The glew context provides access to OpenGL extensions. This function does not follow the Sequel naming conventions, since GLEW uses a function of this name to automatically resolve OpenGL function entry points. Therefore, any OpenGL function support by the driver can be directly called from any method of an initialized renderer.
Returns
the extended OpenGL function table for the window's OpenGL context.
Version
1.0
Referenced by getApplication().
virtual SEQ_API bool seq::Renderer::init (co::Object * initData) inline virtual
Initialize the renderer.
Called once per renderer with a rendering context current before the first call to initContext().
Parameters
initData a per-renderer instance of the object passed to Config::init().
Returns
true on success, false otherwise.
Version
1.0
Definition at line 56 of file renderer.h.
virtual SEQ_API bool seq::Renderer::initContext (co::Object * initData) virtual
Initialize a rendering context.
Called for each window handled by this renderer, after the context has been created and made current.
Parameters
initData a per-renderer instance of the object passed to Config::init().
Returns
true on success, false otherwise.
Version
1.0
Referenced by exit().
SEQ_API co::Object* seq::Renderer::mapObject (const uint128_t & identifier, co::Object * instance)
Map and return an object.
Parameters
identifier unique object identifier used for map operation
instance already created instance to skip factory creation
Returns
0 if not registered, the valid instance otherwise
Version
1.8
See also
co::ObjectMap::map()
Referenced by getApplication().
virtual bool seq::Renderer::processEvent (EventType) inline virtual
Warning
experimental
Returns
true when the event was handled, false if not.
Definition at line 185 of file renderer.h.
References getFrameData().
SEQ_API void seq::Renderer::requestRedraw ()
Request another call to draw().
Version
1.12
Referenced by exit().
SEQ_API void seq::Renderer::setNearFar (const float nearPlane, const float farPlane)
Set the near and far planes.
The given near and far planes update the current perspective and orthographics frustum accordingly.
Parameters
nearPlane the near plane.
farPlane the far plane.
Version
1.7.1
Referenced by exit().
SEQ_API bool seq::Renderer::unmap (co::Object * object)
Unmap an object from the object map.
Parameters
object the object to unmap
Returns
false on if object was not mapped, true otherwise
Version
1.0
See also
co::ObjectMap::unmap()
Referenced by getApplication().
SEQ_API void seq::Renderer::updateNearFar (const Vector4f & boundingSphere)
Update the near and far planes to tightly enclose the given sphere.
Parameters
boundingSphere the sphere bounding of the scene to be rendered.
Version
1.7.1
Referenced by exit().
The documentation for this class was generated from the following file:
renderer.h