Equalizer: eVolve::Node Class Reference
eVolve::Node Class Reference
Public Member Functions
Node (eq::Config *parent)
Public Member Functions inherited from eq::Node
Node (Config *parent)
Construct a new node.
ClientPtr getClient ()
ServerPtr getServer ()
co::CommandQueue * getMainThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
uint32_t getCurrentFrame () const
co::Barrier * getBarrier (const co::ObjectVersion barrier)
FrameDataPtr getFrameData (const co::ObjectVersion &frameDataVersion)
void releaseFrameData (FrameDataPtr data)
void waitInitialized () const
bool isRunning () const
bool isStopped () const
void waitFrameStarted (const uint32_t frameNumber) const
Wait for a frame to be started.
uint32_t getFinishedFrame () const
virtual bool processEvent (const Event &event)
Process a received event.
virtual void setDirty (const uint64_t bits)
void dirtyClientExit ()
Public Member Functions inherited from eq::fabric::Node< Config, Node, Pipe, NodeVisitor >
Config * getConfig ()
const Config * getConfig () const
const Pipes & getPipes () const
bool isApplicationNode () const
EQFABRIC_INL void setApplicationNode (const bool isAppNode)
EQFABRIC_INL NodePath getPath () const
Pipe * findPipe (const UUID &id)
EQFABRIC_INL VisitorResult accept (NodeVisitor &visitor)
Perform a depth-first traversal of this node.
EQFABRIC_INL VisitorResult accept (NodeVisitor &visitor) const
Const-version of accept().
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
void create (Pipe **pipe)
void release (Pipe *pipe)
virtual void output (std::ostream &) const
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
EQFABRIC_INL void setIAttribute (const IAttribute attr, const int32_t value)
EQFABRIC_INL int32_t getIAttribute (const IAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual bool isDirty () const
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
void setError (const int32_t error)
Set an error code why the last operation failed.
eq::fabric::Error getError () const
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Protected Member Functions
virtual ~Node ()
Destruct the node.
virtual bool configInit (const eq::uint128_t &initID)
Initialize this node.
Protected Member Functions inherited from eq::Node
virtual void attach (const UUID &id, const uint32_t instanceID)
void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the parent for a frame.
virtual bool configExit ()
Exit this node.
virtual void frameStart (const uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
virtual void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
virtual void frameTasksFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish all rendering tasks.
Protected Member Functions inherited from eq::fabric::Node< Config, Node, Pipe, NodeVisitor >
Node (Config *parent)
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual EQFABRIC_INL void notifyDetach ()
virtual ChangeType getChangeType () const
virtual uint64_t getRedistributableBits () const
Protected Member Functions inherited from eq::fabric::Object
Object ()
Construct a new Object.
virtual ~Object ()
Destruct the object.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
void setTasks (const uint32_t tasks)
void postRemove (Object *child)
virtual void removeChild (const UUID &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
bool _cmdSync (co::ICommand &command)
Additional Inherited Members
Public Types inherited from eq::fabric::Node< Config, Node, Pipe, NodeVisitor >
typedef std::vector< Pipe * > Pipes
A vector of pointers to pipes.
enum IAttribute
Integer attributes.
Static Public Member Functions inherited from eq::fabric::Node< Config, Node, Pipe, NodeVisitor >
static const std::string & getIAttributeString (const IAttribute attr)
Public Attributes inherited from eq::Node
eq::Node::TransmitThread transmitter
Protected Types inherited from eq::fabric::Node< Config, Node, Pipe, NodeVisitor >
enum DirtyBits
Detailed Description
Definition at line 39 of file share/Equalizer/examples/eVolve/node.h.
Constructor & Destructor Documentation
virtual eVolve::Node::~Node () inline protected virtual
Destruct the node.
Version
1.0
Reimplemented from eq::Node.
Definition at line 45 of file share/Equalizer/examples/eVolve/node.h.
Member Function Documentation
bool eVolve::Node::configInit (const eq::uint128_t & initID) protected virtual
Initialize this node.
Parameters
initID the init identifier.
Version
1.0
Reimplemented from eq::Node.
Definition at line 36 of file eVolve/node.cpp.
References eq::Node::configInit(), eq::fabric::Node< Config, Node, Pipe, NodeVisitor >::getConfig(), eq::fabric::Node< Config, Node, Pipe, NodeVisitor >::getIAttribute(), eq::fabric::Node< Config, Node, Pipe, NodeVisitor >::IATTR_THREAD_MODEL, eVolve::Config::mapData(), and eq::fabric::Object::setError().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eVolve/node.h
eVolve/node.cpp