Equalizer: eVolve::Channel Class Reference
eVolve::Channel Class Reference
Public Member Functions
Channel (eq::Window *parent)
Public Member Functions inherited from eq::Channel
Channel (Window *parent)
Construct a new channel.
virtual bool processEvent (const Event &event)
Process a received event.
virtual void drawStatistics ()
Draw a statistics overlay.
virtual void outlineViewport ()
Outline the current pixel viewport.
void changeLatency (const uint32_t latency)
co::CommandQueue * getPipeThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
uint32_t getCurrentFrame () const
void waitFrameFinished (const uint32_t frame) const
bool isStopped () const
Pipe * getPipe ()
const Pipe * getPipe () const
Node * getNode ()
const Node * getNode () const
Config * getConfig ()
const Config * getConfig () const
ServerPtr getServer ()
const GLEWContext * glewGetContext () const
Get the GLEW context for this channel.
ObjectManager * getObjectManager ()
const DrawableConfig & getDrawableConfig () const
View * getNativeView ()
Get the channel's native view.
const View * getNativeView () const
const-version of getNativeView()
util::FrameBufferObject * getFrameBufferObject ()
const Vector3ub & getUniqueColor () const
void addStatistic (Event &event)
virtual Vector2f getJitter () const
const Frames & getInputFrames ()
const Frames & getOutputFrames ()
View * getView ()
Get the channel's current View.
const View * getView () const
Const version of getView().
Frustumf getScreenFrustum () const
Returns an orthographic frustum for 2D operations on the view.
virtual void applyBuffer ()
Apply the current rendering buffer, including the color mask.
virtual void applyColorMask () const
Apply the current color mask.
virtual void applyViewport () const
Apply the OpenGL viewport for the current rendering task.
virtual void applyFrustum () const
Apply the frustum matrix for the current rendering task.
virtual void applyPerspective () const
Apply the perspective frustum matrix for the current rendering task.
virtual void applyOrtho () const
Apply the orthographic frustum matrix for the current rendering task.
void applyScreenFrustum () const
Apply an orthographic frustum for pixel-based 2D operations.
virtual void applyHeadTransform () const
Apply the transformation to position the view frustum.
virtual void applyPerspectiveTransform () const
Apply the transformation to position the perspective view frustum.
virtual void applyOrthoTransform () const
Apply the transformation to position the orthographic view frustum.
virtual void applyFrameBufferObject ()
Apply the current alternate frame buffer.
void bindFrameBuffer ()
Rebind the current alternate FBO of the channel or window.
virtual void resetRegions ()
Reset the declared regions of interest.
virtual void declareRegion (const eq::PixelViewport &region)
Declare a region covered by the current draw or assemble operation.
void declareRegion (const eq::Viewport &vp)
Convenience method to declare a region in relative coordinates.
PixelViewport getRegion () const
const PixelViewports & getRegions () const
Get the current regions of interest.
Public Member Functions inherited from eq::fabric::Channel< Window, Channel >
virtual bool omitOutput () const
virtual void output (std::ostream &) const
void init ()
Window * getWindow ()
const Window * getWindow () const
bool isDestination () const
void setViewVersion (const co::ObjectVersion &view)
const co::ObjectVersion & getViewVersion () const
void setPixelViewport (const PixelViewport &pvp)
EQFABRIC_INL void setViewport (const Viewport &vp)
const PixelViewport & getNativePixelViewport () const
bool hasFixedViewport () const
EQFABRIC_INL void setNearFar (const float nearPlane, const float farPlane)
Set the near and far planes for this channel.
uint32_t getDrawable () const
EQFABRIC_INL VisitorResult accept (Visitor &visitor)
Perform a depth-first traversal of this channel.
EQFABRIC_INL VisitorResult accept (Visitor &visitor) const
Const-version of accept().
EQFABRIC_INL void setCapabilities (const uint64_t bitmask)
Set the capabilities supported by the channel.
EQFABRIC_INL uint64_t getCapabilities () const
EQFABRIC_INL void setMaxSize (const Vector2i &size)
void setOverdraw (const Vector4i &overdraw)
const Vector2i & getMaxSize () const
EQFABRIC_INL ChannelPath getPath () const
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
uint32_t getDrawBuffer () const
uint32_t getReadBuffer () const
const ColorMask & getDrawBufferMask () const
const PixelViewport & getPixelViewport () const
const Frustumf & getFrustum () const
const Frustumf & getPerspective () const
const Frustumf & getOrtho () const
const Matrix4f & getHeadTransform () const
Return the view matrix.
const Matrix4f & getPerspectiveTransform () const
Return the perspective view matrix.
const Matrix4f & getOrthoTransform () const
Return the orthographic view matrix.
const Viewport & getViewport () const
const Range & getRange () const
const Pixel & getPixel () const
const SubPixel & getSubPixel () const
const Zoom & getZoom () const
uint32_t getPeriod () const
uint32_t getPhase () const
const Vector2i & getPixelOffset () const
Get the channel's current position wrt the destination channel.
Eye getEye () const
const Vector4i & getOverdraw () const
uint32_t getTaskID () const
EQFABRIC_INL int32_t getIAttribute (const IAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual bool isDirty () const
virtual uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
void setError (const int32_t error)
Set an error code why the last operation failed.
eq::fabric::Error getError () const
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Protected Member Functions
virtual ~Channel ()
Destruct the channel.
virtual bool configInit (const eq::uint128_t &initID)
Initialize this channel.
virtual bool configExit ()
Exit this channel.
virtual void frameStart (const eq::uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
virtual void frameDraw (const eq::uint128_t &frameID)
Draw the scene.
virtual void frameAssemble (const eq::uint128_t &frameID)
Assemble all input frames.
virtual void frameReadback (const eq::uint128_t &frameID)
Read back the rendered frame buffer into the output frames.
virtual void frameViewFinish (const eq::uint128_t &frameID)
Finish updating a destination channel.
virtual void frameClear (const eq::uint128_t &frameID)
Clear the frame buffer.
virtual bool useOrtho () const
Select perspective or orthographic rendering.
void clearViewport (const eq::PixelViewport &pvp)
Protected Member Functions inherited from eq::Channel
void attach (const UUID &id, const uint32_t instanceID)
virtual void frameTilesStart (const uint128_t &)
Start a batch of tile rendering operations.
virtual void frameTilesFinish (const uint128_t &)
Finish a batch of tile rendering operations.
virtual void notifyViewportChanged ()
Notification that parameters influencing the vp/pvp have changed.
virtual void notifyStopFrame (const uint32_t lastFrameNumber)
Notify interruption of the rendering.
void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the parent for a frame.
virtual void setupAssemblyState ()
Setup the OpenGL state for a readback or assemble operation.
virtual void resetAssemblyState ()
Reset the OpenGL state after an assembly operation.
virtual void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
virtual void frameViewStart (const uint128_t &frameID)
Start updating a destination channel.
Protected Member Functions inherited from eq::fabric::Channel< Window, Channel >
EQFABRIC_INL Channel (Window *parent)
Construct a new channel.
Channel (const Channel &from)
Construct a copy of a channel (view/segment dest).
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual EQFABRIC_INL void setDirty (const uint64_t bits)
void setDrawable (const uint32_t drawable)
void setIAttribute (const IAttribute attr, const int32_t value)
virtual ChangeType getChangeType () const
virtual uint64_t getRedistributableBits () const
virtual void updateCapabilities ()
void overrideContext (RenderContext &context)
void resetRenderContext ()
const RenderContext & getContext () const
const RenderContext & getNativeContext () const
Protected Member Functions inherited from eq::fabric::Object
Object ()
Construct a new Object.
virtual ~Object ()
Destruct the object.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
void setTasks (const uint32_t tasks)
virtual void notifyDetach ()
void postRemove (Object *child)
virtual void removeChild (const UUID &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
bool _cmdSync (co::ICommand &command)
Additional Inherited Members
Public Types inherited from eq::fabric::Channel< Window, Channel >
enum Drawable
The drawable format defines the components used as an alternate drawable for this channel.
typedef LeafVisitor< Channel > Visitor
The channel visitor type.
typedef Window Parent
The parent window type.
enum IAttribute
Integer attributes for a channel.
Public Types inherited from eq::fabric::Object
enum DirtyBits {
DIRTY_NAME = Serializable::DIRTY_CUSTOM << 0, DIRTY_USERDATA = Serializable::DIRTY_CUSTOM << 1, DIRTY_ERROR = Serializable::DIRTY_CUSTOM << 2, DIRTY_TASKS = Serializable::DIRTY_CUSTOM << 3,
DIRTY_REMOVED = Serializable::DIRTY_CUSTOM << 4, DIRTY_SERIAL = Serializable::DIRTY_CUSTOM << 5, DIRTY_CUSTOM = Serializable::DIRTY_CUSTOM << 6, DIRTY_OBJECT_BITS = DIRTY_NAME | DIRTY_USERDATA | DIRTY_ERROR
}
The changed parts of the object since the last pack().
Static Public Member Functions inherited from eq::fabric::Channel< Window, Channel >
static EQFABRIC_INL const
std::string & getIAttributeString (const IAttribute attr)
Protected Types inherited from eq::fabric::Channel< Window, Channel >
enum DirtyBits
Detailed Description
Definition at line 42 of file share/Equalizer/examples/eVolve/channel.h.
Constructor & Destructor Documentation
virtual eVolve::Channel::~Channel () inline protected virtual
Destruct the channel.
Version
1.0
Reimplemented from eq::Channel.
Definition at line 48 of file share/Equalizer/examples/eVolve/channel.h.
Member Function Documentation
bool eVolve::Channel::configExit () protected virtual
Exit this channel.
Version
1.0
Reimplemented from eq::Channel.
Definition at line 70 of file eVolve/channel.cpp.
References eq::Channel::configExit(), and eq::Frame::getFrameData().
bool eVolve::Channel::configInit (const eq::uint128_t & initID) protected virtual
Initialize this channel.
Parameters
initID the init identifier.
Version
1.0
Reimplemented from eq::Channel.
Definition at line 61 of file eVolve/channel.cpp.
References eq::Channel::configInit(), and eq::fabric::Channel< Window, Channel >::setNearFar().
void eVolve::Channel::frameAssemble (const eq::uint128_t & frameID) protected virtual
Assemble all input frames.
Called 0 to n times during one frame.
Parameters
frameID the per-frame identifier.
See Also
getInputFrames()
Version
1.0
Reimplemented from eq::Channel.
Definition at line 284 of file eVolve/channel.cpp.
References eq::Compositor::assembleFrame(), eq::Compositor::assembleFramesSorted(), eq::Statistic::CHANNEL_FRAME_WAIT_READY, eq::Channel::getDrawableConfig(), eq::Frame::getFrameData(), eq::Frame::getImages(), eq::Channel::getInputFrames(), eq::Channel::getObjectManager(), eq::fabric::Frame::getOffset(), eq::fabric::Channel< Window, Channel >::getPixelViewport(), eq::Frame::getRange(), eq::Channel::getRegions(), eq::fabric::Frame::getZoom(), eq::Frame::readback(), eq::Channel::resetAssemblyState(), eq::fabric::Frame::setOffset(), eq::fabric::Frame::setZoom(), and eq::Frame::waitReady().
void eVolve::Channel::frameClear (const eq::uint128_t & frameID) protected virtual
Clear the frame buffer.
Called 0 to n times during one frame.
Parameters
frameID the per-frame identifier.
Version
1.0
Reimplemented from eq::Channel.
Definition at line 95 of file eVolve/channel.cpp.
References eq::Channel::applyBuffer(), eq::Channel::applyViewport(), and eq::fabric::Channel< Window, Channel >::getRange().
void eVolve::Channel::frameDraw (const eq::uint128_t & frameID) protected virtual
Draw the scene.
Called 0 to n times during one frame.
Parameters
frameID the per-frame identifier.
Version
1.0
Reimplemented from eq::Channel.
Definition at line 146 of file eVolve/channel.cpp.
References eq::Channel::applyBuffer(), eq::Channel::applyFrustum(), eq::Channel::applyHeadTransform(), eq::Channel::applyViewport(), eq::Channel::getPipe(), eq::fabric::Channel< Window, Channel >::getRange(), eq::Channel::getUniqueColor(), and eq::Channel::outlineViewport().
void eVolve::Channel::frameReadback (const eq::uint128_t & frameID) protected virtual
Read back the rendered frame buffer into the output frames.
Called 0 to n times during one frame.
Parameters
frameID the per-frame identifier.
See Also
getOutputFrames()
Version
1.0
Reimplemented from eq::Channel.
Definition at line 385 of file eVolve/channel.cpp.
References eq::fabric::Frame::BUFFER_COLOR, eq::fabric::Frame::BUFFER_DEPTH, eq::Frame::disableBuffer(), eq::Channel::frameReadback(), eq::Frame::getFrameData(), eq::Channel::getOutputFrames(), and eq::Frame::setQuality().
void eVolve::Channel::frameStart (const eq::uint128_t & frameID, const uint32_t frameNumber) protected virtual
Start rendering a frame.
Called once at the beginning of each frame, to do per-frame updates of channel-specific data. This method has to call startFrame().
Parameters
frameID the per-frame identifier.
frameNumber the frame to start.
See Also
Config::startFrame()
Version
1.0
Reimplemented from eq::Channel.
Definition at line 78 of file eVolve/channel.cpp.
References eVolve::BG_COLOR, eVolve::BG_WHITE, eq::Channel::frameStart(), and eq::Channel::getUniqueColor().
void eVolve::Channel::frameViewFinish (const eq::uint128_t & frameID) protected virtual
Finish updating a destination channel.
Called once on each destination channel, e.g., channels which are defined by a view/segment intersection, before frameFinish to update a part of a view.
This is typically used to do operations on the output channel after it has been fully updated, e.g., to draw a 2D overlay.
Parameters
frameID the per-frame identifier.
Version
1.0
Reimplemented from eq::Channel.
Definition at line 401 of file eVolve/channel.cpp.
References eq::Channel::frameViewFinish().
bool eVolve::Channel::useOrtho () const protected virtual
Select perspective or orthographic rendering.
Influences the behaviour of getFrustum, getHeadTransform and the corresponding apply methods in eq::Channel. Intended to be overwritten by the implementation to select orthographic rendering.
Version
1.0
Reimplemented from eq::fabric::Channel< Window, Channel >.
Definition at line 199 of file eVolve/channel.cpp.
The documentation for this class was generated from the following files:
share/Equalizer/examples/eVolve/channel.h
eVolve/channel.cpp