Equalizer: eq::Client Class Reference
eq::Client Class Reference
The client represents a network node of the application in the cluster.
#include <client.h>
Public Member Functions
Client ()
Construct a new client.
virtual ~Client ()
Destruct the client.
bool connectServer (ServerPtr server)
Open and connect an Equalizer server to the local client.
bool disconnectServer (ServerPtr server)
Disconnect and close the connection to an Equalizer server.
virtual bool initLocal (const int argc, char **argv)
Initialize a local, listening node.
virtual bool exitLocal ()
De-initialize a local, listening node.
bool hasCommands ()
virtual co::CommandQueue * getMainThreadQueue ()
const Strings & getActiveLayouts ()
const std::string & getGPUFilter () const
float getModelUnit () const
Public Member Functions inherited from eq::fabric::Client
bool connectServer (co::NodePtr server)
Open and connect an Equalizer server to the local client.
bool disconnectServer (co::NodePtr server)
Disconnect and close the connection to an Equalizer server.
void processCommand (const uint32_t timeout=LB_TIMEOUT_INDEFINITE)
Get and process one pending command from the node command queue.
virtual bool dispatchCommand (co::ICommand &command)
Protected Member Functions
virtual void clientLoop ()
Implements the processing loop for render clients.
virtual void exitClient ()
Exit the process cleanly on render clients.
Detailed Description
The client represents a network node of the application in the cluster.
The methods initLocal() and exitLocal() should be used to set up and exit the listening node instance for each application process.
See Also
fabric::Client for public methods
Definition at line 38 of file client/client.h.
Constructor & Destructor Documentation
eq::Client::Client ()
Construct a new client.
Version
1.0
Reimplemented from eq::fabric::Client.
virtual eq::Client::~Client () virtual
Destruct the client.
Version
1.0
Reimplemented from eq::fabric::Client.
Member Function Documentation
virtual void eq::Client::clientLoop () protected virtual
Implements the processing loop for render clients.
As long as the node is running, that is, between initLocal() and an exit send from the server, this method executes received commands using processCommand() and triggers the message pump between commands.
See Also
Pipe::createMessagePump()
Version
1.0
Reimplemented in eqPly::EqPly, and eVolve::EVolve.
Referenced by eVolve::EVolve::clientLoop().
bool eq::Client::connectServer (ServerPtr server)
Open and connect an Equalizer server to the local client.
The client has to be in the listening state, see initLocal().
Parameters
server the server.
Returns
true if the server was connected, false if not.
Version
1.0
Referenced by osgScaleViewer::OSGScaleViewer::run(), and eqPly::EqPly::run().
bool eq::Client::disconnectServer (ServerPtr server)
Disconnect and close the connection to an Equalizer server.
Parameters
server the server.
Returns
true if the server was disconnected, false if not.
Version
1.0
Referenced by osgScaleViewer::OSGScaleViewer::run(), and eqPly::EqPly::run().
virtual void eq::Client::exitClient () protected virtual
Exit the process cleanly on render clients.
Version
1.0
virtual bool eq::Client::exitLocal () virtual
De-initialize a local, listening node.
Version
1.1.6
virtual co::CommandQueue* eq::Client::getMainThreadQueue () virtual
Returns
the command queue to the main node thread.
Implements eq::fabric::Client.
bool eq::Client::hasCommands ()
Returns
true if the client has commands pending, false otherwise.
Version
1.0
Referenced by eqPly::EqPly::run().
virtual bool eq::Client::initLocal (const int argc, char ** argv) virtual
Initialize a local, listening node.
The –eq-client, –eq-layout and –eq-modelunit command line options are recognized by this method.
–eq-client is used for remote nodes which have been auto-launched by another node, e.g., remote render clients. This method does not return when this command line option is present.
–eq-layout can apply multiple times. Each instance has to be followed by the name of a layout. The given layouts will be activated on all canvases using them during Config::init().
–eq-modelunit is used for scaling the rendered models in all views. The model unit defines the size of the model wrt the virtual room unit which is always in meter. The default unit is 1 (1 meter or EQ_M).
Parameters
argc the command line argument count.
argv the command line argument values.
Returns
true if the client was successfully initialized, false otherwise.
Version
1.0
The documentation for this class was generated from the following file:
client/client.h