Equalizer: eqPly::Pipe Class Reference
eqPly::Pipe Class Reference
The representation of one GPU.
#include <pipe.h>
Public Member Functions
Pipe (eq::Node *parent)
const FrameData & getFrameData () const
Public Member Functions inherited from eq::Pipe
EQ_API Pipe (Node *parent)
Construct a new pipe.
void waitExited () const
void notifyMapped ()
EQ_API void waitFrameFinished (const uint32_t frameNumber) const
EQ_API EventOCommand sendError (const uint32_t error)
Send a pipe error event to the application node.
EQ_API void waitFrameLocal (const uint32_t frameNumber) const
virtual EQ_API bool processEvent (const Event &event)
Process a received event.
void startThread ()
void exitThread ()
void cancelThread ()
bool startTransferThread ()
bool hasTransferThread () const
virtual EQ_API void setDirty (const uint64_t bits)
EQ_API co::CommandQueue * getPipeThreadQueue ()
co::CommandQueue * getMainThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
co::CommandQueue * getTransferThreadQueue ()
EQ_API Config * getConfig ()
EQ_API const Config * getConfig () const
EQ_API ClientPtr getClient ()
EQ_API ServerPtr getServer ()
bool isRunning () const
EQ_API bool isStopped () const
EQ_API uint32_t getCurrentFrame () const
Return the current frame number.
EQ_API uint32_t getFinishedFrame () const
EQ_API WindowSystem getWindowSystem () const
Return the window system used by this pipe.
EQ_API void setSystemPipe (SystemPipe *pipe)
Set the system-specific pipe implementation.
EQ_API SystemPipe * getSystemPipe ()
EQ_API const SystemPipe * getSystemPipe () const
EQ_API void setComputeContext (ComputeContext *ctx)
Set the compute-specific context.
EQ_API const ComputeContext * getComputeContext () const
EQ_API ComputeContext * getComputeContext ()
virtual EQ_API MessagePump * createMessagePump ()
Create a new MessagePump for this pipe.
MessagePump * getMessagePump ()
Frame * getFrame (const co::ObjectVersion &frameVersion, const Eye eye, const bool output)
co::QueueSlave * getQueue (const uint128_t &queueID)
void flushFrames (util::ObjectManager &om)
const View * getView (const co::ObjectVersion &viewVersion) const
View * getView (const co::ObjectVersion &viewVersion)
Public Member Functions inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
Node * getNode ()
const Node * getNode () const
const Windows & getWindows () const
uint32_t getPort () const
Returns the port number of this pipe.
EQFABRIC_INL void setPort (const uint32_t port)
uint32_t getDevice () const
Returns the device number of this pipe.
EQFABRIC_INL void setDevice (const uint32_t device)
const PixelViewport & getPixelViewport () const
EQFABRIC_INL void setPixelViewport (const PixelViewport &pvp)
Set the pipe's pixel viewport.
void notifyPixelViewportChanged ()
EQFABRIC_INL PipePath getPath () const
EQFABRIC_INL VisitorResult accept (PipeVisitor &visitor)
Perform a depth-first traversal of this pipe.
EQFABRIC_INL VisitorResult accept (PipeVisitor &visitor) const
Const-version of accept().
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
void create (eq::Window **window)
void release (eq::Window *window)
virtual void output (std::ostream &) const
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
EQFABRIC_INL void setIAttribute (const IAttribute attr, const int32_t value)
int32_t getIAttribute (const IAttribute attr) const
bool isThreaded () const
Public Member Functions inherited from eq::fabric::Object
virtual EQFABRIC_API bool isDirty () const
virtual EQFABRIC_API void setName (const std::string &name)
Set the name of the object.
EQFABRIC_API const std::string & getName () const
EQFABRIC_API void setUserData (co::Object *userData)
Set user-specific data.
EQFABRIC_API co::Object * getUserData ()
EQFABRIC_API const co::Object * getUserData () const
EQFABRIC_API uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
EQFABRIC_API uint32_t getSerial () const
Protected Member Functions
virtual ~Pipe ()
Destruct the pipe.
virtual eq::WindowSystem selectWindowSystem () const
Choose the window system to be used by this pipe.
virtual bool configInit (const eq::uint128_t &initID)
Initialize this pipe.
virtual bool configExit ()
De-initialize this pipe.
virtual void frameStart (const eq::uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
Protected Member Functions inherited from eq::Pipe
EQ_API void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
EQ_API void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
EQ_API void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the parent for a frame.
virtual EQ_API bool configInitSystemPipe (const uint128_t &initID)
Initialize the OS-specific pipe.
virtual EQ_API void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual EQ_API void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
virtual EQ_API void attach (const uint128_t &id, const uint32_t instanceID)
Protected Member Functions inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
Pipe (Node *parent)
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual EQFABRIC_INL void notifyDetach ()
virtual ChangeType getChangeType () const
eq::Window * _findWindow (const uint128_t &id)
virtual uint64_t getRedistributableBits () const
Protected Member Functions inherited from eq::fabric::Object
EQFABRIC_API Object ()
Construct a new Object.
EQFABRIC_API Object (const Object &)
Construct an unmapped, unregistered copy of an object.
virtual EQFABRIC_API ~Object ()
Destruct the object.
EQFABRIC_API Object & operator= (const Object &from)
NOP assignment operator.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
EQFABRIC_API void setTasks (const uint32_t tasks)
EQFABRIC_API void postRemove (Object *child)
virtual void removeChild (const uint128_t &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
EQFABRIC_API bool _cmdSync (co::ICommand &command)
Additional Inherited Members
Public Types inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
typedef std::vector< eq::Window * > Windows
A vector of pointers to windows.
enum IAttribute
Pipe attributes.
Public Types inherited from eq::fabric::Object
enum DirtyBits {
DIRTY_NAME = Serializable::DIRTY_CUSTOM << 0, DIRTY_USERDATA = Serializable::DIRTY_CUSTOM << 1, DIRTY_TASKS = Serializable::DIRTY_CUSTOM << 2, DIRTY_REMOVED = Serializable::DIRTY_CUSTOM << 3,
DIRTY_SERIAL = Serializable::DIRTY_CUSTOM << 4, DIRTY_CUSTOM = Serializable::DIRTY_CUSTOM << 6, DIRTY_OBJECT_BITS = DIRTY_NAME | DIRTY_USERDATA
}
The changed parts of the object since the last pack().
Static Public Member Functions inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
static EQFABRIC_INL const
std::string & getIAttributeString (const IAttribute attr)
Protected Types inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
enum DirtyBits
Detailed Description
The representation of one GPU.
The pipe object is responsible for maintaining GPU-specific and frame-specific data. The identifier passed by the configuration contains the version of the frame data corresponding to the rendered frame. The pipe's start frame callback synchronizes the thread-local instance of the frame data to this version.
Definition at line 47 of file share/Equalizer/examples/eqPly/pipe.h.
Constructor & Destructor Documentation
virtual eqPly::Pipe::~Pipe () inline protected virtual
Destruct the pipe.
Version
1.0
Reimplemented from eq::Pipe.
Definition at line 55 of file share/Equalizer/examples/eqPly/pipe.h.
Member Function Documentation
bool eqPly::Pipe::configExit () protected virtual
De-initialize this pipe.
Version
1.0
Reimplemented from eq::Pipe.
Definition at line 57 of file eqPly/pipe.cpp.
References eq::Pipe::configExit(), eq::Pipe::getConfig(), and eq::Config::unmapObject().
bool eqPly::Pipe::configInit (const eq::uint128_t & initID) protected virtual
Initialize this pipe.
Parameters
initID the init identifier.
Version
1.0
Reimplemented from eq::Pipe.
Definition at line 45 of file eqPly/pipe.cpp.
References eq::Pipe::configInit(), eq::Pipe::getConfig(), and eq::Config::mapObject().
void eqPly::Pipe::frameStart (const eq::uint128_t & frameID, const uint32_t frameNumber) protected virtual
Start rendering a frame.
Called once at the beginning of each frame, to do per-frame updates of pipe-specific data, for example updating the rendering engine. Waits for the node to start the frame, unless the thread model is async. If the thread model is async, the local synchronization is released immediately.
This method has to call startFrame().
Parameters
frameID the per-frame identifier.
frameNumber the frame to start.
See also
Config::startFrame(), Node::startFrame(), Node::waitFrameStarted()
Version
1.0
Reimplemented from eq::Pipe.
Definition at line 65 of file eqPly/pipe.cpp.
References eq::Pipe::frameStart().
eq::WindowSystem eqPly::Pipe::selectWindowSystem () const protected virtual
Choose the window system to be used by this pipe.
This function determines which of the supported windowing systems is used by this pipe instance.
Returns
the window system currently used by this pipe.
Version
1.0
Reimplemented from eq::Pipe.
Definition at line 39 of file eqPly/pipe.cpp.
References eq::Pipe::getConfig().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqPly/pipe.h
eqPly/pipe.cpp