Equalizer: eq::Pipe Class Reference
eq::Pipe Class Reference
A Pipe represents a graphics card (GPU) on a Node.
#include <pipe.h>
Public Member Functions
EQ_API Pipe (Node *parent)
Construct a new pipe.
virtual EQ_API ~Pipe ()
Destruct the pipe.
void waitExited () const
void notifyMapped ()
EQ_API void waitFrameFinished (const uint32_t frameNumber) const
EQ_API EventOCommand sendError (const uint32_t error)
Send a pipe error event to the application node.
EQ_API void waitFrameLocal (const uint32_t frameNumber) const
virtual EQ_API bool processEvent (const Event &event)
Process a received event.
void startThread ()
void exitThread ()
void cancelThread ()
bool startTransferThread ()
bool hasTransferThread () const
virtual EQ_API void setDirty (const uint64_t bits)
Data Access.
EQ_API co::CommandQueue * getPipeThreadQueue ()
co::CommandQueue * getMainThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
co::CommandQueue * getTransferThreadQueue ()
EQ_API Config * getConfig ()
EQ_API const Config * getConfig () const
EQ_API ClientPtr getClient ()
EQ_API ServerPtr getServer ()
bool isRunning () const
EQ_API bool isStopped () const
EQ_API uint32_t getCurrentFrame () const
Return the current frame number.
EQ_API uint32_t getFinishedFrame () const
EQ_API WindowSystem getWindowSystem () const
Return the window system used by this pipe.
Interface to and from the SystemPipe, the window-system
  specific pieces for a pipe.
EQ_API void setSystemPipe (SystemPipe *pipe)
Set the system-specific pipe implementation.
EQ_API SystemPipe * getSystemPipe ()
EQ_API const SystemPipe * getSystemPipe () const
Interface to and from the ComputeContext
Warning
experimental - may not be supported in the future.
EQ_API void setComputeContext (ComputeContext *ctx)
Set the compute-specific context.
EQ_API const ComputeContext * getComputeContext () const
EQ_API ComputeContext * getComputeContext ()
Configuration.
virtual EQ_API MessagePump * createMessagePump ()
Create a new MessagePump for this pipe.
MessagePump * getMessagePump ()
Public Member Functions inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
Node * getNode ()
const Node * getNode () const
const Windows & getWindows () const
uint32_t getPort () const
Returns the port number of this pipe.
EQFABRIC_INL void setPort (const uint32_t port)
uint32_t getDevice () const
Returns the device number of this pipe.
EQFABRIC_INL void setDevice (const uint32_t device)
const PixelViewport & getPixelViewport () const
EQFABRIC_INL void setPixelViewport (const PixelViewport &pvp)
Set the pipe's pixel viewport.
void notifyPixelViewportChanged ()
EQFABRIC_INL PipePath getPath () const
EQFABRIC_INL VisitorResult accept (PipeVisitor &visitor)
Perform a depth-first traversal of this pipe.
EQFABRIC_INL VisitorResult accept (PipeVisitor &visitor) const
Const-version of accept().
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
void create (eq::Window **window)
void release (eq::Window *window)
virtual void output (std::ostream &) const
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
EQFABRIC_INL void setIAttribute (const IAttribute attr, const int32_t value)
int32_t getIAttribute (const IAttribute attr) const
bool isThreaded () const
Public Member Functions inherited from eq::fabric::Object
virtual EQFABRIC_API bool isDirty () const
virtual EQFABRIC_API void setName (const std::string &name)
Set the name of the object.
EQFABRIC_API const std::string & getName () const
EQFABRIC_API void setUserData (co::Object *userData)
Set user-specific data.
EQFABRIC_API co::Object * getUserData ()
EQFABRIC_API const co::Object * getUserData () const
EQFABRIC_API uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
EQFABRIC_API uint32_t getSerial () const
Operations
Frame * getFrame (const co::ObjectVersion &frameVersion, const Eye eye, const bool output)
co::QueueSlave * getQueue (const uint128_t &queueID)
void flushFrames (util::ObjectManager &om)
const View * getView (const co::ObjectVersion &viewVersion) const
View * getView (const co::ObjectVersion &viewVersion)
EQ_API void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
EQ_API void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
EQ_API void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the parent for a frame.
Callbacks
The callbacks are called by Equalizer during rendering to execute various actions.
class detail::RenderThread
class detail::ThreadAffinityVisitor
virtual EQ_API WindowSystem selectWindowSystem () const
Choose the window system to be used by this pipe.
virtual EQ_API bool configInit (const uint128_t &initID)
Initialize this pipe.
virtual EQ_API bool configInitSystemPipe (const uint128_t &initID)
Initialize the OS-specific pipe.
virtual EQ_API bool configExit ()
De-initialize this pipe.
virtual EQ_API void frameStart (const uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
virtual EQ_API void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual EQ_API void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
virtual EQ_API void attach (const uint128_t &id, const uint32_t instanceID)
Additional Inherited Members
Public Types inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
typedef std::vector< eq::Window * > Windows
A vector of pointers to windows.
enum IAttribute
Pipe attributes.
Public Types inherited from eq::fabric::Object
enum DirtyBits {
DIRTY_NAME = Serializable::DIRTY_CUSTOM << 0, DIRTY_USERDATA = Serializable::DIRTY_CUSTOM << 1, DIRTY_TASKS = Serializable::DIRTY_CUSTOM << 2, DIRTY_REMOVED = Serializable::DIRTY_CUSTOM << 3,
DIRTY_SERIAL = Serializable::DIRTY_CUSTOM << 4, DIRTY_CUSTOM = Serializable::DIRTY_CUSTOM << 6, DIRTY_OBJECT_BITS = DIRTY_NAME | DIRTY_USERDATA
}
The changed parts of the object since the last pack().
Static Public Member Functions inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
static EQFABRIC_INL const
std::string & getIAttributeString (const IAttribute attr)
Protected Types inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
enum DirtyBits
Protected Member Functions inherited from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >
Pipe (Node *parent)
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual EQFABRIC_INL void notifyDetach ()
virtual ChangeType getChangeType () const
eq::Window * _findWindow (const uint128_t &id)
virtual uint64_t getRedistributableBits () const
Protected Member Functions inherited from eq::fabric::Object
EQFABRIC_API Object ()
Construct a new Object.
EQFABRIC_API Object (const Object &)
Construct an unmapped, unregistered copy of an object.
virtual EQFABRIC_API ~Object ()
Destruct the object.
EQFABRIC_API Object & operator= (const Object &from)
NOP assignment operator.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
EQFABRIC_API void setTasks (const uint32_t tasks)
EQFABRIC_API void postRemove (Object *child)
virtual void removeChild (const uint128_t &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
EQFABRIC_API bool _cmdSync (co::ICommand &command)
Detailed Description
A Pipe represents a graphics card (GPU) on a Node.
All Pipe, Window and Channel task methods are executed in a separate co::Worker thread, in parallel with all other pipes in the system. An exception are non-threaded pipes, which execute their tasks on the Node's main thread.
See also
fabric::Pipe
Definition at line 50 of file include/eq/client/pipe.h.
Constructor & Destructor Documentation
EQ_API eq::Pipe::Pipe (Node * parent)
Construct a new pipe.
Version
1.0
virtual EQ_API eq::Pipe::~Pipe () virtual
Destruct the pipe.
Version
1.0
Reimplemented from eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >.
Reimplemented in eqPly::Pipe, and eVolve::Pipe.
Member Function Documentation
virtual EQ_API bool eq::Pipe::configExit () protected virtual
De-initialize this pipe.
Version
1.0
Reimplemented in eqAsync::Pipe, eqPly::Pipe, and eVolve::Pipe.
Referenced by eVolve::Pipe::configExit(), eqPly::Pipe::configExit(), and eqAsync::Pipe::configExit().
virtual EQ_API bool eq::Pipe::configInit (const uint128_t & initID) protected virtual
Initialize this pipe.
Parameters
initID the init identifier.
Version
1.0
Reimplemented in eqPly::Pipe, and eVolve::Pipe.
Referenced by eVolve::Pipe::configInit(), and eqPly::Pipe::configInit().
virtual EQ_API bool eq::Pipe::configInitSystemPipe (const uint128_t & initID) protected virtual
Initialize the OS-specific pipe.
See also
setSystemPipe()
Version
1.0
virtual EQ_API MessagePump* eq::Pipe::createMessagePump () virtual
Create a new MessagePump for this pipe.
At most one message pump per execution thread is created. Each pipe render thread creates one message pump for its window system. The process main thread creates a message pump for AGL pipes and non-threaded pipes. Applications which do their own message pumping outside of Equalizer should return 0 here.
Returns
the message pump, or 0.
Version
1.0
virtual EQ_API void eq::Pipe::frameDrawFinish (const uint128_t & frameID, const uint32_t frameNumber) protected virtual
Finish drawing.
Called once per frame after the last draw operation. Releases the local synchronization if the thread model is draw_sync (the default).
Parameters
frameID the per-frame identifier.
frameNumber the frame to finished with draw.
Version
1.0
virtual EQ_API void eq::Pipe::frameFinish (const uint128_t & frameID, const uint32_t frameNumber) protected virtual
Finish rendering a frame.
Called once at the end of each frame, to do per-frame updates of pipe-specific data, for example updating the rendering engine. Releases the local synchronization if the thread model is local_sync. Always releases the global synchronization for this pipe.
This method has to call releaseFrame().
Parameters
frameID the per-frame identifier.
frameNumber the frame to finish.
Version
1.0
virtual EQ_API void eq::Pipe::frameStart (const uint128_t & frameID, const uint32_t frameNumber) protected virtual
Start rendering a frame.
Called once at the beginning of each frame, to do per-frame updates of pipe-specific data, for example updating the rendering engine. Waits for the node to start the frame, unless the thread model is async. If the thread model is async, the local synchronization is released immediately.
This method has to call startFrame().
Parameters
frameID the per-frame identifier.
frameNumber the frame to start.
See also
Config::startFrame(), Node::startFrame(), Node::waitFrameStarted()
Version
1.0
Reimplemented in eqAsync::Pipe, eqPly::Pipe, and eVolve::Pipe.
Referenced by eVolve::Pipe::frameStart(), eqPly::Pipe::frameStart(), and eqAsync::Pipe::frameStart().
EQ_API ClientPtr eq::Pipe::getClient ()
Returns
the parent client node.
Version
1.0
EQ_API const ComputeContext* eq::Pipe::getComputeContext () const
Returns
the compute context.
EQ_API ComputeContext* eq::Pipe::getComputeContext ()
Returns
the compute context.
EQ_API Config* eq::Pipe::getConfig ()
Returns
the parent configuration.
Version
1.0
Referenced by eVolve::Pipe::configExit(), eqPly::Pipe::configExit(), eVolve::Pipe::configInit(), eqPly::Pipe::configInit(), eVolve::Pipe::selectWindowSystem(), and eqPly::Pipe::selectWindowSystem().
EQ_API const Config* eq::Pipe::getConfig () const
Returns
the parent configuration.
Version
1.0
EQ_API uint32_t eq::Pipe::getCurrentFrame () const
Return the current frame number.
To be called only from the pipe thread. Updated by startFrame().
Returns
the current frame number.
Version
1.0
MessagePump* eq::Pipe::getMessagePump ()
Returns
the pipe's message pump, or 0.
Version
1.0
EQ_API ServerPtr eq::Pipe::getServer ()
Returns
the parent server node.
Version
1.0
EQ_API SystemPipe* eq::Pipe::getSystemPipe ()
Returns
the OS-specific pipe implementation.
Version
1.0
EQ_API const SystemPipe* eq::Pipe::getSystemPipe () const
Returns
the OS-specific pipe implementation.
Version
1.0
EQ_API WindowSystem eq::Pipe::getWindowSystem () const
Return the window system used by this pipe.
The return value is quaranteed to be constant for an initialized pipe, that is, the window system is determined using selectWindowSystem() before configInit() is executed.
Returns
the window system used by this pipe.
Version
1.0
bool eq::Pipe::isRunning () const
Returns
true if this pipe is running, false otherwise.
Version
1.0
EQ_API bool eq::Pipe::isStopped () const
Returns
true if this pipe is stopped, false otherwise.
Version
1.0
virtual EQ_API bool eq::Pipe::processEvent (const Event & event) virtual
Process a received event.
The task of this method is to update the node as necessary, and transform the event into a config event to be send to the application using Config::sendEvent().
Parameters
event the received event.
Returns
true when the event was handled, false if not.
Version
1.5.2
EQ_API void eq::Pipe::releaseFrame (const uint32_t frameNumber) protected
Signal the completion of a frame to the parent.
Parameters
frameNumber the frame to end.
Version
1.0
EQ_API void eq::Pipe::releaseFrameLocal (const uint32_t frameNumber) protected
Release the local synchronization of the parent for a frame.
Parameters
frameNumber the frame to release.
Version
1.0
virtual EQ_API WindowSystem eq::Pipe::selectWindowSystem () const protected virtual
Choose the window system to be used by this pipe.
This function determines which of the supported windowing systems is used by this pipe instance.
Returns
the window system currently used by this pipe.
Version
1.0
Reimplemented in eqPly::Pipe, and eVolve::Pipe.
EQ_API EventOCommand eq::Pipe::sendError (const uint32_t error)
Send a pipe error event to the application node.
Parameters
error the error code.
Version
1.7.1
Referenced by eVolve::Pipe::configInit().
EQ_API void eq::Pipe::setComputeContext (ComputeContext * ctx)
Set the compute-specific context.
EQ_API void eq::Pipe::setSystemPipe (SystemPipe * pipe)
Set the system-specific pipe implementation.
The system-specific pipe implements the window-system-dependent part. The os-specific pipe has to be initialized.
Version
1.0
EQ_API void eq::Pipe::startFrame (const uint32_t frameNumber) protected
Start a frame by unlocking all child resources.
Parameters
frameNumber the frame to start.
Version
1.0
The documentation for this class was generated from the following file:
include/eq/client/pipe.h