Equalizer: eqPly::EqPly Class Reference
eqPly::EqPly Class Reference
The EqPly application instance.
#include <eqPly.h>
Public Member Functions
EqPly (const LocalInitData &initData)
int run ()
Run an eqPly instance.
Public Member Functions inherited from eq::Client
EQ_API Client ()
Construct a new client.
EQ_API bool connectServer (ServerPtr server)
Open and connect an Equalizer server to the local client.
EQ_API bool disconnectServer (ServerPtr server)
Disconnect and close the connection to an Equalizer server.
virtual EQ_API bool initLocal (const int argc, char **argv)
Initialize a local, listening node.
virtual EQ_API bool exitLocal ()
De-initialize a local, listening node.
EQ_API bool hasCommands ()
virtual EQ_API co::CommandQueue * getMainThreadQueue ()
const Strings & getActiveLayouts ()
const std::string & getGPUFilter () const
float getModelUnit () const
void interruptMainThread ()
Experimental: interrupt main thread queue.
Public Member Functions inherited from eq::fabric::Client
EQFABRIC_API bool connectServer (co::NodePtr server)
Open and connect an Equalizer server to the local client.
EQFABRIC_API bool disconnectServer (co::NodePtr server)
Disconnect and close the connection to an Equalizer server.
EQFABRIC_API void processCommand (const uint32_t timeout=LB_TIMEOUT_INDEFINITE)
Get and process one pending command from the node command queue.
virtual EQFABRIC_API bool dispatchCommand (co::ICommand &command)
Static Public Member Functions
static const std::string & getHelp ()
Protected Member Functions
virtual void clientLoop ()
Protected Member Functions inherited from eq::Client
virtual EQ_API ~Client ()
Destruct the client.
virtual EQ_API void exitClient ()
Exit the process cleanly on render clients.
Protected Member Functions inherited from eq::fabric::Client
EQFABRIC_API Client ()
Construct a new client.
Detailed Description
The EqPly application instance.
Definition at line 46 of file eqPly.h.
Member Function Documentation
void eqPly::EqPly::clientLoop () protected virtual
See also
eq::Client::clientLoop.
Reimplemented from eq::Client.
Definition at line 173 of file eqPly.cpp.
References eq::Client::clientLoop().
const std::string & eqPly::EqPly::getHelp () static
Returns
a string containing an online help description.
Definition at line 74 of file eqPly.cpp.
int eqPly::EqPly::run ()
Run an eqPly instance.
Definition at line 83 of file eqPly.cpp.
References eq::Client::connectServer(), eq::Client::disconnectServer(), eqPly::Config::exit(), eq::Config::finishAllFrames(), eq::Config::finishFrame(), eqPly::Config::getAnimationFrame(), eq::Config::getFinishedFrame(), eq::Config::getNextEvent(), eqPly::Config::handleEvent(), eq::Config::handleEvents(), eq::Client::hasCommands(), eqPly::Config::init(), eq::Config::isRunning(), eqPly::Config::needRedraw(), eq::fabric::Client::processCommand(), and eqPly::Config::startFrame().
The documentation for this class was generated from the following files:
eqPly.h
eqPly.cpp