Equalizer: eq::fabric::Global Class Reference
eq::fabric::Global Class Reference
Global parameter handling for the Equalizer fabric namespace.
#include <global.h>
Static Public Member Functions
static EQFABRIC_API void setServer (const std::string &server)
Set the default Equalizer server.
static EQFABRIC_API const
std::string & getServer ()
static EQFABRIC_API ErrorRegistry & getErrorRegistry ()
static EQFABRIC_API void setFlags (const uint32_t flags)
static EQFABRIC_API uint32_t getFlags ()
static EQFABRIC_API void setPrefixes (const Strings &prefixes)
static EQFABRIC_API const Strings & getPrefixes ()
Detailed Description
Global parameter handling for the Equalizer fabric namespace.
Definition at line 30 of file fabric/global.h.
Member Function Documentation
static EQFABRIC_API ErrorRegistry& eq::fabric::Global::getErrorRegistry () static
Returns
the error registry.
Version
1.5
Referenced by eqPly::exitErrors(), eVolve::exitErrors(), eqPly::initErrors(), and eVolve::initErrors().
static EQFABRIC_API const std::string& eq::fabric::Global::getServer () static
Returns
the default Equalizer server.
static EQFABRIC_API void eq::fabric::Global::setServer (const std::string & server) static
Set the default Equalizer server.
Parameters
server the default server.
The documentation for this class was generated from the following file:
fabric/global.h