Equalizer: eVolve::Config Class Reference
eVolve::Config Class Reference
Public Member Functions
Config (eq::ServerPtr parent)
virtual bool init ()
virtual bool exit ()
virtual uint32_t startFrame ()
void setInitData (const LocalInitData &data)
const InitData & getInitData () const
bool loadInitData (const eq::uint128_t &initDataID)
Map per-config data to the local node process.
Public Member Functions inherited from eq::Config
EQ_API Config (ServerPtr parent)
Construct a new config.
void setupMessagePump (Pipe *pipe)
void setupServerConnections (const std::string &connectionData)
EQ_API ClientPtr getClient ()
EQ_API ConstClientPtr getClient () const
EQ_API co::NodePtr getApplicationNode ()
EQ_API co::CommandQueue * getMainThreadQueue ()
EQ_API co::CommandQueue * getCommandThreadQueue ()
EQ_API uint32_t getCurrentFrame () const
EQ_API uint32_t getFinishedFrame () const
EQ_API GLStats::Data getStatistics () const
EQ_API bool isRunning () const
EQ_API void stopRunning ()
Stop the config.
EQ_API int64_t getTime () const
Get the current time in milliseconds.
MessagePump * getMessagePump ()
const Channel * findChannel (const std::string &name) const
virtual EQ_API bool init (const uint128_t &initID)
Initialize this configuration.
EQ_API bool update ()
Update the configuration.
virtual EQ_API void setLatency (const uint32_t latency)
virtual EQ_API bool registerObject (co::Object *object)
Register a distributed object.
virtual EQ_API void deregisterObject (co::Object *object)
Deregister a distributed object.
virtual EQ_API bool mapObject (co::Object *object, const uint128_t &id, const uint128_t &version=co::VERSION_OLDEST)
Map a distributed object.
virtual EQ_API uint32_t mapObjectNB (co::Object *object, const uint128_t &id, const uint128_t &version=co::VERSION_OLDEST)
Start mapping a distributed object.
virtual EQ_API uint32_t mapObjectNB (co::Object *object, const uint128_t &id, const uint128_t &version, co::NodePtr master)
Start mapping a distributed object from a known master.
virtual EQ_API bool mapObjectSync (const uint32_t requestID)
Finalize the mapping of a distributed object.
virtual EQ_API void unmapObject (co::Object *object)
Unmap a mapped object.
EQ_API f_bool_t syncObject (co::Object *object, co::NodePtr master, const uint128_t &id, const uint32_t instanceID=CO_INSTANCE_ALL) override
Synchronize the local object with a remote object.
virtual EQ_API uint32_t startFrame (const uint128_t &frameID)
Request a new frame of rendering.
virtual EQ_API uint32_t finishFrame ()
Finish the rendering of a frame.
virtual EQ_API uint32_t finishAllFrames ()
Finish rendering all pending frames.
EQ_API void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the config for a frame.
EQ_API void stopFrames ()
Asynchronously signal all channels to interrupt their rendering.
EQ_API const ConfigEvent * nextEvent ()
Get the next event.
EQ_API const ConfigEvent * tryNextEvent ()
Try to get the next event.
EQ_API void sendEvent (ConfigEvent &event)
Send an (old) event to the application node.
EQ_API EventOCommand sendEvent (const uint32_t type)
Send an event to the application node.
EQ_API EventOCommand sendError (const uint32_t type, const Error &error)
Send an error event to the application node.
EQ_API Errors getErrors ()
EQ_API EventICommand getNextEvent (const uint32_t timeout=LB_TIMEOUT_INDEFINITE) const
Get the next event.
virtual EQ_API bool handleEvent (EventICommand command)
Handle one config event.
EQ_API bool checkEvent () const
virtual EQ_API void handleEvents ()
Handle all config events.
void addStatistic (const uint32_t originator, const Statistic &stat)
Add an statistic event to the statistics overlay.
Public Member Functions inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
virtual void output (std::ostream &) const
void create (Observer **observer)
void create (Layout **layout)
void create (Canvas **canvas)
void create (Node **node)
void release (Observer *observer)
void release (Layout *layout)
void release (Canvas *canvas)
void release (Node *node)
EQFABRIC_INL lunchbox::RefPtr
< Server > getServer ()
EQFABRIC_INL lunchbox::RefPtr
< const Server > getServer () const
const Observers & getObservers () const
const Layouts & getLayouts () const
const Canvases & getCanvases () const
EQFABRIC_INL uint32_t getTimeout () const
const Nodes & getNodes () const
EQFABRIC_INL Node * findAppNode ()
EQFABRIC_INL const Node * findAppNode () const
EQFABRIC_INL VisitorResult accept (ConfigVisitor &visitor)
Perform a depth-first traversal of this config.
EQFABRIC_INL VisitorResult accept (ConfigVisitor &visitor) const
Const-version of accept().
EQFABRIC_INL T * find (const uint128_t &id)
EQFABRIC_INL const T * find (const uint128_t &id) const
EQFABRIC_INL T * find (const std::string &name)
EQFABRIC_INL const T * find (const std::string &name) const
void find (const uint128_t &id, T **result)
void find (const std::string &name, const T **result) const
Observer * getObserver (const ObserverPath &path)
Layout * getLayout (const LayoutPath &path)
Canvas * getCanvas (const CanvasPath &path)
virtual void updateCanvas (Canvas *)
virtual void exitCanvas (Canvas *)
uint32_t getLatency () const
virtual EQFABRIC_INL void restore ()
void setFAttribute (const FAttribute attr, const float value)
void setIAttribute (const IAttribute attr, const int32_t value)
float getFAttribute (const FAttribute attr) const
int32_t getIAttribute (const IAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual EQFABRIC_API bool isDirty () const
virtual EQFABRIC_API void backup ()
virtual EQFABRIC_API void setName (const std::string &name)
Set the name of the object.
EQFABRIC_API const std::string & getName () const
EQFABRIC_API void setUserData (co::Object *userData)
Set user-specific data.
EQFABRIC_API co::Object * getUserData ()
EQFABRIC_API const co::Object * getUserData () const
EQFABRIC_API uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
EQFABRIC_API uint32_t getSerial () const
Protected Member Functions
virtual ~Config ()
Destruct a config.
virtual bool handleEvent (const eq::ConfigEvent *event)
Protected Member Functions inherited from eq::Config
virtual EQ_API void attach (const uint128_t &id, const uint32_t instanceID)
virtual EQ_API void notifyAttached ()
virtual EQ_API void notifyDetach ()
virtual EQ_API void changeLatency (const uint32_t latency)
virtual EQ_API bool mapViewObjects () const
Protected Member Functions inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
EQFABRIC_INL Config (lunchbox::RefPtr< Server > parent)
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual void _removeChild (const uint128_t &)
void setAppNodeID (const co::NodeID &nodeID)
const co::NodeID & getAppNodeID () const
EQFABRIC_INL EventOCommand sendError (co::NodePtr node, const uint32_t event, const Error &error)
virtual bool mapNodeObjects () const
virtual VisitorResult _acceptCompounds (ConfigVisitor &)
virtual VisitorResult _acceptCompounds (ConfigVisitor &) const
Node * _findNode (const uint128_t &id)
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Protected Member Functions inherited from eq::fabric::Object
EQFABRIC_API Object ()
Construct a new Object.
EQFABRIC_API Object (const Object &)
Construct an unmapped, unregistered copy of an object.
virtual EQFABRIC_API ~Object ()
Destruct the object.
EQFABRIC_API Object & operator= (const Object &from)
NOP assignment operator.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
EQFABRIC_API void setTasks (const uint32_t tasks)
EQFABRIC_API void postRemove (Object *child)
virtual void removeChild (const uint128_t &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
EQFABRIC_API bool _cmdSync (co::ICommand &command)
Protected Attributes
int _spinX
int _spinY
eq::Canvas * _currentCanvas
LocalInitData _initData
FrameData _frameData
uint64_t _messageTime
Additional Inherited Members
Public Types inherited from eq::Config
typedef fabric::Config< Server,
Config, Observer, Layout,
Canvas, Node, ConfigVisitor > Super
base class
Public Types inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
typedef std::vector< Observer * > Observers
A vector of observers.
typedef std::vector< Layout * > Layouts
A vector of layouts.
typedef std::vector< Canvas * > Canvases
A vector of canvases.
typedef std::vector< Node * > Nodes
A vector of nodes.
enum FAttribute
Floating-point attributes.
enum IAttribute
Integer attributes.
Public Types inherited from eq::fabric::Object
enum DirtyBits {
DIRTY_NAME = Serializable::DIRTY_CUSTOM << 0, DIRTY_USERDATA = Serializable::DIRTY_CUSTOM << 1, DIRTY_TASKS = Serializable::DIRTY_CUSTOM << 2, DIRTY_REMOVED = Serializable::DIRTY_CUSTOM << 3,
DIRTY_SERIAL = Serializable::DIRTY_CUSTOM << 4, DIRTY_CUSTOM = Serializable::DIRTY_CUSTOM << 6, DIRTY_OBJECT_BITS = DIRTY_NAME | DIRTY_USERDATA
}
The changed parts of the object since the last pack().
Static Public Member Functions inherited from eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >
static const std::string & getFAttributeString (const FAttribute attr)
static const std::string & getIAttributeString (const IAttribute attr)
Detailed Description
Definition at line 40 of file share/Equalizer/examples/eVolve/config.h.
Constructor & Destructor Documentation
eVolve::Config::~Config () protected virtual
Destruct a config.
Version
1.0
Reimplemented from eq::Config.
Definition at line 44 of file eVolve/config.cpp.
Member Function Documentation
bool eVolve::Config::exit () virtual
See also
eq::Config::exit.
Reimplemented from eq::Config.
Definition at line 82 of file eVolve/config.cpp.
References eq::Config::exit().
Referenced by eVolve::EVolve::run().
bool eVolve::Config::handleEvent (const eq::ConfigEvent * event) protected virtual
See also
eq::Config::handleEvent
Reimplemented from eq::Config.
Definition at line 120 of file eVolve/config.cpp.
References eq::ConfigEvent::data, eq::fabric::Canvas< CFG, C, S, L >::getActiveLayout(), eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >::getCanvases(), eq::fabric::View< class, class, class >::getLayout(), and eq::Config::handleEvent().
bool eVolve::Config::init () virtual
See also
eq::Config::init.
Definition at line 46 of file eVolve/config.cpp.
References eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >::getCanvases(), eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >::getLatency(), eq::Config::init(), and eq::Config::registerObject().
Referenced by eVolve::EVolve::run().
uint32_t eVolve::Config::startFrame () virtual
See also
eq::Config::startFrame.
Definition at line 99 of file eVolve/config.cpp.
References eq::Config::startFrame().
Referenced by eVolve::EVolve::run().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eVolve/config.h
eVolve/config.cpp