Equalizer: eqPixelBench::Channel Class Reference
eqPixelBench::Channel Class Reference
Public Member Functions
Channel (eq::Window *parent)
virtual ~Channel ()
Destruct the channel.
Public Member Functions inherited from eq::Channel
EQ_API Channel (Window *parent)
Construct a new channel.
virtual EQ_API void drawStatistics ()
Draw a statistics overlay.
virtual EQ_API void outlineViewport ()
Outline the current pixel viewport.
void changeLatency (const uint32_t latency)
EQ_API co::CommandQueue * getPipeThreadQueue ()
EQ_API co::CommandQueue * getCommandThreadQueue ()
EQ_API uint32_t getCurrentFrame () const
void waitFrameFinished (const uint32_t frame) const
EQ_API bool isStopped () const
EQ_API Pipe * getPipe ()
EQ_API const Pipe * getPipe () const
EQ_API Node * getNode ()
EQ_API const Node * getNode () const
EQ_API Config * getConfig ()
EQ_API const Config * getConfig () const
EQ_API ServerPtr getServer ()
EQ_API const GLEWContext * glewGetContext () const
Get the GLEW context for this channel.
EQ_API util::ObjectManager & getObjectManager ()
EQ_API const DrawableConfig & getDrawableConfig () const
EQ_API View * getNativeView ()
Get the channel's native view.
EQ_API const View * getNativeView () const
const-version of getNativeView()
EQ_API util::FrameBufferObject * getFrameBufferObject ()
EQ_API const Vector3ub & getUniqueColor () const
EQ_API void addStatistic (Event &event)
virtual EQ_API Vector2f getJitter () const
EQ_API View * getView ()
Get the channel's current View.
EQ_API const View * getView () const
Const version of getView().
EQ_API Frustumf getScreenFrustum () const
Returns an orthographic frustum for 2D operations on the view.
virtual EQ_API void applyBuffer ()
Apply the current rendering buffer, including the color mask.
virtual EQ_API void applyColorMask () const
Apply the current color mask.
virtual EQ_API void applyViewport () const
Apply the OpenGL viewport for the current rendering task.
virtual EQ_API void applyFrustum () const
Apply the frustum matrix for the current rendering task.
virtual EQ_API void applyPerspective () const
Apply the perspective frustum matrix for the current rendering task.
virtual EQ_API void applyOrtho () const
Apply the orthographic frustum matrix for the current rendering task.
EQ_API void applyScreenFrustum () const
Apply an orthographic frustum for pixel-based 2D operations.
virtual EQ_API void applyHeadTransform () const
Apply the transformation to position the view frustum.
virtual EQ_API void applyPerspectiveTransform () const
Apply the transformation to position the perspective view frustum.
virtual EQ_API void applyOrthoTransform () const
Apply the transformation to position the orthographic view frustum.
virtual EQ_API void applyFrameBufferObject ()
Apply the current alternate frame buffer.
EQ_API void bindFrameBuffer ()
Rebind the current alternate FBO of the channel or window.
virtual EQ_API void resetRegions ()
Reset the declared regions of interest.
virtual EQ_API void declareRegion (const eq::PixelViewport &region)
Declare a region covered by the current draw or assemble operation.
EQ_API void declareRegion (const eq::Viewport &vp)
Convenience method to declare a region in relative coordinates.
EQ_API PixelViewport getRegion () const
EQ_API const PixelViewports & getRegions () const
Get the current regions of interest.
EQ_API EventOCommand sendError (const uint32_t error)
Send a channel error event to the application node.
virtual EQ_API bool processEvent (const Event &event)
Process a received event.
Public Member Functions inherited from eq::fabric::Channel< Window, Channel >
virtual bool omitOutput () const
virtual void output (std::ostream &) const
void init ()
Window * getWindow ()
const Window * getWindow () const
bool isDestination () const
void setViewVersion (const co::ObjectVersion &view)
const co::ObjectVersion & getViewVersion () const
void setPixelViewport (const PixelViewport &pvp)
EQFABRIC_INL void setViewport (const Viewport &vp)
const PixelViewport & getNativePixelViewport () const
bool hasFixedViewport () const
EQFABRIC_INL void setNearFar (const float nearPlane, const float farPlane)
Set the near and far planes for this channel.
uint32_t getDrawable () const
EQFABRIC_INL VisitorResult accept (Visitor &visitor)
Perform a depth-first traversal of this channel.
EQFABRIC_INL VisitorResult accept (Visitor &visitor) const
Const-version of accept().
EQFABRIC_INL void setCapabilities (const uint64_t bitmask)
Set the capabilities supported by the channel.
EQFABRIC_INL uint64_t getCapabilities () const
EQFABRIC_INL void setMaxSize (const Vector2i &size)
void setOverdraw (const Vector4i &overdraw)
const Vector2i & getMaxSize () const
EQFABRIC_INL ChannelPath getPath () const
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
uint32_t getDrawBuffer () const
uint32_t getReadBuffer () const
const ColorMask & getDrawBufferMask () const
const PixelViewport & getPixelViewport () const
virtual bool useOrtho () const
Select perspective or orthographic rendering.
const Frustumf & getFrustum () const
const Frustumf & getPerspective () const
const Frustumf & getOrtho () const
const Matrix4f & getHeadTransform () const
Return the view matrix.
const Matrix4f & getPerspectiveTransform () const
Return the perspective view matrix.
const Matrix4f & getOrthoTransform () const
Return the orthographic view matrix.
const Viewport & getViewport () const
const Range & getRange () const
const Pixel & getPixel () const
const SubPixel & getSubPixel () const
const Zoom & getZoom () const
uint32_t getPeriod () const
uint32_t getPhase () const
const Vector2i & getPixelOffset () const
Get the channel's current position wrt the destination channel.
Eye getEye () const
const Vector4i & getOverdraw () const
uint32_t getTaskID () const
EQFABRIC_INL int32_t getIAttribute (const IAttribute attr) const
EQFABRIC_INL const std::string & getSAttribute (const SAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual EQFABRIC_API bool isDirty () const
virtual EQFABRIC_API uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
virtual EQFABRIC_API void setName (const std::string &name)
Set the name of the object.
EQFABRIC_API const std::string & getName () const
EQFABRIC_API void setUserData (co::Object *userData)
Set user-specific data.
EQFABRIC_API co::Object * getUserData ()
EQFABRIC_API const co::Object * getUserData () const
EQFABRIC_API uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
EQFABRIC_API uint32_t getSerial () const
Protected Member Functions
virtual void frameStart (const eq::uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
virtual void frameDraw (const eq::uint128_t &frameID)
Draw the scene.
virtual bool configExit ()
Exit this channel.
Protected Member Functions inherited from eq::Channel
EQ_API void attach (const uint128_t &id, const uint32_t instanceID)
virtual void frameTilesStart (const uint128_t &)
Start a batch of tile rendering operations.
virtual void frameTilesFinish (const uint128_t &)
Finish a batch of tile rendering operations.
virtual EQ_API void notifyViewportChanged ()
Notification that parameters influencing the vp/pvp have changed.
virtual EQ_API void notifyStopFrame (const uint32_t lastFrameNumber)
Notify interruption of the rendering.
EQ_API void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
EQ_API void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
EQ_API void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the parent for a frame.
virtual EQ_API void setupAssemblyState ()
Setup the OpenGL state for a readback or assemble operation.
virtual EQ_API void resetAssemblyState ()
Reset the OpenGL state after an assembly operation.
virtual EQ_API bool configInit (const uint128_t &initID)
Initialize this channel.
virtual EQ_API void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual EQ_API void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
virtual EQ_API void frameClear (const uint128_t &frameID)
Clear the frame buffer.
virtual EQ_API void frameAssemble (const uint128_t &frameID, const Frames &frames)
Assemble all input frames.
virtual EQ_API void frameReadback (const uint128_t &frameID, const Frames &frames)
Read back the rendered frame buffer into the output frames.
virtual EQ_API void frameViewStart (const uint128_t &frameID)
Start updating a destination channel.
virtual EQ_API void frameViewFinish (const uint128_t &frameID)
Finish updating a destination channel.
Protected Member Functions inherited from eq::fabric::Channel< Window, Channel >
EQFABRIC_INL Channel (Window *parent)
Construct a new channel.
Channel (const Channel &from)
Construct a copy of a channel (view/segment dest).
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual EQFABRIC_INL void setDirty (const uint64_t bits)
void setDrawable (const uint32_t drawable)
void setIAttribute (const IAttribute attr, const int32_t value)
void setSAttribute (const SAttribute attr, const std::string &value)
virtual ChangeType getChangeType () const
virtual uint64_t getRedistributableBits () const
virtual void updateCapabilities ()
void overrideContext (RenderContext &context)
void resetContext ()
const RenderContext & getContext () const
const RenderContext & getNativeContext () const
Protected Member Functions inherited from eq::fabric::Object
EQFABRIC_API Object ()
Construct a new Object.
EQFABRIC_API Object (const Object &)
Construct an unmapped, unregistered copy of an object.
virtual EQFABRIC_API ~Object ()
Destruct the object.
EQFABRIC_API Object & operator= (const Object &from)
NOP assignment operator.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
EQFABRIC_API void setTasks (const uint32_t tasks)
virtual EQFABRIC_API void notifyDetach ()
EQFABRIC_API void postRemove (Object *child)
virtual void removeChild (const uint128_t &)
template<class C , class S >
void commitChild (C *child, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class S >
void commitChildren (const std::vector< C * > &children, S *sender, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, uint32_t cmd, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
EQFABRIC_API bool _cmdSync (co::ICommand &command)
Additional Inherited Members
Public Types inherited from eq::fabric::Channel< Window, Channel >
enum Drawable
The drawable format defines the components used as an alternate drawable for this channel.
typedef LeafVisitor< Channel > Visitor
The channel visitor type.
typedef Window Parent
The parent window type.
enum IAttribute
Integer attributes for a channel.
enum SAttribute
String attributes.
Public Types inherited from eq::fabric::Object
enum DirtyBits {
DIRTY_NAME = Serializable::DIRTY_CUSTOM << 0, DIRTY_USERDATA = Serializable::DIRTY_CUSTOM << 1, DIRTY_TASKS = Serializable::DIRTY_CUSTOM << 2, DIRTY_REMOVED = Serializable::DIRTY_CUSTOM << 3,
DIRTY_SERIAL = Serializable::DIRTY_CUSTOM << 4, DIRTY_CUSTOM = Serializable::DIRTY_CUSTOM << 6, DIRTY_OBJECT_BITS = DIRTY_NAME | DIRTY_USERDATA
}
The changed parts of the object since the last pack().
Static Public Member Functions inherited from eq::fabric::Channel< Window, Channel >
static EQFABRIC_INL const
std::string & getIAttributeString (const IAttribute attr)
static EQFABRIC_INL const
std::string & getSAttributeString (const SAttribute attr)
Protected Types inherited from eq::fabric::Channel< Window, Channel >
enum DirtyBits
Detailed Description
Definition at line 39 of file share/Equalizer/examples/eqPixelBench/channel.h.
Constructor & Destructor Documentation
virtual eqPixelBench::Channel::~Channel () inline virtual
Destruct the channel.
Version
1.0
Reimplemented from eq::Channel.
Definition at line 43 of file share/Equalizer/examples/eqPixelBench/channel.h.
Member Function Documentation
bool eqPixelBench::Channel::configExit () protected virtual
Exit this channel.
Version
1.0
Reimplemented from eq::Channel.
Definition at line 77 of file eqPixelBench/channel.cpp.
References eq::Channel::configExit(), and eq::Frame::getFrameData().
void eqPixelBench::Channel::frameDraw (const eq::uint128_t & frameID) protected virtual
Draw the scene.
Called 0 to n times during one frame.
Parameters
frameID the per-frame identifier.
Version
1.0
Reimplemented from eq::Channel.
Definition at line 99 of file eqPixelBench/channel.cpp.
References eq::Channel::applyBuffer(), eq::Channel::applyFrustum(), eq::Channel::applyHeadTransform(), eq::Channel::applyViewport(), eq::Channel::resetAssemblyState(), and eq::Channel::setupAssemblyState().
void eqPixelBench::Channel::frameStart (const eq::uint128_t & frameID, const uint32_t frameNumber) protected virtual
Start rendering a frame.
Called once at the beginning of each frame, to do per-frame updates of channel-specific data. This method has to call startFrame().
Parameters
frameID the per-frame identifier.
frameNumber the frame to start.
See also
Config::startFrame()
Version
1.0
Reimplemented from eq::Channel.
Definition at line 83 of file eqPixelBench/channel.cpp.
References eq::Channel::frameStart(), eqPixelBench::Config::getClock(), and eq::Channel::getConfig().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqPixelBench/channel.h
eqPixelBench/channel.cpp