Equalizer: eVolve Namespace Reference
eVolve Namespace Reference
The Equalizer Volume Rendering Example.
Classes
class Channel
class Config
struct DataInTextureDimensions
Structure that contain actual dimensions of data that is stored in volume texture.
class EVolve
class FrameData
class GLSLShaders
class InitData
class LocalInitData
class Node
class Pipe
class RawVolumeModel
Load model to texture.
class RawVolumeModelRenderer
struct SliceClipper
struct VolumeInfo
struct VolumeScaling
Contain overall volume proportions relatively [-1,-1,-1]..[1,1,1] cube.
class Window
Typedefs
typedef RawVolumeModelRenderer Renderer
Enumerations
enum Error {
ERROR_EVOLVE_ARB_SHADER_OBJECTS_MISSING = eq::ERROR_CUSTOM, ERROR_EVOLVE_EXT_BLEND_FUNC_SEPARATE_MISSING, ERROR_EVOLVE_ARB_MULTITEXTURE_MISSING, ERROR_EVOLVE_LOADSHADERS_FAILED,
ERROR_EVOLVE_LOADMODEL_FAILED, ERROR_EVOLVE_MAPOBJECT_FAILED
}
Defines errors produced by eVolve.
enum ColorMode { COLOR_MODEL, COLOR_DEMO, COLOR_HALF_DEMO, COLOR_ALL }
enum BackgroundMode { BG_BLACK, BG_WHITE, BG_COLOR, BG_ALL }
enum NormalsQuality { NQ_FULL, NQ_MEDIUM, NQ_MINIMAL, NQ_ALL }
enum LogTopics { LOG_STATS = eq::LOG_CUSTOM }
Functions
void initErrors ()
Set up eVolve-specific error codes.
void exitErrors ()
Clear eVolve-specific error codes.
void orderFrames (eq::Frames &frames, const eq::Matrix4d &modelviewM, const eq::Matrix3d &modelviewITM, const eq::Matrix4f &rotation, const bool orthographic)
Detailed Description
The Equalizer Volume Rendering Example.
Enumeration Type Documentation
enum eVolve::BackgroundMode
Enumerator
BG_BLACK
Black background.
BG_WHITE
White background.
BG_COLOR
Unique color.
Definition at line 71 of file eVolve.h.
enum eVolve::ColorMode
Enumerator
COLOR_MODEL
Render using the colors defined in the ply file.
COLOR_DEMO
Use a unique color to demonstrate decomposition.
COLOR_HALF_DEMO
50% unique color + 50% original color
Definition at line 63 of file eVolve.h.
enum eVolve::Error
Defines errors produced by eVolve.
Definition at line 37 of file share/Equalizer/examples/eVolve/error.h.
enum eVolve::NormalsQuality
Enumerator
NQ_FULL
Highest normals quality.
NQ_MEDIUM
Average normals quality.
NQ_MINIMAL
Basic normal approximation.
Definition at line 79 of file eVolve.h.
Function Documentation
void eVolve::exitErrors ()
Clear eVolve-specific error codes.
Clear Sequel-specific error codes.
Definition at line 69 of file eVolve/error.cpp.
References eq::fabric::ErrorRegistry::eraseString(), and eq::fabric::Global::getErrorRegistry().
void eVolve::initErrors ()
Set up eVolve-specific error codes.
Set up Sequel-specific error codes.
Definition at line 61 of file eVolve/error.cpp.
References eq::fabric::Global::getErrorRegistry(), and eq::fabric::ErrorRegistry::setString().