Equalizer: co::Serializable Class Reference
co::Serializable Class Reference
Base class for distributed, inheritable objects.
#include <serializable.h>
Public Member Functions
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
virtual CO_API uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
Public Member Functions inherited from co::Object
CO_API Object ()
Construct a new distributed object.
virtual CO_API ~Object ()
Destruct the distributed object.
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API bool send (NodePtr node, ObjectPacket &packet)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const std::string &string)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const void *data, const uint64_t size)
Send a packet to peer object instance(s) on another node.
template<class T >
bool send (NodePtr node, ObjectPacket &packet, const std::vector< T > &v)
Send a packet to peer object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual CO_API void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (Command &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void attach (const UUID &id, const uint32_t instanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (Command &command)
Dispatch a command from the receiver thread to the registered queue.
Protected Member Functions
CO_API Serializable ()
Construct a new Serializable.
CO_API Serializable (const Serializable &)
Construct an unmapped, unregistered copy of an serializable.
virtual CO_API ~Serializable ()
Destruct the serializable.
virtual void serialize (co::DataOStream &, const uint64_t)
Worker for pack() and getInstanceData().
virtual void deserialize (co::DataIStream &, const uint64_t)
Worker for unpack() and applyInstanceData().
virtual ChangeType getChangeType () const
virtual CO_API void setDirty (const uint64_t bits)
Add dirty flags to mark data for distribution.
virtual CO_API void unsetDirty (const uint64_t bits)
Remove dirty flags to clear data from distribution.
virtual CO_API void notifyAttached ()
Notify that this object has been registered or mapped.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (Command &command)
The default handler for handling commands.
Protected Types
enum DirtyBits { DIRTY_NONE = 0, DIRTY_CUSTOM = 1, DIRTY_ALL = 0xFFFFFFFFFFFFFFFFull }
The changed parts of the serializable since the last pack().
Friends
class detail::Serializable
Additional Inherited Members
Public Types inherited from co::Object
enum ChangeType {
NONE, STATIC, INSTANCE, DELTA,
UNBUFFERED
}
Object change handling characteristics, see Programming Guide.
Public Types inherited from co::Dispatcher
typedef CommandFunc< Dispatcher > Func
Detailed Description
Base class for distributed, inheritable objects.
This class implements one usage pattern of co::Object, which allows subclassing and serialization of distributed Objects. The implementation hierarchy co::Serializable -> eq::fabric::Object -> eq::fabric::Frustum illustrates the usage of this class.
Definition at line 35 of file serializable.h.
Member Enumeration Documentation
enum co::Serializable::DirtyBits protected
The changed parts of the serializable since the last pack().
Subclasses should define their own bits, starting at DIRTY_CUSTOM.
Version:
1.0
Reimplemented in eq::fabric::Channel< W, C >, eq::fabric::Channel< Window, Channel >, eq::fabric::View< L, V, O >, eq::fabric::View< Layout, View, Observer >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Segment< C, S, CH >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eqPly::FrameData, eqPly::FrameData, eq::fabric::Observer< C, O >, eq::fabric::Observer< Config, Observer >, eq::fabric::Object, eq::fabric::Layout< C, L, V >, eq::fabric::Layout< Config, Layout, View >, eVolve::FrameData, osgScaleViewer::FrameData, eqNbody::FrameData, co::ObjectMap, and eqNbody::SharedDataProxy.
Definition at line 97 of file serializable.h.
Constructor & Destructor Documentation
CO_API co::Serializable::Serializable () protected
Construct a new Serializable.
Version:
1.0
CO_API co::Serializable::Serializable (const Serializable &) protected
Construct an unmapped, unregistered copy of an serializable.
Version:
1.0
virtual CO_API co::Serializable::~Serializable () protected virtual
Destruct the serializable.
Version:
1.0
Member Function Documentation
virtual CO_API uint128_t co::Serializable::commit (const uint32_t incarnation = CO_COMMIT_NEXT) virtual
Commit a new version of this object.
Objects using the change type STATIC can not be committed.
Master instances will increment new versions continously, starting at VERSION_FIRST. If the object has not changed, no new version will be generated, that is, the current version is returned. The high value of the returned version will always be 0.
Slave objects can be commited, but have certain caveats for serialization. Please refer to the Programming Guide for more details. Slave object commits will return a random version on a successful commit, or VERSION_NONE if the object has not changed since the last commit. The high value of a successful commit will never be 0.
The incarnation count is meaningful for buffered master objects. The commit implementation will keep all instance data committed with an incarnation count newer than current_incarnation - getAutoObsolete(). By default, each call to commit creates a new incarnation, retaining the data from last getAutoObsolete() commit calls. When the application wishes to auto obsolete by another metric than commit calls, it has to consistently provide an incarnation counter. Buffers with a higher incarnation count than the current are discarded. A typical use case is to tie the auto obsoletion to an application-specific frame loop. Decreasing the incarnation counter will lead to undefined results.
Parameters:
incarnation the commit incarnation for auto obsoletion.
Returns:
the new head version.
Reimplemented from co::Object.
Reimplemented in eq::fabric::Config< S, C, O, L, CV, N, V >, eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Segment< C, S, CH >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eq::fabric::Object, and co::ObjectMap.
Referenced by eVolve::Config::startFrame(), osgScaleViewer::Config::startFrame(), and eqPly::Config::startFrame().
virtual void co::Serializable::deserialize (co::DataIStream & , const uint64_t) inline protected virtual
Worker for unpack() and applyInstanceData().
This function is called with the dirty bits send by the master instance. The dirty bits are received beforehand, and do not need to be deserialized by the overriding method.
See also:
serialize()
Version:
1.0
Reimplemented in eq::fabric::Channel< W, C >, eq::fabric::Channel< Window, Channel >, eq::fabric::View< L, V, O >, eq::fabric::View< Layout, View, Observer >, eq::fabric::Config< S, C, O, L, CV, N, V >, eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Segment< C, S, CH >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::Object, eq::fabric::Canvas< CFG, C, S, L >, eq::fabric::Canvas< Config, Canvas, Segment, Layout >, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eqPly::FrameData, eqPly::FrameData, eq::fabric::Observer< C, O >, eq::fabric::Observer< Config, Observer >, seq::ViewData, eq::fabric::Layout< C, L, V >, eq::fabric::Layout< Config, Layout, View >, osgScaleViewer::FrameData, eqNbody::FrameData, eVolve::FrameData, eq::View, co::ObjectMap, and eqNbody::SharedDataProxy.
Definition at line 87 of file serializable.h.
Referenced by eqNbody::FrameData::deserialize().
virtual ChangeType co::Serializable::getChangeType () const inline protected virtual
Returns:
how the changes are to be handled.
Reimplemented from co::Object.
Reimplemented in eq::fabric::Channel< W, C >, eq::fabric::Channel< Window, Channel >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eqPly::FrameData, eqPly::FrameData, osgScaleViewer::FrameData, eVolve::FrameData, co::ObjectMap, and eqNbody::SharedDataProxy.
Definition at line 89 of file serializable.h.
References co::Object::DELTA.
CO_API uint64_t co::Serializable::getDirty () const
Returns:
the current dirty bit mask.
Version:
1.0
virtual CO_API bool co::Serializable::isDirty () const virtual
Returns:
true if the serializable has to be committed.
Version:
1.0
Reimplemented from co::Object.
Reimplemented in eq::fabric::Object, and co::ObjectMap.
virtual CO_API bool co::Serializable::isDirty (const uint64_t dirtyBits) const virtual
Returns:
true if the given dirty bit is set.
Version:
1.0
virtual CO_API void co::Serializable::notifyAttached () protected virtual
Notify that this object has been registered or mapped.
The method is called from the thread initiating the registration or mapping, after the operation has been completed successfully.
See also:
isMaster()
Reimplemented from co::Object.
Reimplemented in eq::Config, and co::ObjectMap.
virtual void co::Serializable::serialize (co::DataOStream & , const uint64_t) inline protected virtual
Worker for pack() and getInstanceData().
Override this and deserialize() if you want to distribute subclassed data.
This method is called with DIRTY_ALL from getInstanceData() and with the actual dirty bits from pack(), which also resets the dirty state afterwards. The dirty bits are transmitted beforehand, and do not need to be transmitted by the overriding method.
Version:
1.0
Reimplemented in eq::fabric::Channel< W, C >, eq::fabric::Channel< Window, Channel >, eq::fabric::View< L, V, O >, eq::fabric::View< Layout, View, Observer >, eq::fabric::Config< S, C, O, L, CV, N, V >, eq::fabric::Config< Server, Config, Observer, Layout, Canvas, Node, ConfigVisitor >, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Segment< C, S, CH >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::Object, eq::fabric::Canvas< CFG, C, S, L >, eq::fabric::Canvas< Config, Canvas, Segment, Layout >, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eqPly::FrameData, eqPly::FrameData, eq::fabric::Observer< C, O >, eq::fabric::Observer< Config, Observer >, seq::ViewData, eq::fabric::Layout< C, L, V >, eq::fabric::Layout< Config, Layout, View >, eqNbody::FrameData, osgScaleViewer::FrameData, eVolve::FrameData, co::ObjectMap, and eqNbody::SharedDataProxy.
Definition at line 75 of file serializable.h.
Referenced by eqNbody::FrameData::serialize().
virtual CO_API void co::Serializable::setDirty (const uint64_t bits) protected virtual
Add dirty flags to mark data for distribution.
Version:
1.0
Reimplemented in eq::fabric::Channel< W, C >, eq::fabric::Channel< Window, Channel >, eq::fabric::View< L, V, O >, eq::fabric::View< Layout, View, Observer >, eq::Pipe, eq::fabric::Window< P, W, C >, eq::fabric::Window< Pipe, Window, Channel >, eq::fabric::Pipe< N, P, W, V >, eq::fabric::Pipe< Node, Pipe, eq::Window, PipeVisitor >, eq::fabric::Segment< C, S, CH >, eq::fabric::Segment< Canvas, Segment, Channel >, eq::fabric::Canvas< CFG, C, S, L >, eq::fabric::Canvas< Config, Canvas, Segment, Layout >, eq::Node, eq::fabric::Node< C, N, P, V >, eq::fabric::Node< Config, Node, Pipe, NodeVisitor >, eq::fabric::Observer< C, O >, eq::fabric::Observer< Config, Observer >, eq::fabric::Layout< C, L, V >, and eq::fabric::Layout< Config, Layout, View >.
Referenced by osgScaleViewer::FrameData::setCameraLookAtPoint(), osgScaleViewer::FrameData::setCameraPosition(), osgScaleViewer::FrameData::setCameraUpVector(), and osgScaleViewer::FrameData::toggleStatistics().
virtual CO_API void co::Serializable::unsetDirty (const uint64_t bits) protected virtual
Remove dirty flags to clear data from distribution.
Version:
1.0
The documentation for this class was generated from the following file:
serializable.h