Equalizer: lunchbox::Condition Class Reference
lunchbox::Condition Class Reference
A condition variable and associated lock.
#include <condition.h>
Public Member Functions
LUNCHBOX_API Condition ()
Construct a new condition variable.
LUNCHBOX_API ~Condition ()
Destruct this condition variable.
LUNCHBOX_API void lock ()
Lock the mutex.
LUNCHBOX_API void unlock ()
Unlock the mutex.
LUNCHBOX_API void signal ()
Signal the condition.
LUNCHBOX_API void broadcast ()
Broadcast the condition.
LUNCHBOX_API void wait ()
Atomically unlock the mutex, wait for a signal and relock the mutex.
LUNCHBOX_API bool timedWait (const uint32_t timeout)
Atomically unlock the mutex, wait for a signal and relock the mutex.
Detailed Description
A condition variable and associated lock.
Follows closely pthread_condition and mutex
Definition at line 33 of file condition.h.
Constructor & Destructor Documentation
LUNCHBOX_API lunchbox::Condition::Condition ()
Construct a new condition variable.
Version:
1.0
LUNCHBOX_API lunchbox::Condition::~Condition ()
Destruct this condition variable.
Version:
1.0
Member Function Documentation
LUNCHBOX_API void lunchbox::Condition::broadcast ()
Broadcast the condition.
Version:
1.0
Referenced by lunchbox::Monitor< State >::operator++(), lunchbox::Monitor< State >::operator--(), lunchbox::Monitor< State >::operator|=(), and lunchbox::Monitor< State >::set().
LUNCHBOX_API void lunchbox::Condition::lock ()
Lock the mutex.
Version:
1.0
Referenced by lunchbox::MTQueue< const void * >::clear(), lunchbox::MTQueue< const void * >::getBack(), lunchbox::MTQueue< const void * >::getFront(), lunchbox::Monitor< State >::operator++(), lunchbox::Monitor< State >::operator--(), lunchbox::MTQueue< const void * >::operator=(), lunchbox::MTQueue< const void * >::operator[](), lunchbox::Monitor< State >::operator|=(), lunchbox::MTQueue< const void * >::pop(), lunchbox::MTQueue< const void * >::push(), lunchbox::MTQueue< const void * >::pushFront(), lunchbox::Monitor< State >::set(), lunchbox::MTQueue< const void * >::setMaxSize(), lunchbox::MTQueue< const void * >::timedPop(), lunchbox::Monitor< State >::timedWaitEQ(), lunchbox::Monitor< State >::timedWaitGE(), lunchbox::Monitor< State >::timedWaitNE(), lunchbox::MTQueue< const void * >::tryPop(), lunchbox::Monitor< State >::waitEQ(), lunchbox::Monitor< State >::waitGE(), lunchbox::Monitor< State >::waitLE(), lunchbox::Monitor< State >::waitNE(), and lunchbox::MTQueue< const void * >::waitSize().
LUNCHBOX_API void lunchbox::Condition::signal ()
Signal the condition.
Version:
1.0
Referenced by lunchbox::MTQueue< const void * >::clear(), lunchbox::MTQueue< const void * >::operator=(), lunchbox::MTQueue< const void * >::pop(), lunchbox::MTQueue< const void * >::push(), lunchbox::MTQueue< const void * >::pushFront(), lunchbox::MTQueue< const void * >::setMaxSize(), lunchbox::MTQueue< const void * >::timedPop(), and lunchbox::MTQueue< const void * >::tryPop().
LUNCHBOX_API bool lunchbox::Condition::timedWait (const uint32_t timeout)
Atomically unlock the mutex, wait for a signal and relock the mutex.
The operation is aborted after the given timeout and false is returned.
Parameters:
timeout the timeout in milliseconds to wait for the signal.
Returns:
true on success, false on timeout.
Version:
1.0
Referenced by lunchbox::MTQueue< const void * >::timedPop(), lunchbox::Monitor< State >::timedWaitEQ(), lunchbox::Monitor< State >::timedWaitGE(), and lunchbox::Monitor< State >::timedWaitNE().
LUNCHBOX_API void lunchbox::Condition::unlock ()
Unlock the mutex.
Version:
1.0
Referenced by lunchbox::MTQueue< const void * >::clear(), lunchbox::MTQueue< const void * >::getBack(), lunchbox::MTQueue< const void * >::getFront(), lunchbox::Monitor< State >::operator++(), lunchbox::Monitor< State >::operator--(), lunchbox::MTQueue< const void * >::operator=(), lunchbox::MTQueue< const void * >::operator[](), lunchbox::Monitor< State >::operator|=(), lunchbox::MTQueue< const void * >::pop(), lunchbox::MTQueue< const void * >::push(), lunchbox::MTQueue< const void * >::pushFront(), lunchbox::Monitor< State >::set(), lunchbox::MTQueue< const void * >::setMaxSize(), lunchbox::MTQueue< const void * >::timedPop(), lunchbox::Monitor< State >::timedWaitEQ(), lunchbox::Monitor< State >::timedWaitGE(), lunchbox::Monitor< State >::timedWaitNE(), lunchbox::MTQueue< const void * >::tryPop(), lunchbox::Monitor< State >::waitEQ(), lunchbox::Monitor< State >::waitGE(), lunchbox::Monitor< State >::waitLE(), lunchbox::Monitor< State >::waitNE(), and lunchbox::MTQueue< const void * >::waitSize().
LUNCHBOX_API void lunchbox::Condition::wait ()
Atomically unlock the mutex, wait for a signal and relock the mutex.
Version:
1.0
Referenced by lunchbox::MTQueue< const void * >::operator[](), lunchbox::MTQueue< const void * >::pop(), lunchbox::MTQueue< const void * >::push(), lunchbox::MTQueue< const void * >::pushFront(), lunchbox::MTQueue< const void * >::setMaxSize(), lunchbox::Monitor< State >::waitEQ(), lunchbox::Monitor< State >::waitGE(), lunchbox::Monitor< State >::waitLE(), lunchbox::Monitor< State >::waitNE(), and lunchbox::MTQueue< const void * >::waitSize().
The documentation for this class was generated from the following file:
condition.h