Equalizer: co::base::Clock Class Reference
co::base::Clock Class Reference
A class for time measurements.
#include <clock.h>
Public Member Functions
COBASE_API Clock ()
Construct a new clock.
COBASE_API ~Clock ()
Destroy the clock.
COBASE_API void reset ()
Reset the base time of the clock to the current time.
COBASE_API void set (const int64_t time)
Set the current time of the clock.
COBASE_API float getTimef () const
COBASE_API float resetTimef ()
COBASE_API int64_t getTime64 () const
COBASE_API double getTimed () const
COBASE_API float getMilliSecondsf () const
Returns the millisecond part of the time elapsed since the last reset.
Detailed Description
A class for time measurements.
Definition at line 32 of file clock.h.
Constructor & Destructor Documentation
COBASE_API co::base::Clock::Clock ()
Construct a new clock.
Version:
1.0
COBASE_API co::base::Clock::~Clock ()
Destroy the clock.
Version:
1.0
Member Function Documentation
COBASE_API float co::base::Clock::getMilliSecondsf () const
Returns the millisecond part of the time elapsed since the last reset.
Obviously the returned time overflows once per second.
Returns:
the millisecond part of the time elapsed.
Version:
1.0
COBASE_API int64_t co::base::Clock::getTime64 () const
Returns:
the elapsed time in milliseconds since the last clock reset.
Version:
1.0
Referenced by eq::Config::getTime().
COBASE_API double co::base::Clock::getTimed () const
Returns:
the elapsed time in milliseconds since the last clock reset.
Version:
1.0
COBASE_API float co::base::Clock::getTimef () const
Returns:
the elapsed time in milliseconds since the last clock reset.
Version:
1.0
Referenced by eqPixelBench::Channel::frameStart(), eVolve::EVolve::run(), eqPly::EqPly::run(), and osgScaleViewer::Config::startFrame().
COBASE_API void co::base::Clock::reset ()
Reset the base time of the clock to the current time.
Version:
1.0
Referenced by eVolve::EVolve::run(), eqPly::EqPly::run(), eqPixelBench::Config::startFrame(), and osgScaleViewer::Config::startFrame().
COBASE_API float co::base::Clock::resetTimef ()
Returns:
the elapsed time in milliseconds since the last clock reset and atomically reset the clock.
Version:
1.0
Referenced by eqPly::EqPly::run().
COBASE_API void co::base::Clock::set (const int64_t time)
Set the current time of the clock.
Version:
1.0
The documentation for this class was generated from the following file:
clock.h