Equalizer: co::base::Global Class Reference
co::base::Global Class Reference
Global parameter handling for the Equalizer base library.
#include <global.h>
Static Public Member Functions
static COBASE_API PluginRegistry & getPluginRegistry ()
static COBASE_API ErrorRegistry & getErrorRegistry ()
Friends
COBASE_API bool init (const int argc, char **argv)
Initialize the Equalizer base classes.
COBASE_API bool exit ()
De-initialize the Equalizer base classes.
Attributes
enum IAttribute { IATTR_ROBUSTNESS, IATTR_TIMEOUT_DEFAULT, IATTR_ALL }
Global integer attributes.
static COBASE_API void setIAttribute (const IAttribute attr, const int32_t value)
Set an integer attribute.
static COBASE_API int32_t getIAttribute (const IAttribute attr)
Detailed Description
Global parameter handling for the Equalizer base library.
Definition at line 32 of file co/base/global.h.
Member Enumeration Documentation
enum co::base::Global::IAttribute
Global integer attributes.
Definition at line 44 of file co/base/global.h.
Member Function Documentation
static COBASE_API ErrorRegistry& co::base::Global::getErrorRegistry () [static]
Returns:
the error registry.
Version:
1.0
Referenced by eqPly::exitErrors(), eVolve::exitErrors(), eqPly::initErrors(), and eVolve::initErrors().
static COBASE_API int32_t co::base::Global::getIAttribute (const IAttribute attr) [static]
Returns:
the value of an integer attribute.
static COBASE_API PluginRegistry& co::base::Global::getPluginRegistry () [static]
Returns:
the plugin registry.
Version:
1.0
static COBASE_API void co::base::Global::setIAttribute (const IAttribute attr, const int32_t value) [static]
Set an integer attribute.
Friends And Related Function Documentation
COBASE_API bool exit () [friend]
De-initialize the Equalizer base classes.
Returns:
true if the library was successfully de-initialised, false otherwise.
Version:
1.0
Returns:
true if the library was successfully de-initialised, false otherwise.
true if the library was successfully de-initialized, false otherwise.
true if the library was successfully de-initialized, false otherwise.
Version:
1.0
COBASE_API bool init (const int argc, char ** argv) [friend]
Initialize the Equalizer base classes.
Parameters:
argc the command line argument count.
argv the command line argument values.
Returns:
true if the library was successfully initialised, false otherwise
Version:
1.0
Parameters:
argc the command line argument count.
argv the command line argument values.
Returns:
true if the library was successfully initialised, false otherwise.
Parameters:
argc the command line argument count.
argv the command line argument values.
Returns:
true if the library was successfully initialized, false otherwise.
Version:
1.0
Definition at line 38 of file co/init.h.
The documentation for this class was generated from the following file:
co/base/global.h