Lunchbox: lunchbox::TLS Class Reference
lunchbox::TLS Class Reference
Provides thread-local storage API used by PerThread and PerThreadRef.
#include <tls.h>
Public Types
typedef void(* ThreadDestructor_t) (void *)
Public Member Functions
TLS (ThreadDestructor_t dtorFunc)
Construct a new per-thread storage.
~TLS ()
Destruct the per-thread storage.
void set (const void *data)
Set the data for this thread-local storage.
void * get ()
const void * get () const
Detailed Description
Provides thread-local storage API used by PerThread and PerThreadRef.
Definition at line 28 of file tls.h.
Constructor & Destructor Documentation
lunchbox::TLS::TLS (ThreadDestructor_t dtorFunc) explicit
Construct a new per-thread storage.
Parameters
dtorFunc the destructor function called to destroy thread-local storage, not called if 0.
Version
1.7.2
lunchbox::TLS::~TLS ()
Destruct the per-thread storage.
Version
1.7.2
Member Function Documentation
void* lunchbox::TLS::get ()
Returns
the data for this thread-local storage.
Version
1.7.2
Referenced by lunchbox::PerThreadRef< T >::get(), lunchbox::PerThread< T, D >::get(), lunchbox::PerThreadRef< T >::getPointer(), lunchbox::PerThreadRef< T >::isValid(), lunchbox::PerThread< T, D >::isValid(), lunchbox::PerThreadRef< T >::operator!(), lunchbox::PerThread< T, D >::operator!(), lunchbox::PerThreadRef< T >::operator->(), and lunchbox::PerThread< T, D >::operator->().
const void* lunchbox::TLS::get () const
Returns
the data for this thread-local storage.
Version
1.7.2
void lunchbox::TLS::set (const void * data)
Set the data for this thread-local storage.
Version
1.7.2
Referenced by lunchbox::PerThreadRef< T >::operator=(), and lunchbox::PerThread< T, D >::operator=().
The documentation for this class was generated from the following file:
tls.h