Equalizer: eqPly::Node Class Reference
eqPly::Node Class Reference
Representation of a node in the cluster.
#include <node.h>
Public Member Functions
Node (eq::Config *parent)
Construct a new node.
Public Member Functions inherited from eq::Node
ClientPtr getClient ()
ServerPtr getServer ()
co::CommandQueue * getMainThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
uint32_t getCurrentFrame () const
co::Barrier * getBarrier (const co::ObjectVersion barrier)
FrameDataPtr getFrameData (const co::ObjectVersion &frameDataVersion)
void releaseFrameData (FrameDataPtr data)
void waitInitialized () const
bool isRunning () const
bool isStopped () const
void waitFrameStarted (const uint32_t frameNumber) const
Wait for a frame to be started.
uint32_t getFinishedFrame () const
virtual void setDirty (const uint64_t bits)
void dirtyClientExit ()
Public Member Functions inherited from eq::fabric::Node< Config, Node, Pipe, NodeVisitor >
Config * getConfig ()
const Config * getConfig () const
const Pipes & getPipes () const
bool isApplicationNode () const
EQFABRIC_INL void setApplicationNode (const bool isAppNode)
EQFABRIC_INL NodePath getPath () const
Pipe * findPipe (const UUID &id)
EQFABRIC_INL VisitorResult accept (NodeVisitor &visitor)
Traverse this node and all children using a node visitor.
EQFABRIC_INL VisitorResult accept (NodeVisitor &visitor) const
Const-version of accept().
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
void create (Pipe **pipe)
void release (Pipe *pipe)
virtual void output (std::ostream &) const
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
EQFABRIC_INL void setIAttribute (const IAttribute attr, const int32_t value)
EQFABRIC_INL int32_t getIAttribute (const IAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual bool isDirty () const
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
void setError (const int32_t error)
Set an error code why the last operation failed.
co::Error getError () const
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Public Member Functions inherited from co::Serializable
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
Public Member Functions inherited from co::Object
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API bool send (NodePtr node, ObjectPacket &packet)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const std::string &string)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const void *data, const uint64_t size)
Send a packet to peer object instance(s) on another node.
template<class T >
bool send (NodePtr node, ObjectPacket &packet, const std::vector< T > &v)
Send a packet to peer object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (Command &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (CommandPtr command)
Dispatch a command from the receiver thread to the registered queue.
Protected Member Functions
virtual ~Node ()
Destruct the node.
virtual bool configInit (const eq::uint128_t &initID)
Initialize this node.
Protected Member Functions inherited from eq::Node
virtual void attach (const UUID &id, const uint32_t instanceID)
void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
void releaseFrameLocal (const uint32_t frameNumber)
Release the local synchronization of the parent for a frame.
virtual bool configExit ()
Exit this node.
virtual void frameStart (const uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
virtual void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
virtual void frameTasksFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish all rendering tasks.
Protected Member Functions inherited from eq::fabric::Node< Config, Node, Pipe, NodeVisitor >
Node (Config *parent)
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
Worker for pack() and getInstanceData().
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
Worker for unpack() and applyInstanceData().
virtual EQFABRIC_INL void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual ChangeType getChangeType () const
virtual uint64_t getRedistributableBits () const
Protected Member Functions inherited from eq::fabric::Object
Object ()
Construct a new Object.
virtual ~Object ()
Destruct the object.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
void setTasks (const uint32_t tasks)
void postRemove (Object *child)
virtual void removeChild (const UUID &)
template<class C , class PKG , class S >
void commitChild (C *child, S *sender, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class PKG , class S >
void commitChildren (const std::vector< C * > &children, S *sender, const uint32_t incarnation)
template<class C , class PKG >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
bool _cmdSync (co::Command &command)
Protected Member Functions inherited from co::Serializable
CO_API Serializable ()
Construct a new Serializable.
CO_API Serializable (const Serializable &)
Construct an unmapped, unregistered copy of an serializable.
virtual CO_API ~Serializable ()
Destruct the serializable.
virtual CO_API void unsetDirty (const uint64_t bits)
Remove dirty flags to clear data from distribution.
virtual CO_API void notifyAttached ()
Notify that this object has been registered or mapped.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (Command &command)
The default handler for handling commands.
Additional Inherited Members
Public Attributes inherited from eq::Node
eq::Node::TransmitThread transmitter
Detailed Description
Representation of a node in the cluster.
Manages node-specific data, namely requesting the mapping of the initialization data by the local Config instance.
Definition at line 45 of file share/Equalizer/examples/eqPly/node.h.
Constructor & Destructor Documentation
eqPly::Node::Node (eq::Config * parent) inline
Construct a new node.
Version:
1.0
Reimplemented from eq::Node.
Definition at line 48 of file share/Equalizer/examples/eqPly/node.h.
virtual eqPly::Node::~Node () inline protected virtual
Destruct the node.
Version:
1.0
Reimplemented from eq::Node.
Definition at line 51 of file share/Equalizer/examples/eqPly/node.h.
Member Function Documentation
bool eqPly::Node::configInit (const eq::uint128_t & initID) protected virtual
Initialize this node.
Parameters:
initID the init identifier.
Version:
1.0
Reimplemented from eq::Node.
Definition at line 36 of file eqPly/node.cpp.
References eq::Node::configInit(), eq::fabric::Node< Config, Node, Pipe, NodeVisitor >::getConfig(), eq::fabric::Node< Config, Node, Pipe, NodeVisitor >::getIAttribute(), eq::fabric::Node< Config, Node, Pipe, NodeVisitor >::IATTR_THREAD_MODEL, eqPly::Config::loadData(), and eq::fabric::Object::setError().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqPly/node.h
eqPly/node.cpp