Equalizer: co::Global Class Reference
co::Global Class Reference
Global parameter handling for the Collage library.
#include <global.h>
Static Public Member Functions
static CO_API void setProgramName (const std::string &programName)
Sets the name of the program.
static CO_API const std::string & getProgramName ()
static CO_API void setWorkDir (const std::string &workDir)
Sets the working directory of the program.
static CO_API const std::string & getWorkDir ()
static CO_API void setDefaultPort (const uint16_t port)
Sets the default listening port.
static CO_API uint16_t getDefaultPort ()
static CO_API void setObjectBufferSize (const uint32_t size)
Set the minimum buffer size for Object serialization.
static CO_API uint32_t getObjectBufferSize ()
static CO_API bool fromString (const std::string &data)
Set the global variables.
static CO_API void toString (std::string &data)
Write global variables to data in the format for fromString().
static CO_API PluginRegistry & getPluginRegistry ()
static CO_API ErrorRegistry & getErrorRegistry ()
static CO_API uint32_t getKeepaliveTimeout ()
Attributes
enum IAttribute {
IATTR_INSTANCE_CACHE_SIZE, IATTR_NODE_SEND_QUEUE_SIZE, IATTR_NODE_SEND_QUEUE_AGE, IATTR_RSP_ACK_TIMEOUT,
IATTR_RSP_ERROR_DOWNSCALE, IATTR_RSP_ERROR_UPSCALE, IATTR_RSP_ERROR_MAXSCALE, IATTR_RSP_MIN_SENDRATE_SHIFT,
IATTR_RSP_NUM_BUFFERS, IATTR_RSP_ACK_FREQUENCY, IATTR_UDP_MTU, IATTR_UDP_BUFFER_SIZE,
IATTR_QUEUE_MIN_SIZE, IATTR_QUEUE_REFILL, IATTR_RDMA_RING_BUFFER_SIZE_MB, IATTR_RDMA_SEND_QUEUE_DEPTH,
IATTR_RDMA_RESOLVE_TIMEOUT_MS, IATTR_ROBUSTNESS, IATTR_TIMEOUT_DEFAULT, IATTR_OBJECT_COMPRESSION,
IATTR_ALL
}
Global integer attributes.
static CO_API void setIAttribute (const IAttribute attr, const int32_t value)
Set an integer attribute.
static CO_API int32_t getIAttribute (const IAttribute attr)
static CO_API uint32_t getTimeout ()
Detailed Description
Global parameter handling for the Collage library.
Definition at line 28 of file co/global.h.
Member Enumeration Documentation
enum co::Global::IAttribute
Global integer attributes.
Definition at line 102 of file co/global.h.
Member Function Documentation
static CO_API bool co::Global::fromString (const std::string & data) static
Set the global variables.
The data is expected to be a list of unsigned ints in the format &#35;&#35;uint0&#35;uint1&#35;uint2&#35;...&#35;uint(n-1)&#35;&#35; with n = Global::IATTR_ALL. If the data format is correct, global variables will be changed and true will be returned. Otherwise there will be no change and false will be returned.
Parameters:
data the global variables in the described format
Returns:
true on success, false otherwise.
static CO_API uint16_t co::Global::getDefaultPort () static
Returns:
the default listening port.
static CO_API ErrorRegistry& co::Global::getErrorRegistry () static
Returns:
the error registry.
Version:
1.0
Referenced by eqPly::exitErrors(), eVolve::exitErrors(), eqPly::initErrors(), and eVolve::initErrors().
static CO_API int32_t co::Global::getIAttribute (const IAttribute attr) static
Returns:
the value of an integer attribute.
static CO_API uint32_t co::Global::getKeepaliveTimeout () static
Returns:
the keepalive timeout.
static CO_API uint32_t co::Global::getObjectBufferSize () static
Returns:
the minimum buffer size for Object serialization.
static CO_API PluginRegistry& co::Global::getPluginRegistry () static
Returns:
the plugin registry.
Version:
1.0
static CO_API const std::string& co::Global::getProgramName () static
Returns:
the program name.
static CO_API uint32_t co::Global::getTimeout () static
Returns:
the timeout, a concrete time or LB_TIMEOUT_INDEFINITE.
static CO_API const std::string& co::Global::getWorkDir () static
Returns:
the working directory of the program.
static CO_API void co::Global::setDefaultPort (const uint16_t port) static
Sets the default listening port.
Parameters:
port the default port.
static CO_API void co::Global::setIAttribute (const IAttribute attr, const int32_t value) static
Set an integer attribute.
static CO_API void co::Global::setObjectBufferSize (const uint32_t size) static
Set the minimum buffer size for Object serialization.
The buffer size is used during serialization. When a DataOStream has buffered at least size bytes, the data is send to the slave nodes. The default is 60.000 bytes.
Parameters:
size the treshold before the DataOStream sends a buffer.
static CO_API void co::Global::setProgramName (const std::string & programName) static
Sets the name of the program.
Parameters:
programName the program name.
static CO_API void co::Global::setWorkDir (const std::string & workDir) static
Sets the working directory of the program.
Parameters:
workDir the working directory.
static CO_API void co::Global::toString (std::string & data) static
Write global variables to data in the format for fromString().
The documentation for this class was generated from the following file:
co/global.h