Equalizer: eqPly::FrameData Class Reference
eqPly::FrameData Class Reference
Frame-specific data.
#include <frameData.h>
Public Member Functions
void reset ()
void reset ()
Rendering flags.
void setModelID (const eq::uint128_t &id)
void setColorMode (const ColorMode color)
void setRenderMode (const mesh::RenderMode mode)
void setIdle (const bool idleMode)
void toggleOrtho ()
void toggleStatistics ()
void toggleHelp ()
void toggleWireframe ()
void toggleColorMode ()
void adjustQuality (const float delta)
void togglePilotMode ()
void toggleRenderMode ()
void toggleCompression ()
eq::uint128_t getModelID () const
ColorMode getColorMode () const
float getQuality () const
bool useOrtho () const
bool useStatistics () const
bool showHelp () const
bool useWireframe () const
bool usePilotMode () const
bool isIdle () const
mesh::RenderMode getRenderMode () const
bool useCompression () const
void setModelID (const eq::uint128_t &id)
void setColorMode (const ColorMode color)
void setRenderMode (const mesh::RenderMode mode)
void setIdle (const bool idleMode)
void toggleOrtho ()
void toggleStatistics ()
void toggleHelp ()
void toggleWireframe ()
void toggleColorMode ()
void adjustQuality (const float delta)
void togglePilotMode ()
void toggleRenderMode ()
void toggleCompression ()
eq::uint128_t getModelID () const
ColorMode getColorMode () const
float getQuality () const
bool useOrtho () const
bool useStatistics () const
bool showHelp () const
bool useWireframe () const
bool usePilotMode () const
bool isIdle () const
mesh::RenderMode getRenderMode () const
bool useCompression () const
Camera parameters.
void setCameraPosition (const eq::Vector3f &position)
void setRotation (const eq::Vector3f &rotation)
void setModelRotation (const eq::Vector3f &rotation)
void spinCamera (const float x, const float y)
void spinModel (const float x, const float y, const float z)
void moveCamera (const float x, const float y, const float z)
const eq::Matrix4f & getCameraRotation () const
const eq::Matrix4f & getModelRotation () const
const eq::Vector3f & getCameraPosition () const
void setCameraPosition (const eq::Vector3f &position)
void setRotation (const eq::Vector3f &rotation)
void setModelRotation (const eq::Vector3f &rotation)
void spinCamera (const float x, const float y)
void spinModel (const float x, const float y, const float z)
void moveCamera (const float x, const float y, const float z)
const eq::Matrix4f & getCameraRotation () const
const eq::Matrix4f & getModelRotation () const
const eq::Vector3f & getCameraPosition () const
View interface.
void setCurrentViewID (const eq::uint128_t &id)
eq::uint128_t getCurrentViewID () const
void setCurrentViewID (const eq::uint128_t &id)
eq::uint128_t getCurrentViewID () const
Public Member Functions inherited from co::Serializable
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
virtual CO_API uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
Public Member Functions inherited from co::Object
CO_API Object ()
Construct a new distributed object.
virtual CO_API ~Object ()
Destruct the distributed object.
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API bool send (NodePtr node, ObjectPacket &packet)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const std::string &string)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const void *data, const uint64_t size)
Send a packet to peer object instance(s) on another node.
template<class T >
bool send (NodePtr node, ObjectPacket &packet, const std::vector< T > &v)
Send a packet to peer object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual CO_API void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (Command &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void attach (const UUID &id, const uint32_t instanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (CommandPtr command)
Dispatch a command from the receiver thread to the registered queue.
Message overlay.
enum DirtyBits {
DIRTY_CAMERA = co::Serializable::DIRTY_CUSTOM << 0, DIRTY_FLAGS = co::Serializable::DIRTY_CUSTOM << 1, DIRTY_VIEW = co::Serializable::DIRTY_CUSTOM << 2, DIRTY_MESSAGE = co::Serializable::DIRTY_CUSTOM << 3,
DIRTY_CAMERA = co::Serializable::DIRTY_CUSTOM << 0, DIRTY_FLAGS = co::Serializable::DIRTY_CUSTOM << 1, DIRTY_VIEW = co::Serializable::DIRTY_CUSTOM << 2, DIRTY_MESSAGE = co::Serializable::DIRTY_CUSTOM << 3
}
The changed parts of the data since the last pack().
enum DirtyBits {
DIRTY_CAMERA = co::Serializable::DIRTY_CUSTOM << 0, DIRTY_FLAGS = co::Serializable::DIRTY_CUSTOM << 1, DIRTY_VIEW = co::Serializable::DIRTY_CUSTOM << 2, DIRTY_MESSAGE = co::Serializable::DIRTY_CUSTOM << 3,
DIRTY_CAMERA = co::Serializable::DIRTY_CUSTOM << 0, DIRTY_FLAGS = co::Serializable::DIRTY_CUSTOM << 1, DIRTY_VIEW = co::Serializable::DIRTY_CUSTOM << 2, DIRTY_MESSAGE = co::Serializable::DIRTY_CUSTOM << 3
}
The changed parts of the data since the last pack().
void setMessage (const std::string &message)
const std::string & getMessage () const
void setMessage (const std::string &message)
const std::string & getMessage () const
virtual void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual ChangeType getChangeType () const
virtual void serialize (co::DataOStream &os, const uint64_t dirtyBits)
virtual void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
virtual ChangeType getChangeType () const
Additional Inherited Members
Protected Member Functions inherited from co::Serializable
CO_API Serializable ()
Construct a new Serializable.
CO_API Serializable (const Serializable &)
Construct an unmapped, unregistered copy of an serializable.
virtual CO_API ~Serializable ()
Destruct the serializable.
virtual CO_API void setDirty (const uint64_t bits)
Add dirty flags to mark data for distribution.
virtual CO_API void unsetDirty (const uint64_t bits)
Remove dirty flags to clear data from distribution.
virtual CO_API void notifyAttached ()
Notify that this object has been registered or mapped.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (Command &command)
The default handler for handling commands.
Protected Types inherited from co::Serializable
Detailed Description
Frame-specific data.
The frame-specific data is used as a per-config distributed object and contains mutable, rendering-relevant data. Each rendering thread (pipe) keeps its own instance synchronized with the frame currently being rendered. The data is managed by the Config, which modifies it directly.
Definition at line 44 of file share/Equalizer/examples/eqPly/frameData.h.
Member Enumeration Documentation
enum eqPly::FrameData::DirtyBits protected
The changed parts of the data since the last pack().
Reimplemented from co::Serializable.
Definition at line 124 of file share/Equalizer/examples/eqPly/frameData.h.
enum eqPly::FrameData::DirtyBits protected
The changed parts of the data since the last pack().
Reimplemented from co::Serializable.
Definition at line 124 of file share/Equalizer/examples/seqPly/frameData.h.
Member Function Documentation
void eqPly::FrameData::deserialize (co::DataIStream & is, const uint64_t dirtyBits) protected virtual
See also:
Object::deserialize()
Reimplemented from co::Serializable.
Definition at line 69 of file eqPly/frameData.cpp.
References eqNbody::FrameData::deserialize().
Referenced by eVolve::FrameData::deserialize().
virtual void eqPly::FrameData::deserialize (co::DataIStream & is, const uint64_t dirtyBits) protected virtual
See also:
Object::deserialize()
Reimplemented from co::Serializable.
virtual ChangeType eqPly::FrameData::getChangeType () const inline protected virtual
Returns:
how the changes are to be handled.
Reimplemented from co::Serializable.
Definition at line 121 of file share/Equalizer/examples/eqPly/frameData.h.
References co::Object::DELTA.
virtual ChangeType eqPly::FrameData::getChangeType () const inline protected virtual
Returns:
how the changes are to be handled.
Reimplemented from co::Serializable.
Definition at line 121 of file share/Equalizer/examples/seqPly/frameData.h.
References co::Object::DELTA.
void eqPly::FrameData::serialize (co::DataOStream & os, const uint64_t dirtyBits) protected virtual
See also:
Object::serialize()
Reimplemented from co::Serializable.
Definition at line 54 of file eqPly/frameData.cpp.
References eqNbody::FrameData::serialize().
Referenced by eVolve::FrameData::serialize().
virtual void eqPly::FrameData::serialize (co::DataOStream & os, const uint64_t dirtyBits) protected virtual
See also:
Object::serialize()
Reimplemented from co::Serializable.
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqPly/frameData.h
share/Equalizer/examples/seqPly/frameData.h
eqPly/frameData.cpp
seqPly/frameData.cpp