Equalizer: eq::Frame Class Reference
eq::Frame Class Reference
A holder for a frame data and related parameters.
#include <frame.h>
Public Member Functions
Frame ()
Construct a new frame.
virtual ~Frame ()
Destruct the frame.
Data Access
const std::string & getName () const
const Range & getRange () const
const Pixel & getPixel () const
const SubPixel & getSubPixel () const
uint32_t getPeriod () const
uint32_t getPhase () const
void setZoomFilter (const ZoomFilter zoomFilter)
Set the filter applied to zoomed assemble operations.
ZoomFilter getZoomFilter () const
const Images & getImages () const
void setData (FrameData *data)
Set the data for this frame.
FrameData * getData ()
const FrameData * getData () const
void setFrameData (FrameDataPtr data)
Set the data for this frame.
FrameDataPtr getFrameData ()
ConstFrameDataPtr getFrameData () const
uint32_t getBuffers () const
void disableBuffer (const Buffer buffer)
Disable the usage of a frame buffer attachment for all images.
void setAlphaUsage (const bool useAlpha)
Set alpha usage for newly allocated images.
void setQuality (const Frame::Buffer buffer, const float quality)
Set the minimum quality after compression.
void useCompressor (const Frame::Buffer buffer, const uint32_t name)
Sets a compressor for compression for following transmissions.
Operations
void clear ()
void deleteGLObjects (ObjectManager *om)
void readback (ObjectManager *glObjects, const DrawableConfig &config)
Read back an image.
void readback (ObjectManager *glObjects, const DrawableConfig &config, const PixelViewports &regions)
Read back a set of images.
Images startReadback (ObjectManager *glObjects, const DrawableConfig &config, const PixelViewports &regions)
Start reading back a set of images for this frame.
void setReady ()
Set the frame ready.
bool isReady () const
Test the readiness of the frame.
void waitReady (const uint32_t timeout=LB_TIMEOUT_INDEFINITE) const
Wait for the frame to become available.
void addListener (lunchbox::Monitor< uint32_t > &listener)
Add a listener which will be incremented when the frame is ready.
void removeListener (lunchbox::Monitor< uint32_t > &listener)
Remove a frame listener.
Public Member Functions inherited from eq::fabric::Frame
const std::vector< uint128_t > & getInputNodes (const Eye eye) const
const std::vector< uint128_t > & getInputNetNodes (const Eye eye) const
void setName (const std::string &name)
Set the name of the frame.
const Vector2i & getOffset () const
void setOffset (const Vector2i &offset)
Set the position of the frame wrt the channel.
void setZoom (const Zoom &zoom)
Set the zoom for this frame holder.
const Zoom & getZoom () const
const co::ObjectVersion & getDataVersion (const Eye) const
Public Member Functions inherited from co::Object
CO_API Object ()
Construct a new distributed object.
virtual CO_API ~Object ()
Destruct the distributed object.
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
virtual bool isDirty () const
Return if this object needs a commit.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
virtual CO_API uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
virtual void pack (DataOStream &os)
Serialize the modifications since the last call to commit().
virtual void unpack (DataIStream &is)
Deserialize a change.
CO_API bool send (NodePtr node, ObjectPacket &packet)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const std::string &string)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const void *data, const uint64_t size)
Send a packet to peer object instance(s) on another node.
template<class T >
bool send (NodePtr node, ObjectPacket &packet, const std::vector< T > &v)
Send a packet to peer object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyAttached ()
Notify that this object has been registered or mapped.
virtual CO_API void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (Command &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void attach (const UUID &id, const uint32_t instanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (CommandPtr command)
Dispatch a command from the receiver thread to the registered queue.
Additional Inherited Members
Public Types inherited from eq::fabric::Frame
enum Buffer {
BUFFER_NONE = LB_BIT_NONE, BUFFER_UNDEFINED = LB_BIT1, BUFFER_COLOR = LB_BIT5, BUFFER_DEPTH = LB_BIT9,
BUFFER_ALL = LB_BIT_ALL_32
}
The buffer format defines which components of the frame are to be used during readback and assembly.
enum Type { TYPE_MEMORY, TYPE_TEXTURE }
The storage type for pixel data.
Public Types inherited from co::Object
enum ChangeType {
NONE, STATIC, INSTANCE, DELTA,
UNBUFFERED
}
Object change handling characteristics, see Programming Guide.
Public Types inherited from co::Dispatcher
typedef CommandFunc< Dispatcher > Func
Protected Member Functions inherited from eq::fabric::Frame
virtual ChangeType getChangeType () const
virtual void getInstanceData (co::DataOStream &os)
Serialize all instance information of this distributed object.
virtual void applyInstanceData (co::DataIStream &is)
Deserialize the instance data.
void _setDataVersion (const unsigned i, const co::ObjectVersion &ov)
std::vector< uint128_t > & _getInputNodes (const unsigned i)
std::vector< uint128_t > & _getInputNetNodes (const unsigned i)
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (Command &command)
The default handler for handling commands.
Detailed Description
A holder for a frame data and related parameters.
A Frame has to be set up with a FrameData which ultimately holds the pixel data using images. Input and output frames provided by the eq::Channel are set up correctly with FrameData to connect one output frame to one ore more input frames. Some Frame parameters are (input-)frame-specific, while others are set by the output frame on its data and therefore shared between all input frames.
Definition at line 41 of file client/frame.h.
Constructor & Destructor Documentation
eq::Frame::Frame ()
Construct a new frame.
Version:
1.0
Reimplemented from eq::fabric::Frame.
virtual eq::Frame::~Frame () virtual
Destruct the frame.
Version:
1.0
Reimplemented from eq::fabric::Frame.
Member Function Documentation
void eq::Frame::addListener (lunchbox::Monitor< uint32_t > & listener)
Add a listener which will be incremented when the frame is ready.
Parameters:
listener the listener.
Version:
1.0
void eq::Frame::disableBuffer (const Buffer buffer)
Disable the usage of a frame buffer attachment for all images.
Parameters:
buffer the buffer to disable.
Version:
1.0
Referenced by eVolve::Channel::frameReadback().
uint32_t eq::Frame::getBuffers () const
Returns:
the enabled frame buffer attachments.
Version:
1.0
FrameData* eq::Frame::getData ()
Returns:
the frame's data.
Deprecated:
const FrameData* eq::Frame::getData () const
Returns:
the frame's data.
Deprecated:
FrameDataPtr eq::Frame::getFrameData ()
Returns:
the frame's data.
Version:
1.3.2
Referenced by eVolve::Channel::frameAssemble(), and eVolve::Channel::frameReadback().
ConstFrameDataPtr eq::Frame::getFrameData () const
Returns:
the frame's data.
Version:
1.4
const Images& eq::Frame::getImages () const
Returns:
all images of this frame.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble().
const std::string& eq::Frame::getName () const
Returns:
the name of the frame.
Version:
1.0
Reimplemented from eq::fabric::Frame.
uint32_t eq::Frame::getPeriod () const
Returns:
the DPlex period relative to the destination channel.
Version:
1.0
Referenced by eqPly::Channel::frameAssemble().
uint32_t eq::Frame::getPhase () const
Returns:
the DPlex phase relative to the destination channel.
Version:
1.0
const Pixel& eq::Frame::getPixel () const
Returns:
the pixel parameters relative to the destination channel.
Version:
1.0
const Range& eq::Frame::getRange () const
Returns:
the database range relative to the destination channel.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble().
const SubPixel& eq::Frame::getSubPixel () const
Returns:
the subpixel parameters wrt the destination channel.
Version:
1.0
Referenced by eqPly::Channel::frameAssemble().
ZoomFilter eq::Frame::getZoomFilter () const
Returns:
the filter applied to zoomed assemble operations.
Version:
1.0
bool eq::Frame::isReady () const
Test the readiness of the frame.
Returns:
true if the frame is ready, false if not.
Version:
1.0
void eq::Frame::readback (ObjectManager * glObjects, const DrawableConfig & config)
Read back an image.
The image is added to the data, existing images are retained.
Parameters:
glObjects the GL object manager for the current GL context.
config the configuration of the source frame buffer.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble().
void eq::Frame::readback (ObjectManager * glObjects, const DrawableConfig & config, const PixelViewports & regions)
Read back a set of images.
The images are added to the data, existing images are retained.
Parameters:
glObjects the GL object manager for the current GL context.
config the configuration of the source frame buffer.
regions the areas to read back.
Version:
1.0
void eq::Frame::removeListener (lunchbox::Monitor< uint32_t > & listener)
Remove a frame listener.
Parameters:
listener the listener.
Version:
1.0
void eq::Frame::setAlphaUsage (const bool useAlpha)
Set alpha usage for newly allocated images.
Version:
1.0
Referenced by eqPly::Channel::frameReadback().
void eq::Frame::setData (FrameData * data)
Set the data for this frame.
Deprecated:
void eq::Frame::setFrameData (FrameDataPtr data)
Set the data for this frame.
Version:
1.3.2
Referenced by eqPixelBench::Channel::Channel(), and eVolve::Channel::Channel().
void eq::Frame::setQuality (const Frame::Buffer buffer, const float quality)
Set the minimum quality after compression.
Version:
1.0
Referenced by eVolve::Channel::frameReadback(), and eqPly::Channel::frameReadback().
void eq::Frame::setReady ()
Set the frame ready.
Equalizer sets the frame automatically ready after readback and after network transmission.
Version:
1.0
void eq::Frame::setZoomFilter (const ZoomFilter zoomFilter)
Set the filter applied to zoomed assemble operations.
Version:
1.0
Images eq::Frame::startReadback (ObjectManager * glObjects, const DrawableConfig & config, const PixelViewports & regions)
Start reading back a set of images for this frame.
The newly read images are added to the data, existing images are retained. The finish for the new images has to be done by the caller. The regions are relative to the current OpenGL viewport.
Parameters:
glObjects the GL object manager for the current GL context.
config the configuration of the source frame buffer.
regions the areas to read back.
Returns:
the new images which need finishReadback.
Version:
1.3.2
void eq::Frame::useCompressor (const Frame::Buffer buffer, const uint32_t name)
Sets a compressor for compression for following transmissions.
Referenced by eqPly::Channel::frameReadback().
void eq::Frame::waitReady (const uint32_t timeout = LB_TIMEOUT_INDEFINITE) const
Wait for the frame to become available.
Version:
1.0
Referenced by eVolve::Channel::frameAssemble().
The documentation for this class was generated from the following file:
client/frame.h