Equalizer: eq::fabric::ConfigVisitor< C, OV, LV, CV, NV > Class Template Reference
eq::fabric::ConfigVisitor< C, OV, LV, CV, NV > Class Template Reference
A visitor to traverse configs and all children.
#include <configVisitor.h>
Public Member Functions
ConfigVisitor ()
Construct a new config visitor.
virtual ~ConfigVisitor ()
Destruct this config visitor.
virtual VisitorResult visitPre (C *config)
Visit a config on the down traversal.
virtual VisitorResult visitPost (C *config)
Visit a config on the up traversal.
virtual VisitorResult visitPre (const C *)
Visit a config on the down traversal.
virtual VisitorResult visitPost (const C *)
Visit a config on the up traversal.
Detailed Description
template<class C, class OV, class LV, class CV, class NV>
class eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >
A visitor to traverse configs and all children.
See also:
Config::accept()
Definition at line 30 of file configVisitor.h.
Constructor & Destructor Documentation
template<class C , class OV , class LV , class CV , class NV > eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::ConfigVisitor () inline
Construct a new config visitor.
Version:
1.0
Definition at line 34 of file configVisitor.h.
template<class C , class OV , class LV , class CV , class NV > virtual eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::~ConfigVisitor () inline virtual
Destruct this config visitor.
Version:
1.0
Definition at line 37 of file configVisitor.h.
Member Function Documentation
template<class C , class OV , class LV , class CV , class NV > virtual VisitorResult eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::visitPost (C * config) inline virtual
Visit a config on the up traversal.
Version:
1.0
Definition at line 44 of file configVisitor.h.
References eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::visitPost().
Referenced by eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::visitPost().
template<class C , class OV , class LV , class CV , class NV > virtual VisitorResult eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::visitPost (const C *) inline virtual
Visit a config on the up traversal.
Version:
1.0
Definition at line 52 of file configVisitor.h.
References eq::fabric::TRAVERSE_CONTINUE.
template<class C , class OV , class LV , class CV , class NV > virtual VisitorResult eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::visitPre (C * config) inline virtual
Visit a config on the down traversal.
Version:
1.0
Definition at line 40 of file configVisitor.h.
References eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::visitPre().
Referenced by eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::visitPre().
template<class C , class OV , class LV , class CV , class NV > virtual VisitorResult eq::fabric::ConfigVisitor< C, OV, LV, CV, NV >::visitPre (const C *) inline virtual
Visit a config on the down traversal.
Version:
1.0
Definition at line 48 of file configVisitor.h.
References eq::fabric::TRAVERSE_CONTINUE.
The documentation for this class was generated from the following file:
configVisitor.h