Equalizer: eq::Window Class Reference
eq::Window Class Reference
A Window represents an on-screen or off-screen drawable.
#include <window.h>
Public Member Functions
Window (Pipe *parent)
Construct a new window.
virtual ~Window ()
Destruct the window.
Data Access
co::CommandQueue * getPipeThreadQueue ()
co::CommandQueue * getCommandThreadQueue ()
uint32_t getCurrentFrame () const
const Node * getNode () const
Node * getNode ()
const Config * getConfig () const
Config * getConfig ()
ClientPtr getClient ()
ServerPtr getServer ()
bool isRunning () const
bool isStopped () const
bool getRenderContext (const int32_t x, const int32_t y, RenderContext &context) const
Get the last rendering context at the x, y position.
OpenGL context handling and sharing
void setSharedContextWindow (Window *sharedContextWindow)
Set the window with which this window shares the OpenGL context.
const Window * getSharedContextWindow () const
Window * getSharedContextWindow ()
ObjectManager * getObjectManager ()
const ObjectManager * getObjectManager () const
const Font * getSmallFont ()
const Font * getMediumFont ()
const GLEWContext * glewGetContext () const
Get the GLEW context for this window.
const GLEWContext * getTransferGlewContext ()
uint32_t getColorFormat () const
SystemWindow interface
void setSystemWindow (SystemWindow *window)
Set the OS-specific window.
const SystemWindow * getSystemWindow () const
SystemWindow * getSystemWindow ()
const SystemPipe * getSystemPipe () const
SystemPipe * getSystemPipe ()
const eq::SystemWindow * getTransferSystemWindow ()
void deleteTransferSystemWindow ()
Public Member Functions inherited from eq::fabric::Window< Pipe, Window, Channel >
EQFABRIC_INL WindowPath getPath () const
void init ()
const Pipe * getPipe () const
Pipe * getPipe ()
const Channels & getChannels () const
const DrawableConfig & getDrawableConfig () const
const PixelViewport & getPixelViewport () const
const Viewport & getViewport () const
virtual EQFABRIC_INL void setPixelViewport (const PixelViewport &pvp)
Set the window's pixel viewport wrt its parent pipe.
EQFABRIC_INL void setViewport (const Viewport &vp)
Set the window's viewport wrt its parent pipe.
bool hasFixedViewport () const
EQFABRIC_INL VisitorResult accept (Visitor &visitor)
Traverse this window and all children using a window visitor.
EQFABRIC_INL VisitorResult accept (Visitor &visitor) const
Const-version of accept().
virtual EQFABRIC_INL void backup ()
virtual EQFABRIC_INL void restore ()
void create (Channel **channel)
void release (Channel *channel)
virtual void output (std::ostream &) const
virtual EQFABRIC_INL uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
void setIAttribute (const IAttribute attr, const int32_t value)
Set a window attribute.
int32_t getIAttribute (const IAttribute attr) const
Public Member Functions inherited from eq::fabric::Object
virtual bool isDirty () const
void setName (const std::string &name)
Set the name of the object.
const std::string & getName () const
void setUserData (co::Object *userData)
Set user-specific data.
co::Object * getUserData ()
const co::Object * getUserData () const
void setError (const int32_t error)
Set an error code why the last operation failed.
co::Error getError () const
uint32_t getTasks () const
Return the set of tasks this channel might execute in the worst case.
uint32_t getSerial () const
Public Member Functions inherited from co::Serializable
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
Public Member Functions inherited from co::Object
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API bool send (NodePtr node, ObjectPacket &packet)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const std::string &string)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const void *data, const uint64_t size)
Send a packet to peer object instance(s) on another node.
template<class T >
bool send (NodePtr node, ObjectPacket &packet, const std::vector< T > &v)
Send a packet to peer object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (Command &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (CommandPtr command)
Dispatch a command from the receiver thread to the registered queue.
Public Types
typedef eq::ObjectManager ObjectManager
The per-window OpenGL object manager.
typedef BitmapFont Font
Fonts used for overlays.
Public Types inherited from eq::fabric::Window< Pipe, Window, Channel >
typedef std::vector< Channel * > Channels
A vector of pointers to channels.
typedef ElementVisitor< Window,
LeafVisitor< Channel > > Visitor
The Window visitor type.
enum IAttribute
Window attributes.
Public Types inherited from eq::fabric::Object
Protected Member Functions
virtual void attach (const UUID &id, const uint32_t instanceID)
Protected Member Functions inherited from eq::fabric::Window< Pipe, Window, Channel >
Window (Pipe *parent)
virtual EQFABRIC_INL void serialize (co::DataOStream &os, const uint64_t dirtyBits)
Worker for pack() and getInstanceData().
virtual EQFABRIC_INL void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
Worker for unpack() and applyInstanceData().
virtual EQFABRIC_INL void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual EQFABRIC_INL void setDirty (const uint64_t bits)
void _setDrawableConfig (const DrawableConfig &drawableConfig)
virtual ChangeType getChangeType () const
Channel * _findChannel (const UUID &id)
virtual uint64_t getRedistributableBits () const
Protected Member Functions inherited from eq::fabric::Object
Object ()
Construct a new Object.
virtual ~Object ()
Destruct the object.
virtual bool hasMasterUserData ()
virtual uint32_t getUserDataLatency () const
void setTasks (const uint32_t tasks)
void postRemove (Object *child)
virtual void removeChild (const UUID &)
template<class C , class PKG , class S >
void commitChild (C *child, S *sender, const uint32_t incarnation)
template<class C >
void commitChild (C *child, const uint32_t incarnation)
template<class C , class PKG , class S >
void commitChildren (const std::vector< C * > &children, S *sender, const uint32_t incarnation)
template<class C , class PKG >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void commitChildren (const std::vector< C * > &children, const uint32_t incarnation)
template<class C >
void syncChildren (const std::vector< C * > &children)
template<class P , class C >
void releaseChildren (const std::vector< C * > &children)
bool _cmdSync (co::Command &command)
Protected Member Functions inherited from co::Serializable
CO_API Serializable ()
Construct a new Serializable.
CO_API Serializable (const Serializable &)
Construct an unmapped, unregistered copy of an serializable.
virtual CO_API ~Serializable ()
Destruct the serializable.
virtual CO_API void unsetDirty (const uint64_t bits)
Remove dirty flags to clear data from distribution.
virtual CO_API void notifyAttached ()
Notify that this object has been registered or mapped.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (Command &command)
The default handler for handling commands.
Friends
class Pipe
class Channel
Actions
virtual void flush () const
Flush outstanding rendering requests.
virtual void finish () const
Finish outstanding rendering requests.
virtual void swapBuffers ()
Swap the front and back buffer of the window.
virtual void drawFPS ()
Render the current framerate as on overlay.
float getFPS () const
virtual void makeCurrent (const bool cache=true) const
Make the window's drawable and context current.
void makeCurrentTransfer (const bool cache=true)
virtual void bindFrameBuffer () const
virtual void notifyViewportChanged ()
void startFrame (const uint32_t frameNumber)
Start a frame by unlocking all child resources.
void releaseFrame (const uint32_t frameNumber)
Signal the completion of a frame to the parent.
void releaseFrameLocal (const uint32_t frameNumber)
Signal the release of the local synchronization to the parent.
Callbacks
The callbacks are called by Equalizer during rendering to execute various actions.
virtual bool processEvent (const Event &event)
Process a received event.
virtual bool configInit (const uint128_t &initID)
Initialize this window.
virtual bool configInitSystemWindow (const uint128_t &initID)
Initialize the OS-specific window.
virtual bool configInitGL (const uint128_t &initID)
Initialize the OpenGL state for this window.
virtual bool configExit ()
Exit this window.
virtual bool configExitSystemWindow ()
De-initialize the OS-specific window.
virtual bool configExitGL ()
De-initialize the OpenGL state for this window.
virtual void frameStart (const uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
virtual void frameFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish rendering a frame.
virtual void frameDrawFinish (const uint128_t &frameID, const uint32_t frameNumber)
Finish drawing.
Additional Inherited Members
Static Public Member Functions inherited from eq::fabric::Window< Pipe, Window, Channel >
static EQFABRIC_INL const
std::string & getIAttributeString (const IAttribute attr)
Protected Types inherited from eq::fabric::Window< Pipe, Window, Channel >
enum DirtyBits
The changed parts of the object since the last pack().
Detailed Description
A Window represents an on-screen or off-screen drawable.
A drawable is a 2D rendering surface, typically attached to an OpenGL context. A window uses an SystemWindow implementation to manage the operating system specific handling of window and context creation.
A Window is a child of a Pipe. The task methods for all windows of a pipe are executed in the same pipe thread. All window and subsequent channel task methods are executed in the order the windows are defined on the pipe, with the exception of the swap and finish tasks, which are executed after all windows have been updated. This ensures that all windows of a given pipe swap at the same time.
The default window initialization methods initialize all windows of the same pipe with a shared context, so that OpenGL objects can be reused between them for optimal GPU memory usage. The window facilitates OpenGL object management by providing an ObjectManager for allocating and sharing OpenGL objects.
Please note that each window potentially has its own OpenGL command buffer, thus glFlush is needed to synchronize the state of OpenGL objects between windows. Therefore, Equalizer calls flush() at the end of each frame for each window.
See also:
fabric::Window
Definition at line 63 of file include/eq/client/window.h.
Member Typedef Documentation
typedef BitmapFont eq::Window::Font
Fonts used for overlays.
Version:
1.0
Definition at line 70 of file include/eq/client/window.h.
typedef eq::ObjectManager eq::Window::ObjectManager
The per-window OpenGL object manager.
Version:
1.0
Definition at line 67 of file include/eq/client/window.h.
Constructor & Destructor Documentation
eq::Window::Window (Pipe * parent)
Construct a new window.
Version:
1.0
Reimplemented in eqAsync::Window, eqPly::Window, osgScaleViewer::Window, eqNbody::Window, eqPixelBench::Window, and eVolve::Window.
virtual eq::Window::~Window () virtual
Destruct the window.
Version:
1.0
Reimplemented from eq::fabric::Window< Pipe, Window, Channel >.
Reimplemented in eqPly::Window, eVolve::Window, osgScaleViewer::Window, and eqNbody::Window.
Member Function Documentation
virtual bool eq::Window::configExit () protected virtual
Exit this window.
Version:
1.0
virtual bool eq::Window::configExitGL () inline protected virtual
De-initialize the OpenGL state for this window.
Version:
1.0
Reimplemented in eqPly::Window, and osgScaleViewer::Window.
Definition at line 393 of file include/eq/client/window.h.
virtual bool eq::Window::configExitSystemWindow () protected virtual
De-initialize the OS-specific window.
Version:
1.0
Referenced by eqPly::Window::configInitSystemWindow().
virtual bool eq::Window::configInit (const uint128_t & initID) protected virtual
Initialize this window.
Parameters:
initID the init identifier.
Version:
1.0
Reimplemented in eVolve::Window, and eqPixelBench::Window.
virtual bool eq::Window::configInitGL (const uint128_t & initID) protected virtual
Initialize the OpenGL state for this window.
Parameters:
initID the init identifier.
Returns:
true if the initialization was successful, false if not.
Version:
1.0
Reimplemented in eqAsync::Window, eqPly::Window, eVolve::Window, and osgScaleViewer::Window.
Referenced by osgScaleViewer::Window::configInitGL(), eqAsync::Window::configInitGL(), and eqPly::Window::configInitGL().
virtual bool eq::Window::configInitSystemWindow (const uint128_t & initID) protected virtual
Initialize the OS-specific window.
See also:
setSystemWindow()
Version:
1.0
Reimplemented in eqPly::Window.
Referenced by eqPly::Window::configInitSystemWindow().
virtual void eq::Window::drawFPS () virtual
Render the current framerate as on overlay.
Version:
1.0
virtual void eq::Window::finish () const inline virtual
Finish outstanding rendering requests.
Called before a software swap barrier to ensure that the window will swap directly after the barrier is left.
Version:
1.0
Definition at line 222 of file include/eq/client/window.h.
virtual void eq::Window::flush () const inline virtual
Flush outstanding rendering requests.
Called at the end of each frame from frameFinish() to ensure timely execution of pending rendering requests.
Version:
1.0
Definition at line 213 of file include/eq/client/window.h.
virtual void eq::Window::frameDrawFinish (const uint128_t & frameID, const uint32_t frameNumber) protected virtual
Finish drawing.
Called once per frame after the last draw operation. Typically releases the local node thread synchronization for this frame.
Parameters:
frameID the per-frame identifier.
frameNumber the frame to finished with draw.
Version:
1.0
virtual void eq::Window::frameFinish (const uint128_t & frameID, const uint32_t frameNumber) protected virtual
Finish rendering a frame.
Called once at the end of each frame, to do per-frame updates of window-specific data. This method has to call releaseFrame(). The default implementation also flushes all rendering commands. This light-weight call ensures that all outstanding rendering commands for the window's context are being executed in a timely fashion.
Parameters:
frameID the per-frame identifier.
frameNumber the frame to finish.
Version:
1.0
virtual void eq::Window::frameStart (const uint128_t & frameID, const uint32_t frameNumber) protected virtual
Start rendering a frame.
Called once at the beginning of each frame, to do per-frame updates of window-specific data. This method has to call startFrame().
Parameters:
frameID the per-frame identifier.
frameNumber the frame to start.
Version:
1.0
Reimplemented in eqPly::Window.
ClientPtr eq::Window::getClient ()
Returns:
the Client of this window.
Version:
1.0
const Config* eq::Window::getConfig () const
Returns:
the Config of this window.
Version:
1.0
Referenced by eqPly::Window::configInitGL().
Config* eq::Window::getConfig ()
Returns:
the Config of this window.
Version:
1.0
float eq::Window::getFPS () const inline
Returns:
the window's average framerate.
Version:
1.0
Definition at line 231 of file include/eq/client/window.h.
const Font* eq::Window::getMediumFont ()
Returns:
a medium bitmap font used for overlays.
Warning:
experimental - may not be supported in the future.
const Node* eq::Window::getNode () const
Returns:
the Node of this window.
Version:
1.0
Referenced by osgScaleViewer::Window::configInitGL().
Node* eq::Window::getNode ()
Returns:
the Node of this window.
Version:
1.0
ObjectManager* eq::Window::getObjectManager () inline
Returns:
the window's object manager instance.
Version:
1.0
Definition at line 154 of file include/eq/client/window.h.
Referenced by eqPly::Window::configInitGL().
const ObjectManager* eq::Window::getObjectManager () const inline
Returns:
the window's object manager instance.
Version:
1.0
Definition at line 157 of file include/eq/client/window.h.
bool eq::Window::getRenderContext (const int32_t x, const int32_t y, RenderContext & context) const
Get the last rendering context at the x, y position.
If no render context is found on the given position, false is returned and context is not modified.
Returns:
true if a render context was found, false otherwise.
Warning:
experimental - may not be supported in the future.
ServerPtr eq::Window::getServer ()
Returns:
the Server of this window.
Version:
1.0
const Window* eq::Window::getSharedContextWindow () const inline
Returns:
the window with which this window shares the GL context.
Version:
1.0
Definition at line 144 of file include/eq/client/window.h.
Referenced by osgScaleViewer::Window::configInitGL().
Window* eq::Window::getSharedContextWindow () inline
Returns:
the window with which this window shares the GL context.
Version:
1.0
Definition at line 151 of file include/eq/client/window.h.
const Font* eq::Window::getSmallFont ()
Returns:
a small bitmap font used for overlays.
Warning:
experimental - may not be supported in the future.
const SystemPipe* eq::Window::getSystemPipe () const
Returns:
the OS-specific pipe implementation.
Version:
1.0
SystemPipe* eq::Window::getSystemPipe ()
Returns:
the OS-specific pipe implementation.
Version:
1.0
const SystemWindow* eq::Window::getSystemWindow () const inline
Returns:
the OS-specific window implementation.
Version:
1.0
Definition at line 270 of file include/eq/client/window.h.
SystemWindow* eq::Window::getSystemWindow () inline
Returns:
the OS-specific window implementation.
Version:
1.0
Definition at line 273 of file include/eq/client/window.h.
const GLEWContext* eq::Window::glewGetContext () const
Get the GLEW context for this window.
The glew context is provided and initialized by the SystemWindow, and provides access to OpenGL extensions. This function does not follow the Equalizer naming conventions, since GLEW uses a function of this name to automatically resolve OpenGL function entry points. Therefore, any OpenGL function support by the driver can be directly called from any method of an initialized window.
Returns:
the extended OpenGL function table for the window's OpenGL context.
Version:
1.0
Referenced by eVolve::Window::configInitGL().
bool eq::Window::isRunning () const inline
Returns:
true if this window is running, false otherwise.
Version:
1.0
Definition at line 106 of file include/eq/client/window.h.
bool eq::Window::isStopped () const inline
Returns:
true if this window is stopped, false otherwise.
Version:
1.0
Definition at line 112 of file include/eq/client/window.h.
virtual void eq::Window::makeCurrent (const bool cache = true) const virtual
Make the window's drawable and context current.
GL drivers tend to behave sub-optimally if too many makeCurrent calls happen in a multi-threaded program. When caching is enabled, this method will only call SystemWindow::makeCurrent if it has not been done before for this window on this thread.
Version:
1.3.2
virtual bool eq::Window::processEvent (const Event & event) virtual
Process a received event.
The task of this method is to update the window as necessary, and transform the event into an config event to be send to the application using Config::sendEvent().
Parameters:
event the received window system event.
Returns:
true when the event was handled, false if not.
Version:
1.0
void eq::Window::releaseFrame (const uint32_t frameNumber) protected
Signal the completion of a frame to the parent.
Parameters:
frameNumber the frame to end.
Version:
1.0
void eq::Window::releaseFrameLocal (const uint32_t frameNumber) protected
Signal the release of the local synchronization to the parent.
Parameters:
frameNumber the frame to release.
Version:
1.0
void eq::Window::setSharedContextWindow (Window * sharedContextWindow) inline
Set the window with which this window shares the OpenGL context.
By default it is set to the first window of the pipe in the window's constructor. The shared context window is used during initialization to setup the OpenGL context and util::ObjectManager.
Version:
1.0
Definition at line 137 of file include/eq/client/window.h.
void eq::Window::setSystemWindow (SystemWindow * window)
Set the OS-specific window.
The SystemWindow implements the window-system-dependent part, e.g., the drawable creation. This window forwards certain calls, e.g., swapBuffers(), to the SystemWindow. The os-specific window has to be initialized.
Version:
1.0
void eq::Window::startFrame (const uint32_t frameNumber) protected
Start a frame by unlocking all child resources.
Parameters:
frameNumber the frame to start.
Version:
1.0
virtual void eq::Window::swapBuffers () virtual
Swap the front and back buffer of the window.
Version:
1.0
Reimplemented in eVolve::Window, and eqNbody::Window.
Referenced by eqNbody::Window::swapBuffers().
The documentation for this class was generated from the following file:
include/eq/client/window.h