Equalizer: eqNbody::FrameData Class Reference
eqNbody::FrameData Class Reference
Public Member Functions
void init (unsigned int numBodies)
void initHostData ()
void exit ()
void updateParameters (NBodyConfig config, float clusterScale, float velocityScale, float ts)
void toggleStatistics ()
bool useStatistics () const
unsigned int getNumDataProxies (void) const
eq::uint128_t getProxyID (unsigned int ndx) const
eq::uint128_t getProxyVersion (unsigned int ndx) const
eq::uint128_t getVersionForProxyID (const eq::uint128_t &pid) const
void addProxyID (const eq::uint128_t &pid, const float *range)
void updateProxyID (const eq::uint128_t &pid, const eq::uint128_t &version, const float *range)
virtual eq::uint128_t commit ()
bool isReady ()
const float * getPosData () const
const float * getVelData () const
const float * getColData () const
float getTimeStep () const
float getClusterScale () const
float getVelocityScale () const
float * getPos () const
float * getVel () const
float * getCol () const
uint32_t getNumBytes (void) const
uint32_t getNumBodies (void) const
Public Member Functions inherited from co::Serializable
CO_API uint64_t getDirty () const
virtual CO_API bool isDirty () const
virtual CO_API bool isDirty (const uint64_t dirtyBits) const
virtual CO_API uint128_t commit (const uint32_t incarnation=CO_COMMIT_NEXT)
Commit a new version of this object.
Public Member Functions inherited from co::Object
CO_API Object ()
Construct a new distributed object.
virtual CO_API ~Object ()
Destruct the distributed object.
bool isAttached () const
LocalNodePtr getLocalNode ()
CO_API void setID (const UUID &identifier)
Set the object's unique identifier.
const UUID & getID () const
uint32_t getInstanceID () const
CO_API bool isBuffered () const
CO_API bool isMaster () const
virtual uint64_t getMaxVersions () const
Limit the number of queued versions of slave instances.
virtual CO_API uint32_t chooseCompressor () const
Return the compressor to be used for data transmission.
CO_API void push (const uint128_t &groupID, const uint128_t &objectType, const Nodes &nodes)
Push the instance data of the object to the given nodes.
CO_API void setAutoObsolete (const uint32_t count)
Automatically obsolete old versions.
CO_API uint32_t getAutoObsolete () const
virtual CO_API uint128_t sync (const uint128_t &version=VERSION_HEAD)
Sync to a given version.
CO_API uint128_t getHeadVersion () const
CO_API uint128_t getVersion () const
virtual CO_API void notifyNewHeadVersion (const uint128_t &version)
Notification that a new head version was received by a slave object.
virtual void notifyNewVersion ()
Notification that a new version was received by a master object.
CO_API bool send (NodePtr node, ObjectPacket &packet)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const std::string &string)
Send a packet to peer object instance(s) on another node.
CO_API bool send (NodePtr node, ObjectPacket &packet, const void *data, const uint64_t size)
Send a packet to peer object instance(s) on another node.
template<class T >
bool send (NodePtr node, ObjectPacket &packet, const std::vector< T > &v)
Send a packet to peer object instance(s) on another node.
virtual void notifyAttach ()
Notify that this object will be registered or mapped.
virtual CO_API void notifyDetach ()
Notify that this object will be deregistered or unmapped.
virtual void notifyDetached ()
Notify that this object has been deregistered or unmapped.
uint32_t getMasterInstanceID () const
NodePtr getMasterNode ()
void addSlave (Command &command)
CO_API void removeSlave (NodePtr node, const uint32_t instanceID)
CO_API void removeSlaves (NodePtr node)
void setMasterNode (NodePtr node)
void addInstanceDatas (const ObjectDataIStreamDeque &, const uint128_t &)
void setupChangeManager (const Object::ChangeType type, const bool master, LocalNodePtr localNode, const uint32_t masterInstanceID)
virtual CO_API void attach (const UUID &id, const uint32_t instanceID)
virtual CO_API void detach ()
void transfer (Object *from)
void applyMapData (const uint128_t &version)
void sendInstanceData (Nodes &nodes)
Public Member Functions inherited from co::Dispatcher
CO_API Dispatcher (const Dispatcher &from)
const Dispatcher & operator= (const Dispatcher &)
NOP assignment operator.
virtual CO_API bool dispatchCommand (CommandPtr command)
Dispatch a command from the receiver thread to the registered queue.
Protected Member Functions
virtual void serialize (co::DataOStream &os, const uint64_t dirtyBits)
Worker for pack() and getInstanceData().
virtual void deserialize (co::DataIStream &is, const uint64_t dirtyBits)
Worker for unpack() and applyInstanceData().
Protected Member Functions inherited from co::Serializable
CO_API Serializable ()
Construct a new Serializable.
CO_API Serializable (const Serializable &)
Construct an unmapped, unregistered copy of an serializable.
virtual CO_API ~Serializable ()
Destruct the serializable.
virtual ChangeType getChangeType () const
virtual CO_API void setDirty (const uint64_t bits)
Add dirty flags to mark data for distribution.
virtual CO_API void unsetDirty (const uint64_t bits)
Remove dirty flags to clear data from distribution.
virtual CO_API void notifyAttached ()
Notify that this object has been registered or mapped.
Protected Member Functions inherited from co::Object
CO_API Object (const Object &)
Copy constructor.
const Object & operator= (const Object &)
NOP assignment operator.
Protected Member Functions inherited from co::Dispatcher
template<typename T >
void registerCommand (const uint32_t command, const CommandFunc< T > &func, CommandQueue *destinationQueue)
Registers a command member function for a command.
CO_API bool _cmdUnknown (Command &command)
The default handler for handling commands.
Protected Types
enum DirtyBits { DIRTY_DATA = co::Serializable::DIRTY_CUSTOM << 0, DIRTY_PROXYDATA = co::Serializable::DIRTY_CUSTOM << 1, DIRTY_FLAGS = co::Serializable::DIRTY_CUSTOM << 2 }
The changed parts of the serializable since the last pack().
Protected Types inherited from co::Serializable
Detailed Description
Definition at line 46 of file share/Equalizer/examples/eqNBody/frameData.h.
Member Enumeration Documentation
enum eqNbody::FrameData::DirtyBits protected
The changed parts of the serializable since the last pack().
Subclasses should define their own bits, starting at DIRTY_CUSTOM.
Version:
1.0
Reimplemented from co::Serializable.
Definition at line 100 of file share/Equalizer/examples/eqNBody/frameData.h.
Member Function Documentation
void eqNbody::FrameData::deserialize (co::DataIStream & , const uint64_t) protected virtual
Worker for unpack() and applyInstanceData().
This function is called with the dirty bits send by the master instance. The dirty bits are received beforehand, and do not need to be deserialized by the overriding method.
See also:
serialize()
Version:
1.0
Reimplemented from co::Serializable.
Definition at line 81 of file eqNBody/frameData.cpp.
References co::Serializable::deserialize(), and co::DataIStream::read().
Referenced by eqPly::FrameData::deserialize().
void eqNbody::FrameData::serialize (co::DataOStream & , const uint64_t) protected virtual
Worker for pack() and getInstanceData().
Override this and deserialize() if you want to distribute subclassed data.
This method is called with DIRTY_ALL from getInstanceData() and with the actual dirty bits from pack(), which also resets the dirty state afterwards. The dirty bits are transmitted beforehand, and do not need to be transmitted by the overriding method.
Version:
1.0
Reimplemented from co::Serializable.
Definition at line 57 of file eqNBody/frameData.cpp.
References co::Serializable::serialize(), and co::DataOStream::write().
Referenced by eqPly::FrameData::serialize().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqNBody/frameData.h
eqNBody/frameData.cpp