Equalizer: eqPly Namespace Reference
eqPly Namespace Reference
The Equalizer polygonal rendering example.
Classes
class CameraAnimation
Loads sequence of camera positions and interpolates them on a per-frame basis.
class Channel
The rendering entity, updating a part of a Window.
class Config
The configuration, run be the EqPly application.
struct ConfigEvent
class EqPly
The EqPly application instance.
class FrameData
Frame-specific data.
class InitData
class LocalInitData
Manages the argument parsing and non-distributed part of the initialization data.
class ModelAssigner
Helper to assign models to views.
class Node
Representation of a node in the cluster.
class Pipe
The representation of one GPU.
class Tracker
class VertexBufferDist
co::Object to distribute a model, holds a VertexBufferBase node.
class VertexBufferState
class View
class Window
A window represent an OpenGL drawable and context.
Functions
std::ostream & operator<< (std::ostream &os, const ConfigEvent *event)
void initErrors ()
Set up eqPly-specific error codes.
void exitErrors ()
Clear eqPly-specific error codes.
Typedefs
typedef mesh::VertexBufferRoot Model
typedef VertexBufferDist ModelDist
typedef std::vector< Model * > Models
typedef std::vector< ModelDist * > ModelDists
typedef Models::const_iterator ModelsCIter
typedef ModelDists::const_iterator ModelDistsCIter
Enumerations
enum ColorMode { COLOR_MODEL, COLOR_DEMO, COLOR_WHITE, COLOR_ALL }
enum LogTopics { LOG_STATS = eq::LOG_CUSTOM << 0, LOG_CULL = eq::LOG_CUSTOM << 1 }
enum Error { ERROR_EQPLY_MAPOBJECT_FAILED = eq::ERROR_CUSTOM }
Defines errors produced by eqPly.
Detailed Description
The Equalizer polygonal rendering example.
Function Documentation
void eqPly::exitErrors ()
Clear eqPly-specific error codes.
Clear Sequel-specific error codes.
Definition at line 58 of file eqPly/error.cpp.
References co::ErrorRegistry::eraseString(), and co::Global::getErrorRegistry().
void eqPly::initErrors ()
Set up eqPly-specific error codes.
Set up Sequel-specific error codes.
Definition at line 50 of file eqPly/error.cpp.
References co::Global::getErrorRegistry(), and co::ErrorRegistry::setString().
Enumeration Type Documentation
enum eqPly::ColorMode
Enumerator:
COLOR_MODEL
Render using the colors defined in the ply file.
COLOR_DEMO
Use a unique color to demonstrate decomposition.
COLOR_WHITE
Render in solid white (mostly for anaglyph stereo)
Definition at line 76 of file eqPly.h.
enum eqPly::Error
Defines errors produced by eqPly.
Definition at line 37 of file share/Equalizer/examples/eqPly/error.h.