set(VMMLIB_MATURITY "EP")
set(VMMLIB_DESCRIPTION "Templatized C++ vector and matrix math library")
set(VMMLIB_GIT_ROOT_URL "git@github.com:Eyescale/vmmlib.git")
set(VMMLIB_PACKAGE_URL "https://launchpad.net/~eilemann/+archive/equalizer-dev")
set(VMMLIB_CI_URL "git@travis-ci.org:Eyescale/vmmlib")
set(VMMLIB_CI_PNG "git@travis-ci.org:Eyescale/vmmlib.png")
set(VMMLIB_ISSUES_URL "git@github.com:Eyescale/vmmlib/issues")
