Equalizer: eVolve::Pipe Class Reference
eVolve::Pipe Class Reference
Public Member Functions
Pipe (eq::Node *parent)
Construct a new pipe.
const FrameData & getFrameData () const
Renderer * getRenderer ()
const Renderer * getRenderer () const
Protected Member Functions
virtual ~Pipe ()
Destruct the pipe.
virtual eq::WindowSystem selectWindowSystem () const
Choose the window system to be used by this pipe.
virtual bool configInit (const eq::uint128_t &initID)
Initialize this pipe.
virtual bool configExit ()
De-initialize this pipe.
virtual void frameStart (const eq::uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
Detailed Description
Definition at line 38 of file share/Equalizer/examples/eVolve/pipe.h.
Constructor & Destructor Documentation
eVolve::Pipe::Pipe (eq::Node * parent) [inline]
Construct a new pipe.
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 41 of file share/Equalizer/examples/eVolve/pipe.h.
virtual eVolve::Pipe::~Pipe () [inline, protected, virtual]
Destruct the pipe.
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 49 of file share/Equalizer/examples/eVolve/pipe.h.
Member Function Documentation
bool eVolve::Pipe::configExit () [protected, virtual]
De-initialize this pipe.
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 96 of file eVolve/pipe.cpp.
References eq::Pipe::getConfig(), and eq::Config::unmapObject().
bool eVolve::Pipe::configInit (const eq::uint128_t & initID) [protected, virtual]
Initialize this pipe.
Parameters:
initID the init identifier.
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 65 of file eVolve/pipe.cpp.
References eq::Pipe::configInit(), EQINFO, EQWARN, eq::Pipe::getConfig(), eq::fabric::Object::getError(), eq::Config::mapObject(), and eq::fabric::Object::setError().
void eVolve::Pipe::frameStart (const eq::uint128_t & frameID, const uint32_t frameNumber) [protected, virtual]
Start rendering a frame.
Called once at the beginning of each frame, to do per-frame updates of pipe-specific data, for example updating the rendering engine. Waits for the node to start the frame, unless the thread model is async. If the thread model is async, the local synchronization is released immediately.
This method has to call startFrame().
Parameters:
frameID the per-frame identifier.
frameNumber the frame to start.
See also:
Config::startFrame(), Node::startFrame(), Node::waitFrameStarted()
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 107 of file eVolve/pipe.cpp.
References co::Object::sync().
eq::WindowSystem eVolve::Pipe::selectWindowSystem () const [protected, virtual]
Choose the window system to be used by this pipe.
This function determines which of the supported windowing systems is used by this pipe instance.
Returns:
the window system currently used by this pipe.
Version:
1.0
Reimplemented from eq::Pipe.
Definition at line 47 of file eVolve/pipe.cpp.
References EQWARN, eq::Pipe::getConfig(), and eq::Pipe::supportsWindowSystem().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eVolve/pipe.h
eVolve/pipe.cpp