Equalizer: eqPixelBench::Config Class Reference
eqPixelBench::Config Class Reference
Public Member Functions
Config (co::base::RefPtr< eq::Server > parent)
virtual uint32_t startFrame (const eq::uint128_t &frameID)
virtual bool handleEvent (const eq::ConfigEvent *event)
const co::base::Clock * getClock () const
Protected Member Functions
virtual ~Config ()
Destruct a config.
Detailed Description
Definition at line 37 of file share/Equalizer/examples/eqPixelBench/config.h.
Constructor & Destructor Documentation
eqPixelBench::Config::~Config () [protected, virtual]
Destruct a config.
Version:
1.0
Reimplemented from eq::Config.
Definition at line 43 of file eqPixelBench/config.cpp.
Member Function Documentation
const co::base::Clock* eqPixelBench::Config::getClock () const [inline]
Returns:
the clock started by startFrame, or 0 on render clients.
Definition at line 49 of file share/Equalizer/examples/eqPixelBench/config.h.
bool eqPixelBench::Config::handleEvent (const eq::ConfigEvent * event) [virtual]
See also:
eq::Config::handleEvent
Reimplemented from eq::Config.
Definition at line 58 of file eqPixelBench/config.cpp.
References eq::ConfigEvent::data, and eqNbody::Config::handleEvent().
Referenced by eqPly::Config::handleEvent().
uint32_t eqPixelBench::Config::startFrame (const eq::uint128_t & frameID) [virtual]
See also:
eq::Config::startFrame
Reimplemented from eq::Config.
Definition at line 49 of file eqPixelBench/config.cpp.
References co::base::Clock::reset(), and eq::Config::startFrame().
Referenced by eqPly::Config::startFrame().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqPixelBench/config.h
eqPixelBench/config.cpp