Equalizer: co::base::ErrorRegistry Class Reference
co::base::ErrorRegistry Class Reference
A registry translating error codes to strings.
#include <errorRegistry.h>
Public Member Functions
COBASE_API const std::string & getString (const uint32_t error) const
COBASE_API void setString (const uint32_t error, const std::string &text)
Set an error string for the given error code.
COBASE_API void eraseString (const uint32_t error)
Clear a given error code string.
bool isEmpty () const
Detailed Description
A registry translating error codes to strings.
Applications can register custom error strings starting at eq::ERROR_CUSTOM. Error registration and erasure is not thread-safe. Equalizer registers errors only during eq::init(). It is strongly advised to register application-specific errors before eq::init() and erase them after eq::exit().
See also:
co::base::Error, eq::Error
Definition at line 40 of file errorRegistry.h.
Member Function Documentation
COBASE_API void co::base::ErrorRegistry::eraseString (const uint32_t error)
Clear a given error code string.
Version:
1.0
Referenced by eVolve::exitErrors(), and eqPly::exitErrors().
COBASE_API const std::string& co::base::ErrorRegistry::getString (const uint32_t error) const
Returns:
the error string for the given error code.
Version:
1.0
COBASE_API void co::base::ErrorRegistry::setString (const uint32_t error, const std::string & text)
Set an error string for the given error code.
Version:
1.0
Referenced by eVolve::initErrors(), and eqPly::initErrors().
The documentation for this class was generated from the following file:
errorRegistry.h