Equalizer: osgScaleViewer::Node Class Reference
osgScaleViewer::Node Class Reference
Public Member Functions
Node (eq::Config *parent)
Creates a Node.
int32_t getUniqueContextID ()
osg::ref_ptr< osg::Node > getModel ()
osg::ref_ptr< osg::FrameStamp > getFrameStamp ()
Protected Member Functions
virtual bool configInit (const eq::uint128_t &initID)
Initialize this node.
virtual bool configExit ()
Exit this node.
virtual void frameStart (const eq::uint128_t &frameID, const uint32_t frameNumber)
Start rendering a frame.
Detailed Description
Definition at line 46 of file share/Equalizer/examples/osgScaleViewer/node.h.
Constructor & Destructor Documentation
osgScaleViewer::Node::Node (eq::Config * parent)
Creates a Node.
Parameters:
parent the node's parent.
Reimplemented from eq::Node.
Definition at line 46 of file osgScaleViewer/node.cpp.
Member Function Documentation
bool osgScaleViewer::Node::configExit () [protected, virtual]
Exit this node.
Version:
1.0
Reimplemented from eq::Node.
Definition at line 109 of file osgScaleViewer/node.cpp.
bool osgScaleViewer::Node::configInit (const eq::uint128_t & initID) [protected, virtual]
Initialize this node.
Parameters:
initID the init identifier.
Version:
1.0
Reimplemented from eq::Node.
Definition at line 51 of file osgScaleViewer/node.cpp.
References eq::Node::configInit(), eq::fabric::Node< Config, Node, Pipe, NodeVisitor >::getConfig(), osgScaleViewer::InitData::getImageFileName(), osgScaleViewer::Config::getInitData(), osgScaleViewer::InitData::getModelFileName(), osgScaleViewer::SceneReader::readImage(), and osgScaleViewer::SceneReader::readModel().
void osgScaleViewer::Node::frameStart (const eq::uint128_t & frameID, const uint32_t frameNumber) [protected, virtual]
Start rendering a frame.
Called once at the beginning of each frame, to start the node's frame and to do per-frame updates of node-specific data. This method has to call startFrame(). Immediately releases local synchronization if the thread model is async.
Parameters:
frameID the per-frame identifier.
frameNumber the frame to start.
See also:
startFrame(), Config::beginFrame()
Version:
1.0
Reimplemented from eq::Node.
Definition at line 118 of file osgScaleViewer/node.cpp.
References eq::fabric::Node< Config, Node, Pipe, NodeVisitor >::getConfig(), and eq::Config::getTime().
The documentation for this class was generated from the following files:
share/Equalizer/examples/osgScaleViewer/node.h
osgScaleViewer/node.cpp