set(PRESSION_MATURITY "EP")
set(PRESSION_DESCRIPTION "Compressor, decompressor, uploader and downloader plugins")
set(PRESSION_GIT_ROOT_URL "https://github.com/Eyescale/Pression.git")
set(PRESSION_PACKAGE_URL "https://launchpad.net/~eilemann/+archive/equalizer-dev")
set(PRESSION_CI_URL "https://travis-ci.org/Eyescale/Pression")
set(PRESSION_CI_PNG "https://travis-ci.org/Eyescale/Pression.png")
set(PRESSION_ISSUES_URL "https://github.com/Eyescale/Pression/issues")
