set(COLLAGE_MATURITY "EP")
set(COLLAGE_DESCRIPTION "")
set(COLLAGE_GIT_ROOT_URL "https://github.com/Eyescale/Collage.git")
set(COLLAGE_PACKAGE_URL "")
set(COLLAGE_CI_URL "https://travis-ci.org/Eyescale/Collage")
set(COLLAGE_CI_PNG "https://travis-ci.org/Eyescale/Collage.png")
set(COLLAGE_ISSUES_URL "https://github.com/Eyescale/Collage/issues")
