Equalizer: osgScaleViewer::Channel Class Reference
osgScaleViewer::Channel Class Reference
The Channel renders the frames in frameDraw().
#include <channel.h>
Public Member Functions
Channel (eq::Window *parent)
Construct a new channel.
Protected Member Functions
virtual void frameClear (const eq::uint128_t &frameID)
virtual void frameDraw (const eq::uint128_t &frameID)
void frameViewFinish (const eq::uint128_t &frameID)
Detailed Description
The Channel renders the frames in frameDraw().
This is done by querying the pipe for the viewer and then asking the viewer to render the scene.
Definition at line 56 of file share/Equalizer/examples/osgScaleViewer/channel.h.
Constructor & Destructor Documentation
osgScaleViewer::Channel::Channel (eq::Window * parent)
Construct a new channel.
Version:
1.0
Reimplemented from eq::Channel.
Definition at line 47 of file osgScaleViewer/channel.cpp.
Member Function Documentation
void osgScaleViewer::Channel::frameClear (const eq::uint128_t & frameID) [protected, virtual]
See also:
eq::Channel::frameClear()
Reimplemented from eq::Channel.
Definition at line 53 of file osgScaleViewer/channel.cpp.
void osgScaleViewer::Channel::frameDraw (const eq::uint128_t & frameID) [protected, virtual]
See also:
eq::Channel::frameDraw()
Reimplemented from eq::Channel.
Definition at line 59 of file osgScaleViewer/channel.cpp.
References osgScaleViewer::FrameData::getCameraLookAtPoint(), osgScaleViewer::FrameData::getCameraPosition(), osgScaleViewer::FrameData::getCameraUpVector(), eq::fabric::Channel< Window, Channel >::getDrawBuffer(), eq::fabric::Channel< Window, Channel >::getDrawBufferMask(), osgScaleViewer::Pipe::getFrameData(), eq::fabric::Channel< Window, Channel >::getFrustum(), eq::fabric::Channel< Window, Channel >::getHeadTransform(), eq::Channel::getPipe(), eq::fabric::Channel< Window, Channel >::getPixelViewport(), and eq::fabric::Channel< Window, Channel >::getWindow().
void osgScaleViewer::Channel::frameViewFinish (const eq::uint128_t & frameID) [protected, virtual]
See also:
eq::Channel::frameViewFinish()
Reimplemented from eq::Channel.
Definition at line 109 of file osgScaleViewer/channel.cpp.
References eq::Channel::applyBuffer(), eq::Channel::applyViewport(), eq::Channel::drawStatistics(), osgScaleViewer::Pipe::getFrameData(), eq::Channel::getPipe(), and osgScaleViewer::FrameData::useStatistics().
The documentation for this class was generated from the following files:
share/Equalizer/examples/osgScaleViewer/channel.h
osgScaleViewer/channel.cpp