var hierarchy =
[
    [ "alist", "structalist.html", null ],
    [ "boost::la::matrix_traits< vmml::matrix< M, N, T > >", "structboost_1_1la_1_1matrix__traits_3_01vmml_1_1matrix_3_01_m_00_01_n_00_01_t_01_4_01_4.html", null ],
    [ "boost::la::vector_traits< vmml::vector< M, T > >", "structboost_1_1la_1_1vector__traits_3_01vmml_1_1vector_3_01_m_00_01_t_01_4_01_4.html", null ],
    [ "cilist", "structcilist.html", null ],
    [ "cllist", "structcllist.html", null ],
    [ "complex", "structcomplex.html", null ],
    [ "doublecomplex", "structdoublecomplex.html", null ],
    [ "icilist", "structicilist.html", null ],
    [ "inlist", "structinlist.html", null ],
    [ "vmml::matrix< M, N, float_t >", "classvmml_1_1matrix.html", null ],
    [ "vmml::matrix< T::COLS, T::COLS, Tinternal >", "classvmml_1_1matrix.html", null ],
    [ "vmml::matrix< T::COLS, T::ROWS, Texternal >", "classvmml_1_1matrix.html", null ],
    [ "vmml::matrix< T::COLS, T::ROWS, Tinternal >", "classvmml_1_1matrix.html", null ],
    [ "vmml::matrix< T::ROWS, T::COLS, Tinternal >", "classvmml_1_1matrix.html", null ],
    [ "vmml::matrix< T::ROWS, T::COLS, typename T::value_type >", "classvmml_1_1matrix.html", null ],
    [ "vmml::matrix< T::ROWS, T::ROWS, Tinternal >", "classvmml_1_1matrix.html", null ],
    [ "Multitype", "union_multitype.html", null ],
    [ "Namelist", "struct_namelist.html", null ],
    [ "olist", "structolist.html", null ],
    [ "binary_function", null, [
      [ "vmml::matrix_equals_allow_inverted_columns< T >", "structvmml_1_1matrix__equals__allow__inverted__columns.html", null ],
      [ "vmml::matrix_equals_allow_inverted_rows< T >", "structvmml_1_1matrix__equals__allow__inverted__rows.html", null ]
    ] ],
    [ "std::exception", null, [
      [ "vmml::exception", "classvmml_1_1exception.html", null ]
    ] ],
    [ "vmml::tensor3< R1, R2, R3, char >", "classvmml_1_1tensor3.html", null ],
    [ "vmml::tensor3< R1, R2, R3, T_coeff >", "classvmml_1_1tensor3.html", null ],
    [ "vmml::tensor3< R1, R2, R3, T_internal >", "classvmml_1_1tensor3.html", null ],
    [ "vmml::tensor4< R1, R2, R3, R4, T_internal >", "classvmml_1_1tensor4.html", null ],
    [ "Vardesc", "struct_vardesc.html", null ],
    [ "vmml::vector< 3, T >", "classvmml_1_1vector.html", null ],
    [ "vmml::vector< 4, T >", "classvmml_1_1vector.html", [
      [ "vmml::quaternion< T >", "classvmml_1_1quaternion.html", null ]
    ] ],
    [ "vmml::vector< M, float_t >", "classvmml_1_1vector.html", null ],
    [ "vmml::vector< T::COLS, Tinternal >", "classvmml_1_1vector.html", null ],
    [ "vmml::vector< T::ROWS, Tinternal >", "classvmml_1_1vector.html", null ],
    [ "vmml::AxisAlignedBoundingBox< T >", "classvmml_1_1_axis_aligned_bounding_box.html", null ],
    [ "vmml::blas::daxpy_params< float_t >", "structvmml_1_1blas_1_1daxpy__params.html", null ],
    [ "vmml::blas::dgemm_params< float_t >", "structvmml_1_1blas_1_1dgemm__params.html", null ],
    [ "vmml::blas::dot_params< float_t >", "structvmml_1_1blas_1_1dot__params.html", null ],
    [ "vmml::blas_daxpy< M, float_t >", "structvmml_1_1blas__daxpy.html", null ],
    [ "vmml::blas_dgemm< M, K, N, float_t >", "structvmml_1_1blas__dgemm.html", null ],
    [ "vmml::blas_dot< M, float_t >", "structvmml_1_1blas__dot.html", null ],
    [ "vmml::compute_pseudoinverse< T, Tinternal >", "classvmml_1_1compute__pseudoinverse.html", null ],
    [ "vmml::compute_pseudoinverse< T, Tinternal >::tmp_matrices", "structvmml_1_1compute__pseudoinverse_1_1tmp__matrices.html", null ],
    [ "vmml::compute_pseudoinverse< T, Tinternal >::tmp_matrices_inv", "structvmml_1_1compute__pseudoinverse_1_1tmp__matrices__inv.html", null ],
    [ "vmml::cp3_tensor< R, I1, I2, I3, T_value, T_coeff >", "classvmml_1_1cp3__tensor.html", null ],
    [ "vmml::enable_if< condition, T >", "structvmml_1_1enable__if.html", null ],
    [ "vmml::enable_if< false, T >", "structvmml_1_1enable__if_3_01false_00_01_t_01_4.html", null ],
    [ "vmml::except_here", "structvmml_1_1except__here.html", null ],
    [ "vmml::frustum< T >", "classvmml_1_1frustum.html", null ],
    [ "vmml::frustum_culler< T >", "classvmml_1_1frustum__culler.html", null ],
    [ "vmml::intersection< T >", "classvmml_1_1intersection.html", null ],
    [ "vmml::lapack::eigs_params< float_t >", "structvmml_1_1lapack_1_1eigs__params.html", null ],
    [ "vmml::lapack::gaussian_elimination< M, N, float_t >", "structvmml_1_1lapack_1_1gaussian__elimination.html", null ],
    [ "vmml::lapack::linear_least_squares_xgels< M, N, float_t >", "structvmml_1_1lapack_1_1linear__least__squares__xgels.html", null ],
    [ "vmml::lapack::linear_least_squares_xgesv< M, N, float_t >", "structvmml_1_1lapack_1_1linear__least__squares__xgesv.html", null ],
    [ "vmml::lapack::llsq_params_xgels< float_t >", "structvmml_1_1lapack_1_1llsq__params__xgels.html", null ],
    [ "vmml::lapack::llsq_params_xgesv< float_t >", "structvmml_1_1lapack_1_1llsq__params__xgesv.html", null ],
    [ "vmml::lapack::svd_params< float_t >", "structvmml_1_1lapack_1_1svd__params.html", null ],
    [ "vmml::lapack::xgesv_params< float_t >", "structvmml_1_1lapack_1_1xgesv__params.html", null ],
    [ "vmml::lapack_svd< M, N, float_t >", "structvmml_1_1lapack__svd.html", null ],
    [ "vmml::lapack_sym_eigs< N, float_t >", "structvmml_1_1lapack__sym__eigs.html", null ],
    [ "vmml::lapack_sym_eigs< N, float_t >::eigenvalue_compare", "structvmml_1_1lapack__sym__eigs_1_1eigenvalue__compare.html", null ],
    [ "vmml::linear_least_squares", "structvmml_1_1linear__least__squares.html", null ],
    [ "vmml::lowpass_filter< M, T >", "classvmml_1_1lowpass__filter.html", null ],
    [ "vmml::math::abs_greater< T >", "structvmml_1_1math_1_1abs__greater.html", null ],
    [ "vmml::math::abs_less< T >", "structvmml_1_1math_1_1abs__less.html", null ],
    [ "vmml::matrix< M, N, T >", "classvmml_1_1matrix.html", null ],
    [ "vmml::qtucker3_tensor< R1, R2, R3, I1, I2, I3, T_value, T_coeff >", "classvmml_1_1qtucker3__tensor.html", null ],
    [ "vmml::set_to_identity_functor< T >", "structvmml_1_1set__to__identity__functor.html", null ],
    [ "vmml::set_to_zero_functor< T >", "structvmml_1_1set__to__zero__functor.html", null ],
    [ "vmml::t3_converter< I1, I2, I3, T >", "classvmml_1_1t3__converter.html", null ],
    [ "vmml::t3_hooi< R1, R2, R3, I1, I2, I3, T >", "classvmml_1_1t3__hooi.html", null ],
    [ "vmml::t3_hooi< R1, R2, R3, I1, I2, I3, T >::init_dct", "structvmml_1_1t3__hooi_1_1init__dct.html", null ],
    [ "vmml::t3_hooi< R1, R2, R3, I1, I2, I3, T >::init_hosvd", "structvmml_1_1t3__hooi_1_1init__hosvd.html", null ],
    [ "vmml::t3_hooi< R1, R2, R3, I1, I2, I3, T >::init_random", "structvmml_1_1t3__hooi_1_1init__random.html", null ],
    [ "vmml::t3_hopm< R, I1, I2, I3, T >", "classvmml_1_1t3__hopm.html", null ],
    [ "vmml::t3_hopm< R, I1, I2, I3, T >::init_dct", "structvmml_1_1t3__hopm_1_1init__dct.html", null ],
    [ "vmml::t3_hopm< R, I1, I2, I3, T >::init_hosvd", "structvmml_1_1t3__hopm_1_1init__hosvd.html", null ],
    [ "vmml::t3_hopm< R, I1, I2, I3, T >::init_random", "structvmml_1_1t3__hopm_1_1init__random.html", null ],
    [ "vmml::t3_hopm< R, I1, I2, I3, T >::lambda_compare", "structvmml_1_1t3__hopm_1_1lambda__compare.html", null ],
    [ "vmml::t3_hosvd< R1, R2, R3, I1, I2, I3, T >", "classvmml_1_1t3__hosvd.html", null ],
    [ "vmml::t3_ihooi< R1, R2, R3, NBLOCKS, I1, I2, I3, T_val, T_coeff >", "classvmml_1_1t3__ihooi.html", null ],
    [ "vmml::t3_ihopm< R, NBLOCKS, I1, I2, I3, T_val, T_coeff >", "classvmml_1_1t3__ihopm.html", null ],
    [ "vmml::t3_ttm", "classvmml_1_1t3__ttm.html", null ],
    [ "vmml::t4_converter< I1, I2, I3, I4, T >", "classvmml_1_1t4__converter.html", null ],
    [ "vmml::t4_hooi< R1, R2, R3, R4, I1, I2, I3, I4, T >", "classvmml_1_1t4__hooi.html", null ],
    [ "vmml::t4_hooi< R1, R2, R3, R4, I1, I2, I3, I4, T >::init_hosvd", "structvmml_1_1t4__hooi_1_1init__hosvd.html", null ],
    [ "vmml::t4_hooi< R1, R2, R3, R4, I1, I2, I3, I4, T >::init_random", "structvmml_1_1t4__hooi_1_1init__random.html", null ],
    [ "vmml::t4_hosvd< R1, R2, R3, R4, I1, I2, I3, I4, T >", "classvmml_1_1t4__hosvd.html", null ],
    [ "vmml::t4_ttm", "classvmml_1_1t4__ttm.html", null ],
    [ "vmml::tensor3< I1, I2, I3, T >", "classvmml_1_1tensor3.html", null ],
    [ "vmml::tensor3_const_iterator< T >", "classvmml_1_1tensor3__const__iterator.html", null ],
    [ "vmml::tensor3_iterator< T >", "classvmml_1_1tensor3__iterator.html", null ],
    [ "vmml::tensor4< I1, I2, I3, I4, T >", "classvmml_1_1tensor4.html", null ],
    [ "vmml::tensor_mmapper< T, C >", "classvmml_1_1tensor__mmapper.html", null ],
    [ "vmml::tensor_stats", "classvmml_1_1tensor__stats.html", null ],
    [ "vmml::tucker3_exporter< R1, R2, R3, I1, I2, I3, T_value, T_coeff >", "classvmml_1_1tucker3__exporter.html", null ],
    [ "vmml::tucker3_importer< R1, R2, R3, I1, I2, I3, T_value, T_coeff >", "classvmml_1_1tucker3__importer.html", null ],
    [ "vmml::tucker3_tensor< R1, R2, R3, I1, I2, I3, T_value, T_coeff >", "classvmml_1_1tucker3__tensor.html", null ],
    [ "vmml::tucker4_tensor< R1, R2, R3, R4, I1, I2, I3, I4, T >", "classvmml_1_1tucker4__tensor.html", null ],
    [ "vmml::validator", "classvmml_1_1validator.html", null ],
    [ "vmml::vector< M, T >", "classvmml_1_1vector.html", null ]
];