Equalizer: eqNbody::Channel Class Reference
eqNbody::Channel Class Reference
Public Member Functions
Channel (eq::Window *parent)
Construct a new channel.
Protected Member Functions
virtual ~Channel ()
Destruct the channel.
virtual bool configInit (const eq::uint128_t &initID)
Initialize this channel.
virtual void frameDraw (const eq::uint128_t &frameID)
Draw the scene.
Detailed Description
Definition at line 39 of file share/Equalizer/examples/eqNBody/channel.h.
Constructor & Destructor Documentation
eqNbody::Channel::Channel (eq::Window * parent)
Construct a new channel.
Version:
1.0
Reimplemented from eq::Channel.
Definition at line 44 of file eqNBody/channel.cpp.
References eq::Channel::glewGetContext().
eqNbody::Channel::~Channel () [protected, virtual]
Destruct the channel.
Version:
1.0
Reimplemented from eq::Channel.
Definition at line 52 of file eqNBody/channel.cpp.
Member Function Documentation
bool eqNbody::Channel::configInit (const eq::uint128_t & initID) [protected, virtual]
Initialize this channel.
Parameters:
initID the init identifier.
Version:
1.0
Reimplemented from eq::Channel.
Definition at line 61 of file eqNBody/channel.cpp.
References eq::Channel::configInit(), eq::Channel::getConfig(), and eq::Channel::getPipe().
void eqNbody::Channel::frameDraw (const eq::uint128_t & frameID) [protected, virtual]
Draw the scene.
Called 0 to n times during one frame.
Parameters:
frameID the per-frame identifier.
Version:
1.0
Reimplemented from eq::Channel.
Definition at line 74 of file eqNBody/channel.cpp.
References eq::Channel::getPipe(), eq::fabric::Channel< Window, Channel >::getRange(), and eq::Channel::outlineViewport().
The documentation for this class was generated from the following files:
share/Equalizer/examples/eqNBody/channel.h
eqNBody/channel.cpp